' Gambas module file

Private wwwpath As String = "https://www.laurux.fr/drupal/documentation"


Public Sub Open(Rubrique As String, Optional Module as String = "Ecrans")
  
  If Exist(Application.Path & "/" & Module & "/" & Rubrique & ".html")
    Exec ["xdg-open", Application.Path & "/" & Module & "/" & Rubrique & ".html"]
  Else
    'Pointe sur la documentation globale pour l'instant
    Exec ["xdg-open", wwwpath]
  Endif
  
End
