' Gambas module file

Private Soc As String
Private Tab As String
Private Tab1 As String
Private intitule As String
Private Hfile As File
Private Lig As String
Private code As String = ""
Private TabSoc As String
Private SocResult As Result
Private rResult As Result
Private r2Result As Result
Private bMaj As Boolean = False

Public Sub Verif_Version()

  TabSoc = "Fiches_Societes"
  SocResult = Utils.db.Exec("SELECT * from  " & TabSoc & "")
  If SocResult.Available Then Soc = SocResult!cd_sc

  '***************************Maj 2.04**************************************
  If Start.LocalSettings["/dbase/Version"] = "Laurux V2,03" Then
    SocResult = Utils.db.Exec("SELECT * from  " & TabSoc & "")
    If SocResult.Available Then
      Repeat
        Soc = SocResult!cd_sc
        Maj204()
      Until SocResult.MoveNext()
      Start.LocalSettings["/dbase/Version"] = "Laurux V2,04"
      Start.LocalSettings.Save
    Endif
  Endif

  '***************************Maj 2.06**************************************
  If Start.LocalSettings["/dbase/Version"] = "Laurux V2,05" Then
    SocResult = Utils.db.Exec("SELECT * from  " & TabSoc & "")
    If SocResult.Available Then
      Repeat
        Soc = SocResult!cd_sc
        Maj206()
      Until SocResult.MoveNext()
      Start.LocalSettings["/dbase/Version"] = "Laurux V2,06"
      Start.LocalSettings.Save
    Endif
  Endif

  '***************************Maj 2.07**************************************
  If Start.LocalSettings["/dbase/Version"] = "Laurux V2,06" Then
    SocResult = Utils.db.Exec("SELECT * from  " & TabSoc & "")
    If SocResult.Available Then
      Repeat
        Soc = SocResult!cd_sc
        Maj207()
      Until SocResult.MoveNext()
      Start.LocalSettings["/dbase/Version"] = "Laurux V2,07"
      Start.LocalSettings.Save
    Endif
  Endif

  '************************* on met à jour la zone des taux de mo *********************
  If Start.LocalSettings["/dbase/Version"] = "Laurux V2,07" Then
    SocResult = Utils.db.Exec("SELECT * from  " & TabSoc & "")
    If SocResult.Available Then
      Repeat
        Soc = SocResult!cd_sc
        Maj208()
      Until SocResult.MoveNext()
      Start.LocalSettings["/dbase/Version"] = "Laurux V2,07"
      Start.LocalSettings.Save
    Endif
  Endif

  '************************* Maj 2.08*********************
  If Start.LocalSettings["/dbase/Version"] = "Laurux V2,07" Then
    SocResult = Utils.db.Exec("SELECT * from  " & TabSoc & "")
    If SocResult.Available Then
      Repeat
        Soc = SocResult!cd_sc
        Maj208()
      Until SocResult.MoveNext()
      Start.LocalSettings["/dbase/Version"] = "Laurux V2,08"
      Start.LocalSettings.Save
    Endif
  Endif

  '************************* Maj 2.09*********************
  If Start.LocalSettings["/dbase/Version"] = "Laurux V2,08" Then
    SocResult = Utils.db.Exec("SELECT * from  " & TabSoc & "")
    If SocResult.Available Then
      Repeat
        Soc = SocResult!cd_sc
        Maj209()
      Until SocResult.MoveNext()
      Start.LocalSettings["/dbase/Version"] = "Laurux V2,09"
      Start.LocalSettings.Save
    Endif
  Endif

  '************************* Maj 2.10 *********************
  If Start.LocalSettings["/dbase/Version"] = "Laurux V2,09" Then
    SocResult = Utils.db.Exec("SELECT * from  " & TabSoc & "")
    If SocResult.Available Then
      Repeat
        Soc = SocResult!cd_sc
        Maj210()
      Until SocResult.MoveNext()
      Start.LocalSettings["/dbase/Version"] = "Laurux V2,10"
      Start.LocalSettings.Save
    Endif
  Endif

  '************************* Maj 2.11 *********************
  If Start.LocalSettings["/dbase/Version"] = "Laurux V2,10" Or If Start.LocalSettings["/dbase/Version"] = "Laurux V2,10a" Then
    SocResult = Utils.db.Exec("SELECT * from  " & TabSoc & "")
    If SocResult.Available Then
      Repeat
        Soc = SocResult!cd_sc
        Maj211()
      Until SocResult.MoveNext()
      Start.LocalSettings["/dbase/Version"] = "Laurux V2,11"
      Start.LocalSettings.Save
    Endif
  Endif

  '************************* Maj 2.12 *********************
  If Start.LocalSettings["/dbase/Version"] = "Laurux V2,11" Then
    SocResult = Utils.db.Exec("SELECT * from  " & TabSoc & "")
    If SocResult.Available Then
      Repeat
        Soc = SocResult!cd_sc
        Maj212()
      Until SocResult.MoveNext()
      Start.LocalSettings["/dbase/Version"] = "Laurux V2,12"
      Start.LocalSettings.Save
    Endif
  Endif

  '************************* Maj 2.13 *********************
  If Start.LocalSettings["/dbase/Version"] = "Laurux V2,12" Then
    Start.LocalSettings["/dbase/Version"] = "Laurux V2,13"
  Endif

  '************************* Maj 2.13 *********************
  If Start.LocalSettings["/dbase/Version"] = "Laurux V2,13" Then
    SocResult = Utils.db.Exec("SELECT * from  " & TabSoc & "")
    If SocResult.Available Then
      Repeat
        Soc = SocResult!cd_sc
        Maj213()
      Until SocResult.MoveNext()
      Start.LocalSettings["/dbase/Version"] = "Laurux V2,13a"
      Start.LocalSettings.Save
    Endif
  Endif

  '************************* Maj 2.14 *********************
  If Start.LocalSettings["/dbase/Version"] = "Laurux V2,13" Or If Start.LocalSettings["/dbase/Version"] = "Laurux V2,13a" Then
    SocResult = Utils.db.Exec("SELECT * from  " & TabSoc & "")
    If SocResult.Available Then
      Repeat
        Soc = SocResult!cd_sc
        Maj208()
      Until SocResult.MoveNext()
      Start.LocalSettings["/dbase/Version"] = "Laurux V2,14"
      Start.LocalSettings.Save
    Endif
  Endif

  '************************* Maj 2.15 *********************
  If Start.LocalSettings["/dbase/Version"] = "Laurux V2,14" Then
    SocResult = Utils.db.Exec("SELECT * from  " & TabSoc & "")
    If SocResult.Available Then
      Repeat
        Soc = SocResult!cd_sc
        Maj215()
      Until SocResult.MoveNext()
      Start.LocalSettings["/dbase/Version"] = "Laurux V2,15"
      Start.LocalSettings.Save
    Endif
  Endif

  '************************* Maj 2.15a *********************
  If Start.LocalSettings["/dbase/Version"] = "Laurux V2,15" Then
    SocResult = Utils.db.Exec("SELECT * from  " & TabSoc & "")
    If SocResult.Available Then
      Repeat
        Soc = SocResult!cd_sc
        Maj215a()
      Until SocResult.MoveNext()
      Start.LocalSettings["/dbase/Version"] = "Laurux V2,15a"
      Start.LocalSettings.Save
    Endif
  Endif

  '************************* Maj 2.16 *********************
  If Start.LocalSettings["/dbase/Version"] = "Laurux V2,15" Or If Start.LocalSettings["/dbase/Version"] = "Laurux V2,15a" Then
    SocResult = Utils.db.Exec("SELECT * from  " & TabSoc & "")
    If SocResult.Available Then
      Repeat
        Soc = SocResult!cd_sc
        Maj216()
      Until SocResult.MoveNext()
      Start.LocalSettings["/dbase/Version"] = "Laurux V2,16"
      Start.LocalSettings.Save
    Endif
  Endif

  '************************* Maj 2.17 *********************
  If Start.LocalSettings["/dbase/Version"] = "Laurux V2,16" Then
    SocResult = Utils.db.Exec("SELECT * from  " & TabSoc & "")
    If SocResult.Available Then
      Repeat
        Soc = SocResult!cd_sc
        Maj217()
      Until SocResult.MoveNext()
      Start.LocalSettings["/dbase/Version"] = "Laurux V2,17"
      Start.LocalSettings.Save
    Endif
  Endif

  '************************* Maj 2.17a *********************
  If Start.LocalSettings["/dbase/Version"] = "Laurux V2,17" Then
    SocResult = Utils.db.Exec("SELECT * from  " & TabSoc & "")
    If SocResult.Available Then
      Repeat
        Soc = SocResult!cd_sc
        Maj217a()
      Until SocResult.MoveNext()
      Start.LocalSettings["/dbase/Version"] = "Laurux V2,17a"
      Start.LocalSettings.Save
    Endif
  Endif

  '************************* Maj 2.18 *********************
  If Start.LocalSettings["/dbase/Version"] = "Laurux V2,17a" Then
    SocResult = Utils.db.Exec("SELECT * from  " & TabSoc & "")
    If SocResult.Available Then
      Repeat
        Soc = SocResult!cd_sc
        Maj218()
      Until SocResult.MoveNext()
      Start.LocalSettings["/dbase/Version"] = "Laurux V2,18"
      Start.LocalSettings.Save
    Endif
  Endif
  '************************* Maj 2.19 *********************
  If Start.LocalSettings["/dbase/Version"] = "Laurux V2,18" Or If Start.LocalSettings["/dbase/Version"] = "Laurux V2,19" Then
    SocResult = Utils.db.Exec("SELECT * from  " & TabSoc & "")
    If SocResult.Available Then
      Repeat
        Soc = SocResult!cd_sc
        If Start.LocalSettings["/dbase/Host"] = "localhost" Then Maj219()
      Until SocResult.MoveNext()
      Start.LocalSettings["/dbase/Version"] = "Laurux V2,19"
      Start.LocalSettings.Save
    Endif
  Endif

  '************************* Maj 2.20 *********************
  If Start.LocalSettings["/dbase/Version"] = "Laurux V2,19" Then
    SocResult = Utils.db.Exec("SELECT * from  " & TabSoc & "")
    If SocResult.Available Then
      Repeat
        Soc = SocResult!cd_sc
        If Start.LocalSettings["/dbase/Host"] = "localhost" Then Maj220()
      Until SocResult.MoveNext()
      Start.LocalSettings["/dbase/Version"] = "Laurux V2,20"
      Start.LocalSettings.Save
    Endif
  Endif

  '************************* Maj 2.21 *********************
  If Start.LocalSettings["/dbase/Version"] = "Laurux V2.20" Or If Start.LocalSettings["/dbase/Version"] = "Laurux V2.20" Then
    SocResult = Utils.db.Exec("SELECT * from  " & TabSoc & "")
    If SocResult.Available Then
      Repeat
        Soc = SocResult!cd_sc
        If Start.LocalSettings["/dbase/Maj"] Then Maj221()
      Until SocResult.MoveNext()
      Start.LocalSettings["/dbase/Version"] = "Laurux V2.21"
      Start.LocalSettings.Save
    Endif
  Endif

  '************************* Maj 2.22 *********************
  If Start.LocalSettings["/dbase/Maj"] Then
    If Start.LocalSettings["/dbase/Version"] = "Laurux V2.21" Then
      SocResult = Utils.db.Exec("SELECT * from  " & TabSoc & "")
      If SocResult.Available Then
        Repeat
          Soc = SocResult!cd_sc
          Maj222()
        Until SocResult.MoveNext()
        Start.LocalSettings["/dbase/Version"] = "Laurux V2.22"
        Start.LocalSettings.Save
      Endif
    Endif
  Endif

  '************************* Maj 2.23 *********************
  If Start.LocalSettings["/dbase/Maj"] Or If Start.LocalSettings["/dbase/Host"] = "localhost" Then
    If Start.LocalSettings["/dbase/Version"] = "Laurux V2.22" Then
      SocResult = Utils.db.Exec("SELECT * from  " & TabSoc & "")
      If SocResult.Available Then
        Repeat
          Soc = SocResult!cd_sc
          Maj223()
        Until SocResult.MoveNext()
      Endif
      Start.LocalSettings["/dbase/Version"] = "Laurux V2.23"
      Start.LocalSettings.Save
    Endif
  Endif

  '************************* Maj 2.24 *********************
  If Start.LocalSettings["/dbase/Maj"] Or If Start.LocalSettings["/dbase/Host"] = "localhost" Then
    If Start.LocalSettings["/dbase/Version"] = "Laurux V2.23" Then
      SocResult = Utils.db.Exec("SELECT * from  " & TabSoc & "")
      If SocResult.Available Then
        Repeat
          Soc = SocResult!cd_sc
          Maj224()
        Until SocResult.MoveNext()
      Endif
      Start.LocalSettings["/dbase/Version"] = "Laurux V2.24"
      Start.LocalSettings.Save
    Endif
  Endif

  '************************* Maj 2.25 *********************
  If Start.LocalSettings["/dbase/Maj"] Or If Start.LocalSettings["/dbase/Host"] = "localhost" Then
    If Start.LocalSettings["/dbase/Version"] = "Laurux V2.24" Then
      SocResult = Utils.db.Exec("SELECT * from  " & TabSoc & "")
      If SocResult.Available Then
        Repeat
          Soc = SocResult!cd_sc
          Maj225()
        Until SocResult.MoveNext()
      Endif
      Start.LocalSettings["/dbase/Version"] = "Laurux V2.25"
      Start.LocalSettings.Save
    Endif
  Endif

  '************************* Maj 2.26 *********************
  If Start.LocalSettings["/dbase/Maj"] Or If Start.LocalSettings["/dbase/Host"] = "localhost" Then
    If Start.LocalSettings["/dbase/Version"] = "Laurux V2.25" Then
      SocResult = Utils.db.Exec("SELECT * from  " & TabSoc & "")
      If SocResult.Available Then
        Repeat
          Soc = SocResult!cd_sc
          Maj225()
        Until SocResult.MoveNext()
      Endif
      Start.LocalSettings["/dbase/Version"] = "Laurux V2.26"
      Start.LocalSettings.Save
    Endif
  Endif

  '************************* Maj 2.27 *********************
  If Start.LocalSettings["/dbase/Maj"] Or If Start.LocalSettings["/dbase/Host"] = "localhost" Then
    If Start.LocalSettings["/dbase/Version"] = "Laurux V2.26" Then
      SocResult = Utils.db.Exec("SELECT * from  " & TabSoc & "")
      If SocResult.Available Then
        Repeat
          Soc = SocResult!cd_sc
          Maj227()
        Until SocResult.MoveNext()
      Endif
      Start.LocalSettings["/dbase/Version"] = "Laurux V2.27"
      Start.LocalSettings.Save
    Endif
  Endif

  '************************* Maj 2.28 *********************
  If Start.LocalSettings["/dbase/Maj"] Or If Start.LocalSettings["/dbase/Host"] = "localhost" Then
    If Start.LocalSettings["/dbase/Version"] = "Laurux V2.27" Then
      SocResult = Utils.db.Exec("SELECT * from  " & TabSoc & "")
      If SocResult.Available Then
        Repeat
          Soc = SocResult!cd_sc
          Maj228()
        Until SocResult.MoveNext()
      Endif
      Start.LocalSettings["/dbase/Version"] = "Laurux V2.28"
      Start.LocalSettings.Save
    Endif
  Endif

  '************************* Maj 2.29 *********************
  If Start.LocalSettings["/dbase/Maj"] Or If Start.LocalSettings["/dbase/Host"] = "localhost" Then
    If Start.LocalSettings["/dbase/Version"] = "Laurux V2.28" Or If Start.LocalSettings["/dbase/Version"] = "Laurux V2.28a" Then
      SocResult = Utils.db.Exec("SELECT * from  " & TabSoc & "")
      If SocResult.Available Then
        Repeat
          Soc = SocResult!cd_sc
          Maj229()
        Until SocResult.MoveNext()
      Endif
      Start.LocalSettings["/dbase/Version"] = "Laurux V2.29"
      Start.LocalSettings.Save
    Endif
  Endif

  '************************* Maj 2.30 *********************
  If Start.LocalSettings["/dbase/Maj"] Or If Start.LocalSettings["/dbase/Host"] = "localhost" Then
    If Start.LocalSettings["/dbase/Version"] = "Laurux V2.29" Then
      SocResult = Utils.db.Exec("SELECT * from  " & TabSoc & "")
      If SocResult.Available Then
        Repeat
          Soc = SocResult!cd_sc
          Maj230()
        Until SocResult.MoveNext()
      Endif
      Start.LocalSettings["/dbase/Version"] = "Laurux V2.30"
      Start.LocalSettings.Save
    Endif
  Endif

  '************************* Maj 3.00 *********************
  If Start.LocalSettings["/dbase/Maj"] Or If Start.LocalSettings["/dbase/Host"] = "localhost" Then
    If Start.LocalSettings["/dbase/Version"] = "Laurux V2.30" Then
      SocResult = Utils.db.Exec("SELECT * from  " & TabSoc & "")
      If SocResult.Available Then
        Repeat
          Soc = SocResult!cd_sc
          Maj231()
        Until SocResult.MoveNext()
      Endif
      Start.LocalSettings["/dbase/Version"] = "Laurux V3.00"
      Start.LocalSettings.Save
    Endif
  Endif

  '************************* Maj 3.01 *********************
  If Start.LocalSettings["/dbase/Maj"] Or If Start.LocalSettings["/dbase/Host"] = "localhost" Then
    If Start.LocalSettings["/dbase/Version"] = "Laurux V3.00" Then
      SocResult = Utils.db.Exec("SELECT * from  " & TabSoc & "")
      If SocResult.Available Then
        Repeat
          Soc = SocResult!cd_sc
          Maj301()
        Until SocResult.MoveNext()
      Endif
      Start.LocalSettings["/dbase/Version"] = "Laurux V3.01"
      Start.LocalSettings.Save
    Endif
  Endif

  '************************* Maj 3.02 *********************
  If Start.LocalSettings["/dbase/Maj"] Or If Start.LocalSettings["/dbase/Host"] = "localhost" Then
    If Start.LocalSettings["/dbase/Version"] = "Laurux V3.01" Then
      SocResult = Utils.db.Exec("SELECT * from  " & TabSoc & "")
      If SocResult.Available Then
        Repeat
          Soc = SocResult!cd_sc
          Maj302()
        Until SocResult.MoveNext()
      Endif
      Start.LocalSettings["/dbase/Version"] = "Laurux V3.02"
      Start.LocalSettings.Save
    Endif
  Endif

  '************************* Maj 3.03 *********************
  If Start.LocalSettings["/dbase/Maj"] Or If Start.LocalSettings["/dbase/Host"] = "localhost" Then
    If Start.LocalSettings["/dbase/Version"] = "Laurux V3.02" Then
      SocResult = Utils.db.Exec("SELECT * from  " & TabSoc & "")
      If SocResult.Available Then
        Repeat
          Soc = SocResult!cd_sc
          Maj303()
        Until SocResult.MoveNext()
      Endif
      Start.LocalSettings["/dbase/Version"] = "Laurux V3.03"
      Start.LocalSettings.Save
    Endif
  Endif

  '************************* Maj 3.04 *********************
  If Start.LocalSettings["/dbase/Maj"] Or If Start.LocalSettings["/dbase/Host"] = "localhost" Then
    If Start.LocalSettings["/dbase/Version"] = "Laurux V3.03" Then
      SocResult = Utils.db.Exec("SELECT * from  " & TabSoc & "")
      If SocResult.Available Then
        Repeat
          Soc = SocResult!cd_sc
          Maj304()
        Until SocResult.MoveNext()
      Endif
      Start.LocalSettings["/dbase/Version"] = "Laurux V3.04"
      Start.LocalSettings.Save
    Endif
  Endif

  '************************* Maj 3.05 *********************
  If Start.LocalSettings["/dbase/Maj"] Or If Start.LocalSettings["/dbase/Host"] = "localhost" Then
    If Start.LocalSettings["/dbase/Version"] = "Laurux V3.04" Then
      SocResult = Utils.db.Exec("SELECT * from  " & TabSoc & "")
      If SocResult.Available Then
        Repeat
          Soc = SocResult!cd_sc
          Maj305()
        Until SocResult.MoveNext()
      Endif
      Start.LocalSettings["/dbase/Version"] = "Laurux V3.05"
      Start.LocalSettings.Save
    Endif
  Endif

  '************************* Maj 3.06 *********************
  If Start.LocalSettings["/dbase/Maj"] Or If Start.LocalSettings["/dbase/Host"] = "localhost" Then
    If Start.LocalSettings["/dbase/Version"] = "Laurux V3.05" Then
      SocResult = Utils.db.Exec("SELECT * from  " & TabSoc & "")
      If SocResult.Available Then
        Repeat
          Soc = SocResult!cd_sc
          Maj306()
        Until SocResult.MoveNext()
      Endif
      Start.LocalSettings["/dbase/Version"] = "Laurux V3.06"
      Start.LocalSettings.Save
    Endif
  Endif

  '************************* Maj 3.07 *********************
  If Start.LocalSettings["/dbase/Maj"] Or If Start.LocalSettings["/dbase/Host"] = "localhost" Then
    If Start.LocalSettings["/dbase/Version"] = "Laurux V3.06" Then
      SocResult = Utils.db.Exec("SELECT * from  " & TabSoc & "")
      If SocResult.Available Then
        Repeat
          Soc = SocResult!cd_sc
          Maj307()
        Until SocResult.MoveNext()
      Endif
      Start.LocalSettings["/dbase/Version"] = "Laurux V3.07"
      Start.LocalSettings.Save
    Endif
  Endif

  '************************* Maj 3.08 *********************
  If Start.LocalSettings["/dbase/Maj"] Or If Start.LocalSettings["/dbase/Host"] = "localhost" Then
    If Start.LocalSettings["/dbase/Version"] = "Laurux V3.07" Then
      SocResult = Utils.db.Exec("SELECT * from  " & TabSoc & "")
      If SocResult.Available Then
        Soc = SocResult!cd_sc
        Maj308()
      Endif
      Start.LocalSettings["/dbase/Version"] = "Laurux V3.08"
      Start.LocalSettings.Save
      Start.LocalSettings.Reload
    Endif
  Endif

  '************************* Maj 3.09 *********************
  If Start.LocalSettings["/dbase/Maj"] Or If Start.LocalSettings["/dbase/Host"] = "localhost" Then
    If Start.LocalSettings["/dbase/Version"] = "Laurux V3.08" Then
      Soc = Start.LocalSettings["/Soc"]
      Start.LocalSettings["/Societes/Soc" & Soc] = "Laurux V3.08"
      Start.LocalSettings.Save
      Start.LocalSettings.Reload
      Maj309()
      Start.LocalSettings["/Societes/Soc" & Soc] = "Laurux V3.09"
      Start.LocalSettings["/dbase/Version"] = "Laurux V3.09"
      Start.LocalSettings.Save
      Start.LocalSettings.Reload
    Endif
  Endif

  '************************* Maj 3.10 *********************
  If Start.LocalSettings["/dbase/Maj"] Or If Start.LocalSettings["/dbase/Host"] = "localhost" Then
    If Start.LocalSettings["/Societes/Soc" & Start.societe] = "Laurux V3.09" Then
      Maj310()
      Start.LocalSettings["/Societes/Soc" & Start.societe] = "Laurux V3.10"
      Start.LocalSettings["/dbase/Version"] = "Laurux V3.10"
      Start.LocalSettings.Save
      Start.LocalSettings.Reload
    Endif
  Endif

  '************************* Maj 3.10b *********************
  If Start.LocalSettings["/dbase/Maj"] Then
    If Start.LocalSettings["/Societes/Soc" & Start.societe] = "Laurux V3.10" Then
      Maj310b()
      Start.LocalSettings["/Societes/Soc" & Start.societe] = "Laurux V3.10b"
      Start.LocalSettings.Save
      Start.LocalSettings.Reload
    Endif
  Endif

  '************************* Maj 3.11 *********************
  If Start.LocalSettings["/dbase/Maj"] Then
    If Start.LocalSettings["/Societes/Soc" & Start.societe] = "Laurux V3.10" Or If Start.LocalSettings["/Societes/Soc" & Start.societe] = "Laurux V3.10b" Then
      Maj311()
      Start.LocalSettings["/Societes/Soc" & Start.societe] = "Laurux V3.11"
      Start.LocalSettings["/dbase/Version"] = "Laurux V3.11"
      Start.LocalSettings.Save
      Start.LocalSettings.Reload
    Endif
  Endif

  '************************* Maj 3.12 *********************
  If Start.LocalSettings["/Societes/Soc" & Start.societe] = "Laurux V3.11" Then
    If Start.LocalSettings["/dbase/Maj"] Then Maj312()
    Start.LocalSettings["/Societes/Soc" & Start.societe] = "Laurux V3.12"
    Start.LocalSettings["/dbase/Version"] = "Laurux V3.12"
    Start.LocalSettings.Save
    Start.LocalSettings.Reload
  Endif

  '************************* Maj 3.12a *********************
  If Start.LocalSettings["/Societes/Soc" & Start.societe] = "Laurux V3.12" Then
    If Start.LocalSettings["/dbase/Maj"] Then Maj312a()
    Start.LocalSettings["/Societes/Soc" & Start.societe] = "Laurux V3.12a"
    Start.LocalSettings["/dbase/Version"] = "Laurux V3.12a"
    Start.LocalSettings.Save
    Start.LocalSettings.Reload
  Endif

  '************************* Maj 3.13 *********************
  If Start.LocalSettings["/Societes/Soc" & Start.societe] = "Laurux V3.12a" Then
    If Start.LocalSettings["/dbase/Maj"] Then Maj312a()
    Start.LocalSettings["/Societes/Soc" & Start.societe] = "Laurux V3.13"
    Start.LocalSettings["/dbase/Version"] = "Laurux V3.13"
    Start.LocalSettings.Save
    Start.LocalSettings.Reload
  Endif

  '************************* Maj 3.14 *********************
  If Start.LocalSettings["/Societes/Soc" & Start.societe] = "Laurux V3.13" Then
    If Start.LocalSettings["/dbase/Maj"] Then Maj314()
    Start.LocalSettings["/Societes/Soc" & Start.societe] = "Laurux V3.14"
    Start.LocalSettings["/dbase/Version"] = "Laurux V3.14"
    Start.LocalSettings.Save
    Start.LocalSettings.Reload
  Endif

  '************************* Maj 3.15 *********************
  If Start.LocalSettings["/Societes/Soc" & Start.societe] = "Laurux V3.14" Then
    If Start.LocalSettings["/dbase/Maj"] Then Maj315()
    Start.LocalSettings["/Societes/Soc" & Start.societe] = "Laurux V3.15"
    Start.LocalSettings["/dbase/Version"] = "Laurux V3.15"
    Start.LocalSettings.Save
    Start.LocalSettings.Reload
  Endif

  '************************* Maj 3.16 *********************
  If Start.LocalSettings["/Societes/Soc" & Start.societe] = "Laurux V3.15" Then
    If Start.LocalSettings["/dbase/Maj"] Then Maj316()
    Start.LocalSettings["/Societes/Soc" & Start.societe] = "Laurux V3.16"
    Start.LocalSettings["/dbase/Version"] = "Laurux V3.16"
    Start.LocalSettings.Save
    Start.LocalSettings.Reload
  Endif

  '************************* Maj 3.17 *********************
  If Start.LocalSettings["/Societes/Soc" & Start.societe] = "Laurux V3.16" Then
    If Start.LocalSettings["/dbase/Maj"] Then Maj317()
    Start.LocalSettings["/Societes/Soc" & Start.societe] = "Laurux V3.17"
    Start.LocalSettings["/dbase/Version"] = "Laurux V3.17"
    Start.LocalSettings.Save
    Start.LocalSettings.Reload
  Endif

  '************************* Maj 3.18 *********************
  If Start.LocalSettings["/Societes/Soc" & Start.societe] = "Laurux V3.17" Then
    If Start.LocalSettings["/dbase/Maj"] Then Maj318()
    Start.LocalSettings["/Societes/Soc" & Start.societe] = "Laurux V3.18"
    Start.LocalSettings["/dbase/Version"] = "Laurux V3.18"
    Start.LocalSettings.Save
    Start.LocalSettings.Reload
  Endif

  '************************* Maj 3.19 *********************
  If Start.LocalSettings["/Societes/Soc" & Start.societe] = "Laurux V3.18" Then
    If Start.LocalSettings["/dbase/Maj"] Then Maj319()
    Start.LocalSettings["/Societes/Soc" & Start.societe] = "Laurux V3.19"
    Start.LocalSettings["/dbase/Version"] = "Laurux V3.19"
    Start.LocalSettings.Save
    Start.LocalSettings.Reload
  Endif

  '************************* Maj 3.20 *********************
  If Start.LocalSettings["/Societes/Soc" & Start.societe] = "Laurux V3.19" Then
    If Start.LocalSettings["/dbase/Maj"] Then Maj320()
    Start.LocalSettings["/Societes/Soc" & Start.societe] = "Laurux V3.20"
    Start.LocalSettings["/dbase/Version"] = "Laurux V3.20"
    Start.LocalSettings.Save
    Start.LocalSettings.Reload
  Endif

  '************************* Maj 3.21 *********************
  If Start.LocalSettings["/Societes/Soc" & Start.societe] = "Laurux V3.20" Then
    If Start.LocalSettings["/dbase/Maj"] Then Maj321()
    Start.LocalSettings["/Societes/Soc" & Start.societe] = "Laurux V3.21"
    Start.LocalSettings["/dbase/Version"] = "Laurux V3.21"
    Start.LocalSettings.Save
    Start.LocalSettings.Reload
  Endif

  '************************* Maj 3.22 *********************
  If Start.LocalSettings["/Societes/Soc" & Start.societe] = "Laurux V3.21" Then
    If Start.LocalSettings["/dbase/Maj"] Then Maj322()
    Start.LocalSettings["/Societes/Soc" & Start.societe] = "Laurux V3.22"
    Start.LocalSettings["/dbase/Version"] = "Laurux V3.22"
    Start.LocalSettings["/Soc" & Start.Societe & "/Faca"] = False
    Start.LocalSettings.Save
    Start.LocalSettings.Reload
  Endif

  '************************* Maj 3.23 *********************
  If Start.LocalSettings["/Societes/Soc" & Start.societe] = "Laurux V3.22" Then
    If Start.LocalSettings["/dbase/Maj"] Then Maj323()
    Start.LocalSettings["/Societes/Soc" & Start.societe] = "Laurux V3.23"
    Start.LocalSettings["/dbase/Version"] = "Laurux V3.23"
    Start.LocalSettings.Save
    Start.LocalSettings.Reload
  Endif

  '************************* Maj 3.24 *********************
  If Start.LocalSettings["/Societes/Soc" & Start.societe] = "Laurux V3.23" Then
    If Start.LocalSettings["/dbase/Maj"] Then Maj324()
    Start.LocalSettings["/Societes/Soc" & Start.societe] = "Laurux V3.24"
    Start.LocalSettings["/dbase/Version"] = "Laurux V3.24"
    Start.LocalSettings.Save
    Start.LocalSettings.Reload
  Endif

  '************************* Maj 3.25 *********************
  If Start.LocalSettings["/Societes/Soc" & Start.societe] = "Laurux V3.24" Then
    If Start.LocalSettings["/dbase/Maj"] Then Maj325()
    Start.LocalSettings["/Societes/Soc" & Start.societe] = "Laurux V3.25"
    Start.LocalSettings["/dbase/Version"] = "Laurux V3.25"
    Start.LocalSettings.Save
    Start.LocalSettings.Reload
  Endif

  '************************* Maj 3.26 *********************
  If Start.LocalSettings["/Societes/Soc" & Start.societe] = "Laurux V3.25" Then
    If Start.LocalSettings["/dbase/Maj"] Then Maj326()
    Start.LocalSettings["/Societes/Soc" & Start.societe] = "Laurux V3.26"
    Start.LocalSettings["/dbase/Version"] = "Laurux V3.26"
    Start.LocalSettings.Save
    Start.LocalSettings.Reload
  Endif

  '************************* Maj 3.27 *********************
  If Start.LocalSettings["/Societes/Soc" & Start.societe] = "Laurux V3.26" Then
    If Start.LocalSettings["/dbase/Maj"] Then Maj327()
    Start.LocalSettings["/Societes/Soc" & Start.societe] = "Laurux V3.27"
    Start.LocalSettings["/dbase/Version"] = "Laurux V3.27"
    Start.LocalSettings.Save
    Start.LocalSettings.Reload
  Endif

  '************************* Maj 3.28 *********************
  If Start.LocalSettings["/Societes/Soc" & Start.societe] = "Laurux V3.27" Then
    If Start.LocalSettings["/dbase/Maj"] Then Maj328()
    Start.LocalSettings["/Societes/Soc" & Start.societe] = "Laurux V3.28"
    Start.LocalSettings["/dbase/Version"] = "Laurux V3.28"
    Start.LocalSettings.Save
    Start.LocalSettings.Reload
  Endif

  '************************* Maj 3.29 *********************
  If Start.LocalSettings["/Societes/Soc" & Start.societe] = "Laurux V3.28" Then
    If Start.LocalSettings["/dbase/Maj"] Then Maj329()
    Start.LocalSettings["/Societes/Soc" & Start.societe] = "Laurux V3.29"
    Start.LocalSettings["/dbase/Version"] = "Laurux V3.29"
    Start.LocalSettings.Save
    Start.LocalSettings.Reload
  Endif

  '************************* Maj 3.30 *********************
  If Start.LocalSettings["/Societes/Soc" & Start.societe] = "Laurux V3.29" Then
    If Start.LocalSettings["/dbase/Maj"] Then Maj330()
    Start.LocalSettings["/Societes/Soc" & Start.societe] = "Laurux V3.30"
    Start.LocalSettings["/dbase/Version"] = "Laurux V3.30"
    Start.LocalSettings.Save
    Start.LocalSettings.Reload
  Endif

  '************************* Maj 3.31 *********************
  If Start.LocalSettings["/Societes/Soc" & Start.societe] = "Laurux V3.30" Then
    If Start.LocalSettings["/dbase/Maj"] Then Maj331()
    Start.LocalSettings["/Societes/Soc" & Start.societe] = "Laurux V3.31"
    Start.LocalSettings["/dbase/Version"] = "Laurux V3.31"
    Start.LocalSettings.Save
    Start.LocalSettings.Reload
  Endif

  '************************* Maj 3.32 *********************
  If Start.LocalSettings["/Societes/Soc" & Start.societe] = "Laurux V3.31" Then
    If Start.LocalSettings["/dbase/Maj"] Then Maj332()
    Start.LocalSettings["/Societes/Soc" & Start.societe] = "Laurux V3.32"
    Start.LocalSettings["/dbase/Version"] = "Laurux V3.32"
    Start.LocalSettings.Save
    Start.LocalSettings.Reload
  Endif

  '************************* Maj 3.33 *********************
  If Start.LocalSettings["/Societes/Soc" & Start.societe] = "Laurux V3.32" Then
    If Start.LocalSettings["/dbase/Maj"] Then Maj333()
    Start.LocalSettings["/Societes/Soc" & Start.societe] = "Laurux V3.33"
    Start.LocalSettings["/dbase/Version"] = "Laurux V3.33"
    Start.LocalSettings.Save
    Start.LocalSettings.Reload
  Endif

  '************************* Maj 3.34 *********************
  If Start.LocalSettings["/Societes/Soc" & Start.societe] = "Laurux V3.33" Then
    If Start.LocalSettings["/dbase/Maj"] Then Maj334()
    Start.LocalSettings["/Societes/Soc" & Start.societe] = "Laurux V3.34"
    Start.LocalSettings["/dbase/Version"] = "Laurux V3.34"
    Start.LocalSettings.Save
    Start.LocalSettings.Reload
  Endif

  '************************* Maj 3.35 *********************
  If Start.LocalSettings["/Societes/Soc" & Start.societe] = "Laurux V3.34" Then
    If Start.LocalSettings["/dbase/Maj"] Then Maj335()
    Start.LocalSettings["/Societes/Soc" & Start.societe] = "Laurux V3.35"
    Start.LocalSettings["/dbase/Version"] = "Laurux V3.35"
    Start.LocalSettings.Save
    Start.LocalSettings.Reload
  Endif

  '************************* Maj 3.36 *********************
  If Start.LocalSettings["/Societes/Soc" & Start.societe] = "Laurux V3.35" Then
    If Start.LocalSettings["/dbase/Maj"] Then Maj336()
    Start.LocalSettings["/Societes/Soc" & Start.societe] = "Laurux V3.36"
    Start.LocalSettings["/dbase/Version"] = "Laurux V3.36"
    Start.LocalSettings.Save
    Start.LocalSettings.Reload
  Endif

  '************************* Maj 3.37 *********************
  If Start.LocalSettings["/Societes/Soc" & Start.societe] = "Laurux V3.36" Then
    If Start.LocalSettings["/dbase/Maj"] Then Maj337()
    Start.LocalSettings["/Societes/Soc" & Start.societe] = "Laurux V3.37"
    Start.LocalSettings["/dbase/Version"] = "Laurux V3.37"
    Start.LocalSettings.Save
    Start.LocalSettings.Reload
  Endif

  '************************* Maj 3.38 *********************
  If Start.LocalSettings["/Societes/Soc" & Start.societe] = "Laurux V3.37" Then
    If Start.LocalSettings["/dbase/Maj"] Then Maj338()
    Start.LocalSettings["/Societes/Soc" & Start.societe] = "Laurux V3.38"
    Start.LocalSettings["/dbase/Version"] = "Laurux V3.38"
    Start.LocalSettings.Save
    Start.LocalSettings.Reload
  Endif

  '************************* Maj 3.39 *********************
  If Start.LocalSettings["/Societes/Soc" & Start.societe] = "Laurux V3.38" Then
    If Start.LocalSettings["/dbase/Maj"] Then Maj339()
    Start.LocalSettings["/Societes/Soc" & Start.societe] = "Laurux V3.39"
    Start.LocalSettings["/dbase/Version"] = "Laurux V3.39"
    Start.LocalSettings.Save
    Start.LocalSettings.Reload
  Endif

  '************************* Maj 3.40 *********************
  If Start.LocalSettings["/Societes/Soc" & Start.societe] = "Laurux V3.39" Then
    If Start.LocalSettings["/dbase/Maj"] Then Maj340()
    Start.LocalSettings["/Societes/Soc" & Start.societe] = "Laurux V3.40"
    Start.LocalSettings["/dbase/Version"] = "Laurux V3.40"
    Start.LocalSettings.Save
    Start.LocalSettings.Reload
  Endif

  '************************* Maj 3.41 *********************
  If Start.LocalSettings["/Societes/Soc" & Start.societe] = "Laurux V3.40" Then
    If Start.LocalSettings["/dbase/Maj"] Then Maj341()
    Start.LocalSettings["/Societes/Soc" & Start.societe] = "Laurux V3.41"
    Start.LocalSettings["/dbase/Version"] = "Laurux V3.41"
    Start.LocalSettings.Save
    Start.LocalSettings.Reload
  Endif

  '************************* Maj 3.42 *********************
  If Start.LocalSettings["/Societes/Soc" & Start.societe] = "Laurux V3.41" Then
    If Start.LocalSettings["/dbase/Maj"] Then Maj342()
    Start.LocalSettings["/Societes/Soc" & Start.societe] = "Laurux V3.42"
    Start.LocalSettings["/dbase/Version"] = "Laurux V3.42"
    Start.LocalSettings.Save
    Start.LocalSettings.Reload
  Endif

  '************************* Maj 3.43 *********************
  If Start.LocalSettings["/Societes/Soc" & Start.societe] = "Laurux V3.42" Then
    If Start.LocalSettings["/dbase/Maj"] Then Maj343()
    Start.LocalSettings["/Societes/Soc" & Start.societe] = "Laurux V3.43"
    Start.LocalSettings["/dbase/Version"] = "Laurux V3.43"
    Start.LocalSettings.Save
    Start.LocalSettings.Reload
  Endif

  '************************* Maj 3.44 *********************
  If Start.LocalSettings["/Societes/Soc" & Start.societe] = "Laurux V3.43" Then
    If Start.LocalSettings["/dbase/Maj"] Then Maj344()
    Start.LocalSettings["/Societes/Soc" & Start.societe] = "Laurux V3.44"
    Start.LocalSettings["/dbase/Version"] = "Laurux V3.44"
    Start.LocalSettings.Save
    Start.LocalSettings.Reload
  Endif

  '************************* Maj 3.45 *********************
  If Start.LocalSettings["/Societes/Soc" & Start.societe] = "Laurux V3.44" Then
    If Start.LocalSettings["/dbase/Maj"] Then Maj345()
    Start.LocalSettings["/Societes/Soc" & Start.societe] = "Laurux V3.45"
    Start.LocalSettings["/dbase/Version"] = "Laurux V3.45"
    Start.LocalSettings.Save
    Start.LocalSettings.Reload
  Endif

  '************************* Maj 3.46 *********************
  If Start.LocalSettings["/Societes/Soc" & Start.societe] = "Laurux V3.45" Then
    If Start.LocalSettings["/dbase/Maj"] Then Maj346()
    Start.LocalSettings["/Societes/Soc" & Start.societe] = "Laurux V3.46"
    Start.LocalSettings["/dbase/Version"] = "Laurux V3.46"
    Start.LocalSettings.Save
    Start.LocalSettings.Reload
  Endif

  '************************* Maj 3.47 *********************
  If Start.LocalSettings["/Societes/Soc" & Start.societe] = "Laurux V3.46" Then
    If Start.LocalSettings["/dbase/Maj"] Then Maj347()
    Start.LocalSettings["/Societes/Soc" & Start.societe] = "Laurux V3.47"
    Start.LocalSettings["/dbase/Version"] = "Laurux V3.47"
    Start.LocalSettings.Save
    Start.LocalSettings.Reload
  Endif

  '************************* Maj 3.48 *********************
  If Start.LocalSettings["/Societes/Soc" & Start.societe] = "Laurux V3.47" Then
    If Start.LocalSettings["/dbase/Maj"] Then Maj348()
    Start.LocalSettings["/Societes/Soc" & Start.societe] = "Laurux V3.48"
    Start.LocalSettings["/dbase/Version"] = "Laurux V3.48"
    Start.LocalSettings.Save
    Start.LocalSettings.Reload
  Endif

  '************************* Maj 3.49 *********************
  If Start.LocalSettings["/Societes/Soc" & Start.societe] = "Laurux V3.48" Then
    If Start.LocalSettings["/dbase/Maj"] Then Maj349()
    Start.LocalSettings["/Societes/Soc" & Start.societe] = "Laurux V3.49"
    Start.LocalSettings["/dbase/Version"] = "Laurux V3.49"
    Start.LocalSettings.Save
    Start.LocalSettings.Reload
  Endif

  '************************* Maj 3.50 *********************
  If Start.LocalSettings["/Societes/Soc" & Start.societe] = "Laurux V3.49" Then
    If Start.LocalSettings["/dbase/Maj"] Then Maj350()
    Start.LocalSettings["/Societes/Soc" & Start.societe] = "Laurux V3.50"
    Start.LocalSettings["/dbase/Version"] = "Laurux V3.50"
  Endif

  '************************* Maj 3.51 *********************
  If Start.LocalSettings["/Societes/Soc" & Start.societe] = "Laurux V3.50" Then
    If Start.LocalSettings["/dbase/Maj"] Then Maj351()
    Start.LocalSettings["/Societes/Soc" & Start.societe] = "Laurux V3.51"
    Start.LocalSettings["/dbase/Version"] = "Laurux V3.51"
  Endif

  '************************* Maj 3.52 *********************
  If Start.LocalSettings["/Societes/Soc" & Start.societe] = "Laurux V3.51" Then
    If Start.LocalSettings["/dbase/Maj"] Then Maj352()
    Start.LocalSettings["/Societes/Soc" & Start.societe] = "Laurux V3.52"
    Start.LocalSettings["/dbase/Version"] = "Laurux V3.52"
  Endif

  '************************* Maj 3.53 *********************
  If Start.LocalSettings["/Societes/Soc" & Start.societe] = "Laurux V3.52" Then
    If Start.LocalSettings["/dbase/Maj"] Then Maj353()
    Start.LocalSettings["/Societes/Soc" & Start.societe] = "Laurux V3.53"
    Start.LocalSettings["/dbase/Version"] = "Laurux V3.53"
  Endif

  '************************* Maj 3.54 *********************
  If Start.LocalSettings["/Societes/Soc" & Start.societe] = "Laurux V3.53" Then
    If Start.LocalSettings["/dbase/Maj"] Then Maj354()
    Start.LocalSettings["/Societes/Soc" & Start.societe] = "Laurux V3.54"
    Start.LocalSettings["/dbase/Version"] = "Laurux V3.54"
  Endif

  '************************* Maj 3.55 *********************
  If Start.LocalSettings["/Societes/Soc" & Start.societe] = "Laurux V3.54" Then
    If Start.LocalSettings["/dbase/Maj"] Then Maj355()
    Start.LocalSettings["/Societes/Soc" & Start.societe] = "Laurux V3.55"
    Start.LocalSettings["/dbase/Version"] = "Laurux V3.55"
  Endif

  '************************* Maj 3.56 *********************
  If Start.LocalSettings["/Societes/Soc" & Start.societe] = "Laurux V3.55" Then
    If Start.LocalSettings["/dbase/Maj"] Then Maj356()
    Start.LocalSettings["/Societes/Soc" & Start.societe] = "Laurux V3.56"
    Start.LocalSettings["/dbase/Version"] = "Laurux V3.56"
  Endif

  '************************* Maj 3.57 *********************
  If Start.LocalSettings["/Societes/Soc" & Start.societe] = "Laurux V3.56" Then
    If Start.LocalSettings["/dbase/Maj"] Then Maj357()
    Start.LocalSettings["/Societes/Soc" & Start.societe] = "Laurux V3.57"
    Start.LocalSettings["/dbase/Version"] = "Laurux V3.57"
  Endif

  '************************* Maj 3.58 *********************
  If Start.LocalSettings["/Societes/Soc" & Start.societe] = "Laurux V3.57" Then
    If Start.LocalSettings["/dbase/Maj"] Then Maj358()
    Start.LocalSettings["/Societes/Soc" & Start.societe] = "Laurux V3.58"
    Start.LocalSettings["/dbase/Version"] = "Laurux V3.58"
    Start.LocalSettings.Save
    Start.LocalSettings.Reload
  Endif

  '************************* Maj 3.59 *********************
  If Start.LocalSettings["/Societes/Soc" & Start.societe] = "Laurux V3.58" Then
    If Start.LocalSettings["/dbase/Maj"] Then Maj359()
    Start.LocalSettings["/Societes/Soc" & Start.societe] = "Laurux V3.59"
    Start.LocalSettings["/dbase/Version"] = "Laurux V3.59"
    Start.LocalSettings.Save
    Start.LocalSettings.Reload
  Endif

  '************************* Maj 3.60 *********************
  '  If Start.LocalSettings["/Societes/Soc" & Start.societe] = "Laurux V3.59" Then
  '   If Start.LocalSettings["/dbase/Maj"] Then Maj360()
  '   Start.LocalSettings["/Societes/Soc" & Start.societe] = "Laurux V3.60"
  '   Start.LocalSettings["/dbase/Version"] = "Laurux V3.60"
  '   Start.LocalSettings.Save
  '   Start.LocalSettings.Reload
  '  Endif

  '************************* Maj 3.60 *********************
  If Majversion.Version = "3.59" Or If IsNull(Majversion.Version) Then
    If Start.LocalSettings["/dbase/Maj"] Then Maj360()
  Endif

  '************************* Maj 3.61 *********************
  If Majversion.Version = "3.60" Or If IsNull(Majversion.Version) Then
    If Start.LocalSettings["/dbase/Maj"] Then Maj361()
    Try Utils.db.Exec("update Fiches_Parametres set version = &1 ", "3.61")
  Endif

  '************************* Maj 3.62 *********************
  rResult = Utils.db.Exec("SELECT * from  Fiches_Parametres")
  If rResult!version = "3.61" Then
    If Start.LocalSettings["/dbase/Maj"] Then Maj362()
    Try Utils.db.Exec("update Fiches_Parametres set version = &1 ", "3.62")
  Endif

  '************************* Maj 3.63 *********************
  rResult = Utils.db.Exec("SELECT * from  Fiches_Parametres")
  If rResult!version = "3.62" Then
    If Start.LocalSettings["/dbase/Maj"] Then Maj363()
    Try Utils.db.Exec("update Fiches_Parametres set version = &1 ", "3.63")
  Endif

  '************************* Maj 3.64 *********************
  rResult = Utils.db.Exec("SELECT * from  Fiches_Parametres")
  If rResult!version = "3.63" Then
    If Start.LocalSettings["/dbase/Maj"] Then Maj364()
    Try Utils.db.Exec("update Fiches_Parametres set version = &1 ", "3.64")
  Endif

  '************************* Maj 3.65 *********************
  rResult = Utils.db.Exec("SELECT * from  Fiches_Parametres")
  If rResult!version = "3.64" Then
    If Start.LocalSettings["/dbase/Maj"] Then Maj365()
    Try Utils.db.Exec("update Fiches_Parametres set version = &1 ", "3.65")
  Endif

  '************************* Maj 3.66 *********************
  rResult = Utils.db.Exec("SELECT * from  Fiches_Parametres")
  If rResult!version = "3.65" Then
    If Start.LocalSettings["/dbase/Maj"] Then Maj366()
    Try Utils.db.Exec("update Fiches_Parametres set version = &1 ", "3.66")
  Endif

  '************************* Maj 3.67 *********************
  rResult = Utils.db.Exec("SELECT * from  Fiches_Parametres")
  If rResult!version = "3.66" Then
    If Start.LocalSettings["/dbase/Maj"] Then Maj367()
    Try Utils.db.Exec("update Fiches_Parametres set version = &1 ", "3.67")
  Endif

  '************************* Maj 3.68 *********************
  rResult = Utils.db.Exec("SELECT * from  Fiches_Parametres")
  If rResult!version = "3.67" Then
    If Start.LocalSettings["/dbase/Maj"] Then Maj368()
    Try Utils.db.Exec("update Fiches_Parametres set version = &1 ", "3.68")
    'Laurux-Pos compatibility version
    Try Utils.db.Exec("update Fiches_Parametres set version_pos = &1 ", "3.25")
  Endif

  '************************* Maj 3.69 *********************
  rResult = Utils.db.Exec("SELECT * from  Fiches_Parametres")
  If rResult!version = "3.68" Then
    If Start.LocalSettings["/dbase/Maj"] Then Maj369()
    Try Utils.db.Exec("update Fiches_Parametres set version = &1 ", "3.69")
    'Laurux-Pos compatibility version
    Try Utils.db.Exec("update Fiches_Parametres set version_pos = &1 ", "3.26")
  Endif

  If bMaj Then Shell "xdg-open 'http://www.laurux.fr/drupal/changelog'"

End

Public Sub Maj40()

  Tab = "Fiches_Four"
  Try Utils.db.Exec("ALTER TABLE " & Tab & " ADD (fo_pays char(30))")
  Tab1 = "Fiches_Cli" & Soc
  Try Utils.db.Exec("ALTER TABLE " & Tab1 & " ADD (cli_pays char(30))")
  Tab = "Fiches_Cpostaux" & Soc
  Try Utils.db.EXEC("CREATE TABLE " & Tab &
    " (cp Char(5) NOT NULL," &
    "burdist Char(35), " &
    Utils.db.AutoIncrement("lInd") & ")")
  Try rResult = Utils.db.Exec("SELECT * from  " & Tab1 & "")
  If Not Error Then
    If rResult.Available Then
      Repeat
        r2Result = Utils.db.Exec("SELECT * from  " & Tab & " where cp = &1 and burdist = &2", rResult!cli_cd_ptl, rResult!cli_ville)
        If Not r2Result.Available Then
          If Not IsNull(rResult!cli_cd_ptl) Then Try Utils.db.Exec("Insert into  " & Tab & " (cp,burdist) values (&1,&2)", rResult!cli_cd_ptl, rResult!cli_ville)
        Endif
      Until rResult.MoveNext()
    Endif
  Endif
  Tab1 = "Fiches_Four" & Soc
  Try rResult = Utils.db.Exec("SELECT * from  " & Tab1 & "")
  If Not Error Then
    If rResult.Available Then
      Repeat
        r2Result = Utils.db.Exec("SELECT * from  " & Tab & " where cp = &1 and burdist = &2", rResult!fo_cd_ptl, rResult!fo_ville)
        If Not r2Result.Available Then
          If Not IsNull(rResult!fo_cd_ptl) Then Try Utils.db.Exec("Insert into  " & Tab & " (cp,burdist) values (&1,&2)", rResult!fo_cd_ptl, rResult!fo_ville)
        Endif
      Until rResult.MoveNext()
    Endif
  Endif
  Tab = "Fiches_Art" & Soc
  Try Utils.db.Exec("ALTER TABLE " & Tab & " ADD (art_mat TINYINT(1))")
  Tab = "Fiches_Materiels" & Soc
  Try Utils.db.EXEC("CREATE TABLE " & Tab &
    " (mat_serie char(30) NOT NULL," &
    "mat_code char(15)NOT NULL," &
    "mat_design char(50) ," &
    "mat_design2 char(50) ," &
    "mat_fam char(5) ," &
    "mat_four char(8) ," &
    "mat_cli Char(8) ," &
    "mat_cequ char(15) ," &
    "mat_cbarre char(15) ," &
    "mat_cfour char(25) ," &
    "mat_paht Decimal(12,3) ," &
    "mat_frais Decimal(7,3) , " &
    "mat_prvt Decimal(7,3) , " &
    "mat_coef Decimal(7,4) ," &
    "mat_pvht Decimal(12,3) ," &
    "mat_tva Decimal(10,3) ," &
    "mat_pvttc Decimal(12,3) ," &
    "mat_cdarr Char(4), " &
    "mat_pvar Decimal(12,3), " &
    "mat_dec Char(1), " &
    "mat_nbd Char(1), " &
    "mat_qte Char(1) , " &
    "mat_dpa Decimal(10,2) , " &
    "mat_dfour Char(8) , " &
    "mat_pmp Decimal(10,2) , " &
    "mat_ddate Char(10) , " &
    "mat_com Decimal(12,3) ," &
    "mat_ect Integer(1) ," &
    "mat_eco Decimal(5,2) ," &
    "mat_poids decimal(11, 3)," &
    "mat_poids2 decimal(11,3)," &
    "mat_photo char(20)," &
    "mat_crst text," &
    "mat_vendu Integer(1) ," &
    "mat_bl char(15)," &
    "mat_rcpt char(15)," &
    "mat_bl char(15)," &
    "mat_marque Char(20)," &
    "mat_type Char(20)," &
    "mat_matdiv Integer(1)," &
    "mat_dtevte date ," &
    "mat_dateg1 date," &
    "mat_chkgarantie TINYINT(1)," &
    "PRIMARY KEY (mat_serie, mat_code))")

  Tab = "Fiches_Marques"
  Try Utils.db.EXEC("CREATE TABLE " & Tab &
    " (code Char(5) NOT NULL," &
    "intitule Char(35), " &
    Utils.db.AutoIncrement("lInd") & ")")
  Tab = "Fiches_Art"
  Try Utils.db.Exec("ALTER TABLE " & Tab & " ADD (art_marque Char(20))")
  Tab = "Fiches_Materiels"
  Try Utils.db.Exec("ALTER TABLE " & Tab & " ADD (mat_marque Char(20))")
  Try Utils.db.Exec("ALTER TABLE " & Tab & " ADD (mat_type Char(20))")
  Try Utils.db.Exec("ALTER TABLE " & Tab & " ADD (mat_matdiv Integer(1))")
  Tab = "Fiches_Ligcom"
  Try Utils.db.Exec("ALTER TABLE " & Tab & " ADD (coda char(15))")
  Tab = "Fiches_BlM"
  Try Utils.db.EXEC("CREATE TABLE " & Tab &
    " (numbl Char(6) NOT NULL," &
    "type Char(1) ," &
    "cdclibl Char(8) ," &
    "cvclibl Char(9) ," &
    "nmclibl char(35) ," &
    "pnmclibl char(35) ," &
    "adr1bl char(35) ," &
    "adr2bl char(35) ," &
    "cpbl char(5) ," &
    "villebl char(35) ," &
    "tvar TINYINT," &
    "datebl date ," &
    "rmobl char(6) ," &
    "rartbl char(5) ," &
    "exobl TINYINT," &
    "remmobl decimal(12,2) ," &
    "remartbl decimal(12,2) ," &
    "marge_art decimal(12,2)," &
    "marge_mo decimal(12,2)," &
    "totalht Decimal(12,2)," &
    "imp Integer(1), " &
    "acpt Char(12), " &
    "mreg Char(10), " &
    "mtreg Char(12), " &
    "reg Char(15), " &
    "ech date, " &
    "numfac Char(10), " &
    "dtefac Date, " &
    "retro TINYINT, " &
    "numserie Char(15), " &
    "codep Char(15), " &
    "PRIMARY KEY (numbl))")

  Tab = "Fiches_LigblM"
  Try Utils.db.EXEC("CREATE TABLE " & Tab &
    " (num_ligbl Char(6) NOT NULL," &
    "numlig_ligbl Char(6) NOT NULL," &
    "code_ligbl Char(15) ," &
    "libel_ligbl char(50) ," &
    "fam_ligbl char(5) ," &
    "pu_ligbl char(12) ," &
    "dec_ligbl char(1) , " &
    "qte_ligbl char(6) ," &
    "brut_ligbl char(12) ," &
    "rem_ligbl char(6) ," &
    "netht_ligbl char(12) ," &
    "tx_ligbl char(1) ," &
    "nettc_ligbl char(12) ," &
    "typel_ligbl char(1) ," &
    "tm_ligbl char(1) ," &
    "com_ligbl Varchar(82) ," &
    "block_ligbl Char(6) ," &
    "pdstotal_ligbl decimal(12,3) ," &
    "mrgart_ligbl Decimal(12,3) , " &
    "mrgmo_ligbl Decimal(12,3) , " &
    "PRIMARY KEY (num_ligbl, numlig_ligbl))")

  Tab = "Fiches_HistoFacM"
  Try Utils.db.EXEC("CREATE TABLE " & Tab &
    " (numfac Char(10) NOT NULL," &
    "cdclifac Char(8) ," &
    "cvclifac Char(9) ," &
    "nmclifac char(35) ," &
    "pnmclifac char(35) ," &
    "adr1fac char(35) ," &
    "adr2fac char(35) ," &
    "cpfac char(5) ," &
    "villefac char(35) ," &
    "datefac date ," &
    "rmofac char(6) ," &
    "rartfac char(5) ," &
    "Exofac TINYINT," &
    "remmofac decimal(12,2) ," &
    "remartfac decimal(12,2) ," &
    "marge_art decimal(12,2)," &
    "marge_mo decimal(12,2)," &
    "totfac decimal(12,2), " &
    "reg Char(15), " &
    "numerobl Char(6), " &
    "ech date, " &
    "acpt Char(12), " &
    "mreg Char(10), " &
    "mtreg Char(12), " &
    "numserie Char(15), " &
    "codep Char(15), " &
    "INDEX (cdclifac), " &
    "INDEX (nmclifac), " &
    "PRIMARY KEY (numfac))")

  Tab = "Fiches_HistoLigfacM"
  Try Utils.db.EXEC("CREATE TABLE " & Tab &
    " (num_ligfac Char(10) NOT NULL," &
    "numlig_ligfac Char(6) NOT NULL," &
    "code_ligfac Char(15) ," &
    "libel_ligfac char(50) ," &
    "fam_ligfac char(5) ," &
    "pu_ligfac char(12) ," &
    "qte_ligfac char(6) ," &
    "brut_ligfac char(12) ," &
    "rem_ligfac char(6) ," &
    "netht_ligfac char(12) ," &
    "tx_ligfac char(1) ," &
    "nettc_ligfac char(12) ," &
    "typel_ligfac char(1) ," &
    "tm_ligfac char(1) ," &
    "com_ligfac Varchar(82) ," &
    "bloc char(6) ," &
    "PRIMARY KEY (num_ligfac, numlig_ligfac))")

  Tab = "Fiches_EntMat"
  Try Utils.db.EXEC("CREATE TABLE " & Tab &
    " (numserie Char(15) NOT NULL," &
    "codep Char(15) NOT NULL," &
    "marque Char(20)," &
    "type Char(20)," &
    "design char(50)," &
    "design2 char(50)," &
    "libelle Text," &
    "bloc char(6)," &
    "numbl Char(6) NOT NULL," &
    "PRIMARY KEY (numserie, codep, numbl))")

  Tab = "Fiches_HistoFacM"
  Try Utils.db.Exec("ALTER TABLE " & Tab & " ADD (mtreg Char(12))")

  Tab = "Fiches_BlM"
  Try Utils.db.Exec("ALTER TABLE " & Tab & " ADD (mtreg Char(12))")

  Tab = "Fiches_Materiels"
  Try Utils.db.Exec("ALTER TABLE " & Tab & " ADD (mat_cli Char(8))")
  Try Utils.db.Exec("ALTER TABLE " & Tab & " ADD (mat_matdiv Integer(1))")
  Try Utils.db.Exec("ALTER TABLE " & Tab & " DROP PRIMARY KEY ")
  Try Utils.db.Exec("ALTER TABLE " & Tab & " ADD PRIMARY KEY (mat_serie, mat_code)")
  Try Utils.db.Exec("ALTER TABLE " & Tab & " change mat_coef mat_coef Decimal(7, 4)")

  Tab = "Fiches_Art"
  Try Utils.db.Exec("ALTER TABLE " & Tab & " change art_coef art_coef Decimal(7, 4)")

  Tab = "Fiches_HistoFacM"
  Try Utils.db.Exec("ALTER TABLE " & Tab & " ADD (mtreg Char(12))")

  Tab = "Fiches_BlM"
  Try Utils.db.Exec("ALTER TABLE " & Tab & " ADD (mtreg Char(12))")

  Tab = "Fiches_Materiels"
  Try Utils.db.Exec("ALTER TABLE " & Tab & " ADD (mat_cli Char(8))")
  Try Utils.db.Exec("ALTER TABLE " & Tab & " ADD (mat_matdiv Integer(1))")
  Try Utils.db.Exec("ALTER TABLE " & Tab & " DROP PRIMARY KEY ")
  Try Utils.db.Exec("ALTER TABLE " & Tab & " ADD PRIMARY KEY (mat_serie, mat_code)")
  Try Utils.db.Exec("ALTER TABLE " & Tab & " change mat_coef mat_coef Decimal(7, 4)")

  Tab = "Fiches_Art"
  Try Utils.db.Exec("ALTER TABLE " & Tab & " change art_coef art_coef Decimal(7, 4)")
  Tab = "Fiches_HisentMat"
  Try Utils.db.EXEC("CREATE TABLE " & Tab &
    " (numserie Char(15) NOT NULL," &
    "codep Char(15) NOT NULL," &
    "marque Char(20)," &
    "type Char(20)," &
    "design char(50)," &
    "design2 char(50)," &
    "libelle Text," &
    "bloc char(6)," &
    "numfac Char(10) NOT NULL," &
    "PRIMARY KEY (numserie, codep, numfac))")

  Tab = "Fiches_Bl"
  Try Utils.db.Exec("ALTER TABLE " & Tab & " ADD (totalttc Decimal(12,2))")
  Try Utils.db.Exec("ALTER TABLE " & Tab & " ADD (numserie Char(15))")
  Try Utils.db.Exec("ALTER TABLE " & Tab & " ADD (codep Char(15))")

  Tab = "Fiches_BlM"
  Try Utils.db.Exec("ALTER TABLE " & Tab & " ADD (totalttc Decimal(12,2))")

  Tab = "Fiches_EntMat"
  Try Utils.db.Exec("ALTER TABLE " & Tab & " ADD (marque Char(20))")
  Try Utils.db.Exec("ALTER TABLE " & Tab & " ADD (type Char(20))")
  Try Utils.db.Exec("ALTER TABLE " & Tab & " ADD (design Char(50))")
  Try Utils.db.Exec("ALTER TABLE " & Tab & " ADD (design2 Char(20))")

  Tab = "Fiches_HistoFac"
  Try Utils.db.Exec("ALTER TABLE " & Tab & " ADD (numserie Char(15))")
  Try Utils.db.Exec("ALTER TABLE " & Tab & " ADD (codep Char(15))")
  Try Utils.db.Exec("ALTER TABLE " & Tab & " ADD (mtreg Char(12))")

  Tab = "Fiches_Commentaires"
  Try Utils.db.Exec("ALTER TABLE " & Tab & " change intitule intitule Text")
  Tab = "Fiches_Ligbl"
  Try Utils.db.Exec("ALTER TABLE " & Tab & " change com_ligbl com_ligbl Text")
  Tab = "Fiches_LigblM"
  Try Utils.db.Exec("ALTER TABLE " & Tab & " change com_ligbl com_ligbl Text")
  Tab = "Fiches_HistoLigfac"
  Try Utils.db.Exec("ALTER TABLE " & Tab & " change com_ligfac com_ligfac Text")
  Tab = "Fiches_HistoLigfacM"
  Try Utils.db.Exec("ALTER TABLE " & Tab & " change com_ligfac com_ligfac Text")

  Tab = "Fiches_Identite"
  Try Utils.db.Exec("drop Table IF exists " & Tab & "")
  Tab = "Fiches_Identite"
  Try Utils.db.exec("CREATE TABLE " & Tab &
    " (code CHAR(2) NOT NULL ," &
    "libelle CHAR(9) , " &
    "PRIMARY KEY (code))")
  If Not Error Then
    code = "01"
    Tab = "Fiches_Identite"
    HFile = Open "CV.txt" For Read
    While Not Eof(hFile)
      Line Input #hFile, Lig
      rResult = Utils.db.Exec("SELECT * FROM " & Tab & " WHERE libelle= &1", lig)
      If Not rResult.Available Then
        Try Utils.db.Exec("INSERT INTO " & Tab & "(code,libelle) VALUES (&1, &2)", Code, lig)
      Endif
      Code = Val(code) + 1
      Code = Format$(code, "00")
    Wend
    Close #HFile
  Endif
  Tab = "Fiches_Societes"
  Utils.db.Exec("ALTER TABLE " & Tab & " change type_sc type_sc char(9)")

  Tab = "Fiches_Ligbl"
  Try Utils.db.Exec("ALTER TABLE " & Tab & " change block_ligbl block_ligbl Char(20)")
  Tab = "Fiches_LigblM"
  Try Utils.db.Exec("ALTER TABLE " & Tab & " change block_ligbl block_ligbl Char(20)")
  Tab = "Fiches_HistoLigfac"
  Try Utils.db.Exec("ALTER TABLE " & Tab & " change bloc bloc Char(20)")
  Tab = "Fiches_HistoLigfacM"
  Try Utils.db.Exec("ALTER TABLE " & Tab & " change bloc bloc Char(20)")
  Tab = "Fiches_Art"
  Try Utils.db.Exec("ALTER TABLE " & Tab & " ADD (art_impcar TINYINT(1))")
  Tab = "Fiches_Bl"
  Try Utils.db.Exec("ALTER TABLE " & Tab & " drop art_suspendu")

End

Public Sub Maj41()

  Tab = "Fiches_Bl"
  Try Utils.db.Exec("ALTER TABLE " & Tab & " drop art_suspendu")

End

Public Sub Maj42()

  Tab = "Fiches_Art"
  Try Utils.db.Exec("ALTER TABLE " & Tab & " ADD (art_casier Char(5))")

End

Public Sub Maj43()

  Utils.db.Exec("ALTER TABLE " & Cbase.Table("TabCli") & " change cli_id_tva cli_id_tva Char(15)")
  Tab = "Fiches_Numabon"
  Try Utils.db.EXEC("CREATE TABLE " & Tab &
    " (numero Char(15) NOT NULL," &
    "intitule Char(30) NOT NULL," &
    "type Char(1) NOT NULL," &
    "typem Char(1) NOT NULL," &
    "PRIMARY KEY (numero))")
  Try Utils.db.Exec("ALTER TABLE " & Tab & " ADD (art_impcar TINYINT(1))")
  Utils.db.Exec("ALTER TABLE " & Cbase.Table("TabCli") & " change cli_id_tva cli_id_tva Char(15)")
  Tab = "Fiches_Ligabon"
  Try Utils.db.EXEC("CREATE TABLE " & Tab &
    " (numero Char(15) NOT NULL," &
    "compte Char(10) NOT NULL," &
    "intitule Char(40) NOT NULL," &
    "debit Char(10) NOT NULL," &
    "credit Char(10) NOT NULL," &
    "PRIMARY KEY (numero, compte))")
  Tab = "Fiches_Cli"
  Try Utils.db.Exec("ALTER TABLE " & Tab & " change cli_obs cli_obs Text")
  Tab = "Fiches_Four"
  Try Utils.db.Exec("ALTER TABLE " & Tab & " change fo_obs fo_obs Text")

End

Public Sub Maj44()

  Tab = "Fiches_Tleg"
  Try Utils.db.EXEC("CREATE TABLE " & Tab &
    " (intitule Text," &
    Utils.db.AutoIncrement("lInd") & ")")
  Intitule = "RESERVE DE PROPRIETE: Le vendeur se réserve la proprieté des marchandises jusqu'au paiement intégral de leur prix en principal et intérêts, par l'acheteur."
  Intitule = Intitule & "\nLa responsabilité des marchandises est transferée dès leur délivrance. Nos marchandises voyagent aux risques et périls des destinataires."
  Intitule = Intitule & "\nAucune piece n'est reprise apres 8 jours de livraison, les pieces commandées spécialement ne sont jamais reprises. Sauf application des règles obligatoires de compétence a l'égard des non"
  Intitule = Intitule & "\ncommercants, toutes contestations seront transmises aux juridictions du siege de notre entreprise."
  Try Utils.db.Exec("INSERT INTO " & Tab & "(intitule) VALUES (&1)", Intitule)
  Tab = "Fiches_Societes"
  Try Utils.db.Exec("ALTER TABLE " & Tab & " ADD (banq Char(30))")
  Try Utils.db.Exec("ALTER TABLE " & Tab & " ADD (bic Char(11))")
  Try Utils.db.Exec("ALTER TABLE " & Tab & " change banq banq Char(30)")
  Tab = "Fiches_Art"
  Try Utils.db.Exec("ALTER TABLE " & Tab & " ADD (art_pvcons Decimal(12,3))")

End

Public Sub Maj45()

  Tab = "Fiches_Agenda"
  Try Utils.db.EXEC("CREATE TABLE " & Tab &
    " (daction Char(20)," &
    "haction Char(20)," &
    "iaction Text," &
    Utils.db.AutoIncrement("lInd") & ")")

End

Public Sub Maj46()

  Tab = "Fiches_Txtmo"
  Try Utils.db.Exec("ALTER TABLE " & Tab & " change tx_txtmo tx_txtmo Char(10)")

  Tab = "Fiches_Mo"
  Try Utils.db.Exec("ALTER TABLE " & Tab & " change mo_tva mo_tva Char(1)")

  Tab = "Fiches_Art"
  Try Utils.db.Exec("ALTER TABLE " & Tab & " change art_tva art_tva Char(1)")
  Try Utils.db.Exec("ALTER TABLE " & Tab & " change art_prvt art_prvt Decimal(12,3)")

  Tab = "Fiches_BlM"
  Try Utils.db.Exec("ALTER TABLE " & Tab & " ADD (desg1 Char(50))")
  Try Utils.db.Exec("ALTER TABLE " & Tab & " ADD (desg2 Char(50))")
  Try Utils.db.Exec("ALTER TABLE " & Tab & " ADD (marque Char(15))")
  Try Utils.db.Exec("ALTER TABLE " & Tab & " ADD (typemat Char(15))")

  Tab = "Fiches_Bl"
  Try Utils.db.Exec("ALTER TABLE " & Tab & " ADD (desg1 Char(50))")
  Try Utils.db.Exec("ALTER TABLE " & Tab & " ADD (desg2 Char(50))")
  Try Utils.db.Exec("ALTER TABLE " & Tab & " ADD (marque Char(15))")
  Try Utils.db.Exec("ALTER TABLE " & Tab & " ADD (typemat Char(15))")

End

Public Sub Maj50()

  Tab = "Fiches_Vendeurs"
  Try Utils.db.EXEC("CREATE TABLE " & Tab &
    " (code Char(2)," &
    "nom Char(35)," &
    "mdp Char(15)," &
    "admin TINYINT," &
    Utils.db.AutoIncrement("lInd") & ")")

  Tab = "Fiches_Caisses"
  Try Utils.db.EXEC("CREATE TABLE " & Tab &
    " (code Char(2)," &
    "intitule Char(30)," &
    "dteov date ," &
    "dtefm date ," &
    "fndc decimal(12,2) ," &
    "dntk Char(7)," &
    "tkz integer(1)," &
    "connecte integer(1)," &
    "imp Char(15)," &
    "typeimp char(10)," &
    "type char(20)," &
    "ecole TINYINT," &
    "poste char(20)," &
    Utils.db.AutoIncrement("lInd") & ")")

  Tab = "Fiches_Avoirs"
  Try Utils.db.EXEC("CREATE TABLE " & Tab &
    " (intitule Char(30)," &
    "dte Char(17) ," &
    "montant decimal(12,2) ," &
    "montantdu decimal(12,2) ," &
    "ntk Char(7)," &
    Utils.db.AutoIncrement("lInd") & ")")

  Tab = "Fiches_LibelTicket"
  Try Utils.db.EXEC("CREATE TABLE " & Tab &
    "(libeltk VarChar(250)," &
    Utils.db.AutoIncrement("lInd") & ")")

  Tab = "Fiches_LibelAvoirs"
  Try Utils.db.EXEC("CREATE TABLE " & Tab &
    "(libelav Char(250)," &
    Utils.db.AutoIncrement("lInd") & ")")

  Tab = "Fiches_ClientCaisse"
  Try Utils.db.EXEC("CREATE TABLE " & Tab &
    "(code VarChar(8)," &
    "nom VarChar(30)," &
    Utils.db.AutoIncrement("lInd") & ")")

  Tab = "Fiches_HisEntTickets"
  Try Utils.db.EXEC("CREATE TABLE " & Tab &
    "(caisse Char(2)," &
    "vendeur Char(35)," &
    "numero Char(7)," &
    "date Date," &
    "client Char(30)," &
    "scheque Char(1)," &
    "mcheque Char(12)," &
    "nmcheque Char(30)," &
    "scarte  Char(1)," &
    "nmcarte Char(30)," &
    "mcarte Char(12)," &
    "sespeces Char(1)," &
    "mespeces Char(12)," &
    "scredit  Char(1)," &
    "mcredit Char(12)," &
    "nmcredit Char(30)," &
    "sbachat  Char(1)," &
    "mbachat Char(12)," &
    "scavoir  Char(1)," &
    "mavoir Char(12)," &
    "nmavoir Char(30)," &
    "mht Char(12)," &
    "mtva Char(12)," &
    "mttc Char(12)," &
    "savoir Char(1) ," &
    "INDEX (numero), " &
    Utils.db.AutoIncrement("lInd") & ")")

  Tab = "Fiches_HisLigTickets"
  Try Utils.db.EXEC("CREATE TABLE " & Tab &
    "(numero Char(7)," &
    "numlig Char(3)," &
    "code Char(15)," &
    "intitule  Char(50)," &
    "montant Char(12)," &
    "qte Char(12)," &
    "type Char(1)," &
    "fam Char(5)," &
    "INDEX (numero), " &
    Utils.db.AutoIncrement("lInd") & ")")

  Tab = "Fiches_EntTicketz"
  Try Utils.db.EXEC("CREATE TABLE " & Tab &
    "(caisse Char(2)," &
    "vendeur Char(35)," &
    "numero Char(7)," &
    "date Char(17)," &
    "client Char(30)," &
    "scheque Char(1)," &
    "mcheque Char(12)," &
    "nmcheque Char(30)," &
    "scarte  Char(1)," &
    "nmcarte Char(30)," &
    "mcarte Char(12)," &
    "sespeces Char(1)," &
    "mespeces Char(12)," &
    "scredit  Char(1)," &
    "mcredit Char(12)," &
    "nmcredit Char(30)," &
    "sbachat  Char(1)," &
    "mbachat Char(12)," &
    "scavoir  Char(1)," &
    "mavoir Char(12)," &
    "nmavoir Char(30)," &
    "sresto  Char(1)," &
    "mresto Char(12)," &
    "mht Char(12)," &
    "mtva Char(12)," &
    "mttc Char(12)," &
    "statut Char(1)," &
    "savoir Char(1) ," &
    "type Char(1) ," &
    "mrem Char(12)," &
    Utils.db.AutoIncrement("lInd") & ")")

  Tab = "Fiches_LigTicketz"
  Try Utils.db.EXEC("CREATE TABLE " & Tab &
    "(numero Char(7)," &
    "numlig Char(3)," &
    "code Char(15)," &
    "intitule  Char(50)," &
    "montant Char(12)," &
    "qte Char(12)," &
    "type Char(2)," &
    "fam Char(5)," &
    "mht Char(12)," &
    "mrem Char(12)," &
    Utils.db.AutoIncrement("lInd") & ")")

  Tab = "Fiches_Caisses"
  Try Utils.db.Exec("ALTER TABLE " & Tab & " ADD (connecte integer(1))")
  Try Utils.db.Exec("ALTER TABLE " & Tab & " ADD (typeimp char(10))")
  Try Utils.db.Exec("ALTER TABLE " & Tab & " ADD (type char(20))")
  Try Utils.db.Exec("ALTER TABLE " & Tab & " ADD (poste char(20))")
  Try Utils.db.Exec("ALTER TABLE " & Tab & " ADD (ecole TINYINT)")

  Tab = "Fiches_HisEntTickets"
  Try Utils.db.Exec("ALTER TABLE " & Tab & " ADD (caisse Char(2))")

  Tab = "Fiches_LigTicketz"
  Try Utils.db.Exec("ALTER TABLE " & Tab & " ADD (mrem Char(12))")

  Tab = "Fiches_Statut"
  Try Utils.db.exec("CREATE TABLE " & Tab &
    " (code CHAR(2) NOT NULL ," &
    "libelle CHAR(25) , " &
    "PRIMARY KEY (code))")

  Tab = "Fiches_Cli"
  Try Utils.db.Exec("ALTER TABLE " & Tab & " ADD (cli_statut char(2))")

End

Public Sub Maj201()

  Tab = "Fiches_EntTicketz"
  Try Utils.db.Exec("ALTER TABLE " & Tab & " ADD (vendeur Char(35))")
  Tab = "Fiches_HisEntTickets"
  Try Utils.db.Exec("ALTER TABLE " & Tab & " ADD (vendeur Char(35))")

End

Public Sub Maj202()

  Tab = "Fiches_Promo"
  Try Utils.db.exec("CREATE TABLE " & Tab &
    " (code CHAR(6) NOT NULL ," &
    "libelle CHAR(50) , " &
    "datedeb date ," &
    "datefin date ," &
    "PRIMARY KEY (code))")

  Tab = "Fiches_ArtPromo"
  Try Utils.db.exec("CREATE TABLE " & Tab &
    " (code_promo CHAR(6) NOT NULL ," &
    "code CHAR(15) NOT NULL ," &
    "libelle CHAR(50) , " &
    "pmp Decimal(12,3) ," &
    "pht Decimal(12,3) ," &
    "pttc Decimal(12,3) ," &
    "qte Decimal(12,3) ," &
    "PRIMARY KEY (code_promo, code))")

End

Public Sub Maj203()

  Tab = "Fiches_RemCliFam"
  Try Utils.db.exec("CREATE TABLE " & Tab &
    "(codec CHAR(8) NOT NULL ," &
    "codef CHAR(5) NOT NULL ," &
    "remise decimal(6,3) , " &
    "PRIMARY KEY (codec, codef))")

  Tab = "Fiches_PrdComp"
  Try Utils.db.exec("CREATE TABLE " & Tab &
    "(codep CHAR(15) NOT NULL ," &
    "codec CHAR(50) NOT NULL ," &
    "libelle CHAR(50) , " &
    "qte Char(12) ," &
    "PRIMARY KEY (codep, codec))")

  Tab = "Fiches_Art"
  Try Utils.db.Exec("ALTER TABLE " & Tab & " ADD (art_prdcomp TINYINT(1))")
  Try Utils.db.Exec("ALTER TABLE " & Tab & " ADD (art_impdetail TINYINT(1))")

  Tab = "Fiches_HisLigTickets"
  Try Utils.db.Exec("ALTER TABLE " & Tab & " ADD (mht Char(12))")
  Try Utils.db.Exec("ALTER TABLE " & Tab & " ADD (mrem Char(12))")

  Tab = "Fiches_Parametres"
  Try Utils.db.Exec("ALTER TABLE " & Tab & " ADD (viremc Char(8))")
  Try Utils.db.Exec("ALTER TABLE " & Tab & " ADD (viremchq Char(8))")
  Try Utils.db.Exec("ALTER TABLE " & Tab & " ADD (virema Char(8))")

  Utils.db.Exec("UPdate  " & tab & "  SET  viremc = &1, viremchq = &2, virema = &3", Start.LocalSettings["/Soc" & Start.Societe & "/Vic"], Start.LocalSettings["/Soc" & Start.Societe & "/Vichq"], Start.LocalSettings["/Soc" & Start.Societe & "/Viautre"])

End

Public Sub Maj204()

  Tab = "Fiches_CdBarre"
  Try Utils.db.exec("CREATE TABLE " & Tab &
    "(codep CHAR(15) NOT NULL ," &
    "codeb CHAR(13) NOT NULL ," &
    "PRIMARY KEY (codep, codeb))")
  Tab1 = "Fiches_Art"
  rResult = Utils.db.Exec("SELECT * from  " & Tab1 & "")
  If rResult.Available Then
    Repeat
      r2Result = Utils.db.Exec("SELECT * from  " & Tab & " where codep = &1 and codeb = &2", rResult!art_code, rResult!art_cbarre)
      If Not r2Result.Available Then
        Utils.db.Exec("Insert into  " & Tab & " (codep,codeb) values (&1,&2)", rResult!art_code, rResult!art_cbarre)
      Endif
    Until rResult.MoveNext()
  Endif

End

Public Sub Maj205()

  Tab = "Fiches_PrdComp"
  Try Utils.db.Exec("ALTER TABLE " & Tab & " change qte qte Char(12)")

End

Public Sub Maj206()

  Tab = "Fiches_Marques"
  Try Utils.db.Exec("ALTER TABLE " & Tab & " change intitule intitule Char(20)")

  Tab = "Fiches_Agenda"
  Try Utils.db.Exec("ALTER TABLE " & Tab & " add (nuser Char(35))")

End

Public Sub Maj207()

  Tab = "Fiches_EtiProd"
  Try Utils.db.Exec("ALTER TABLE " & Tab & " change code code Char(25)")

  Tab = "Fiches_EtiGond"
  Try Utils.db.Exec("ALTER TABLE " & Tab & " change code code Char(25)")

  Tab = "Fiches_Four"
  Try Utils.db.Exec("ALTER TABLE " & Tab & " add (fo_franco Decimal(12,2))")

  Tab = "Fiches_Art"
  Try Utils.db.Exec("ALTER TABLE " & Tab & " ADD (art_remcas1 Decimal(5,2))")
  Try Utils.db.Exec("ALTER TABLE " & Tab & " ADD (art_remcas2 Decimal(5,2))")
  Try Utils.db.Exec("ALTER TABLE " & Tab & " ADD (art_remcas3 Decimal(5,2))")
  Try Utils.db.Exec("ALTER TABLE " & Tab & " change art_cequ art_cequ Char(25)")
  Try Utils.db.Exec("ALTER TABLE " & Tab & " change art_tva art_tva Char(1)")

End

Public Sub Maj208()

  Tab = "Fiches_Txtmo"
  Try Utils.db.Exec("ALTER TABLE " & Tab & " change code_txtmo code_txtmo Char(5)")
  Try Utils.db.Exec("ALTER TABLE " & Tab & " ADD (prvt_txtmo Decimal(12,3))")
  Tab = "Fiches_Art"
  Try Utils.db.Exec("ALTER TABLE " & Tab & " ADD (art_datefbt Date)")
  Try Utils.db.Exec("ALTER TABLE " & Tab & " ADD (art_pbfbt Decimal(12,3))")
  Try Utils.db.Exec("ALTER TABLE " & Tab & " ADD (art_ddatefbt Date)")
  Try Utils.db.Exec("ALTER TABLE " & Tab & " ADD (art_centrale Char(2))")
  Try Utils.db.Exec("ALTER TABLE " & Tab & " ADD (art_refcentrale Char(13))")
  Tab = "Fiches_Centrales"
  Try Utils.db.exec("CREATE TABLE " & Tab &
    " (code CHAR(2) NOT NULL ," &
    "libelle CHAR(25) , " &
    "PRIMARY KEY (code))")
  Tab = "Fiches_Four"
  Try Utils.db.Exec("ALTER TABLE " & Tab & " ADD (fo_centrale TINYINT(1))")
  Try Utils.db.Exec("ALTER TABLE " & Tab & " ADD (fo_ccentrale Char(2))")
  Tab = "Fiches_Mo"
  Try Utils.db.Exec("ALTER TABLE " & Tab & " ADD (mo_prvt Decimal(12,3))")
  Try Utils.db.Exec("ALTER TABLE " & Tab & " ADD (mo_marge Decimal(12,3))")
  Tab = "Fiches_Ligbl"
  Try Utils.db.Exec("ALTER TABLE " & Tab & " ADD (mrgart_ligbl Decimal(12,3))")
  Try Utils.db.Exec("ALTER TABLE " & Tab & " ADD (mrgmo_ligbl Decimal(12,3))")

End

Public Sub Maj209()

  Tab = "Fiches_Carte"
  Try Utils.db.Exec("CREATE TABLE " & Tab &
    " (code int(13) NOT NULL ," &
    "rs_soc CHAR(9)," &
    "nom CHAR(35)," &
    "pnm CHAR(35)," &
    "adr1 CHAR(35)," &
    "adr2 CHAR(35)," &
    "cd_ptl CHAR(5)," &
    "ville CHAR(35)," &
    "email CHAR(40)," &
    "tel_bur CHAR(16)," &
    "tel_dom CHAR(16)," &
    "tel_poste CHAR(16)," &
    "pble CHAR(16)," &
    "fx1 CHAR(16)," &
    "fx2 CHAR(16)," &
    "datec date ," &
    "datef date ," &
    "rem TINYINT," &
    "promo TINYINT," &
    "tp1 Decimal(12,3), " &
    "tp2 Decimal(12,3), " &
    "tg1 Decimal(12,3), " &
    "tg2 Decimal(12,3), " &
    "obs Text," &
    "PRIMARY KEY (code))")

  Tab = "Fiches_HisEntTickets"
  Try Utils.db.Exec("ALTER TABLE " & Tab & " ADD (carte Char(13))")
  Try Utils.db.Exec("ALTER TABLE " & Tab & " ADD (points Decimal(12,3))")
  Try Utils.db.Exec("ALTER TABLE " & Tab & " ADD (sbonus Char(1))")
  Try Utils.db.Exec("ALTER TABLE " & Tab & " ADD (mbonus Char(12))")

  Tab = "Fiches_EntTicketz"
  Try Utils.db.Exec("ALTER TABLE " & Tab & " ADD (carte Char(13))")
  Try Utils.db.Exec("ALTER TABLE " & Tab & " ADD (points Decimal(12,3))")
  Try Utils.db.Exec("ALTER TABLE " & Tab & " ADD (sbonus Char(1))")
  Try Utils.db.Exec("ALTER TABLE " & Tab & " ADD (mbonus Char(12))")

  'Mise à jour des caisses
  Tab1 = "Fiches_Caisses"
  rResult = Utils.db.Exec("SELECT * FROM " & Tab1 & " ")
  If rResult.Available Then
    Repeat
      Tab = "Fiches_EntTickets" & rResult!code
      Try Utils.db.Exec("ALTER TABLE " & Tab & " ADD (carte Char(13))")
      Try Utils.db.Exec("ALTER TABLE " & Tab & " ADD (points Decimal(12,3))")
      Try Utils.db.Exec("ALTER TABLE " & Tab & " ADD (sbonus Char(1))")
      Try Utils.db.Exec("ALTER TABLE " & Tab & " ADD (mbonus Char(12))")
      Tab = "Fiches_LigTickets" & rResult!code
      Try Utils.db.Exec("ALTER TABLE " & Tab & " ADD (mht Char(12))")
      Try Utils.db.Exec("ALTER TABLE " & Tab & " ADD (mrem Char(12))")
    Until rResult.MoveNext()
  Endif

  'Mise à jour des préférences pour la gestion des coupons
  Start.LocalSettings["/Soc" & Start.Societe & "/Coupon"] = 0

End

Public Sub Maj210()

  Tab = "Fiches_Carte"
  Try Utils.db.Exec("ALTER TABLE " & Tab & " ADD (cb Char(13))")

  Tab = "Fiches_Art"
  Try Utils.db.Exec("ALTER TABLE " & Tab & " ADD (art_bonus Decimal(5,2))")

  Tab1 = "Fiches_Caisses"
  rResult = Utils.db.Exec("SELECT * FROM " & Tab1 & " ")
  If rResult.Available Then
    Repeat
      Tab = "Fiches_LigTickets" & rResult!code
      Try Utils.db.Exec("ALTER TABLE " & Tab & " ADD (mtva Char(12))")
      Try Utils.db.Exec("ALTER TABLE " & Tab & " ADD (block Char(4))")
    Until rResult.MoveNext()
  Endif

  Tab = "Fiches_LigTicketz"
  Try Utils.db.Exec("ALTER TABLE " & Tab & " ADD (mtva Char(12))")
  Try Utils.db.Exec("ALTER TABLE " & Tab & " ADD (block Char(4))")

End

Public Sub Maj211()

  Tab1 = "Fiches_Caisses"
  rResult = Utils.db.Exec("SELECT * FROM " & Tab1 & " ")
  If rResult.Available Then
    Repeat
      Tab = "Fiches_LigTickets" & rResult!code
      Try Utils.db.Exec("ALTER TABLE " & Tab & " ADD (mtva Char(12))")
      Try Utils.db.Exec("ALTER TABLE " & Tab & " ADD (block Char(4))")
    Until rResult.MoveNext()
  Endif

  Tab = "Fiches_LigTicketz"
  Try Utils.db.Exec("ALTER TABLE " & Tab & " ADD (mtva Char(12))")
  Try Utils.db.Exec("ALTER TABLE " & Tab & " ADD (block Char(4))")

  Tab = "Fiches_Cli"
  Try Utils.db.Exec("ALTER TABLE " & Tab & " ADD (cli_rs_soc2 CHAR(9))")
  Try Utils.db.Exec("ALTER TABLE " & Tab & " ADD (cli_nom2 CHAR(35))")
  Try Utils.db.Exec("ALTER TABLE " & Tab & " ADD (cli_pnm2 CHAR(35))")
  Try Utils.db.Exec("ALTER TABLE " & Tab & " ADD (cli_adr12 CHAR(35))")
  Try Utils.db.Exec("ALTER TABLE " & Tab & " ADD (cli_adr22 CHAR(35))")
  Try Utils.db.Exec("ALTER TABLE " & Tab & " ADD (cli_cd_ptl2 CHAR(5))")
  Try Utils.db.Exec("ALTER TABLE " & Tab & " ADD (cli_ville2 CHAR(35))")
  Try Utils.db.Exec("ALTER TABLE " & Tab & " ADD (cli_cnt1 CHAR(17))")
  Try Utils.db.Exec("ALTER TABLE " & Tab & " ADD (cli_cnt2 CHAR(40))")
  Try Utils.db.Exec("ALTER TABLE " & Tab & " ADD (cli_cnt3 CHAR(25))")
  Try Utils.db.Exec("ALTER TABLE " & Tab & " ADD (cli_cnt4 CHAR(17))")
  Try Utils.db.Exec("ALTER TABLE " & Tab & " ADD (cli_cnt5 CHAR(40))")
  Try Utils.db.Exec("ALTER TABLE " & Tab & " ADD (cli_cnt6 CHAR(25))")
  Try Utils.db.Exec("ALTER TABLE " & Tab & " ADD (cli_cnt7 CHAR(17))")
  Try Utils.db.Exec("ALTER TABLE " & Tab & " ADD (cli_cnt8 CHAR(40))")
  Try Utils.db.Exec("ALTER TABLE " & Tab & " ADD (cli_cnt9 CHAR(25))")
  Try Utils.db.Exec("ALTER TABLE " & Tab & " ADD (cli_cnt10 CHAR(17))")
  Try Utils.db.Exec("ALTER TABLE " & Tab & " ADD (cli_cnt11 CHAR(40))")
  Try Utils.db.Exec("ALTER TABLE " & Tab & " ADD (cli_cnt12 CHAR(25))")
  Try Utils.db.Exec("ALTER TABLE " & Tab & " ADD (cli_cnt13 CHAR(17))")
  Try Utils.db.Exec("ALTER TABLE " & Tab & " ADD (cli_cnt14 CHAR(40))")
  Try Utils.db.Exec("ALTER TABLE " & Tab & " ADD (cli_cnt15 CHAR(25))")

  Tab = "Fiches_Four"
  Try Utils.db.Exec("ALTER TABLE " & Tab & " ADD (fo_cnt1 CHAR(17))")
  Try Utils.db.Exec("ALTER TABLE " & Tab & " ADD (fo_cnt2 CHAR(40))")
  Try Utils.db.Exec("ALTER TABLE " & Tab & " ADD (fo_cnt3 CHAR(25))")
  Try Utils.db.Exec("ALTER TABLE " & Tab & " ADD (fo_cnt4 CHAR(17))")
  Try Utils.db.Exec("ALTER TABLE " & Tab & " ADD (fo_cnt5 CHAR(40))")
  Try Utils.db.Exec("ALTER TABLE " & Tab & " ADD (fo_cnt6 CHAR(25))")
  Try Utils.db.Exec("ALTER TABLE " & Tab & " ADD (fo_cnt7 CHAR(17))")
  Try Utils.db.Exec("ALTER TABLE " & Tab & " ADD (fo_cnt8 CHAR(40))")
  Try Utils.db.Exec("ALTER TABLE " & Tab & " ADD (fo_cnt9 CHAR(25))")
  Try Utils.db.Exec("ALTER TABLE " & Tab & " ADD (fo_cnt10 CHAR(17))")
  Try Utils.db.Exec("ALTER TABLE " & Tab & " ADD (fo_cnt11 CHAR(40))")
  Try Utils.db.Exec("ALTER TABLE " & Tab & " ADD (fo_cnt12 CHAR(25))")
  Try Utils.db.Exec("ALTER TABLE " & Tab & " ADD (fo_cnt13 CHAR(17))")
  Try Utils.db.Exec("ALTER TABLE " & Tab & " ADD (fo_cnt14 CHAR(40))")
  Try Utils.db.Exec("ALTER TABLE " & Tab & " ADD (fo_cnt15 CHAR(25))")

  Tab = "Fiches_LigblM"
  Try Utils.db.Exec("ALTER TABLE " & Tab & " ADD (mrgart_ligbl Decimal(12,3))")
  Try Utils.db.Exec("ALTER TABLE " & Tab & " ADD (mrgmo_ligbl Decimal(12,3))")

End

Public Sub Maj212()

  Tab1 = "Fiches_Caisses"
  rResult = Utils.db.Exec("SELECT * FROM " & Tab1 & " ")
  If rResult.Available Then
    Repeat
      Tab = "Fiches_LigTickets" & rResult!code
      Try Utils.db.Exec("ALTER TABLE " & Tab & " ADD (mtva Char(12))")
      Try Utils.db.Exec("ALTER TABLE " & Tab & " ADD (block Char(4))")
    Until rResult.MoveNext()
  Endif

  Tab = "Fiches_LigTicketz"
  Try Utils.db.Exec("ALTER TABLE " & Tab & " ADD (mtva Char(12))")
  Try Utils.db.Exec("ALTER TABLE " & Tab & " ADD (block Char(4))")

  Tab = "Fiches_AdrlivC"
  Try Utils.db.EXEC("CREATE TABLE " & Tab &
    " (code Int NOT NULL, " &
    "rs_soc CHAR(9)," &
    "nom CHAR(35)," &
    "pnm CHAR(35)," &
    "adr1 CHAR(35)," &
    "adr2 CHAR(35)," &
    "cd_ptl CHAR(5)," &
    "ville CHAR(35)," &
    Utils.db.AutoIncrement("num") & ")")

  Tab = "Fiches_ContactC"
  Try Utils.db.EXEC("CREATE TABLE " & Tab &
    " (code Int NOT NULL, " &
    "nom CHAR(35)," &
    "pnm CHAR(35)," &
    "fonction CHAR(35)," &
    "tel CHAR(16)," &
    "mail CHAR(40)," &
    Utils.db.AutoIncrement("num") & ")")

  Tab = "Fiches_ContactF"
  Try Utils.db.EXEC("CREATE TABLE " & Tab &
    " (code Int NOT NULL, " &
    "nom CHAR(35)," &
    "pnm CHAR(35)," &
    "fonction CHAR(35)," &
    "tel CHAR(16)," &
    "mail CHAR(40)," &
    Utils.db.AutoIncrement("num") & ")")

End

Public Sub Maj213()

  Tab = "Fiches_Cli"
  Utils.db.Exec("ALTER TABLE " & Tab & " change cli_num_cpt cli_num_cpt CHAR(11)")

  Tab = "Fiches_Four"
  Utils.db.Exec("ALTER TABLE " & Tab & " change fo_num_cpt fo_num_cpt CHAR(11)")

End

Public Sub Maj215()

  Tab = "Fiches_Acomptes"
  Try Utils.db.EXEC("CREATE TABLE " & Tab &
    "(intitule Char(30)," &
    "type Char(15)," &
    "montant Char(12)," &
    "date date ," &
    Utils.db.AutoIncrement("lInd") & ")")

  Tab = "Fiches_Parametres"
  Try Utils.db.Exec("ALTER TABLE " & Tab & " ADD (jrnal4 Char(2))")

  Tab = "Fiches_Caisses"
  Try Utils.db.Exec("ALTER TABLE " & Tab & " change dntk dntk CHAR(7)")

End

Public Sub Maj215a()

  Tab = "Fiches_Caisses"
  Try Utils.db.Exec("ALTER TABLE " & Tab & " change dntk dntk CHAR(7)")

End

Public Sub Maj216()

  Tab = "Fiches_Cli"
  Try Utils.db.Exec("ALTER TABLE " & Tab & " ADD (cli_reg char(15))")

End

Public Sub Maj217()

  Tab = "Fiches_Traites"
  Try Utils.db.EXEC("CREATE TABLE " & Tab &
    "(code Char(8) ," &
    "montant Char(12) ," &
    "date date ," &
    "datech date ," &
    "numfac Char(12) ," &
    "imp TINYINT," &
    Utils.db.AutoIncrement("lInd") & ")")

End

Public Sub Maj217a()

  Tab = "Fiches_Art"
  Try Utils.db.Exec("ALTER TABLE " & Tab & " ADD (INDEX id_code (art_code))")
  Try Utils.db.Exec("ALTER TABLE " & Tab & " ADD (INDEX id_design (art_design))")
  Try Utils.db.Exec("ALTER TABLE " & Tab & " ADD (INDEX id_fam (art_fam))")
  Try Utils.db.Exec("ALTER TABLE " & Tab & " ADD (INDEX id_four (art_four))")
  Try Utils.db.Exec("ALTER TABLE " & Tab & " ADD (INDEX id_cequ (art_cequ))")
  Try Utils.db.Exec("ALTER TABLE " & Tab & " ADD (INDEX id_cbarre (art_cbarre))")
  Try Utils.db.Exec("ALTER TABLE " & Tab & " ADD (INDEX id_cfour (art_cfour))")
  Try Utils.db.Exec("ALTER TABLE " & Tab & " ADD (INDEX id_refcentrale (art_refcentrale))")
  Try Utils.db.Exec("ALTER TABLE " & Tab & " ADD (INDEX id_casier (art_casier))")
  Try Utils.db.Exec("ALTER TABLE " & Tab & " ADD (INDEX id_code_fam_four (art_code, art_fam, art_four))")
  Try Utils.db.Exec("ALTER TABLE " & Tab & " ADD (INDEX id_code_four_fam (art_code, art_four, art_fam))")
  Try Utils.db.Exec("ALTER TABLE " & Tab & " ADD (INDEX id_fam_code (art_fam, art_code))")
  Try Utils.db.Exec("ALTER TABLE " & Tab & " ADD (INDEX id_four_code (art_four, art_code))")
  Try Utils.db.Exec("ALTER TABLE " & Tab & " ADD (INDEX id_casier_fam (art_casier, art_fam))")

  Tab = "Fiches_Cli"
  Try Utils.db.Exec("ALTER TABLE " & Tab & " ADD (INDEX id_code (cli_code))")
  Try Utils.db.Exec("ALTER TABLE " & Tab & " ADD (INDEX id_nom (cli_nom))")
  Try Utils.db.Exec("ALTER TABLE " & Tab & " ADD (INDEX id_adr1 (cli_adr1))")
  Try Utils.db.Exec("ALTER TABLE " & Tab & " ADD (INDEX id_adr2 (cli_adr2))")
  Try Utils.db.Exec("ALTER TABLE " & Tab & " ADD (INDEX id_cdptl (cli_cd_ptl))")
  Try Utils.db.Exec("ALTER TABLE " & Tab & " ADD (INDEX id_ville (cli_ville))")

  Tab = "Fiches_Four"
  Try Utils.db.Exec("ALTER TABLE " & Tab & " ADD (INDEX id_code (fo_code))")
  Try Utils.db.Exec("ALTER TABLE " & Tab & " ADD (INDEX id_nom (fo_nom))")
  Try Utils.db.Exec("ALTER TABLE " & Tab & " ADD (INDEX id_adr1 (fo_adr1))")
  Try Utils.db.Exec("ALTER TABLE " & Tab & " ADD (INDEX id_adr2 (fo_adr2))")
  Try Utils.db.Exec("ALTER TABLE " & Tab & " ADD (INDEX id_cdptl (fo_cd_ptl))")
  Try Utils.db.Exec("ALTER TABLE " & Tab & " ADD (INDEX id_ville (fo_ville))")

  Tab = "Fiches_HisEntTickets"
  Try Utils.db.Exec("ALTER TABLE " & Tab & " ADD (INDEX id_caisse (caisse))")
  Try Utils.db.Exec("ALTER TABLE " & Tab & " ADD (INDEX id_numero (numero))")
  Try Utils.db.Exec("ALTER TABLE " & Tab & " ADD (INDEX id_date (date))")
  Try Utils.db.Exec("ALTER TABLE " & Tab & " ADD (INDEX id_vendeur (vendeur))")
  Try Utils.db.Exec("ALTER TABLE " & Tab & " ADD (INDEX id_montanttc (montanttc))")

  Tab = "Fiches_HisLigTickets"
  Try Utils.db.Exec("ALTER TABLE " & Tab & " ADD (INDEX id_numero(numero))")
  Try Utils.db.Exec("ALTER TABLE " & Tab & " ADD (INDEX id_numlig (numlig))")
  Try Utils.db.Exec("ALTER TABLE " & Tab & " ADD (INDEX id_code (code))")
  Try Utils.db.Exec("ALTER TABLE " & Tab & " ADD (INDEX id_type (type))")

  Tab = "Fiches_HisentMat"
  Try Utils.db.Exec("ALTER TABLE " & Tab & " ADD (INDEX id_numserie (numserie))")
  Try Utils.db.Exec("ALTER TABLE " & Tab & " ADD (INDEX id_codep (codep))")
  Try Utils.db.Exec("ALTER TABLE " & Tab & " ADD (INDEX id_marque (marque))")
  Try Utils.db.Exec("ALTER TABLE " & Tab & " ADD (INDEX id_numfac (numfac))")

  Tab = "Fiches_HistoFac"
  Try Utils.db.Exec("ALTER TABLE " & Tab & " ADD (INDEX id_numfac (numfac))")
  Try Utils.db.Exec("ALTER TABLE " & Tab & " ADD (INDEX id_clifac (cdclifac))")
  Try Utils.db.Exec("ALTER TABLE " & Tab & " ADD (INDEX id_totfac (totfac))")
  Try Utils.db.Exec("ALTER TABLE " & Tab & " ADD (INDEX id_datefac (datefac))")
  Try Utils.db.Exec("ALTER TABLE " & Tab & " ADD (INDEX id_numserie(numserie))")

  Tab = "Fiches_HistoLigfac"
  Try Utils.db.Exec("ALTER TABLE " & Tab & " ADD (INDEX id_num (num_ligfac))")
  Try Utils.db.Exec("ALTER TABLE " & Tab & " ADD (INDEX id_numlig (numlig_ligfac))")
  Try Utils.db.Exec("ALTER TABLE " & Tab & " ADD (INDEX id_code (code_ligfac))")
  Try Utils.db.Exec("ALTER TABLE " & Tab & " ADD (INDEX id_fam (fam_ligfac))")
  Try Utils.db.Exec("ALTER TABLE " & Tab & " ADD (INDEX id_typel (typel_ligfac))")

  Tab = "Fiches_HistoFacM"
  Try Utils.db.Exec("ALTER TABLE " & Tab & " ADD (INDEX id_numfac (numfac))")
  Try Utils.db.Exec("ALTER TABLE " & Tab & " ADD (INDEX id_cdclifac (cdclifac))")
  Try Utils.db.Exec("ALTER TABLE " & Tab & " ADD (INDEX id_totfac (totfac))")
  Try Utils.db.Exec("ALTER TABLE " & Tab & " ADD (INDEX id_datefac (datefac))")
  Try Utils.db.Exec("ALTER TABLE " & Tab & " ADD (INDEX id_numserie(numserie))")

  Tab = "Fiches_HistoLigfacM"
  Try Utils.db.Exec("ALTER TABLE " & Tab & " ADD (INDEX id_num (num_ligfac))")
  Try Utils.db.Exec("ALTER TABLE " & Tab & " ADD (INDEX id_numlig (numlig_ligfac))")
  Try Utils.db.Exec("ALTER TABLE " & Tab & " ADD (INDEX id_code (code_ligfac))")
  Try Utils.db.Exec("ALTER TABLE " & Tab & " ADD (INDEX id_fam (fam_ligfac))")
  Try Utils.db.Exec("ALTER TABLE " & Tab & " ADD (INDEX id_typel (typel_ligfac))")

  Tab = "Fiches_Materiels"
  Try Utils.db.Exec("ALTER TABLE " & Tab & " ADD (INDEX id_serie (mat_serie))")
  Try Utils.db.Exec("ALTER TABLE " & Tab & " ADD (INDEX id_code (mat_code))")
  Try Utils.db.Exec("ALTER TABLE " & Tab & " ADD (INDEX id_design(mat_design))")
  Try Utils.db.Exec("ALTER TABLE " & Tab & " ADD (INDEX id_fam (mat_fam))")
  Try Utils.db.Exec("ALTER TABLE " & Tab & " ADD (INDEX id_four (mat_four))")
  Try Utils.db.Exec("ALTER TABLE " & Tab & " ADD (INDEX id_cequ (mat_cequ))")
  Try Utils.db.Exec("ALTER TABLE " & Tab & " ADD (INDEX id_cbarre (mat_cbarre))")
  Try Utils.db.Exec("ALTER TABLE " & Tab & " ADD (INDEX id_cfour (mat_cfour))")
  Try Utils.db.Exec("ALTER TABLE " & Tab & " ADD (INDEX id_marque (mat_marque))")

End

Public Sub Maj218()

  Tab = "Fiches_Suivis"
  Try Utils.db.EXEC("CREATE TABLE " & Tab &
    "(code Char(8) ," &
    "nom Char(70) ," &
    "numdev VarChar(12) ," &
    "datedev date ," &
    "numfac Char(12) ," &
    "datefac date ," &
    "qte Decimal(12,2), " &
    "pu Decimal(12,2), " &
    "total Decimal(12,2), " &
    "margemo Decimal(12,2), " &
    "ach Decimal(12,2), " &
    "vtes Decimal(12,2), " &
    "qte2 Decimal(12,2), " &
    "pu2 Decimal(12,2), " &
    "total2 Decimal(12,2), " &
    "margemo2 Decimal(12,2), " &
    "ach2 Decimal(12,2), " &
    "vtes2 Decimal(12,2), " &
    "INDEX (code), " &
    "INDEX (numdev), " &
    "INDEX (numfac), " &
    Utils.db.AutoIncrement("lInd") & ")")

  Tab = "Fiches_Art"
  Try Utils.db.Exec("ALTER TABLE " & Tab & " change art_photo art_photo Char(35)")

  Tab = "Fiches_Bl"
  Try Utils.db.Exec("ALTER TABLE " & Tab & " add htbl TINYINT")

  Tab = "Fiches_Art"
  Try Utils.db.Exec("ALTER TABLE " & Tab & " modify art_photo VarChar(35)")
  Try Utils.db.Exec("ALTER TABLE " & Tab & " modify art_design VarChar(50)")
  Try Utils.db.Exec("ALTER TABLE " & Tab & " modify art_design2 VarChar(50)")
  Try Utils.db.Exec("ALTER TABLE " & Tab & " modify art_marque VarChar(20)")
  Try Utils.db.Exec("ALTER TABLE " & Tab & " modify art_cequ VarChar(15)")
  Try Utils.db.Exec("ALTER TABLE " & Tab & " modify art_barre VarChar(15)")
  Try Utils.db.Exec("ALTER TABLE " & Tab & " modify art_cfour VarChar(25)")
  Try Utils.db.Exec("ALTER TABLE " & Tab & " modify art_mincom VarChar(12)")

  Tab = "Fiches_Mat"
  Try Utils.db.Exec("ALTER TABLE " & Tab & " modify art_photo VarChar(35)")
  Try Utils.db.Exec("ALTER TABLE " & Tab & " modify art_design VarChar(50)")
  Try Utils.db.Exec("ALTER TABLE " & Tab & " modify art_design2 VarChar(50)")
  Try Utils.db.Exec("ALTER TABLE " & Tab & " modify art_marque VarChar(20)")
  Try Utils.db.Exec("ALTER TABLE " & Tab & " modify art_type VarChar(15)")

  Tab = "Fiches_Marques"
  Try Utils.db.Exec("ALTER TABLE " & Tab & " modify intitule VarChar(20)")

  Tab = "Fiches_Libelles"
  Try Utils.db.Exec("ALTER TABLE " & Tab & " modify intitule VarChar(30)")

  Tab = "Fiches_Mvt"
  Try Utils.db.Exec("ALTER TABLE " & Tab & " modify intitule VarChar(40)")
  Try Utils.db.Exec("ALTER TABLE " & Tab & " modify libelle VarChar(30)")

  Tab = "Fiches_Mvt1"
  Try Utils.db.Exec("ALTER TABLE " & Tab & " modify intitule VarChar(40)")
  Try Utils.db.Exec("ALTER TABLE " & Tab & " modify libelle VarChar(30)")

  Tab = "Fiches_Mvt2"
  Try Utils.db.Exec("ALTER TABLE " & Tab & " modify intitule VarChar(40)")
  Try Utils.db.Exec("ALTER TABLE " & Tab & " modify libelle VarChar(30)")

  Tab = "Fiches_Mvt3"
  Try Utils.db.Exec("ALTER TABLE " & Tab & " modify intitule VarChar(40)")
  Try Utils.db.Exec("ALTER TABLE " & Tab & " modify libelle VarChar(30)")

  Tab = "Fiches_Mvt4"
  Try Utils.db.Exec("ALTER TABLE " & Tab & " modify intitule VarChar(40)")
  Try Utils.db.Exec("ALTER TABLE " & Tab & " modify libelle VarChar(30)")

  Tab = "Fiches_Mvt5"
  Try Utils.db.Exec("ALTER TABLE " & Tab & " modify intitule VarChar(40)")
  Try Utils.db.Exec("ALTER TABLE " & Tab & " modify libelle VarChar(30)")

  Tab = "Fiches_Four"
  Try Utils.db.Exec("ALTER TABLE " & Tab & " modify fo_nom VarChar(35)")
  Try Utils.db.Exec("ALTER TABLE " & Tab & " modify fo_pnm VarChar(35)")
  Try Utils.db.Exec("ALTER TABLE " & Tab & " modify fo_adr1 VarChar(35)")
  Try Utils.db.Exec("ALTER TABLE " & Tab & " modify fo_adr2 VarChar(35)")
  Try Utils.db.Exec("ALTER TABLE " & Tab & " modify fo_ville VarChar(35)")
  Try Utils.db.Exec("ALTER TABLE " & Tab & " modify fo_email VarChar(150)")
  Try Utils.db.Exec("ALTER TABLE " & Tab & " modify (fo_cnt1 VARCHAR(17))")
  Try Utils.db.Exec("ALTER TABLE " & Tab & " modify (fo_cnt2 VARCHAR(40))")
  Try Utils.db.Exec("ALTER TABLE " & Tab & " modify (fo_cnt3 VARCHAR(25))")
  Try Utils.db.Exec("ALTER TABLE " & Tab & " modify (fo_cnt4 VARCHAR(17))")
  Try Utils.db.Exec("ALTER TABLE " & Tab & " modify (fo_cnt5 VARCHAR(40))")
  Try Utils.db.Exec("ALTER TABLE " & Tab & " modify (fo_cnt6 VARCHAR(25))")
  Try Utils.db.Exec("ALTER TABLE " & Tab & " modify (fo_cnt7 VARCHAR(17))")
  Try Utils.db.Exec("ALTER TABLE " & Tab & " modify (fo_cnt8 VARCHAR(40))")
  Try Utils.db.Exec("ALTER TABLE " & Tab & " modify (fo_cnt9 VARCHAR(25))")
  Try Utils.db.Exec("ALTER TABLE " & Tab & " modify (fo_cnt10 VARCHAR(17))")
  Try Utils.db.Exec("ALTER TABLE " & Tab & " modify (fo_cnt11 VARCHAR(40))")
  Try Utils.db.Exec("ALTER TABLE " & Tab & " modify (fo_cnt12 VARCHAR(25))")
  Try Utils.db.Exec("ALTER TABLE " & Tab & " modify (fo_cnt13 VARCHAR(17))")
  Try Utils.db.Exec("ALTER TABLE " & Tab & " modify (fo_cnt14 VARCHAR(40))")
  Try Utils.db.Exec("ALTER TABLE " & Tab & " modify (fo_cnt15 VARCHAR(25))")

  Tab = "Fiches_Cli"
  Try Utils.db.Exec("ALTER TABLE " & Tab & " modify cli_nom VarChar(35)")
  Try Utils.db.Exec("ALTER TABLE " & Tab & " modify cli_pnm VarChar(35)")
  Try Utils.db.Exec("ALTER TABLE " & Tab & " modify cli_adr1 VarChar(35)")
  Try Utils.db.Exec("ALTER TABLE " & Tab & " modify cli_adr2 VarChar(35)")
  Try Utils.db.Exec("ALTER TABLE " & Tab & " modify cli_ville VarChar(35)")
  Try Utils.db.Exec("ALTER TABLE " & Tab & " modify cli_email VarChar(150)")
  Try Utils.db.Exec("ALTER TABLE " & Tab & " modify cli_nom2 VarChar(35)")
  Try Utils.db.Exec("ALTER TABLE " & Tab & " modify cli_pnm2 VarChar(35)")
  Try Utils.db.Exec("ALTER TABLE " & Tab & " modify cli_adr12 VarChar(35)")
  Try Utils.db.Exec("ALTER TABLE " & Tab & " modify cli_adr22 VarChar(35)")
  Try Utils.db.Exec("ALTER TABLE " & Tab & " modify cli_ville2 VarChar(35)")
  Try Utils.db.Exec("ALTER TABLE " & Tab & " modify cli_fx1 VarChar(16)")
  Try Utils.db.Exec("ALTER TABLE " & Tab & " modify cli_fx2 VarChar(16)")
  Try Utils.db.Exec("ALTER TABLE " & Tab & " modify (cli_cnt1 VARCHAR(17))")
  Try Utils.db.Exec("ALTER TABLE " & Tab & " modify (cli_cnt2 VARCHAR(40))")
  Try Utils.db.Exec("ALTER TABLE " & Tab & " modify (cli_cnt3 VARCHAR(25))")
  Try Utils.db.Exec("ALTER TABLE " & Tab & " modify (cli_cnt4 VARCHAR(17))")
  Try Utils.db.Exec("ALTER TABLE " & Tab & " modify (cli_cnt5 VARCHAR(40))")
  Try Utils.db.Exec("ALTER TABLE " & Tab & " modify (cli_cnt6 VARCHAR(25))")
  Try Utils.db.Exec("ALTER TABLE " & Tab & " modify (cli_cnt7 VARCHAR(17))")
  Try Utils.db.Exec("ALTER TABLE " & Tab & " modify (cli_cnt8 VARCHAR(40))")
  Try Utils.db.Exec("ALTER TABLE " & Tab & " modify (cli_cnt9 VARCHAR(25))")
  Try Utils.db.Exec("ALTER TABLE " & Tab & " modify (cli_cnt10 VARCHAR(17))")
  Try Utils.db.Exec("ALTER TABLE " & Tab & " modify (cli_cnt11 VARCHAR(40))")
  Try Utils.db.Exec("ALTER TABLE " & Tab & " modify (cli_cnt12 VARCHAR(25))")
  Try Utils.db.Exec("ALTER TABLE " & Tab & " modify (cli_cnt13 VARCHAR(17))")
  Try Utils.db.Exec("ALTER TABLE " & Tab & " modify (cli_cnt14 VARCHAR(40))")
  Try Utils.db.Exec("ALTER TABLE " & Tab & " modify (cli_cnt15 VARCHAR(25))")
  Try Utils.db.Exec("ALTER TABLE " & Tab & " modify (cli_reg VARCHAR(15))")

  Tab = "Fiches_Cli_Vtl"
  Try Utils.db.Exec("ALTER TABLE " & Tab & " modify intitule_vtl VarChar(40)")

  Tab = "Fiches_Four_Vtl"
  Try Utils.db.Exec("ALTER TABLE " & Tab & " modify intitule_fvtl VarChar(40)")

  Tab = "Fiches_Comptes"
  Try Utils.db.Exec("ALTER TABLE " & Tab & " modify intitule VarChar(40)")

  Tab = "Fiches_Relances"
  Try Utils.db.Exec("ALTER TABLE " & Tab & " modify intitule VarChar(30)")
  Try Utils.db.Exec("ALTER TABLE " & Tab & " modify libelle VarChar(30)")

  Tab = "Fiches_Fam"
  Try Utils.db.Exec("ALTER TABLE " & Tab & " modify libell_fam VarChar(30)")

  Tab = "Fiches_Mo"
  Try Utils.db.Exec("ALTER TABLE " & Tab & " modify mo_design VarChar(50)")

  Tab = "Fiches_Txtmo"
  Try Utils.db.Exec("ALTER TABLE " & Tab & " modify libell_txtmo VarChar(25)")

  Tab = "Fiches_Bl"
  Try Utils.db.Exec("ALTER TABLE " & Tab & " modify cvclibl VarChar(9)")
  Try Utils.db.Exec("ALTER TABLE " & Tab & " modify nmclibl VarChar(35)")
  Try Utils.db.Exec("ALTER TABLE " & Tab & " modify pnmclibl VarChar(35)")
  Try Utils.db.Exec("ALTER TABLE " & Tab & " modify adr1bl VarChar(35)")
  Try Utils.db.Exec("ALTER TABLE " & Tab & " modify adr2bl VarChar(35)")
  Try Utils.db.Exec("ALTER TABLE " & Tab & " modify villebl VarChar(35)")
  Try Utils.db.Exec("ALTER TABLE " & Tab & " modify acpt VarChar(12)")
  Try Utils.db.Exec("ALTER TABLE " & Tab & " modify mreg VarChar(10)")
  Try Utils.db.Exec("ALTER TABLE " & Tab & " modify reg VarChar(15)")
  Try Utils.db.Exec("ALTER TABLE " & Tab & " modify numserie VarChar(15)")
  Try Utils.db.Exec("ALTER TABLE " & Tab & " modify codep VarChar(15)")
  Try Utils.db.Exec("ALTER TABLE " & Tab & " modify mtreg VarChar(12)")
  Try Utils.db.Exec("ALTER TABLE " & Tab & " modify desg1 VarChar(50)")
  Try Utils.db.Exec("ALTER TABLE " & Tab & " modify desg2 VarChar(50)")
  Try Utils.db.Exec("ALTER TABLE " & Tab & " modify marque VarChar(15)")
  Try Utils.db.Exec("ALTER TABLE " & Tab & " modify typemat VarChar(15)")

  Tab = "Fiches_Ligbl"
  Try Utils.db.Exec("ALTER TABLE " & Tab & " modify code_ligbl VarChar(15)")
  Try Utils.db.Exec("ALTER TABLE " & Tab & " modify libel_ligbl VarChar(50)")

  Tab = "Fiches_HistoFac"
  Try Utils.db.Exec("ALTER TABLE " & Tab & " modify nmclifac VarChar(35)")
  Try Utils.db.Exec("ALTER TABLE " & Tab & " modify pnmclifac VarChar(35)")
  Try Utils.db.Exec("ALTER TABLE " & Tab & " modify adr1fac VarChar(35)")
  Try Utils.db.Exec("ALTER TABLE " & Tab & " modify adr2fac VarChar(35)")
  Try Utils.db.Exec("ALTER TABLE " & Tab & " modify villefac VarChar(35)")
  Try Utils.db.Exec("ALTER TABLE " & Tab & " modify acpt VarChar(12)")
  Try Utils.db.Exec("ALTER TABLE " & Tab & " modify mreg VarChar(10)")
  Try Utils.db.Exec("ALTER TABLE " & Tab & " modify reg VarChar(15)")
  Try Utils.db.Exec("ALTER TABLE " & Tab & " modify numserie VarChar(15)")
  Try Utils.db.Exec("ALTER TABLE " & Tab & " modify codep VarChar(15)")

  Tab = "Fiches_HistoLigfac"
  Try Utils.db.Exec("ALTER TABLE " & Tab & " modify code_ligfac VarChar(15)")
  Try Utils.db.Exec("ALTER TABLE " & Tab & " modify libel_ligfac VarChar(50)")

  Tab = "Fiches_BlM"
  Try Utils.db.Exec("ALTER TABLE " & Tab & " modify cvclibl VarChar(9)")
  Try Utils.db.Exec("ALTER TABLE " & Tab & " modify nmclibl VarChar(35)")
  Try Utils.db.Exec("ALTER TABLE " & Tab & " modify pnmclibl VarChar(35)")
  Try Utils.db.Exec("ALTER TABLE " & Tab & " modify adr1bl VarChar(35)")
  Try Utils.db.Exec("ALTER TABLE " & Tab & " modify adr2bl VarChar(35)")
  Try Utils.db.Exec("ALTER TABLE " & Tab & " modify villebl VarChar(35)")
  Try Utils.db.Exec("ALTER TABLE " & Tab & " modify acpt VarChar(12)")
  Try Utils.db.Exec("ALTER TABLE " & Tab & " modify mreg VarChar(10)")
  Try Utils.db.Exec("ALTER TABLE " & Tab & " modify reg VarChar(15)")
  Try Utils.db.Exec("ALTER TABLE " & Tab & " modify numserie VarChar(15)")
  Try Utils.db.Exec("ALTER TABLE " & Tab & " modify codep VarChar(15)")
  Try Utils.db.Exec("ALTER TABLE " & Tab & " modify mtreg VarChar(12)")
  Try Utils.db.Exec("ALTER TABLE " & Tab & " modify desg1 VarChar(50)")
  Try Utils.db.Exec("ALTER TABLE " & Tab & " modify desg2 VarChar(50)")
  Try Utils.db.Exec("ALTER TABLE " & Tab & " modify marque VarChar(15)")
  Try Utils.db.Exec("ALTER TABLE " & Tab & " modify typemat VarChar(15)")

  Tab = "Fiches_LigblM"
  Try Utils.db.Exec("ALTER TABLE " & Tab & " modify code_ligbl VarChar(15)")
  Try Utils.db.Exec("ALTER TABLE " & Tab & " modify libel_ligbl VarChar(50)")

  Tab = "Fiches_HistoFacM"
  Try Utils.db.Exec("ALTER TABLE " & Tab & " modify nmclifac VarChar(35)")
  Try Utils.db.Exec("ALTER TABLE " & Tab & " modify pnmclifac VarChar(35)")
  Try Utils.db.Exec("ALTER TABLE " & Tab & " modify adr1fac VarChar(35)")
  Try Utils.db.Exec("ALTER TABLE " & Tab & " modify adr2fac VarChar(35)")
  Try Utils.db.Exec("ALTER TABLE " & Tab & " modify villefac VarChar(35)")
  Try Utils.db.Exec("ALTER TABLE " & Tab & " modify acpt VarChar(12)")
  Try Utils.db.Exec("ALTER TABLE " & Tab & " modify mreg VarChar(10)")
  Try Utils.db.Exec("ALTER TABLE " & Tab & " modify reg VarChar(15)")
  Try Utils.db.Exec("ALTER TABLE " & Tab & " modify numserie VarChar(15)")
  Try Utils.db.Exec("ALTER TABLE " & Tab & " modify codep VarChar(15)")

  Tab = "Fiches_HistoLigfacM"
  Try Utils.db.Exec("ALTER TABLE " & Tab & " modify code_ligfac VarChar(15)")
  Try Utils.db.Exec("ALTER TABLE " & Tab & " modify libel_ligfac VarChar(50)")

  Tab = "Fiches_HisentMat"
  Try Utils.db.Exec("ALTER TABLE " & Tab & " modify codep VarChar(15)")
  Try Utils.db.Exec("ALTER TABLE " & Tab & " modify marque VarChar(20)")
  Try Utils.db.Exec("ALTER TABLE " & Tab & " modify type VarChar(20)")
  Try Utils.db.Exec("ALTER TABLE " & Tab & " modify design VarChar(50)")
  Try Utils.db.Exec("ALTER TABLE " & Tab & " modify design2 VarChar(50)")

  Tab = "Fiches_EntMat"
  Try Utils.db.Exec("ALTER TABLE " & Tab & " modify numserie VarChar(15)")
  Try Utils.db.Exec("ALTER TABLE " & Tab & " modify codep VarChar(15)")
  Try Utils.db.Exec("ALTER TABLE " & Tab & " modify marque VarChar(20)")
  Try Utils.db.Exec("ALTER TABLE " & Tab & " modify type VarChar(20)")
  Try Utils.db.Exec("ALTER TABLE " & Tab & " modify design VarChar(50)")
  Try Utils.db.Exec("ALTER TABLE " & Tab & " modify design2 VarChar(50)")

  Tab = "Fiches_Totalisation"
  Try Utils.db.Exec("ALTER TABLE " & Tab & " modify intitule VarChar(25)")
  Try Utils.db.Exec("ALTER TABLE " & Tab & " modify totalht VarChar(25)")
  Try Utils.db.Exec("ALTER TABLE " & Tab & " modify totaltva VarChar(25)")

  Tab = "Fiches_Entrecpt"
  Try Utils.db.Exec("ALTER TABLE " & Tab & " modify numrecpt VarChar(15)")

  Tab = "Fiches_Ligrecpt"
  Try Utils.db.Exec("ALTER TABLE " & Tab & " modify design VarChar(30)")
  Try Utils.db.Exec("ALTER TABLE " & Tab & " modify numrecpt VarChar(15)")

  Tab = "Fiches_Ligcom"
  Try Utils.db.Exec("ALTER TABLE " & Tab & " modify code VarChar(25)")
  Try Utils.db.Exec("ALTER TABLE " & Tab & " modify design VarChar(50)")
  Try Utils.db.Exec("ALTER TABLE " & Tab & " modify numcom VarChar(15)")

  Tab = "Fiches_Rubriques"
  Try Utils.db.Exec("ALTER TABLE " & Tab & " modify intitule VarChar(70)")

  Tab = "Fiches_Echeances"
  Try Utils.db.Exec("ALTER TABLE " & Tab & " modify libell VarChar(20)")

  Tab = "Fiches_Typec"
  Try Utils.db.Exec("ALTER TABLE " & Tab & " modify libelle VarChar(25)")

  Tab = "Fiches_Statut"
  Try Utils.db.Exec("ALTER TABLE " & Tab & " modify libelle VarChar(25)")

  Tab = "Fiches_EtiProd"
  Try Utils.db.Exec("ALTER TABLE " & Tab & " modify code VarChar(25)")

  Tab = "Fiches_EtiGond"
  Try Utils.db.Exec("ALTER TABLE " & Tab & " modify code VarChar(25)")

  Tab = "Fiches_Numabon"
  Try Utils.db.Exec("ALTER TABLE " & Tab & " modify numero VarChar(15)")
  Try Utils.db.Exec("ALTER TABLE " & Tab & " modify intitule VarChar(30)")

  Tab = "Fiches_Ligabon"
  Try Utils.db.Exec("ALTER TABLE " & Tab & " modify numero VarChar(15)")
  Try Utils.db.Exec("ALTER TABLE " & Tab & " modify compte VarChar(10)")
  Try Utils.db.Exec("ALTER TABLE " & Tab & " modify intitule VarChar(30)")

  Tab = "Fiches_Agenda"
  Try Utils.db.Exec("ALTER TABLE " & Tab & " modify daction VarChar(20)")
  Try Utils.db.Exec("ALTER TABLE " & Tab & " modify haction VarChar(20)")
  Try Utils.db.Exec("ALTER TABLE " & Tab & " modify nuser VarChar(35)")

  Tab = "Fiches_Vendeurs"
  Try Utils.db.Exec("ALTER TABLE " & Tab & " modify nom VarChar(35)")
  Try Utils.db.Exec("ALTER TABLE " & Tab & " modify mdp VarChar(15)")

  Tab = "Fiches_Caisses"
  Try Utils.db.Exec("ALTER TABLE " & Tab & " modify intitule VarChar(30)")

  Tab = "Fiches_Avoirs"
  Try Utils.db.Exec("ALTER TABLE " & Tab & " modify intitule VarChar(30)")

  Tab = "Fiches_ClientCaisse"
  Try Utils.db.Exec("ALTER TABLE " & Tab & " modify nom VarChar(30)")

  Tab = "Fiches_HisEntTickets"
  Try Utils.db.Exec("ALTER TABLE " & Tab & " modify vendeur VarChar(35)")
  Try Utils.db.Exec("ALTER TABLE " & Tab & " modify client VarChar(30)")
  Try Utils.db.Exec("ALTER TABLE " & Tab & " modify nmcheque VarChar(30)")
  Try Utils.db.Exec("ALTER TABLE " & Tab & " modify nmcarte VarChar(30)")
  Try Utils.db.Exec("ALTER TABLE " & Tab & " modify nmcredit VarChar(30)")
  Try Utils.db.Exec("ALTER TABLE " & Tab & " modify nmavoir VarChar(30)")

  Tab = "Fiches_HisLigTickets"
  Try Utils.db.Exec("ALTER TABLE " & Tab & " modify code VarChar(15)")
  Try Utils.db.Exec("ALTER TABLE " & Tab & " modify intitule VarChar(35)")

  Tab = "Fiches_EntTicketz"
  Try Utils.db.Exec("ALTER TABLE " & Tab & " modify vendeur VarChar(35)")
  Try Utils.db.Exec("ALTER TABLE " & Tab & " modify client VarChar(30)")
  Try Utils.db.Exec("ALTER TABLE " & Tab & " modify nmcheque VarChar(30)")
  Try Utils.db.Exec("ALTER TABLE " & Tab & " modify nmcarte VarChar(30)")
  Try Utils.db.Exec("ALTER TABLE " & Tab & " modify nmcredit VarChar(30)")
  Try Utils.db.Exec("ALTER TABLE " & Tab & " modify nmavoir VarChar(30)")

  Tab = "Fiches_LigTicketz"
  Try Utils.db.Exec("ALTER TABLE " & Tab & " modify code VarChar(15)")
  Try Utils.db.Exec("ALTER TABLE " & Tab & " modify intitule VarChar(35)")

  Tab = "Fiches_Promo"
  Try Utils.db.Exec("ALTER TABLE " & Tab & " modify code VarChar(15)")
  Try Utils.db.Exec("ALTER TABLE " & Tab & " modify libelle VarChar(50)")

  Tab = "Fiches_ArtPromo"
  Try Utils.db.Exec("ALTER TABLE " & Tab & " modify code VarChar(15)")
  Try Utils.db.Exec("ALTER TABLE " & Tab & " modify libelle VarChar(50)")

  Tab = "Fiches_PrdComp"
  Try Utils.db.Exec("ALTER TABLE " & Tab & " modify codep VarChar(15)")
  Try Utils.db.Exec("ALTER TABLE " & Tab & " modify codec VarChar(50)")
  Try Utils.db.Exec("ALTER TABLE " & Tab & " modify libelle VarChar(50)")
  Try Utils.db.Exec("ALTER TABLE " & Tab & " modify qte VarChar(50)")

  Tab = "Fiches_CdBarre"
  Try Utils.db.Exec("ALTER TABLE " & Tab & " modify codep VarChar(15)")

  Tab = "Fiches_Centrales"
  Try Utils.db.Exec("ALTER TABLE " & Tab & " modify libelle VarChar(25)")

  Tab = "Fiches_Carte"
  Try Utils.db.Exec("ALTER TABLE " & Tab & " modify nom VarChar(35)")
  Try Utils.db.Exec("ALTER TABLE " & Tab & " modify pnm VarChar(35)")
  Try Utils.db.Exec("ALTER TABLE " & Tab & " modify adr1 VarChar(35)")
  Try Utils.db.Exec("ALTER TABLE " & Tab & " modify adr2 VarChar(35)")
  Try Utils.db.Exec("ALTER TABLE " & Tab & " modify ville VarChar(35)")
  Try Utils.db.Exec("ALTER TABLE " & Tab & " modify email VarChar(40)")
  Try Utils.db.Exec("ALTER TABLE " & Tab & " modify tel_bur VarChar(16)")
  Try Utils.db.Exec("ALTER TABLE " & Tab & " modify tel_dom VarChar(16)")
  Try Utils.db.Exec("ALTER TABLE " & Tab & " modify tel_poste VarChar(16)")
  Try Utils.db.Exec("ALTER TABLE " & Tab & " modify pble VarChar(16)")
  Try Utils.db.Exec("ALTER TABLE " & Tab & " modify fx1 VarChar(16)")
  Try Utils.db.Exec("ALTER TABLE " & Tab & " modify fx2 VarChar(16)")

  Tab = "Fiches_AdrlivC"
  Try Utils.db.Exec("ALTER TABLE " & Tab & " modify nom VarChar(35)")
  Try Utils.db.Exec("ALTER TABLE " & Tab & " modify pnm VarChar(35)")
  Try Utils.db.Exec("ALTER TABLE " & Tab & " modify adr1 VarChar(35)")
  Try Utils.db.Exec("ALTER TABLE " & Tab & " modify adr2 VarChar(35)")
  Try Utils.db.Exec("ALTER TABLE " & Tab & " modify ville VarChar(35)")

  Tab = "Fiches_ContactC"
  Try Utils.db.Exec("ALTER TABLE " & Tab & " modify nom VarChar(35)")
  Try Utils.db.Exec("ALTER TABLE " & Tab & " modify pnm VarChar(35)")
  Try Utils.db.Exec("ALTER TABLE " & Tab & " modify fonction VarChar(35)")
  Try Utils.db.Exec("ALTER TABLE " & Tab & " modify tel VarChar(16)")
  Try Utils.db.Exec("ALTER TABLE " & Tab & " modify mail VarChar(40)")

  Tab = "Fiches_ContactF"
  Try Utils.db.Exec("ALTER TABLE " & Tab & " modify nom VarChar(35)")
  Try Utils.db.Exec("ALTER TABLE " & Tab & " modify pnm VarChar(35)")
  Try Utils.db.Exec("ALTER TABLE " & Tab & " modify fonction VarChar(35)")
  Try Utils.db.Exec("ALTER TABLE " & Tab & " modify tel VarChar(16)")
  Try Utils.db.Exec("ALTER TABLE " & Tab & " modify mail VarChar(40)")

  Tab = "Fiches_Acomptes"
  Try Utils.db.Exec("ALTER TABLE " & Tab & " modify intitule VarChar(35)")
  Try Utils.db.Exec("ALTER TABLE " & Tab & " modify type VarChar(15)")

  Tab = "Fiches_Suivis"
  Try Utils.db.Exec("ALTER TABLE " & Tab & " modify nom VarChar(70)")

End

Public Sub Maj219()

  Tab = "Fiches_Art"
  Try Utils.db.Exec("ALTER TABLE " & Tab & " modify art_txconv Decimal(7,4)")

  Tab = "Fiches_BlM"
  Try Utils.db.Exec("ALTER TABLE " & Tab & " add htbl TINYINT")

  Tab = "Fiches_Mo"
  Try Utils.db.Exec("ALTER TABLE " & Tab & " add mo_impcar TINYINT(1)")
  Try Utils.db.Exec("ALTER TABLE " & Tab & " add mo_crst Text")

End

Public Sub Maj220()

  Tab = "Fiches_Ligbl" & soc
  Try Utils.db.Exec("ALTER TABLE " & Tab & " modify block_ligbl VarChar(30)")
  Tab = "Fiches_LigblM" & soc
  Try Utils.db.Exec("ALTER TABLE " & Tab & " modify block_ligbl VarChar(30)")
  Tab = "Fiches_HistoLigfac" & soc
  Try Utils.db.Exec("ALTER TABLE " & Tab & " modify bloc VarChar(30)")
  Tab = "Fiches_HistoLigfacM" & soc
  Try Utils.db.Exec("ALTER TABLE " & Tab & " modify bloc VarChar(30)")
  Tab = "Fiches_Libelles" & soc
  Try Utils.db.Exec("ALTER TABLE " & Tab & " modify intitule VarChar(30)")
  Tab = "Fiches_Mo" & soc
  Try Utils.db.Exec("ALTER TABLE " & Tab & " modify mo_design VarChar(50)")

End

Public Sub Maj221()

  Tab = "Fiches_HistoFac"
  Try Utils.db.Exec("ALTER TABLE " & Tab & " ADD (totfacttc decimal(12,2))")
  Tab = "Fiches_HistoFacM"
  Try Utils.db.Exec("ALTER TABLE " & Tab & " ADD (totfacttc decimal(12,2))")
  Tab = "Fiches_Cli"
  Try Utils.db.Exec("ALTER TABLE " & Tab & " ADD (cli_copie TINYINT(1))")
  Tab = "Fiches_Four"
  Try Utils.db.Exec("ALTER TABLE " & Tab & " ADD (fo_copie TINYINT(1))")
  Tab = "Fiches_Entcom"
  Try Utils.db.Exec("ALTER TABLE " & Tab & " ADD (reliquat TINYINT(1))")
  Tab = "Docs_Clients"
  Try Utils.db.EXEC("CREATE TABLE " & Tab &
    "(code VARCHAR(10), " &
    "doc VARCHAR(100)," &
    "doc2 VARCHAR(100)," &
    "PRIMARY KEY (doc, doc2))")
  Try Utils.db.Exec("ALTER TABLE " & Tab & " ADD (doc2 VARCHAR(100))")
  Tab = "Docs_Fournisseurs"
  Try Utils.db.EXEC("CREATE TABLE " & Tab &
    "(code VARCHAR(10), " &
    "doc VARCHAR(100)," &
    "doc2 VARCHAR(100)," &
    "PRIMARY KEY (doc, doc2))")
  Try Utils.db.Exec("ALTER TABLE " & Tab & " ADD (doc2 VARCHAR(100))")
  Tab = "Docs_Produits"
  Try Utils.db.EXEC("CREATE TABLE " & Tab &
    "(code VARCHAR(15), " &
    "doc VARCHAR(100)," &
    "doc2 VARCHAR(100)," &
    "PRIMARY KEY (doc, doc2))")
  Try Utils.db.Exec("ALTER TABLE " & Tab & " ADD (doc2 VARCHAR(100))")
  Tab = "Fiches_Four" & soc
  Try Utils.db.Exec("ALTER TABLE " & Tab & " modify fo_email VarChar(100)")
  Tab = "Fiches_Cli" & soc
  Try Utils.db.Exec("ALTER TABLE " & Tab & " modify cli_email VarChar(100)")

End

Public Sub Maj222()

  Tab = "Docs_Clients" & soc
  Try Utils.db.Exec("ALTER TABLE " & Tab & " modify code VARCHAR(15)")
  Try Utils.db.Exec("ALTER TABLE " & Tab & " modify doc VARCHAR(100)")
  Try Utils.db.Exec("ALTER TABLE " & Tab & " modify doc2 VARCHAR(100)")
  Tab = "Docs_Fournisseurs" & Soc
  Try Utils.db.Exec("ALTER TABLE " & Tab & " modify code VARCHAR(10)")
  Try Utils.db.Exec("ALTER TABLE " & Tab & " modify doc VARCHAR(100)")
  Try Utils.db.Exec("ALTER TABLE " & Tab & " modify doc2 VARCHAR(100)")
  Tab = "Docs_Produits" & Soc
  Try Utils.db.Exec("ALTER TABLE " & Tab & " modify code VARCHAR(10)")
  Try Utils.db.Exec("ALTER TABLE " & Tab & " modify doc VARCHAR(100)")
  Try Utils.db.Exec("ALTER TABLE " & Tab & " modify doc2 VARCHAR(100)")
  Tab = "Fiches_Parametres" & Soc
  Try Utils.db.Exec("ALTER TABLE " & Tab & " add dteinv DATE")

End

Public Sub Maj223()

  Tab = "Fiches_Parametres" & soc
  Try Utils.db.Exec("ALTER TABLE " & Tab & " add dteinv DATE")

  Tab = "Fiches_TxtMail" & soc
  Try Utils.db.EXEC("CREATE TABLE " & Tab &
    " (intitule Text," &
    Utils.db.AutoIncrement("lInd") & ")")

  Tab = "Fiches_Fam" & soc
  Try Utils.db.Exec("ALTER TABLE " & Tab & " modify coef_fam Decimal(6,3)")

  Tab = "Fiches_ImpArtDef" & soc
  Try Utils.db.EXEC("CREATE TABLE " & Tab &
    "(num INT NOT NULL ," &
    "nom VARCHAR(50) ," &
    "cfour CHAR(8) ," &
    "nfour VARCHAR(50) ," &
    "cfam CHAR(5) ," &
    "nfam VARCHAR(50) ," &
    "adrfic VARCHAR(100) ," &
    "typesep CHAR(1) ," &
    "sep CHAR(1) ," &
    "PRIMARY KEY (num))")

  Tab = "Fiches_ImpArtDef2" & soc
  Try Utils.db.EXEC("CREATE TABLE " & Tab &
    "(num INT NOT NULL ," &
    "posorg_1 CHAR(4) ," &
    "col_1 VARCHAR(50) ," &
    "db_1 INT ," &
    "lg_1 INT ," &
    "pos_1 INT ," &
    "posorg_2 CHAR(4) ," &
    "col_2 VARCHAR(50) ," &
    "db_2 INT ," &
    "lg_2 INT ," &
    "pos_2 INT ," &
    "posorg_3 CHAR(4) ," &
    "col_3 VARCHAR(50) ," &
    "db_3 INT ," &
    "lg_3 INT ," &
    "pos_3 INT ," &
    "posorg_4 CHAR(4) ," &
    "col_4 VARCHAR(50) ," &
    "db_4 INT ," &
    "lg_4 INT ," &
    "pos_4 INT ," &
    "posorg_5 CHAR(4) ," &
    "col_5 VARCHAR(50) ," &
    "db_5 INT ," &
    "lg_5 INT ," &
    "pos_5 INT ," &
    "posorg_6 CHAR(4) ," &
    "col_6 VARCHAR(50) ," &
    "db_6 INT ," &
    "lg_6 INT ," &
    "pos_6 INT ," &
    "posorg_7 CHAR(4) ," &
    "col_7 VARCHAR(50) ," &
    "db_7 INT ," &
    "lg_7 INT ," &
    "pos_7 INT ," &
    "posorg_8 CHAR(4) ," &
    "col_8 VARCHAR(50) ," &
    "db_8 INT ," &
    "lg_8 INT ," &
    "pos_8 INT ," &
    "posorg_9 CHAR(4) ," &
    "col_9 VARCHAR(50) ," &
    "db_9 INT ," &
    "lg_9 INT ," &
    "pos_9 INT ," &
    "posorg_10 CHAR(4) ," &
    "col_10 VARCHAR(50) ," &
    "db_10 INT ," &
    "lg_10 INT ," &
    "pos_10 INT ," &
    "posorg_11 CHAR(4) ," &
    "col_11 VARCHAR(50) ," &
    "db_11 INT ," &
    "lg_11 INT ," &
    "pos_11 INT ," &
    "PRIMARY KEY (num))")
  Try Utils.db.Exec("ALTER TABLE " & Tab & " ADD (posorg_12 CHAR(4))")
  Try Utils.db.Exec("ALTER TABLE " & Tab & " ADD (col_12 VARCHAR(50))")
  Try Utils.db.Exec("ALTER TABLE " & Tab & " ADD (db_12 INT)")
  Try Utils.db.Exec("ALTER TABLE " & Tab & " ADD (lg_12 INT)")
  Try Utils.db.Exec("ALTER TABLE " & Tab & " ADD (pos_12 INT)")
  Try Utils.db.Exec("ALTER TABLE " & Tab & " ADD (posorg_13 CHAR(4))")
  Try Utils.db.Exec("ALTER TABLE " & Tab & " ADD (col_13 VARCHAR(50))")
  Try Utils.db.Exec("ALTER TABLE " & Tab & " ADD (db_13 INT)")
  Try Utils.db.Exec("ALTER TABLE " & Tab & " ADD (lg_13 INT)")
  Try Utils.db.Exec("ALTER TABLE " & Tab & " ADD (pos_13 INT)")
  Try Utils.db.Exec("ALTER TABLE " & Tab & " ADD (posorg_14 CHAR(4))")
  Try Utils.db.Exec("ALTER TABLE " & Tab & " ADD (col_14 VARCHAR(50))")
  Try Utils.db.Exec("ALTER TABLE " & Tab & " ADD (db_14 INT)")
  Try Utils.db.Exec("ALTER TABLE " & Tab & " ADD (lg_14 INT)")
  Try Utils.db.Exec("ALTER TABLE " & Tab & " ADD (pos_14 INT)")
  Try Utils.db.Exec("ALTER TABLE " & Tab & " ADD (posorg_15 CHAR(4))")
  Try Utils.db.Exec("ALTER TABLE " & Tab & " ADD (col_15 VARCHAR(50))")
  Try Utils.db.Exec("ALTER TABLE " & Tab & " ADD (db_15 INT)")
  Try Utils.db.Exec("ALTER TABLE " & Tab & " ADD (lg_15 INT)")
  Try Utils.db.Exec("ALTER TABLE " & Tab & " ADD (pos_15 INT)")
  Try Utils.db.Exec("ALTER TABLE " & Tab & " ADD (posorg_16 CHAR(4))")
  Try Utils.db.Exec("ALTER TABLE " & Tab & " ADD (col_16 VARCHAR(50))")
  Try Utils.db.Exec("ALTER TABLE " & Tab & " ADD (db_16 INT)")
  Try Utils.db.Exec("ALTER TABLE " & Tab & " ADD (lg_16 INT)")
  Try Utils.db.Exec("ALTER TABLE " & Tab & " ADD (pos_16 INT)")
  Try Utils.db.Exec("ALTER TABLE " & Tab & " ADD (posorg_17 CHAR(4))")
  Try Utils.db.Exec("ALTER TABLE " & Tab & " ADD (col_17 VARCHAR(50))")
  Try Utils.db.Exec("ALTER TABLE " & Tab & " ADD (db_17 INT)")
  Try Utils.db.Exec("ALTER TABLE " & Tab & " ADD (lg_17 INT)")
  Try Utils.db.Exec("ALTER TABLE " & Tab & " ADD (pos_17 INT)")
  Try Utils.db.Exec("ALTER TABLE " & Tab & " ADD (posorg_18 CHAR(4))")
  Try Utils.db.Exec("ALTER TABLE " & Tab & " ADD (col_18 VARCHAR(50))")
  Try Utils.db.Exec("ALTER TABLE " & Tab & " ADD (db_18 INT)")
  Try Utils.db.Exec("ALTER TABLE " & Tab & " ADD (lg_18 INT)")
  Try Utils.db.Exec("ALTER TABLE " & Tab & " ADD (pos_18 INT)")

  Tab = "Fiches_Mvt"
  Try Utils.db.Exec("ALTER TABLE " & Tab & " modify numerodef Integer(6)")

End

Public Sub Maj224()

  Tab = "Fiches_Mvt" & soc
  Try Utils.db.Exec("ALTER TABLE " & Tab & " modify numerodef Integer(6)")

End

Public Sub Maj225()

  Tab = "Fiches_Cli"
  Try Utils.db.Exec("ALTER TABLE " & Tab & " ADD (cli_actif TINYINT(1))")
  Utils.db.Exec("UPdate  " & tab & "  SET  cli_actif = &1", False)
  Utils.db.Exec("UPdate  " & tab & "  SET  cli_statut = &1", " ")
  Try Utils.db.Exec("ALTER TABLE " & Tab & " ADD (INDEX (cli_statut))")
  Try Utils.db.Exec("ALTER TABLE " & Tab & " ADD (INDEX (cli_actif))")

  Tab = "Fiches_Art"
  Try Utils.db.Exec("ALTER TABLE " & Tab & " ADD (art_colvte Decimal(12,3))")
  Try Utils.db.Exec("ALTER TABLE " & Tab & " ADD (art_pvht2 Decimal(12,3))")

End

Public Sub Maj227()

  Dim retiq As Result
  Dim libelle As String

  Tab = "Fiches_Art"
  Try Utils.db.Exec("ALTER TABLE " & Tab & " ADD (art_cn8 Char(12))")
  Try Utils.db.Exec("ALTER TABLE " & Tab & " ADD (INDEX (art_cn8))")

  Tab = "Fiches_Etiquettes"
  Try Utils.db.Exec("ALTER TABLE " & Tab & " ADD (libelle Char(25))")
  If Not Error Then
    rEtiq = Utils.db.Exec("SELECT * FROM " & Tab & " ")
    If rEtiq.Available Then
      Do
        If rEtiq!libelle = "" Then
          Select Case rEtiq!code
            Case 1
              Libelle = "Article"
            Case 2
              Libelle = "Gondole"
            Case 3
              Libelle = "Client enveloppe"
            Case 4
              Libelle = "Client colis"
          End Select
          Utils.db.Exec("UPdate  " & tab & "  SET libelle = &2 WHERE code = &1", rEtiq!code, Libelle)
        Endif
      Loop Until rEtiq.MoveNext()
    Endif
  Endif

  Tab = "Fiches_Mvtexpdc"
  Try Utils.db.EXEC("CREATE TABLE " & Tab &
    "(mind Int NOT NULL," &
    "code Char(15) NOT NULL," &
    "daterecpt date NOT NULL," &
    "qtep Char(10) ," &
    "qtem Char(10) ," &
    "com VARCHAR(35) ," &
    "type Char(1) ," &
    "INDEX (mind), " &
    Utils.db.AutoIncrement("id") & ")")

  Tab = "Fiches_Traites"
  Try Utils.db.Exec("ALTER TABLE " & Tab & " ADD nom VarChar(35)")
  Try Utils.db.Exec("ALTER TABLE " & Tab & " ADD acceptee Integer(1)")
  Try Utils.db.Exec("ALTER TABLE " & Tab & " ADD ecartee Integer(1)")

  Tab = "Fiches_Lcr"
  Try Utils.db.EXEC("CREATE TABLE " & Tab &
    "(code Char(8) ," &
    "nom VarChar(35) ," &
    "montant Char(12) ," &
    "date date ," &
    "datech date ," &
    "numfac Char(12) ," &
    "acceptee integer," &
    "ecartee integer," &
    "banque VarChar(35) ," &
    "codeentree integer(1)," &
    "bordereau VarChar(35)," &
    Utils.db.AutoIncrement("lInd") & ")")

End

Public Sub Maj228()

  Tab = "Fiches_Mvtexpdc"
  Try Utils.db.EXEC("CREATE TABLE " & Tab &
    "(mind Int NOT NULL," &
    "code Char(15) NOT NULL," &
    "daterecpt date NOT NULL," &
    "qtep Char(10) ," &
    "qtem Char(10) ," &
    "com VARCHAR(35) ," &
    "type Char(1) ," &
    "INDEX (mind), " &
    Utils.db.AutoIncrement("id") & ")")

  Tab = "Fiches_Traites"
  Try Utils.db.Exec("ALTER TABLE " & Tab & " ADD nom VarChar(35)")
  Try Utils.db.Exec("ALTER TABLE " & Tab & " ADD acceptee Integer(1)")
  Try Utils.db.Exec("ALTER TABLE " & Tab & " ADD ecartee Integer(1)")

  Tab = "Fiches_Lcr"
  Try Utils.db.EXEC("CREATE TABLE " & Tab &
    "(code Char(8) ," &
    "nom VarChar(35) ," &
    "montant Char(12) ," &
    "date date ," &
    "datech date ," &
    "numfac Char(12) ," &
    "acceptee integer," &
    "ecartee integer," &
    "banque VarChar(35) ," &
    "codeentree integer(1)," &
    "bordereau VarChar(35)," &
    Utils.db.AutoIncrement("lInd") & ")")

End

Public Sub Maj229()

  Tab = "Fiches_Depots"
  Try Utils.db.EXEC("CREATE TABLE " & Tab &
    "(code Char(8) ," &
    "libelle VarChar(35) ," &
    "adr1 VARCHAR(35)," &
    "adr2 VARCHAR(35)," &
    "cp CHAR(5)," &
    "ville VARCHAR(35)," &
    "PRIMARY KEY (code))")

  Try Utils.db.Exec("INSERT INTO " & Cbase.Table("TabDepots") & "(code, libelle) VALUES (&1, &2)", "01", "Magasin")

  Tab = "Fiches_StkDepots"
  Try Utils.db.EXEC("CREATE TABLE " & Tab &
    "(coded Char(8) ," &
    "codea VarChar(15) ," &
    "qte Decimal(12,3), " &
    "PRIMARY KEY (coded, codea))")
  Try Utils.db.Exec("ALTER TABLE " & Tab & " ADD (INDEX (coded))")
  Try Utils.db.Exec("ALTER TABLE " & Tab & " ADD (INDEX (codea))")

  Tab = "Fiches_TarFour"
  Try Utils.db.EXEC("CREATE TABLE " & Tab &
    "(codea Char(8) ," &
    "codef VarChar(15) ," &
    "paht Decimal(12,3), " &
    "PRIMARY KEY (codea, codef))")
  Try Utils.db.Exec("ALTER TABLE " & Tab & " ADD (INDEX id_coded (codef))")
  Try Utils.db.Exec("ALTER TABLE " & Tab & " ADD (INDEX id_codea (codea))")

  Tab = "Fiches_Sdepots"
  Try Utils.db.EXEC("CREATE TABLE " & Tab &
    "(code Char(2) NOT NULL," &
    "cart Char(15) NOT NULL," &
    "date date NOT NULL," &
    "type Char(1) ," &
    "qte Char(10) ," &
    "com VarChar(50) ," &
    Utils.db.AutoIncrement("mind") & ")")
  
  Try Utils.db.Exec("ALTER TABLE " & Tab & " ADD (INDEX (coded))")
  Try Utils.db.Exec("ALTER TABLE " & Tab & " ADD (INDEX (code))")
  Try Utils.db.Exec("ALTER TABLE " & Tab & " ADD (INDEX (date))")

  Tab = "Fiches_CdFour"
  Try Utils.db.exec("CREATE TABLE " & Tab &
    "(codep CHAR(15) NOT NULL ," &
    "codef CHAR(13) NOT NULL ," &
    "PRIMARY KEY (codep, codef))")

  'Tab1 = "Fiches_Art"
  'rResult = Utils.db.Exec("SELECT * from  " & Tab1 & "")
  'IF rResult.Available THEN
  'REPEAT
  'r2Result = Utils.db.Exec("SELECT * from  " & Tab & " where codep = &1 and codef = &2", rResult!art_code, rResult!art_cfour)
  'IF NOT r2Result.Available THEN
  'TRY Utils.db.Exec("Insert into  " & Tab & " (codep,codef) values (&1,&2)", rResult!art_code, rResult!art_cfour)
  'ENDIF
  'UNTIL rResult.MoveNext()
  'ENDIF

End

Public Sub Maj230()

  Tab = "Fiches_Bl"
  Try Utils.db.Exec("ALTER TABLE " & Tab & " ADD (cdep Varchar(37))")
  Try Utils.db.Exec("ALTER TABLE " & Tab & " ADD (imp TINYINT(1))")

  Tab = "Fiches_BlM"
  Try Utils.db.Exec("ALTER TABLE " & Tab & " ADD (cdep Varchar(37))")
  Try Utils.db.Exec("ALTER TABLE " & Tab & " ADD (imp TINYINT(1))")

  Tab = "Fiches_HistoFac" & soc
  Try Utils.db.Exec("ALTER TABLE " & Tab & " ADD (cdep VarChar(37))")

End

Public Sub Maj231()

  Tab = "Fiches_Ligcom"
  Try Utils.db.Exec("ALTER TABLE " & Tab & " change LInd lInd INT AUTO_INCREMENT") 'impossible de faire ca propre en wrapper sqlite3

  Tab = "Fiches_Regltz"
  Try Utils.db.Exec("ALTER TABLE " & Tab & " ADD (caisse Char(2))")

  Tab = "Fiches_InvT"
  Try Utils.db.Exec("ALTER TABLE " & Tab & " change Inv_nlig inv_nlig Char(9)")

  Tab = "Fiches_Inv"
  Try Utils.db.Exec("ALTER TABLE " & Tab & " change Inv_nlig inv_nlig Char(9)")

End

Public Sub Maj301()

  Tab = "Fiches_Cli"
  Try Utils.db.Exec("ALTER TABLE " & Tab & " ADD (cli_div TINYINT(1))")

End

Public Sub Maj302()

  Tab = "Fiches_BlM"
  Try Utils.db.Exec("ALTER TABLE " & Tab & " ADD (cdep Varchar(37))")
  Try Utils.db.Exec("ALTER TABLE " & Tab & " ADD (imp TINYINT(1))")

End

Public Sub Maj303()

  Dim Params As Result

  Tab = "Fiches_Mvt"
  Try Utils.db.Exec("ALTER TABLE " & Tab & " modify numero Integer(11)")
  Try Utils.db.Exec("ALTER TABLE " & Tab & " modify numerodef Integer(11)")
  Tab = "Fiches_Parametres"
  Params = Utils.db.Exec("SELECT * FROM " & Tab & " ")
  Try Utils.db.Exec("ALTER TABLE " & Tab & " modify numecriture Integer(11)")
  Try Utils.db.Exec("ALTER TABLE " & Tab & " modify numecriture1 Integer(11)")
  Try Utils.db.Exec("ALTER TABLE " & Tab & " modify numecriture2 Integer(11)")
  If Params!numecriture3 > Params!numecriture2 Then
    Utils.db.Exec("UPdate  " & Tab & "  SET numecriture2 = &2 WHERE ind = &1", 0, Params!numecriture3)
  Endif
  If Params!numecriture1 > Params!numecriture Then
    Utils.db.Exec("UPdate  " & Tab & "  SET numecriture = &2 WHERE ind = &1", 0, Params!numecriture1)
  Endif
  Tab = "Fiches_Societes"
  Utils.db.Exec("ALTER TABLE " & Tab & " modify cap_sc Varchar(15)")

End

Public Sub Maj304()

  Tab = "Fiches_TabContact"
  Try Utils.db.Exec("ALTER TABLE " & Tab & " modify Mail Varchar(100)")

  Tab = "Fiches_TabContactF"
  Try Utils.db.Exec("ALTER TABLE " & Tab & " modify Mail Varchar(100)")

  Tab = "Fiches_RubCompt"
  Try Utils.db.Exec("ALTER TABLE " & Tab & " ADD (amortissement TINYINT(1))")

  Tab = "Fiches_Ligabon"
  Try Utils.db.Exec("drop Table IF exists " & Tab & "")
  Try Utils.db.EXEC("CREATE TABLE " & Tab &
    " (numero VARCHAR(15) NOT NULL," &
    "compte VARCHAR(10) NOT NULL," &
    "intitule VARCHAR(30) NOT NULL," &
    "debit Char(10) NOT NULL," &
    "credit Char(10) NOT NULL," &
    "lig Integer(2)," &
    Utils.db.AutoIncrement("lInd") & ")")

  Tab = "Fiches_Banques"
  Try Utils.db.Exec("CREATE TABLE " & Tab &
    " (banques_code int(2) NOT NULL ," &
    "banques_nom VARCHAR(35)," &
    "banques_dmln VARCHAR(35)," &
    "banques_nume CHAR(6)," & ' Numéro émetteur attribué par la banque de france
    "banques_codeb VARCHAR(5)," & ' Code banque
    "banques_codeg VARCHAR(5)," & ' Code guichet
    "banques_numcpt VARCHAR(11)," & ' Numéro compte
    "banques_numsiren VARCHAR(15)," & ' Numéro risque-siren
    "banques_adr CHAR(1)," & ' Adresse bordereau (1- s'imprimera sur bordereau, 0- Ne s'imprimera pas)
    "banques_txt TEXT," & 'Texte d'entête du bordereau
    "banques_fenrg CHAR(6)," & ' Fin d'enregistrement si demandé par la banque ($ODOA$)
    "banques_mail VarChar(35)," &
    "banques_ref VarChar(11)," &
    "banques_entete VarChar(150)," &
    "banques_corps Text," &
    "banques_reftireur VarChar(10)," &
    "PRIMARY KEY (banques_code))")

  Tab = "Fiches_Bordereaux"
  Try Utils.db.EXEC("CREATE TABLE " & Tab &
    "(banque integer(1) ," &
    "codeentree integer(1) ," &
    "dateremise date ," &
    "refremise Char(11) ," &
    "datevaleur date ," &
    "ech1 date ," &
    "ech2 date ," &
    "bordereau Integer," &
    "tot Decimal(12,2)," &
    "etat TINYINT(1)," &
    Utils.db.AutoIncrement("lInd") & ")")

  Tab = "Fiches_TxtMailC"
  Try Utils.db.EXEC("CREATE TABLE " & Tab &
    " (intitule Text," &
    Utils.db.AutoIncrement("lInd") & ")")

End

Public Sub Maj305()

  'Tab = "Fiches_Cli"
  'Try Utils.db.Exec("ALTER TABLE " & Tab & " ADD (cli_tarif tinyint(1))")

  Tab = "Fiches_Tarcli"
  Try Utils.db.EXEC("CREATE TABLE " & Tab &
    " (ccli VARCHAR(10) NOT NULL," &
    "cart VARCHAR(15) NOT NULL," &
    "coef Decimal(7,4) ," &
    Utils.db.AutoIncrement("lInd") & ")")

  Tab = "Fiches_TarTypcli"
  Try Utils.db.EXEC("CREATE TABLE " & Tab &
    " (type VARCHAR(10) NOT NULL," &
    "cart VARCHAR(15) NOT NULL," &
    "coef Decimal(7,4) ," &
    Utils.db.AutoIncrement("lInd") & ")")

  Tab = "Fiches_ContactC"
  Try Utils.db.Exec("ALTER TABLE " & Tab & " modify mail VarChar(100)")

  Tab = "Fiches_ContactF"
  Try Utils.db.Exec("ALTER TABLE " & Tab & " modify mail VarChar(100)")

End

Public Sub Maj306()

  Tab = "Fiches_Rpl1"
  Try Utils.db.exec("CREATE TABLE " & Tab &
    "(codep CHAR(15) NOT NULL ," &
    "coderpl1 CHAR(15) NOT NULL ," &
    "PRIMARY KEY (codep, coderpl1))")

  Tab = "Fiches_Rpl2"
  Try Utils.db.exec("CREATE TABLE " & Tab &
    "(codep CHAR(15) NOT NULL ," &
    "coderpl2 CHAR(15) NOT NULL ," &
    "PRIMARY KEY (codep, coderpl2))")

  Tab = "Fiches_Art"
  Try Utils.db.Exec("ALTER TABLE " & Tab & " ADD (art_crpl1 CHAR(15))")
  Try Utils.db.Exec("ALTER TABLE " & Tab & " ADD (art_crpl2 CHAR(15))")

End

Public Sub Maj307()

  Tab = "Fiches_Mvtexp"
  Try Utils.db.Exec("ALTER TABLE " & Tab & " change MInd mind INT AUTO_INCREMENT") 'impossible de faire ca propre en wrapper sqlite3

End

Public Sub Maj308()

  Tab = "Fiches_Mo"
  Try Utils.db.Exec("ALTER TABLE " & Tab & " DROP  " & "cli_pays" & "")

End

Public Sub Maj309()

  Try Start.LocalSettings["/Soc" & Soc & "/Impbl"] = 0
  Tab = "Fiches_SousComptes" & soc
  Try Utils.db.EXEC("CREATE TABLE " & Tab &
    " (code Char(8) NOT NULL," &
    "code_vtl char(8) NOT NULL," &
    "intitule_vtl VARCHAR(40) ," &
    "PRIMARY KEY (code_vtl))")

  Tab = "Fiches_Parametres"
  Try Utils.db.Exec("ALTER TABLE " & Tab & " change dateinv dteinv DATE")
  If Error Then Try Utils.db.Exec("ALTER TABLE " & Tab & " add dteinv DATE")

  Tab = "Fiches_Comptes"
  Try Utils.db.Exec("ALTER TABLE " & Tab & " ADD (cprincipal TINYINT(1))")
  Try Utils.db.Exec("UPdate  " & tab & "  SET  cprincipal = &1", False)

End

Public Sub Maj310()

  Dim hfil As File
  Dim $Table As String

  Shell "mysql -h " & Start.LocalSettings["/dbase/Host"] & " " & " -u " & Utils.db.Login & " -p" & Utils.db.Password & " -e \"use Laurux" & soc & ";" & "show tables;\" -B -s > ~/tables.txt" Wait
  Try HFil = Open User.Home & "/tmp/tables.txt" For Read
  If Not Error Then
    While Not Eof(hFil)
      Line Input #hFil, Lig
      If IsNumber(Right$(lig, 2)) Then
        If Right$(lig, 2) <> Soc Then
          $Table = Left$(lig, Len(lig) - 2)
          Utils.db.Exec("drop TABLE " & Lig & "")
        Endif
      Endif
    Wend
  Endif
  Shell "mysql -h " & Start.LocalSettings["/dbase/Host"] & " " & " -u " & Utils.db.Login & " -p" & Utils.db.Password & " -e \"use Laurux" & soc & ";" & "show tables;\" -B -s > ~/tables.txt" Wait
  Try HFil = Open User.Home & "/tables.txt" For Read
  If Not Error Then
    While Not Eof(hFil)
      Line Input #hFil, Lig
      If IsNumber(Right$(lig, 2)) Then
        If Right$(lig, 2) = Soc Then
          $Table = Left$(lig, Len(lig) - 2)
          Try Utils.db.Exec("rename Table " & lig & " to " & $table & "")
        Endif
      Endif
    Wend
  Endif

End

Public Sub Maj310b()

  Try Start.LocalSettings["/Soc" & Soc & "/Impbl"] = 0
  Tab = "Fiches_SousComptes"
  Try Utils.db.EXEC("CREATE TABLE " & Tab &
    " (code Char(8) NOT NULL," &
    "code_vtl char(8) NOT NULL," &
    "intitule_vtl VARCHAR(40) ," &
    "PRIMARY KEY (code_vtl))")

  Tab = "Fiches_Parametres"
  Try Utils.db.Exec("ALTER TABLE " & Tab & " change dateinv dteinv DATE")
  If Error Then Try Utils.db.Exec("ALTER TABLE " & Tab & " add dteinv DATE")

  Tab = "Fiches_Comptes"
  Try Utils.db.Exec("ALTER TABLE " & Tab & " ADD (cprincipal TINYINT(1))")
  Try Utils.db.Exec("UPdate  " & tab & "  SET  cprincipal = &1", False)

End

Public Sub Maj311()

  Dim hfil As File
  Dim $Table As String
  Dim $hform As Form
  Dim hLabel As Label

  $hForm = New Form As "Form"
  $hform.Width = 600
  $hform.Height = 400
  $hForm.Border = Border.Etched
  $hform.Title = "Passage version 3.11"
  hLabel = New Label($hForm)
  hLabel.Background = &EBEBEB&
  hLabel.Width = 600
  hLabel.Alignment = 3
  hLabel.Height = $hform.Height / 2
  hLabel.Text = "Passage à la version 3.11. \nCette opération prend un peu de temps.\n\n Veuillez patienter SVP."
  $hForm.Move($hForm.ScreenX, $hForm.ScreenY, 600, 200)
  $hform.Center
  $hform.show
  Wait 1
  $hform.Mouse = Mouse.wait
  Shell "mysql" & " -h " & Start.LocalSettings["/dbase/Host"] & " -u " & Utils.db.Login & " -p" & Utils.db.Password & " -e \"use Laurux" & Start.societe & "; " & "show tables;\" -B -s > ~/tables.txt" Wait
  Try HFil = Open User.Home & "/tmp/tables.txt" For Read
  If Not Error Then
    While Not Eof(hFil)
      Line Input #hFil, Lig
      $Table = Left$(lig, Len(lig) - 2)
      Utils.db.Exec("Alter table " & lig & Utils.db.Engine())
    Wend
  Endif
  $hform.Mouse = Mouse.default
  $hform.Delete

  Tab = "Corsage"
  Try Utils.db.EXEC("CREATE TABLE " & Tab &
    " (acode Char(8) NOT NULL," &
    "ncode char(8) NOT NULL," &
    "PRIMARY KEY (acode))" & Utils.db.Engine())

  Tab = "Corjxs"
  Try Utils.db.EXEC("CREATE TABLE " & Tab &
    " (sage Char(3) NOT NULL," &
    "laurux char(2) NOT NULL," &
    "PRIMARY KEY (sage))" & Utils.db.Engine())

End

Public Sub Maj312()

  Tab = "Fiches_Art"
  Try Utils.db.Exec("ALTER TABLE " & Tab & " ADD (art_ect2 TINYINT(1))")
  Try Utils.db.Exec("ALTER TABLE " & Tab & " ADD (art_eco2 Decimal(6,3))")

  Tab = "Fiches_Regltz"
  Try Utils.db.Exec("ALTER TABLE " & Tab & " ADD (date Char(17))")

End

Public Sub Maj312a()

  Tab = "Fiches_ImpArtDef2"
  Try Utils.db.Exec("ALTER TABLE " & Tab & " ADD (posorg_19 CHAR(4))")
  Try Utils.db.Exec("ALTER TABLE " & Tab & " ADD (col_19 VARCHAR(50))")
  Try Utils.db.Exec("ALTER TABLE " & Tab & " ADD (db_19 INT)")
  Try Utils.db.Exec("ALTER TABLE " & Tab & " ADD (lg_19 INT)")
  Try Utils.db.Exec("ALTER TABLE " & Tab & " ADD (pos_19 INT)")
  Try Utils.db.Exec("ALTER TABLE " & Tab & " ADD (posorg_20 CHAR(4))")
  Try Utils.db.Exec("ALTER TABLE " & Tab & " ADD (col_20 VARCHAR(50))")
  Try Utils.db.Exec("ALTER TABLE " & Tab & " ADD (db_20 INT)")
  Try Utils.db.Exec("ALTER TABLE " & Tab & " ADD (lg_20 INT)")
  Try Utils.db.Exec("ALTER TABLE " & Tab & " ADD (pos_20 INT)")
  Try Utils.db.Exec("ALTER TABLE " & Tab & " ADD (posorg_21 CHAR(4))")
  Try Utils.db.Exec("ALTER TABLE " & Tab & " ADD (col_21 VARCHAR(50))")
  Try Utils.db.Exec("ALTER TABLE " & Tab & " ADD (db_21 INT)")
  Try Utils.db.Exec("ALTER TABLE " & Tab & " ADD (lg_21 INT)")
  Try Utils.db.Exec("ALTER TABLE " & Tab & " ADD (pos_21 INT)")
  Try Utils.db.Exec("ALTER TABLE " & Tab & " ADD (posorg_22 CHAR(4))")
  Try Utils.db.Exec("ALTER TABLE " & Tab & " ADD (col_22 VARCHAR(50))")
  Try Utils.db.Exec("ALTER TABLE " & Tab & " ADD (db_22 INT)")
  Try Utils.db.Exec("ALTER TABLE " & Tab & " ADD (lg_22 INT)")
  Try Utils.db.Exec("ALTER TABLE " & Tab & " ADD (pos_22 INT)")
  Try Utils.db.Exec("ALTER TABLE " & Tab & " ADD (posorg_23 CHAR(4))")
  Try Utils.db.Exec("ALTER TABLE " & Tab & " ADD (col_23 VARCHAR(50))")
  Try Utils.db.Exec("ALTER TABLE " & Tab & " ADD (db_23 INT)")
  Try Utils.db.Exec("ALTER TABLE " & Tab & " ADD (lg_23 INT)")
  Try Utils.db.Exec("ALTER TABLE " & Tab & " ADD (pos_23 INT)")
  Try Utils.db.Exec("ALTER TABLE " & Tab & " ADD (posorg_24 CHAR(4))")
  Try Utils.db.Exec("ALTER TABLE " & Tab & " ADD (col_24 VARCHAR(50))")
  Try Utils.db.Exec("ALTER TABLE " & Tab & " ADD (db_24 INT)")
  Try Utils.db.Exec("ALTER TABLE " & Tab & " ADD (lg_24 INT)")
  Try Utils.db.Exec("ALTER TABLE " & Tab & " ADD (pos_24 INT)")
  Try Utils.db.Exec("ALTER TABLE " & Tab & " ADD (posorg_25 CHAR(4))")
  Try Utils.db.Exec("ALTER TABLE " & Tab & " ADD (col_25 VARCHAR(50))")
  Try Utils.db.Exec("ALTER TABLE " & Tab & " ADD (db_25 INT)")
  Try Utils.db.Exec("ALTER TABLE " & Tab & " ADD (lg_25 INT)")
  Try Utils.db.Exec("ALTER TABLE " & Tab & " ADD (pos_25 INT)")

  Tab = "Fiches_Cequ"
  Try Utils.db.exec("CREATE TABLE " & Tab &
    "(codep CHAR(15) NOT NULL ," &
    "codequ CHAR(15) NOT NULL ," &
    "PRIMARY KEY (codep, codequ))")

  Tab = "Fiches_HistoFacM"
  Try Utils.db.Exec("ALTER TABLE " & Tab & " ADD (cdep VarChar(37))")

End

Public Sub Maj314()

  Tab = "Fiches_Societes"
  Try Utils.db.Exec("ALTER TABLE " & Tab & " ADD (libre Char(35))")
  Tab = "Fiches_Four"
  Try Utils.db.Exec("ALTER TABLE " & Tab & " add (fo_mincom Decimal(12,2))")
  Tab = "Fiches_Ligbl"
  Try Utils.db.Exec("ALTER TABLE " & Tab & " ADD (mrgart_ligbl Decimal(12,3))")
  Try Utils.db.Exec("ALTER TABLE " & Tab & " ADD (mrgmo_ligbl Decimal(12,3))")

End

Public Sub Maj315()

  Tab = "Fiches_CoeffTypec"
  Try Utils.db.exec("CREATE TABLE " & Tab &
    " (coder CHAR(2) NOT NULL ," &
    "codef CHAR(5) NOT NULL ," &
    "coeff decimal(6,3) , " &
    Utils.db.AutoIncrement("lInd") & ")" & Utils.db.Engine())

  Tab = "Fiches_Materiels"
  Try Utils.db.Exec("ALTER TABLE " & Tab & " ADD (mat_dtevte date)")
  Try Utils.db.Exec("ALTER TABLE " & Tab & " ADD (mat_dateg1 date)")
  Try Utils.db.Exec("ALTER TABLE " & Tab & " ADD (mat_dateg2 date)")
  Try Utils.db.Exec("ALTER TABLE " & Tab & " ADD (mat_chkgarantie TINYINT(1))")

  Tab = "Fiches_LigblM"
  Try Utils.db.Exec("ALTER TABLE " & Tab & " ADD (mrgart_ligbl Decimal(12,3))")
  Try Utils.db.Exec("ALTER TABLE " & Tab & " ADD (mrgmo_ligbl Decimal(12,3))")

  Tab = "Fiches_Societes"
  Utils.db.Exec("ALTER TABLE " & Tab & " change email_sc email_sc char(50)")

  Tab = "Corsage"
  Try Utils.db.EXEC("CREATE TABLE " & Tab &
    " (acode Char(8) NOT NULL," &
    "ncode char(8) NOT NULL," &
    "PRIMARY KEY (acode))" & Utils.db.Engine())

  Tab = "Corjxs"
  Try Utils.db.EXEC("CREATE TABLE " & Tab &
    " (sage Char(3) NOT NULL," &
    "laurux char(2) NOT NULL," &
    "PRIMARY KEY (sage))" & Utils.db.Engine())

End

Public Sub Maj316()

  Tab = "Fiches_Ligbl"
  Try Utils.db.Exec("ALTER TABLE " & Tab & " add mtx_ligfac char(5)")
  Tab = "Fiches_LigblM"
  Try Utils.db.Exec("ALTER TABLE " & Tab & " add mtx_ligfac char(5)")
  Tab = "Fiches_HistoLigfac"
  Try Utils.db.Exec("ALTER TABLE " & Tab & " add mtx_ligfac char(5)")
  Tab = "Fiches_HistoLigfacM"
  Try Utils.db.Exec("ALTER TABLE " & Tab & " add mtx_ligfac char(5)")

  Tab = "Fiches_Analytiques"
  Try Utils.db.EXEC("CREATE TABLE " & Tab &
    "(code Char(3)," &
    "compte Char(8)," &
    "pourcent Int," &
    "INDEX (code, compte), " &
    Utils.db.AutoIncrement("lInd") & ")" & Utils.db.Engine())

  Tab = "Fiches_Postes"
  Try Utils.db.EXEC("CREATE TABLE " & Tab &
    "(code Char(3)," &
    "intitulep Char(35)," &
    "INDEX (code), " &
    Utils.db.AutoIncrement("lInd") & ")" & Utils.db.Engine())

  Tab = "Fiches_MvtA"
  Try Utils.db.Exec("CREATE TABLE " & Tab &
    " (numero Integer(6) NOT NULL," &
    "compte CHAR(8) NOT NULL," &
    "intitule Char(30)," &
    "dte date," &
    "numdoc CHAR(10) NOT NULL," &
    "libelle VarChar(50)," &
    "pourcent CHAR(5)," &
    "montantd Decimal(12,2)," &
    "montantc Decimal(12,2)," &
    "jour Char(2)," &
    "poste Char(3)," &
    "validee TINYINT(1)," &
    Utils.db.AutoIncrement("lind") & ")" & Utils.db.Engine())

  Tab = "Fiches_MvtA1"
  Try Utils.db.Exec("CREATE TABLE " & Tab &
    " (numero Integer(6) NOT NULL," &
    "compte CHAR(8) NOT NULL," &
    "intitule Char(30)," &
    "dte date," &
    "numdoc CHAR(10) NOT NULL," &
    "libelle VarChar(50)," &
    "pourcent CHAR(5)," &
    "montantd Decimal(12,2)," &
    "montantc Decimal(12,2)," &
    "jour Char(2)," &
    "poste Char(3)," &
    "validee TINYINT(1)," &
    Utils.db.AutoIncrement("lind") & ")" & Utils.db.Engine())

  Tab = "Fiches_MvtA2"
  Try Utils.db.Exec("CREATE TABLE " & Tab &
    " (numero Integer(6) NOT NULL," &
    "compte CHAR(8) NOT NULL," &
    "intitule Char(30)," &
    "dte date," &
    "numdoc CHAR(10) NOT NULL," &
    "libelle VarChar(50)," &
    "pourcent CHAR(5)," &
    "montantd Decimal(12,2)," &
    "montantc Decimal(12,2)," &
    "jour Char(2)," &
    "poste Char(3)," &
    "validee TINYINT(1)," &
    Utils.db.AutoIncrement("lind") & ")" & Utils.db.Engine())

  Tab = "Fiches_MvtA3"
  Try Utils.db.Exec("CREATE TABLE " & Tab &
    " (numero Integer(6) NOT NULL," &
    "compte CHAR(8) NOT NULL," &
    "intitule Char(30)," &
    "dte date," &
    "numdoc CHAR(10) NOT NULL," &
    "libelle VarChar(50)," &
    "pourcent CHAR(5)," &
    "montantd Decimal(12,2)," &
    "montantc Decimal(12,2)," &
    "jour Char(2)," &
    "poste Char(3)," &
    "validee TINYINT(1)," &
    Utils.db.AutoIncrement("lind") & ")" & Utils.db.Engine())

  Tab = "Fiches_MvtA4"
  Try Utils.db.Exec("CREATE TABLE " & Tab &
    " (numero Integer(6) NOT NULL," &
    "compte CHAR(8) NOT NULL," &
    "intitule Char(30)," &
    "dte date," &
    "numdoc CHAR(10) NOT NULL," &
    "libelle VarChar(50)," &
    "pourcent CHAR(5)," &
    "montantd Decimal(12,2)," &
    "montantc Decimal(12,2)," &
    "jour Char(2)," &
    "poste Char(3)," &
    "validee TINYINT(1)," &
    Utils.db.AutoIncrement("lind") & ")" & Utils.db.Engine())

  Tab = "Fiches_MvtA5"
  Try Utils.db.Exec("CREATE TABLE " & Tab &
    " (numero Integer(6) NOT NULL," &
    "compte CHAR(8) NOT NULL," &
    "intitule Char(30)," &
    "dte date," &
    "numdoc CHAR(10) NOT NULL," &
    "libelle VarChar(50)," &
    "pourcent CHAR(5)," &
    "montantd Decimal(12,2)," &
    "montantc Decimal(12,2)," &
    "jour Char(2)," &
    "poste Char(3)," &
    "validee TINYINT(1)," &
    Utils.db.AutoIncrement("lind") & ")" & Utils.db.Engine())

End

Public Sub Maj317()

  Tab = "Fiches_Cli"
  Try Utils.db.Exec("ALTER TABLE " & Tab & "  add cli_iban char(30)")
  Try Utils.db.Exec("ALTER TABLE " & Tab & "  add cli_bic char(11)")

  Tab = "Fiches_Four"
  Try Utils.db.Exec("ALTER TABLE " & Tab & "  add fo_iban char(30)")
  Try Utils.db.Exec("ALTER TABLE " & Tab & "  add fo_bic char(11)")

  Tab = "Fiches_Entrecpt"
  Try Utils.db.Exec("ALTER TABLE " & Tab & "  add validee TINYINT(1)")

End

Public Sub Maj318()

  Tab = "Fiches_Clid"
  Try Utils.db.Exec("CREATE TABLE " & Tab &
    "(adr VARCHAR(200)," &
    "ddate date," &
    Utils.db.AutoIncrement("lind") & ")" & Utils.db.Engine())

  Tab = "Fiches_Four"
  Try Utils.db.Exec("ALTER TABLE " & Tab & " change cli_iban fo_iban Char(30)")
  Try Utils.db.Exec("ALTER TABLE " & Tab & " change cli_bic fo_bic Char(11)")

  Tab = "Fiches_HistoLigfac"
  rResult = Utils.db.Exec("SELECT * FROM " & Tab & " where typel_ligfac = &1", "C")
  If rResult.Available Then
    Do
      If Not IsNull(rResult!libel_ligfac) Then
        Utils.db.Exec("UPdate " & Tab & " set com_ligfac = &1, libel_ligfac = &2 Where num_ligfac = &3 and numlig_ligfac = &4", rResult!libel_ligfac, "", rResult!num_ligfac, rResult!numlig_ligfac)
      Endif
    Loop Until rResult.MoveNext()
  Endif

End

Public Sub Maj319()

  Tab = "Fiches_Mvt"
  Try Utils.db.Exec("ALTER TABLE " & Tab & "  add dteval date")

End

Public Sub Maj320()

  Tab = "Fiches_HisEntTickets"
  Try Utils.db.Exec("ALTER TABLE " & Tab & " ADD (sresto Char(1))")
  Try Utils.db.Exec("ALTER TABLE " & Tab & " ADD (mresto Char(12))")

  Tab = "Fiches_EntTicketz"
  Try Utils.db.Exec("ALTER TABLE " & Tab & " ADD (sresto Char(1))")
  Try Utils.db.Exec("ALTER TABLE " & Tab & " ADD (mresto Char(12))")

  Tab = "Fiches_Caisses"
  rResult = Utils.db.Exec("SELECT * FROM " & Tab & " ")
  If rResult.Available Then
    Repeat
      Tab = "Fiches_EntTickets" & rResult!code
      Try Utils.db.Exec("ALTER TABLE " & Tab & " ADD (sresto Char(1))")
      Try Utils.db.Exec("ALTER TABLE " & Tab & " ADD (mresto Char(12))")
    Until rResult.MoveNext()
  Endif

  Tab = "Fiches_Banques"
  Try Utils.db.Exec("CREATE TABLE " & Tab &
    " (banques_code int(2) NOT NULL ," &
    "banques_nom VARCHAR(35)," &
    "banques_dmln VARCHAR(35)," &
    "banques_nume CHAR(6)," & ' Numéro émetteur attribué par la banque de france
    "banques_codeb VARCHAR(5)," & ' Code banque
    "banques_codeg VARCHAR(5)," & ' Code guichet
    "banques_numcpt VARCHAR(11)," & ' Numéro compte
    "banques_numsiren VARCHAR(15)," & ' Numéro risque-siren
    "banques_adr CHAR(1)," & ' Adresse bordereau (1- s'imprimera sur bordereau, 0- Ne s'imprimera pas)
    "banques_txt TEXT," & 'Texte d'entête du bordereau
    "banques_fenrg CHAR(6)," & ' Fin d'enregistrement si demandé par la banque ($ODOA$)
    "banques_mail VarChar(35)," &
    "banques_ref VarChar(11)," &
    "banques_entete VarChar(150)," &
    "banques_corps Text," &
    "banques_reftireur VarChar(10)," &
    "PRIMARY KEY (banques_code))")

  Tab = "Fiches_Bordereaux"
  Try Utils.db.EXEC("CREATE TABLE " & Tab &
    "(banque integer(1) ," &
    "codeentree integer(1) ," &
    "dateremise date ," &
    "refremise Char(11) ," &
    "datevaleur date ," &
    "ech1 date ," &
    "ech2 date ," &
    "bordereau Integer," &
    "tot Decimal(12,2)," &
    "etat TINYINT(1)," &
    Utils.db.AutoIncrement("lInd") & ")")

  Tab = "Fiches_Traites"
  Try Utils.db.Exec("ALTER TABLE " & Tab & " ADD nom VarChar(35)")
  Try Utils.db.Exec("ALTER TABLE " & Tab & " ADD acceptee Integer(1)")
  Try Utils.db.Exec("ALTER TABLE " & Tab & " ADD ecartee Integer(1)")

  Tab = "Fiches_Lcr"
  Try Utils.db.EXEC("CREATE TABLE " & Tab &
    "(code Char(8) ," &
    "nom VarChar(35) ," &
    "montant Char(12) ," &
    "date date ," &
    "datech date ," &
    "numfac Char(12) ," &
    "acceptee integer," &
    "ecartee integer," &
    "banque VarChar(35) ," &
    "codeentree integer(1)," &
    "bordereau VarChar(35)," &
    Utils.db.AutoIncrement("lInd") & ")")

  Tab = "Fiches_Fam"
  Try Utils.db.Exec("ALTER TABLE " & Tab & " ADD (compt2_fam Char(8))")
  rResult = Utils.db.Exec("SELECT * FROM " & Tab & " order by code_fam")
  If rResult.Available Then
    Repeat
      Utils.db.Exec("UPdate  " & tab & "  SET  compt2_fam = &1 WHERE compt_fam = &1", rResult!compt_fam)
    Until rResult.MoveNext()
  Endif

  Tab = "Fiches_Four"
  Try Utils.db.Exec("ALTER TABLE " & Tab & " change cli_iban fo_iban Char(30)")
  Try Utils.db.Exec("ALTER TABLE " & Tab & " change cli_bic fo_bic Char(11)")

  Tab = "Fiches_Mvt"
  Try Utils.db.Exec("ALTER TABLE " & Tab & "  add dteval date")

  Tab = "Fiches_Ligabon"
  Try Utils.db.Exec("ALTER TABLE " & Tab & " modify intitule VarChar(40)")

  Tab = "Fiches_Comptes"
  Try Utils.db.Exec("ALTER TABLE " & Tab & " ADD (lettrable TINYINT(1))")
  Utils.db.Exec("UPdate  " & tab & "  SET  lettrable = &1 WHERE type_cc = &2 or type_cc = &3", True, "F", "C")

  Tab = "Fiches_Fam"
  Try Utils.db.Exec("ALTER TABLE " & Tab & " ADD (compt3_fam Char(8))")

  Tab = "Fiches_Entrecpt"
  Try Utils.db.Exec("ALTER TABLE " & Tab & "  add validee TINYINT(1)")

  Tab = "Fiches_Parametres"
  Try Utils.db.Exec("ALTER TABLE " & Tab & " ADD (jrnal5 Char(2))")

  Tab = "Fiches_Entrecpt"
  Try Utils.db.Exec("ALTER TABLE " & Tab & "  add mttc Decimal(12,3)")
  Try Utils.db.Exec("ALTER TABLE " & Tab & "  change  montant montant Decimal(12,3)")

End

Public Sub Maj321()

  Tab = "Fiches_Comptes"
  Try Utils.db.Exec("ALTER TABLE " & Tab & " ADD lettrable TINYINT(1)")
  Utils.db.Exec("UPdate  " & tab & "  SET  lettrable = &1 WHERE type_cc = &2 or type_cc = &3", True, "F", "C")

  Tab = "Fiches_Fam"
  Try Utils.db.Exec("ALTER TABLE " & Tab & " ADD compt3_fam Char(8)")

  Tab = "Fiches_Entrecpt"
  Try Utils.db.Exec("ALTER TABLE " & Tab & "  add validee TINYINT(1)")

  Tab = "Fiches_Parametres"
  Try Utils.db.Exec("ALTER TABLE " & Tab & " ADD jrnal5 Char(2)")

  Tab = "Fiches_Entrecpt"
  Try Utils.db.Exec("ALTER TABLE " & Tab & "  add mttc Decimal(12,3)")
  Try Utils.db.Exec("ALTER TABLE " & Tab & "  change  montant montant Decimal(12,3)")

  Tab = "Corsage"
  Try Utils.db.EXEC("CREATE TABLE " & Tab &
    " (acode Char(8) NOT NULL," &
    "ncode char(8) NOT NULL," &
    "PRIMARY KEY (acode))" & Utils.db.Engine())

  Tab = "Corjxs"
  Try Utils.db.EXEC("CREATE TABLE " & Tab &
    " (sage Char(3) NOT NULL," &
    "laurux char(2) NOT NULL," &
    "PRIMARY KEY (sage))" & Utils.db.Engine())

  Tab = "Fiches_Art"
  Utils.db.Exec("UPdate  " & tab & "  SET  art_stocke = &1 where art_stocke = &2", "1", "-1")

End

Public Sub Maj322()

  Tab = "Fiches_Cli"
  Try Utils.db.Exec("ALTER TABLE " & Tab & " add cli_rum  Char(30)")
  Try Utils.db.Exec("ALTER TABLE " & Tab & " add cli_datab  char(2)")
  Try Utils.db.Exec("ALTER TABLE " & Tab & " add cli_aban  Varchar(15)")

  Tab = "Fiches_Four"
  Try Utils.db.Exec("ALTER TABLE " & Tab & " ADD (fo_exo TINYINT(1))")

  Tab = "Fiches_ContactC"
  Try Utils.db.Exec("ALTER TABLE " & Tab & " modify mail VarChar(150)")

  Tab = "Fiches_ContactF"
  Try Utils.db.Exec("ALTER TABLE " & Tab & " modify mail VarChar(150)")

  Tab = "Fiches_Four"
  Try Utils.db.Exec("ALTER TABLE " & Tab & " modify fo_email VarChar(150)")

  Tab = "Fiches_Cli"
  Try Utils.db.Exec("ALTER TABLE " & Tab & " modify cli_email VarChar(150)")

End

Public Sub Maj323()

  Try Tab = "Fiches_ContactC"
  Utils.db.Exec("ALTER TABLE " & Tab & " modify mail VarChar(150)")

  Try Tab = "Fiches_ContactF"
  Utils.db.Exec("ALTER TABLE " & Tab & " modify mail VarChar(150)")

  Try Tab = "Fiches_Four"
  Utils.db.Exec("ALTER TABLE " & Tab & " modify fo_email VarChar(150)")

  Try Tab = "Fiches_Cli"
  Utils.db.Exec("ALTER TABLE " & Tab & " modify cli_email VarChar(150)")

End

Public Sub Maj324()

  Tab = "Fiches_Art"
  Try Utils.db.Exec("ALTER TABLE " & Tab & " modify art_photo VarChar(100)")

End

Public Sub Maj325()

  Tab = "Fiches_Art"
  Try Utils.db.Exec("ALTER TABLE " & Tab & " modify art_photo VarChar(100)")

  Tab = "Fiches_HisLigTickets"
  Try Utils.db.Exec("ALTER TABLE " & Tab & " ADD (tva VarChar(12))")

  Tab1 = "Fiches_Caisses"
  rResult = Utils.db.Exec("SELECT * FROM " & Tab1 & " ")
  If rResult.Available Then
    Repeat
      Tab = "Fiches_LigTickets" & rResult!code
      Try Utils.db.Exec("ALTER TABLE " & Tab & " ADD (tva VarChar(12))")
    Until rResult.MoveNext()
  Endif

  Tab = "Fiches_LigTicketz"
  Try Utils.db.Exec("ALTER TABLE " & Tab & " ADD (tva VarChar(12))")

  Tab = "Fiches_Postes"
  Try Utils.db.Exec("ALTER TABLE " & Tab & " change intitule intitulep Varchar(35)")

  Tab = "Fiches_Mvt"
  Try Utils.db.Exec("ALTER TABLE " & Tab & "  add export char(1)")

  Tab = "Fiches_Caisses"
  Try Utils.db.Exec("ALTER TABLE " & Tab & " ADD (connecte integer(1))")
  Try Utils.db.Exec("ALTER TABLE " & Tab & " ADD (typeimp char(10))")
  Try Utils.db.Exec("ALTER TABLE " & Tab & " ADD (type char(20))")
  Try Utils.db.Exec("ALTER TABLE " & Tab & " ADD (poste char(20))")
  Try Utils.db.Exec("ALTER TABLE " & Tab & " ADD (ecole TINYINT)")
  Try Utils.db.Exec("ALTER TABLE " & Tab & " ADD (dntk Char(7))")
  Try Utils.db.Exec("ALTER TABLE " & Tab & " ADD (tkz integer(1))")
  Try Utils.db.Exec("ALTER TABLE " & Tab & " ADD (connecte integer(1))")
  Try Utils.db.Exec("ALTER TABLE " & Tab & " ADD (imp Char(15))")
  Try Utils.db.Exec("ALTER TABLE " & Tab & " ADD (typeimp char(10))")
  Try Utils.db.Exec("ALTER TABLE " & Tab & " ADD (type char(20))")
  Try Utils.db.Exec("ALTER TABLE " & Tab & " ADD (ecole TINYINT)")
  Try Utils.db.Exec("ALTER TABLE " & Tab & " ADD (poste char(20))")

  Tab = "Fiches_HistoFacM"
  Try Utils.db.Exec("ALTER TABLE " & Tab & " ADD (cdep VarChar(37))")
  Try Utils.db.Exec("ALTER TABLE " & Tab & " ADD (codep Char(15))")
  Try Utils.db.Exec("ALTER TABLE " & Tab & " ADD (mtreg Char(12))")

  Tab = "Fiches_HistoFac"
  Try Utils.db.Exec("ALTER TABLE " & Tab & " ADD (mtreg Char(12))")

End

Public Sub Maj326()

  Tab = "Fiches_Art"
  Try Utils.db.Exec("ALTER TABLE " & Tab & " ADD (art_depg TINYINT)")
  Try Utils.db.Exec("ALTER TABLE " & Tab & " ADD (art_cnsg TINYINT)")

  Tab1 = "Fiches_Cli"
  Try Utils.db.Exec("ALTER TABLE " & Tab1 & " ADD (cli_sage char(10))")

  Tab = "Fiches_HisInvT"
  Try Utils.db.EXEC("CREATE TABLE " & Tab &
    " (inv_num Int NOT NULL," &
    "inv_code Char(15) , " &
    "inv_qtestock Decimal(12,2) , " &
    "inv_qtecomptee Decimal(12,2) , " &
    "inv_date date , " &
    "PRIMARY KEY (inv_num, inv_code))" & Utils.db.Engine())

End

Public Sub Maj327()

  Tab = "Fiches_Cli"
  Try Utils.db.Exec("ALTER TABLE " & Tab & " ADD (cli_sage char(10))")

  Tab = "Fiches_HisEntTickets"
  Try Utils.db.Exec("ALTER TABLE " & Tab & " ADD (caisse Char(2))")

  Tab = "Fiches_Touches"
  Try Utils.db.EXEC("CREATE TABLE " & Tab &
    " (touche Char(3) NOT NULL," &
    "libelle Char(30) , " &
    "code Char(15) , " &
    "tva Decimal(5,2) , " &
    "PRIMARY KEY (touche))" & Utils.db.Engine())

  Tab = "Fiches_HisEntTickets"
  Utils.db.Exec("UPdate " & Tab & " set sresto = &1, mresto =&2", "", "")

End

Public Sub Maj328()

  Tab = "Fiches_Art"
  Try Utils.db.Exec("ALTER TABLE " & Tab & " ADD (art_ua char(5))")
  Try Utils.db.Exec("ALTER TABLE " & Tab & " ADD (art_uv char(5))")

End

Public Sub Maj329()

  Tab = "Fiches_Touches"
  Try Utils.db.Exec("ALTER TABLE " & Tab & " ADD (coul INT)")
  Try Utils.db.Exec("ALTER TABLE " & Tab & " ADD (fond varchar)")

End

Public Sub Maj330()

  Tab = "Fiches_Touches"
  Try Utils.db.Exec("ALTER TABLE " & Tab & " ADD (coul INT)")
  Try Utils.db.Exec("ALTER TABLE " & Tab & " ADD (fond varchar(100))")

End

Public Sub Maj331()

  Tab = "Fiches_Cli"
  Try Utils.db.Exec("ALTER TABLE " & Tab & " ADD (cli_livraison TINYINT(1))")
  Tab = "Fiches_Bl"
  Try Utils.db.Exec("ALTER TABLE " & Tab & " ADD (livraison TINYINT(1))")
  Tab = "Fiches_Entcom"
  Try Utils.db.Exec("ALTER TABLE " & Tab & " ADD (montantttc varchar(12))")
  Tab = "Fiches_Ligcom"
  Try Utils.db.Exec("ALTER TABLE " & Tab & " ADD (pattc varchar(12))")
  Tab = "Fiches_Entrecpt"
  Try Utils.db.Exec("ALTER TABLE " & Tab & " ADD (mttc varchar(12))")
  Tab = "Fiches_Ligrecpt"
  Try Utils.db.Exec("ALTER TABLE " & Tab & " ADD (pattc varchar(12))")

End

Public Sub Maj332()

  Tab = "Fiches_Ligbl"
  Utils.db.Exec("ALTER TABLE " & Tab & " modify fam_ligbl varchar(5)")
  Try Utils.db.Exec("ALTER TABLE " & Tab & " ADD (four_ligbl varchar(8))")
  Tab = "Fiches_Four"
  Try Utils.db.Exec("ALTER TABLE " & Tab & " add (fo_fport Decimal(12,2))")
  Tab = "Fiches_Entcom"
  Try Utils.db.Exec("ALTER TABLE " & Tab & " ADD (anomalie TINYINT(1))")
  Tab = "Fiches_Entrecpt"
  Try Utils.db.Exec("ALTER TABLE " & Tab & " ADD (anomalie TINYINT(1))")

End

Public Sub Maj333()

  Tab = "Fiches_Entcom"
  Try Utils.db.Exec("ALTER TABLE " & Tab & " ADD (anomalie TINYINT(1))")
  Try Utils.db.Exec("ALTER TABLE " & Tab & " ADD (commentaire TEXT)")
  Tab = "Fiches_Entrecpt"
  Try Utils.db.Exec("ALTER TABLE " & Tab & " ADD (anomalie TINYINT(1))")
  Try Utils.db.Exec("ALTER TABLE " & Tab & " ADD (commentaire TEXT)")

End

Public Sub Maj334()

  Tab = "Fiches_Entcom"
  Try Utils.db.Exec("ALTER TABLE " & Tab & " ADD (anomalie TINYINT(1))")
  Try Utils.db.Exec("ALTER TABLE " & Tab & " ADD (commentaire TEXT)")
  Tab = "Fiches_Entrecpt"
  Try Utils.db.Exec("ALTER TABLE " & Tab & " ADD (anomalie TINYINT(1))")
  Try Utils.db.Exec("ALTER TABLE " & Tab & " ADD (commentaire TEXT)")

End

Public Sub Maj335()

  Tab = "Docs_Fournisseurs"
  Try Utils.db.Exec("ALTER TABLE " & Tab & " DROP PRIMARY KEY ")
  Try Utils.db.Exec("ALTER TABLE " & Tab & " ADD PRIMARY KEY (code, doc)")
  Try Utils.db.Exec("ALTER TABLE " & Tab & " ADD (org char(4))")
  Tab = "Docs_Clients"
  Try Utils.db.Exec("ALTER TABLE " & Tab & " DROP PRIMARY KEY ")
  Try Utils.db.Exec("ALTER TABLE " & Tab & " ADD PRIMARY KEY (code, doc)")
  Try Utils.db.Exec("ALTER TABLE " & Tab & " ADD (org char(4))")
  Tab = "Docs_Produits"
  Try Utils.db.Exec("ALTER TABLE " & Tab & " DROP PRIMARY KEY ")
  Try Utils.db.Exec("ALTER TABLE " & Tab & " ADD PRIMARY KEY (code, doc)")
  Try Utils.db.Exec("ALTER TABLE " & Tab & " ADD (org char(4))")
  Tab = "Docs_Autres"
  Try Utils.db.EXEC("CREATE TABLE " & Tab &
    "(code VARCHAR(10), " &
    "doc VARCHAR(100)," &
    "doc2 VARCHAR(100)," &
    "org char(4)," &
    "PRIMARY KEY (code, doc))")
  Tab = "Docs_Compta"
  Try Utils.db.EXEC("CREATE TABLE " & Tab &
    "(code VARCHAR(10), " &
    "doc VARCHAR(100)," &
    "doc2 VARCHAR(100)," &
    "org char(4)," &
    "PRIMARY KEY (code, doc))")

End

Public Sub Maj336()

  Tab = "Docs_Autres"
  Try Utils.db.EXEC("CREATE TABLE " & Tab &
    "(code VARCHAR(10), " &
    "doc VARCHAR(100)," &
    "doc2 VARCHAR(100)," &
    "org char(4)," &
    "PRIMARY KEY (code, doc))")
  Tab = "Docs_Compta"
  Try Utils.db.Exec("ALTER TABLE " & Tab & " modify doc2 VarChar(300)")
  Try Utils.db.EXEC("CREATE TABLE " & Tab &
    "(code VARCHAR(10), " &
    "doc VARCHAR(100)," &
    "doc2 VARCHAR(300)," &
    "org char(4)," &
    "PRIMARY KEY (code, doc))")

End

Public Sub Maj337()

  Dim rfic As Result

  Tab = "Mails_Four"
  Try Utils.db.EXEC("CREATE TABLE " & Tab &
    "(code VARCHAR(8), " &
    "mail VARCHAR(150)," &
    "PRIMARY KEY (code, mail))")
  Rfic = Utils.db.Exec("SELECT * FROM " & Cbase.Table("TabFour") & "")
  Repeat
    If Not IsNull(rfic!fo_email) Then Try Utils.db.Exec("INSERT INTO " & Cbase.Table("TabMailFour") & " (code, mail) VALUES (&1, &2)", rfic!fo_code, rfic!fo_email)
  Until rfic.MoveNext()

  Tab = "Mails_Cli"
  Try Utils.db.EXEC("CREATE TABLE " & Tab &
    "(code VARCHAR(8), " &
    "mail VARCHAR(150)," &
    "PRIMARY KEY (code, mail))")
  Rfic = Utils.db.Exec("SELECT * FROM " & Cbase.Table("TabCli") & "")
  Repeat
    If Not IsNull(rfic!cli_email) Then Try Utils.db.Exec("INSERT INTO " & Cbase.Table("TabMailCli") & " (code, mail) VALUES (&1, &2)", rfic!cli_code, rfic!cli_email)
  Until rfic.MoveNext()

  Tab = "Fiches_Docactif"
  Try Utils.db.EXEC("Drop TABLE " & Tab & "")
  Try Utils.db.EXEC("CREATE TABLE " & Tab &
    "(numerobl CHAR(8), " &
    "nom VARCHAR(50)," &
    "PRIMARY KEY (numerobl, nom))")

  Tab = "Fiches_Journaux"
  Try Utils.db.Exec("ALTER TABLE " & Tab & " ADD PRIMARY KEY (code_jo)")

  Tab = "Fiches_Mvt"
  Try Utils.db.Exec("ALTER TABLE " & Tab & " modify collectif TINYINT(1)")
  rfic = Utils.db.Exec("Select distinct numero From " & Tab & " where pointee = &1", 1)
  If rfic.Available Then
    Repeat
      Utils.db.Exec("update " & Tab & " set pointee = &1 where numero = &2", 1, rfic!numero)
    Until rfic.MoveNext()
  Endif

End

Public Sub Maj338()

  Tab = "Mails_Cli"
  Try Utils.db.Exec("ALTER TABLE " & Tab & " modify mail VarChar(150)")

  Tab = "Mails_Four"
  Try Utils.db.Exec("ALTER TABLE " & Tab & " modify mail VarChar(150)")

  Tab = "Fiches_BlM"
  Try Utils.db.Exec("ALTER TABLE " & Tab & " ADD (livraison TINYINT(1))")

  Tab = "Fiches_LigblM"
  Try Utils.db.Exec("ALTER TABLE " & Tab & " ADD (four_ligbl varchar(8))")

End

Public Sub Maj339()

  Tab = "Fiches_Caisses"
  Try Utils.db.Exec("ALTER TABLE " & Tab & " modify poste VarChar(30)")

  Tab = "Fiches_Touches"
  Try Utils.db.Exec("ALTER TABLE " & Tab & " ADD (touche_s TINYINT(1))")
  Try Utils.db.Exec("ALTER TABLE " & Tab & " modify touche Char(6)")

End

Public Sub Maj340()

  Tab = "Fiches_Commerciaux"
  Try Utils.db.EXEC("CREATE TABLE " & Tab &
    " (code Char(2)," &
    "nom Char(35)," &
    "prenom Char(35)," &
    "comm Decimal(5,2)," &
    Utils.db.AutoIncrement("lInd") & ")")

  Tab = "Fiches_Cli"
  Try Utils.db.Exec("ALTER TABLE " & Tab & " ADD (cli_comm char(2))")

End

Public Sub Maj341()

  Tab = "Fiches_Sms"
  Try Utils.db.EXEC("CREATE TABLE " & Tab &
    " (numcom char(2) NOT NULL," &
    "intitule text ," &
    "PRIMARY KEY (numcom))" & Utils.db.Engine())

  Tab = "Fiches_ContactC"
  Try Utils.db.Exec("ALTER TABLE " & Tab & " ADD (portable Char(16))")

  Tab = "Fiches_ContactF"
  Try Utils.db.Exec("ALTER TABLE " & Tab & " ADD (portable Char(16))")

  Tab = "Fiches_Docactif"
  Try Utils.db.Exec("ALTER TABLE " & Tab & " ADD (ecran Integer(1))")

  Tab = "Fiches_Numabon"
  Try Utils.db.Exec("ALTER TABLE " & Tab & " modify numero Int")

End

Public Sub Maj342()

  Tab = "Fiches_Numabon"
  Try Utils.db.Exec("ALTER TABLE " & Tab & " modify numero Int")

  Tab = "Fiches_Cli"
  Utils.db.Exec("ALTER TABLE " & Tab & " modify cli_id_tva VARCHAR(15)")

  Tab = "Fiches_Four"
  Utils.db.Exec("ALTER TABLE " & Tab & " modify fo_id_tva VARCHAR(15)")

  Tab = "Fiches_Docactif"
  Try Utils.db.Exec("ALTER TABLE " & Tab & " ADD (ecran Integer(1))")

End

Public Sub Maj343()

  Tab = "Fiches_Mvt"
  Try Utils.db.Exec("ALTER TABLE " & Tab & " drop numerop")
  Try Utils.db.Exec("ALTER TABLE " & Tab & " drop numeropdef")

  Tab = "Fiches_Docactif"
  Try Utils.db.Exec("ALTER TABLE " & Tab & " ADD (ecran Integer(1))")

End

Public Sub Maj344()

  Tab = "Fiches_Bl"
  Try Utils.db.Exec("ALTER TABLE " & Tab & " add (tel VARCHAR(16))")
  Utils.db.Exec("ALTER TABLE " & Tab & " modify tel VARCHAR(16)")
  Tab = "Fiches_BlM"
  Try Utils.db.Exec("ALTER TABLE " & Tab & " add (tel VARCHAR(16))")

End

Public Sub Maj345()

  Try Utils.db.Exec("ALTER TABLE Fiches_Bl modify tel VARCHAR(16)")
  Try Utils.db.Exec("ALTER TABLE Fiches_BlM add (tel VARCHAR(16))")

  Tab = "Fiches_FamDep"
  Try Utils.db.EXEC("CREATE TABLE " & Tab &
    " (fam Char(5)," &
    "compte Char(8)," &
    "depot Char(8)," &
    Utils.db.AutoIncrement("lInd") & ")")

  Try Utils.db.Exec("ALTER TABLE Fiches_Caisses ADD (depot char(8))")
  Try Utils.db.Exec("ALTER TABLE Fiches_HistoLigfac ADD mrgart_ligfac DECIMAL(12,3)")
  Try Utils.db.Exec("ALTER TABLE Fiches_HistoLigfac ADD mrgmo_ligfac DECIMAL(12,3)")
  Try Utils.db.Exec("ALTER TABLE Fiches_HistoLigfacM ADD mrgart_ligfac DECIMAL(12,3)")
  Try Utils.db.Exec("ALTER TABLE Fiches_HistoLigfacM ADD mrgmo_ligfac DECIMAL(12,3)")
  Try Utils.db.Exec("ALTER TABLE Fiches_Art ADD (art_refliee Char(15))")

End

Public Sub Maj346()

  Try Utils.db.Exec("ALTER TABLE Fiches_Art ADD (art_refliee Char(15))")
  Try Utils.db.Exec("update Fiches_HistoFac set exofac = &1", 0)

End

Public Sub Maj347()

  Try Utils.db.Exec("ALTER TABLE Fiches_HistoLigfac modify mrgart_ligfac DECIMAL(12,3)")
  Try Utils.db.Exec("ALTER TABLE Fiches_HistoLigfac modify mrgmo_ligfac DECIMAL(12,3)")
  Try Utils.db.Exec("ALTER TABLE Fiches_HistoLigfacM modify mrgart_ligfac DECIMAL(12,3)")
  Try Utils.db.Exec("ALTER TABLE Fiches_HistoLigfacM modify mrgmo_ligfac DECIMAL(12,3)")
  Try Utils.db.Exec("alter table Fiches_LigTicketz add marge decimal(7, 2)")

End

Public Sub Maj348()

  Try Utils.db.Exec("ALTER TABLE Fiches_Art modify art_datefbt date Null Default Null")
  Try Utils.db.Exec("ALTER TABLE Fiches_Art modify art_ddatefbt date Null Default Null")
  Try Utils.db.Exec("ALTER TABLE Fiches_EntTicketz ADD (nom VARCHAR(35))")
  Try Utils.db.Exec("ALTER TABLE Fiches_HisEntTickets ADD (nom VARCHAR(35))")
  rResult = Utils.db.Exec("SELECT * FROM Fiches_Caisses ")
  If rResult.Available Then
    Repeat
      Tab = "Fiches_EntTickets" & rResult!code
      Try Utils.db.Exec("ALTER TABLE " & Tab & " ADD (nom VARCHAR(35))")
    Until rResult.MoveNext()
  Endif

End

Public Sub Maj349()

  Try Utils.db.Exec("ALTER TABLE Fiches_Four ADD (fo_cb VARCHAR(13))")

End

Public Sub Maj350()

  Try Utils.db.Exec("ALTER TABLE Fiches_Parametres ADD (dnbr Char(8))")
  bMaj = True

End

Public Sub Maj351()

  Try Utils.db.Exec("ALTER TABLE Fiches_Fam ADD (compt4_fam Char(8))")
  bMaj = True

End

Public Sub Maj352()

  Try Utils.db.Exec("ALTER TABLE Fiches_Parametres ADD (nfac TINYINT(1))")
  Try Utils.db.Exec("ALTER TABLE Fiches_PrdComp ADD (mo TINYINT(1))")
  Try Utils.db.Exec("ALTER TABLE Fiches_LigTicketz modify type Char(2)")
  rResult = Utils.db.Exec("SELECT * FROM Fiches_Caisses ")
  If rResult.Available Then
    Repeat
      Tab = "Fiches_LigTickets" & rResult!code
      Try Utils.db.Exec("ALTER TABLE " & Tab & " modify type Char(2)")
    Until rResult.MoveNext()
  Endif
  bMaj = True

End

Public Sub Maj353()

  Try Utils.db.Exec("ALTER TABLE Fiches_Ligrecpt modify design VarChar(50)")
  Try Utils.db.Exec("ALTER TABLE Fiches_Touches ADD (cai Char(2))")
  Try Utils.db.Exec("ALTER TABLE Fiches_Touches DROP PRIMARY KEY ")
  Try Utils.db.Exec("ALTER TABLE Fiches_Touches ADD PRIMARY KEY (touche, cai)")
  Try Utils.db.Exec("ALTER TABLE Fiches_Touches modify touche Char(6)")
  rResult = Utils.db.Exec("SELECT * FROM Fiches_Caisses ")
  If rResult.Available Then
    Repeat
      Try Utils.db.Exec("update Fiches_Touches set cai = &1", rResult!code)
      Tab = "Fiches_EntTickets" & rResult!code
      Try Utils.db.Exec("ALTER TABLE " & Tab & " ADD (suppr TINYINT(1))")
      Try Utils.db.Exec("update " & Tab & " set suppr = &1", False)
    Until rResult.MoveNext()
  Endif

End

Public Sub Maj354()

  rResult = Utils.db.Exec("SELECT * FROM Fiches_Caisses ")
  If rResult.Available Then
    Repeat
      Tab = "Fiches_EntTickets" & rResult!code
      Try Utils.db.Exec("ALTER TABLE " & Tab & " ADD (retro TINYINT(1))")
    Until rResult.MoveNext()
  Endif

  Tab = "Fiches_EntTicketz"
  Try Utils.db.Exec("ALTER TABLE " & Tab & " ADD (retro TINYINT(1))")

  Try Utils.db.Exec("ALTER TABLE Fiches_Bl modify rartbl VarChar(6)")

  Tab = "Fiches_Fam"
  Try Utils.db.Exec("ALTER TABLE " & Tab & " ADD (compt5_fam Char(8))")
  rResult = Utils.db.Exec("SELECT * FROM " & Tab & " order by code_fam")
  If rResult.Available Then
    Repeat
      Utils.db.Exec("UPdate  " & tab & "  SET  compt5_fam = &1 WHERE compt_fam = &1", rResult!compt_fam)
    Until rResult.MoveNext()
  Endif

  Tab = "Fiches_ImpArtDef2"
  Try Utils.db.Exec("ALTER TABLE " & Tab & " ADD (posorg_26 CHAR(4))")
  Try Utils.db.Exec("ALTER TABLE " & Tab & " ADD (col_26 VARCHAR(50))")
  Try Utils.db.Exec("ALTER TABLE " & Tab & " ADD (db_26 INT)")
  Try Utils.db.Exec("ALTER TABLE " & Tab & " ADD (lg_26 INT)")
  Try Utils.db.Exec("ALTER TABLE " & Tab & " ADD (pos_26 INT)")
  Try Utils.db.Exec("ALTER TABLE " & Tab & " ADD (posorg_27 CHAR(4))")
  Try Utils.db.Exec("ALTER TABLE " & Tab & " ADD (col_27 VARCHAR(50))")
  Try Utils.db.Exec("ALTER TABLE " & Tab & " ADD (db_27 INT)")
  Try Utils.db.Exec("ALTER TABLE " & Tab & " ADD (lg_27 INT)")
  Try Utils.db.Exec("ALTER TABLE " & Tab & " ADD (pos_27 INT)")
  Try Utils.db.Exec("ALTER TABLE " & Tab & " ADD (posorg_28 CHAR(4))")
  Try Utils.db.Exec("ALTER TABLE " & Tab & " ADD (col_28 VARCHAR(50))")
  Try Utils.db.Exec("ALTER TABLE " & Tab & " ADD (db_28 INT)")
  Try Utils.db.Exec("ALTER TABLE " & Tab & " ADD (lg_28 INT)")
  Try Utils.db.Exec("ALTER TABLE " & Tab & " ADD (pos_28 INT)")
  Try Utils.db.Exec("ALTER TABLE " & Tab & " ADD (posorg_29 CHAR(4))")
  Try Utils.db.Exec("ALTER TABLE " & Tab & " ADD (col_29 VARCHAR(50))")
  Try Utils.db.Exec("ALTER TABLE " & Tab & " ADD (db_29 INT)")
  Try Utils.db.Exec("ALTER TABLE " & Tab & " ADD (lg_29 INT)")
  Try Utils.db.Exec("ALTER TABLE " & Tab & " ADD (pos_29 INT)")

End

Public Sub Maj355()

  Tab = "Fiches_Cli"
  Try Utils.db.Exec("ALTER TABLE " & Tab & " ADD (cli_autoent TINYINT(1))")
  Tab = "Fiches_BordereauxC" ' On créé la table des bordereaux de chèques
  Try Utils.db.EXEC("CREATE TABLE " & Tab &
    "(banque integer(1) ," &
    "dateremise date ," &
    "bordereau Integer," &
    "montant Decimal(12,2)," &
    "etat TINYINT(1)," &
    "code Char(8), " &
    "nom Varchar(35), " &
    "nfacture Char(10), " &
    Utils.db.AutoIncrement("lInd") & ")")
  Try Utils.db.Exec("ALTER TABLE Fiches_Journaux modify libelle_jo VarChar(30)")

End

Public Sub Maj356()

  Tab = "Fiches_BordereauxC"
  Try Utils.db.Exec("drop Table IF exists " & Tab & "")
  Try Utils.db.EXEC("CREATE TABLE " & Tab &
    "(banque integer(1) ," &
    "dateremise date ," &
    "bordereau Integer," &
    "montant Decimal(12,2)," &
    "etat TINYINT(1)," &
    "code Char(8), " &
    "nom Varchar(35), " &
    "nfacture Char(10), " &
    Utils.db.AutoIncrement("lInd") & ")")
  Try Utils.db.Exec("ALTER TABLE Fiches_Journaux modify libelle_jo VarChar(30)")
  Tab = "Fiches_Parametres"
  Try Utils.db.Exec("ALTER TABLE " & Tab & " ADD PRIMARY KEY (ind)")

End

Public Sub Maj357()

  Tab = "Fiches_Tvaac"
  Try Utils.db.Exec("ALTER TABLE " & Tab & " modify code_tva Char(2)")
  Tab = "Fiches_Tvaav"
  Try Utils.db.Exec("ALTER TABLE " & Tab & " modify code_tva Char(2)")
  Tab = "Fiches_Art"
  Try Utils.db.Exec("ALTER TABLE " & Tab & " modify art_tva Char(2)")
  Tab = "Fiches_Mo"
  Try Utils.db.Exec("ALTER TABLE " & Tab & " modify mo_tva Char(2)")
  Tab = "Fiches_Fam"
  Try Utils.db.Exec("ALTER TABLE " & Tab & " modify cdtva_fam Char(2)")
  Tab = "Fiches_Ligbl"
  Try Utils.db.Exec("ALTER TABLE " & Tab & " modify tx_ligbl Char(2)")
  Tab = "Fiches_LigblM"
  Try Utils.db.Exec("ALTER TABLE " & Tab & " modify tx_ligbl Char(2)")
  Tab = "Fiches_Comptes"
  Try Utils.db.Exec("ALTER TABLE " & Tab & " modify code_tvente Char(2)")
  Try Utils.db.Exec("ALTER TABLE " & Tab & " modify code_tachat Char(2)")
  Tab = "Totalisation"
  Try Utils.db.Exec("ALTER TABLE " & Tab & " modify codetva Char(2)")
  Tab = "Fiches_ImpArtDef2"
  Try Utils.db.Exec("ALTER TABLE " & Tab & " ADD (posorg_30 CHAR(4))")
  Try Utils.db.Exec("ALTER TABLE " & Tab & " ADD (col_30 VARCHAR(50))")
  Try Utils.db.Exec("ALTER TABLE " & Tab & " ADD (db_30 INT)")
  Try Utils.db.Exec("ALTER TABLE " & Tab & " ADD (lg_30 INT)")
  Try Utils.db.Exec("ALTER TABLE " & Tab & " ADD (pos_30 INT)")
  Try Utils.db.Exec("ALTER TABLE " & Tab & " ADD (posorg_31 CHAR(4))")
  Try Utils.db.Exec("ALTER TABLE " & Tab & " ADD (col_31 VARCHAR(50))")
  Try Utils.db.Exec("ALTER TABLE " & Tab & " ADD (db_31 INT)")
  Try Utils.db.Exec("ALTER TABLE " & Tab & " ADD (lg_31 INT)")
  Try Utils.db.Exec("ALTER TABLE " & Tab & " ADD (pos_31 INT)")
  Try Utils.db.Exec("ALTER TABLE " & Tab & " ADD (posorg_32 CHAR(4))")
  Try Utils.db.Exec("ALTER TABLE " & Tab & " ADD (col_32 VARCHAR(50))")
  Try Utils.db.Exec("ALTER TABLE " & Tab & " ADD (db_32 INT)")
  Try Utils.db.Exec("ALTER TABLE " & Tab & " ADD (lg_32 INT)")
  Try Utils.db.Exec("ALTER TABLE " & Tab & " ADD (pos_32 INT)")

  Tab = "Fiches_Users"
  Try Utils.db.EXEC("CREATE TABLE " & Tab &
    "(nom Varchar(20), " &
    "poste Varchar(35), " &
    Utils.db.AutoIncrement("lInd") & ")")

  Tab = "Fiches_Taches"
  Try Utils.db.EXEC("CREATE TABLE " & Tab &
    "(numdoc Varchar(10), " &
    "nom Char(8), " &
    "poste Varchar(40), " &
    "numcli Char(8), " &
    "nomcli Varchar(40), " &
    "texte Varchar(100), " &
    Utils.db.AutoIncrement("lInd") & ")")

  Tab = "Fiches_Carte"
  Try Utils.db.Exec("ALTER TABLE " & Tab & " ADD (divers TINYINT)")
  Try Utils.db.Exec("UPdate  " & tab & "  SET  divers= &1", 0)

  Tab = "Fiches_Bl"
  Try Utils.db.Exec("ALTER TABLE " & Tab & " ADD (reg2 VARCHAR(15))")
  Try Utils.db.Exec("ALTER TABLE " & Tab & " ADD ( mtreg2 VARCHAR(12))")

End

Public Sub Maj358()

  Tab = "Fiches_HisEntTickets"
  Try Utils.db.Exec("ALTER TABLE " & Tab & " modify date Char(17)")

  Tab = "Fiches_Bl"
  Try Utils.db.Exec("ALTER TABLE " & Tab & " modify datebl Datetime")

  Tab = "Fiches_BlM"
  Try Utils.db.Exec("ALTER TABLE " & Tab & " modify datebl Datetime")

  Tab = "Fiches_HistoFac"
  Try Utils.db.Exec("ALTER TABLE " & Tab & " modify datefac Datetime")

  Tab = "Fiches_HistoFacM"
  Try Utils.db.Exec("ALTER TABLE " & Tab & " modify datefac Datetime")

  Tab = "Fiches_MvtM"
  Try Utils.db.Exec("CREATE TABLE " & Tab &
    " (jour Char(2)," &
    "numero Integer(6) NOT NULL," &
    "numerodef Integer(6)," &
    "compte CHAR(8) NOT NULL," &
    "collectif TINYINT," &
    "intitule Char(30)," &
    "dte date," &
    "datee date, " &
    "dateech date, " &
    "numcol Char(3)," &
    "numdoc CHAR(10)," &
    "numlot CHAR(10)," &
    "libelle VarChar(50)," &
    "montantd Decimal(12,2)," &
    "montantc Decimal(12,2)," &
    "validee TINYINT(1)," &
    "provisoire TINYINT(1)," &
    "tresorerie  TINYINT(1)," &
    "pointee TINYINT(1)," &
    "nrlv INTEGER(8)," &
    "lettree TINYINT(1)," &
    "cloturee TINYINT(1)," &
    "dteval date, " &
    "relance INTEGER(1)," &
    "numerop Integer(11)," &
    "numeropdef Integer(11)," &
    "export Char(1)," &
    "control VARCHAR(40)," &
    "supprimee TINYINT(1)," &
    "lind2 INT," &
    Utils.db.AutoIncrement("lind") & ")" & Utils.db.Engine())
  Try Utils.db.Exec("ALTER TABLE " & Tab & " ADD (INDEX date (dte))")
  Try Utils.db.Exec("ALTER TABLE " & Tab & " ADD (INDEX numero2 (numero))")
  Try Utils.db.Exec("ALTER TABLE " & Tab & " ADD (INDEX compte2 (compte))")

  Tab = "Fiches_MvtM1"
  Try Utils.db.Exec("CREATE TABLE " & Tab &
    " (jour Char(2)," &
    "numero Integer(6) NOT NULL," &
    "numerodef Integer(6) NOT NULL," &
    "compte CHAR(8) NOT NULL," &
    "collectif TINYINT," &
    "intitule Char(30)," &
    "dte date," &
    "datee date, " &
    "dateech date, " &
    "numcol Char(3)," &
    "numdoc CHAR(10)," &
    "numlot CHAR(10)," &
    "libelle VarChar(50)," &
    "montantd Decimal(12,2)," &
    "montantc Decimal(12,2)," &
    "validee TINYINT(1)," &
    "provisoire TINYINT(1)," &
    "tresorerie  TINYINT(1)," &
    "pointee TINYINT(1)," &
    "nrlv INTEGER(8)," &
    "lettree TINYINT(1)," &
    "cloturee TINYINT(1)," &
    "dteval date, " &
    "relance INTEGER(1)," &
    "numerop Integer(11)," &
    "numeropdef Integer(11)," &
    "export Char(1)," &
    "control VARCHAR(40)," &
    "supprimee TINYINT(1)," &
    "lind2 INT," &
    Utils.db.AutoIncrement("lind") & ")" & Utils.db.Engine())
  Try Utils.db.Exec("ALTER TABLE " & Tab & " ADD (INDEX date (dte))")
  Try Utils.db.Exec("ALTER TABLE " & Tab & " ADD (INDEX numero2 (numero))")
  Try Utils.db.Exec("ALTER TABLE " & Tab & " ADD (INDEX compte2 (compte))")

  Tab = "Fiches_MvtM2"
  Try Utils.db.Exec("CREATE TABLE " & Tab &
    " (jour Char(2)," &
    "numero Integer(6) NOT NULL," &
    "numerodef Integer(6) NOT NULL," &
    "compte CHAR(8) NOT NULL," &
    "collectif TINYINT," &
    "intitule Char(30)," &
    "dte date," &
    "datee date, " &
    "dateech date, " &
    "numcol Char(3)," &
    "numdoc CHAR(10)," &
    "numlot CHAR(10)," &
    "libelle VarChar(50)," &
    "montantd Decimal(12,2)," &
    "montantc Decimal(12,2)," &
    "validee TINYINT(1)," &
    "provisoire TINYINT(1)," &
    "tresorerie  TINYINT(1)," &
    "pointee TINYINT(1)," &
    "nrlv INTEGER(8)," &
    "lettree TINYINT(1)," &
    "cloturee TINYINT(1)," &
    "dteval date, " &
    "relance INTEGER(1)," &
    "numerop Integer(11)," &
    "numeropdef Integer(11)," &
    "export Char(1)," &
    "control VARCHAR(40)," &
    "supprimee TINYINT(1)," &
    "lind2 INT," &
    Utils.db.AutoIncrement("lind") & ")" & Utils.db.Engine())
  Try Utils.db.Exec("ALTER TABLE " & Tab & " ADD (INDEX date (dte))")
  Try Utils.db.Exec("ALTER TABLE " & Tab & " ADD (INDEX numero2 (numero))")
  Try Utils.db.Exec("ALTER TABLE " & Tab & " ADD (INDEX compte2 (compte))")

  Tab = "Fiches_MvtM3"
  Try Utils.db.Exec("CREATE TABLE " & Tab &
    " (jour Char(2)," &
    "numero Integer(6) NOT NULL," &
    "numerodef Integer(6) NOT NULL," &
    "compte CHAR(8) NOT NULL," &
    "collectif TINYINT," &
    "intitule Char(30)," &
    "dte date," &
    "datee date, " &
    "dateech date, " &
    "numcol Char(3)," &
    "numdoc CHAR(10)," &
    "numlot CHAR(10)," &
    "libelle VarChar(50)," &
    "montantd Decimal(12,2)," &
    "montantc Decimal(12,2)," &
    "validee TINYINT(1)," &
    "provisoire TINYINT(1)," &
    "tresorerie  TINYINT(1)," &
    "pointee TINYINT(1)," &
    "nrlv INTEGER(8)," &
    "lettree TINYINT(1)," &
    "cloturee TINYINT(1)," &
    "dteval date, " &
    "relance INTEGER(1)," &
    "numerop Integer(11)," &
    "numeropdef Integer(11)," &
    "export Char(1)," &
    "control VARCHAR(40)," &
    "supprimee TINYINT(1)," &
    "lind2 INT," &
    Utils.db.AutoIncrement("lind") & ")" & Utils.db.Engine())
  Try Utils.db.Exec("ALTER TABLE " & Tab & " ADD (INDEX date (dte))")
  Try Utils.db.Exec("ALTER TABLE " & Tab & " ADD (INDEX numero2 (numero))")
  Try Utils.db.Exec("ALTER TABLE " & Tab & " ADD (INDEX compte2 (compte))")

  Tab = "Fiches_MvtM4"
  Try Utils.db.Exec("CREATE TABLE " & Tab &
    " (jour Char(2)," &
    "numero Integer(6) NOT NULL," &
    "numerodef Integer(6) NOT NULL," &
    "compte CHAR(8) NOT NULL," &
    "collectif TINYINT," &
    "intitule Char(30)," &
    "dte date," &
    "datee date, " &
    "dateech date, " &
    "numcol Char(3)," &
    "numdoc CHAR(10)," &
    "numlot CHAR(10)," &
    "libelle VarChar(50)," &
    "montantd Decimal(12,2)," &
    "montantc Decimal(12,2)," &
    "validee TINYINT(1)," &
    "provisoire TINYINT(1)," &
    "tresorerie  TINYINT(1)," &
    "pointee TINYINT(1)," &
    "nrlv INTEGER(8)," &
    "lettree TINYINT(1)," &
    "cloturee TINYINT(1)," &
    "dteval date, " &
    "relance INTEGER(1)," &
    "numerop Integer(11)," &
    "numeropdef Integer(11)," &
    "export Char(1)," &
    "control VARCHAR(40)," &
    "supprimee TINYINT(1)," &
    "lind2 INT," &
    Utils.db.AutoIncrement("lind") & ")" & Utils.db.Engine())
  Try Utils.db.Exec("ALTER TABLE " & Tab & " ADD (INDEX date (dte))")
  Try Utils.db.Exec("ALTER TABLE " & Tab & " ADD (INDEX numero2 (numero))")
  Try Utils.db.Exec("ALTER TABLE " & Tab & " ADD (INDEX compte2 (compte))")

  Tab = "Fiches_MvtM5"
  Try Utils.db.Exec("CREATE TABLE " & Tab &
    " (jour Char(2)," &
    "numero Integer(6) NOT NULL," &
    "numerodef Integer(6) NOT NULL," &
    "compte CHAR(8) NOT NULL," &
    "collectif TINYINT," &
    "intitule Char(30)," &
    "dte date," &
    "datee date, " &
    "dateech date, " &
    "numcol Char(3)," &
    "numdoc CHAR(10)," &
    "numlot CHAR(10)," &
    "libelle VarChar(50)," &
    "montantd Decimal(12,2)," &
    "montantc Decimal(12,2)," &
    "validee TINYINT(1)," &
    "provisoire TINYINT(1)," &
    "tresorerie  TINYINT(1)," &
    "pointee TINYINT(1)," &
    "nrlv INTEGER(8)," &
    "lettree TINYINT(1)," &
    "cloturee TINYINT(1)," &
    "dteval date, " &
    "relance INTEGER(1)," &
    "numerop Integer(11)," &
    "numeropdef Integer(11)," &
    "export Char(1)," &
    "control VARCHAR(40)," &
    "supprimee TINYINT(1)," &
    "lind2 INT," &
    Utils.db.AutoIncrement("lind") & ")" & Utils.db.Engine())
  Try Utils.db.Exec("ALTER TABLE " & Tab & " ADD (INDEX date (dte))")
  Try Utils.db.Exec("ALTER TABLE " & Tab & " ADD (INDEX numero2 (numero))")
  Try Utils.db.Exec("ALTER TABLE " & Tab & " ADD (INDEX compte2 (compte))")

  Tab = "Fiches_Mvt"
  Try Utils.db.Exec("ALTER TABLE " & Tab & " ADD (control VARCHAR(40))")
  Try Utils.db.Exec("ALTER TABLE " & Tab & " modify libelle VarChar(50)")
  Tab = "Fiches_Mvt1"
  Try Utils.db.Exec("ALTER TABLE " & Tab & " ADD (control VARCHAR(40))")
  Try Utils.db.Exec("ALTER TABLE " & Tab & " modify libelle VarChar(50)")
  Tab = "Fiches_Mvt2"
  Try Utils.db.Exec("ALTER TABLE " & Tab & " ADD (control VARCHAR(40))")
  Try Utils.db.Exec("ALTER TABLE " & Tab & " modify libelle VarChar(50)")
  Tab = "Fiches_Mvt3"
  Try Utils.db.Exec("ALTER TABLE " & Tab & " ADD (control VARCHAR(40))")
  Try Utils.db.Exec("ALTER TABLE " & Tab & " modify libelle VarChar(50)")
  Tab = "Fiches_Mvt4"
  Try Utils.db.Exec("ALTER TABLE " & Tab & " ADD (control VARCHAR(40))")
  Try Utils.db.Exec("ALTER TABLE " & Tab & " modify libelle VarChar(50)")
  Tab = "Fiches_Mvt5"
  Try Utils.db.Exec("ALTER TABLE " & Tab & " ADD (control VARCHAR(40))")
  Try Utils.db.Exec("ALTER TABLE " & Tab & " modify libelle VarChar(50)")

  Tab = "Fiches_Bl"
  Try Utils.db.Exec("ALTER TABLE " & Tab & " ADD (reg2 VARCHAR(15))")
  Try Utils.db.Exec("ALTER TABLE " & Tab & " ADD ( mtreg2 VARCHAR(12))")

  If Not Error Then bmaj = True

End

Public Sub maj359()

  Tab = "Fiches_EntTicketz"
  Try Utils.db.Exec("ALTER TABLE " & Tab & " ADD (suppr TINYINT(1))")
  Try Utils.db.Exec("update " & Tab & " set suppr = &1", False)
  Tab = "Fiches_HisEntTickets"
  Try Utils.db.Exec("ALTER TABLE " & Tab & " ADD (suppr TINYINT(1))")
  Try Utils.db.Exec("update " & Tab & " set suppr = &1", False)
  Tab = "Fiches_Bl"
  Try Utils.db.Exec("ALTER TABLE " & Tab & " ADD (acquitte TINYINT(1))")
  Tab = "Fiches_HistoFac"
  Try Utils.db.Exec("ALTER TABLE " & Tab & " ADD (acquitte TINYINT(1))")
  Tab = "Fiches_BlM"
  Try Utils.db.Exec("ALTER TABLE " & Tab & " ADD (reg2 VARCHAR(15))")
  Try Utils.db.Exec("ALTER TABLE " & Tab & " ADD ( mtreg2 VARCHAR(12))")
  Try Utils.db.Exec("ALTER TABLE " & Tab & " ADD (acquitte TINYINT(1))")
  Tab = "Fiches_HistoFacM"
  Try Utils.db.Exec("ALTER TABLE " & Tab & " ADD (acquitte TINYINT(1))")
  Tab = "Fiches_Mvt"
  Try Utils.db.Exec("ALTER TABLE " & Tab & " modify control VARCHAR(40)")
  If Not Error Then bmaj = True

End

Public Sub maj360()

  Tab = "Fiches_Mvt"
  Try Utils.db.Exec("ALTER TABLE " & Tab & " modify control VARCHAR(40)")
  Try Utils.db.Exec("ALTER TABLE " & Tab & " ADD (supprimee TINYINT(1))")
  Try Utils.db.Exec("ALTER TABLE " & Tab & "  add export char(1)")
  Try Utils.db.Exec("ALTER TABLE Fiches_Bl modify rartbl VarChar(6)")

  Tab = "Fiches_MvtM"
  Try Utils.db.Exec("ALTER TABLE " & Tab & " ADD (supprimee TINYINT(1))")
  'Reg BL en caisse
  Try Utils.db.Exec("ALTER TABLE Fiches_Bl add (numtick Char(7))")
  Try Utils.db.Exec("ALTER TABLE Fiches_BlM add (numtick Char(7))")
  Try Utils.db.Exec("ALTER TABLE Fiches_HisLigTickets modify type Char(2)")
  'Format de page etiquette
  Try Utils.db.Exec("ALTER TABLE Fiches_Etiquettes add (page VarChar(20))")
  Try Utils.db.Exec("ALTER TABLE Fiches_Etiquettes DROP PRIMARY KEY")
  Try Utils.db.Exec("ALTER TABLE Fiches_Etiquettes ADD PRIMARY KEY (code, page)")
  Try Utils.db.Exec("update Fiches_Etiquettes set page = &1 ", "A4 Portrait")
  Tab = "Fiches_Parametres"
  Try Utils.db.Exec("ALTER TABLE " & Tab & " ADD (version Char(5))")
  Try Utils.db.Exec("update " & Tab & " set version = &1 ", "3.60")
  If Not Error Then bmaj = True
  Try Utils.db.Exec("ALTER TABLE " & Tab & " ADD PRIMARY KEY (ind)")

  Tab = "Fiches_EntTicketz"
  Try Utils.db.Exec("ALTER TABLE " & Tab & " ADD (suppr TINYINT(1))")
  Try Utils.db.Exec("update " & Tab & " set suppr = &1", False)
  Tab = "Fiches_HisEntTickets"
  Try Utils.db.Exec("ALTER TABLE " & Tab & " ADD (suppr TINYINT(1))")
  Try Utils.db.Exec("update " & Tab & " set suppr = &1", False)

  If Not Error Then bmaj = True

End

Public Sub Maj361()

  Tab = "Fiches_MvtM"
  Try Utils.db.Exec("ALTER TABLE " & Tab & " ADD (datem Date)")
  Try Utils.db.Exec("ALTER TABLE " & Tab & " ADD (supprimee TINYINT(1))")

  Tab = "Fiches_Parametres"
  Try Utils.db.Exec("ALTER TABLE " & Tab & " modify dteclec date")
  Try Utils.db.Exec("ALTER TABLE " & Tab & " modify dteclec1 date")
  Try Utils.db.Exec("ALTER TABLE " & Tab & " modify dteclec2 date")
  Try Utils.db.Exec("ALTER TABLE " & Tab & " modify dteclec3 date")
  Try Utils.db.Exec("ALTER TABLE " & Tab & " modify dteclec4 date")
  Try Utils.db.Exec("ALTER TABLE " & Tab & " modify dteclec5 date")
  Try Utils.db.Exec("ALTER TABLE " & Tab & " modify dtepc date")
  Try Utils.db.Exec("ALTER TABLE " & Tab & " modify dtetdec date")
  Try Utils.db.Exec("ALTER TABLE " & Tab & " modify dtefedec date")

  Tab = "Fiches_Cli"
  Try Utils.db.Exec("ALTER TABLE " & Tab & " modify cli_pays CHAR(40)")

  Tab = "Fiches_Four"
  Try Utils.db.Exec("ALTER TABLE " & Tab & " modify fo_pays CHAR(40)")

  If Not Error Then bmaj = True

End

Public Sub Maj362()

  Try Utils.db.Exec("ALTER TABLE Fiches_Bl ADD (email VARCHAR(150))")
  Try Utils.db.Exec("ALTER TABLE Fiches_BlM ADD (email VARCHAR(150))")

  If Not Error Then bmaj = True

End

Public Sub Maj363()

  Tab = "Fiches_EntTicketz"
  Try Utils.db.Exec("ALTER TABLE " & Tab & " ADD (control VARCHAR(40))")

  'Mise à jour des caisse
  Tab1 = "Fiches_Caisses"
  rResult = Utils.db.Exec("SELECT * FROM " & Tab1 & " ")
  If rResult.Available Then
    Repeat
      Tab = "Fiches_EntTickets" & rResult!code
      Try Utils.db.Exec("ALTER TABLE " & Tab & " ADD (control VARCHAR(40))")
    Until rResult.MoveNext()
  Endif

  Tab = "Fiches_HisEntTickets"
  Try Utils.db.Exec("ALTER TABLE " & Tab & " ADD (control VARCHAR(40))")

  Tab = "Fiches_Parametres"
  Try Utils.db.Exec("ALTER TABLE " & Tab & " ADD jrnal5 Char(2)")

  If Not Error Then bmaj = True

End

Public Sub Maj364()

  Dim $hform As Form
  Dim hLabel As Label

  $hForm = New Form As "Form"
  $hform.Width = 600
  $hform.Height = 400
  $hForm.Border = Border.Etched
  $hform.Title = "Passage version 3.64"
  hLabel = New Label($hForm)
  hLabel.Background = &EBEBEB&
  hLabel.Width = 600
  hLabel.Alignment = 3
  hLabel.Height = $hform.Height / 2
  hLabel.Text = "Passage à la version 3.64. \nCette opération prend un peu de temps.\n\n Veuillez patienter SVP."
  $hForm.Move($hForm.ScreenX, $hForm.ScreenY, 600, 200)
  $hform.Center
  $hform.show
  Wait 1
  $hform.Mouse = Mouse.wait
  Tab = "Fiches_Caisses"
  Try Utils.db.Exec("ALTER TABLE " & Tab & " ADD (fndtotp decimal(15,2))")
  Try Utils.db.Exec("ALTER TABLE " & Tab & " ADD (fndtotg decimal(15,2))")
  rResult = Utils.db.Exec("SELECT * FROM  Fiches_Caisses")
  If rResult.Available Then
    Repeat
      Try Utils.db.Exec("UPdate Fiches_Caisses  SET fndtotp = &1, fndtotg = &2 WHERE code = &3", 0, 0, rResult!code)
    Until rResult.movenext()
  Endif
  If Not Error Then bmaj = True
  'On recalcule chaque clé afin qu'elle prenne la clé précédente
  Sha1Calc.CalcSha1_all("Fiches_Mvt")
  $hform.Mouse = Mouse.default
  $hform.Delete
  Tab = "Fiches_Materiels"
  Try Utils.db.Exec("ALTER TABLE " & Tab & " ADD (mat_vendu Integer(1))")

End

Public Sub Maj365()

  Tab = "Fiches_ComMail"
  Try Utils.db.EXEC("CREATE TABLE " & Tab &
    " (numcom char(2) NOT NULL," &
    "intitule text ," &
    "PRIMARY KEY (numcom))" & Utils.db.Engine())

  If Not Error Then bmaj = True

End

Public Sub Maj366()

  Tab = "Fiches_AdrlivBL"
  Try Utils.db.EXEC("CREATE TABLE " & Tab &
    " (numbl Char(6) NOT NULL," &
    "nom VARCHAR(90)," &
    "adr1 VARCHAR(35)," &
    "adr2 VARCHAR(35)," &
    "cp CHAR(5)," &
    "ville VARCHAR(35)," &
    "PRIMARY KEY (numbl))" & Utils.db.Engine())

  Tab = "Fiches_MvtM"
  Try Utils.db.Exec("ALTER TABLE " & Tab & " ADD (datem date)")
  Try Utils.db.Exec("ALTER TABLE " & Tab & " ADD (lind2 INT)")

  If Not Error Then bmaj = True

End

Public Sub Maj367()

  Tab = "Fiches_Ligbl"
  Try Utils.db.Exec("ALTER TABLE " & Tab & " ADD (refl_ligbl VarChar(40))")
  Tab = "Fiches_LigblM"
  Try Utils.db.Exec("ALTER TABLE " & Tab & " ADD (refl_ligbl VarChar(40))")

  If Not Error Then bmaj = True

End

Public Sub Maj368()

  Dim $ipr As New Integer[]
  Dim txt As String

  Start.LocalSettings.Save
  If Exist(User.Home & "/.config/gambas3/Laurux3.conf")
    If Not Exist(User.Home & "/.config/gambas3/" & Application.Name & ".conf")
      Copy User.Home & "/.config/gambas3/Laurux3.conf" To User.Home & "/.config/gambas3/" & Application.Name & ".conf"
    Else
      If Exist(User.Home & "/.config/gambas3/" & Application.Name & ".conf.bak") Then Kill User.Home & "/.config/gambas3/" & Application.Name & ".conf.bak"
      Copy User.Home & "/.config/gambas3/" & Application.Name & ".conf" To User.Home & "/.config/gambas3/" & Application.Name & ".conf.bak"
      Kill User.Home & "/.config/gambas3/" & Application.Name & ".conf"
      Copy User.Home & "/.config/gambas3/Laurux3.conf" To User.Home & "/.config/gambas3/" & Application.Name & ".conf"
      Message.Warning("Warning Maj368 a déplacé le fichier de conf actuel source:\n" & User.Home & "/.config/gambas3/" & Application.Name & ".conf\nvers destination:\n" & User.Home & "/.config/gambas3/" & Application.Name & ".conf.bak!\nLe fichier de conf de la version précédente a été recopié au nouvel emplacement\nVeuillez verifier son contenu!\n source: " & User.Home & "/.config/gambas3/Laurux3.conf\n destination: " & User.Home & "/.config/gambas3/" & Application.Name & ".conf")
    Endif
  Endif
  Start.LocalSettings.Reload

  Tab = "Fiches_Docactif"
  Try Utils.db.EXEC("Drop TABLE " & Tab & "")
  Try Utils.db.EXEC("CREATE TABLE " & Tab &
    "(doc_type CHAR(12), " &
    "doc_num CHAR(8), " &
    "user_name VARCHAR(50), " &
    "process_id INTEGER, " &
    "machine_id VARCHAR(50), " &
    "host_id VARCHAR(50), " &
    "userdb_name VARCHAR(50), " &
    "PRIMARY KEY (doc_type, doc_num))")

  Tab = "Fiches_EntTicketz"
  Try Utils.db.Exec("ALTER TABLE " & Tab & " ADD (prev_numero Char(7))")

  Tab = "Fiches_Parametres"
  Try Utils.db.Exec("ALTER TABLE " & Tab & " ADD (version_pos Char(5))")
  Try Utils.db.Exec("ALTER TABLE " & Tab & " ADD (conf BLOB)")

  Tab = "Fiches_Parametres"
  Try Utils.db.Exec("ALTER TABLE " & Tab & " ADD (version_pos Char(5))")

  Tab = "Fiches_Mvt"
  Try Utils.db.Exec("ALTER TABLE " & Tab & " modify numdoc CHAR(10)")
  Try Utils.db.Exec("ALTER TABLE " & Tab & " modify numlot CHAR(10)")
  Try Utils.db.Exec("ALTER TABLE " & Tab & " modify numero Integer(11) NOT NULL")
  Try Utils.db.Exec("ALTER TABLE " & Tab & " modify numerodef Integer(11)")
  Try Utils.db.Exec("ALTER TABLE " & Tab & " modify intitule VarChar(40)")

  Tab = "Fiches_MvtM"
  Try Utils.db.Exec("ALTER TABLE " & Tab & " modify numdoc CHAR(10)")
  Try Utils.db.Exec("ALTER TABLE " & Tab & " modify numlot CHAR(10)")
  Try Utils.db.Exec("ALTER TABLE " & Tab & " modify numero Integer(11) NOT NULL")
  Try Utils.db.Exec("ALTER TABLE " & Tab & " modify numerodef Integer(11)")
  Try Utils.db.Exec("ALTER TABLE " & Tab & " modify intitule VarChar(40)")
  'Modifications necessaire aux familles
  Try Utils.db.Exec("ALTER TABLE Fiches_Fam MODIFY code_fam char(20)")
  Try Utils.db.Exec("ALTER TABLE Fiches_Art MODIFY art_fam char(20)")
  Try Utils.db.Exec("ALTER TABLE Fiches_RemTypec MODIFY codef char(20)")
  Try Utils.db.Exec("ALTER TABLE Fiches_RemCliFam MODIFY codef char(20)")
  Try Utils.db.Exec("ALTER TABLE Fiches_CoeffTypec MODIFY codef char(20)")
  Try Utils.db.Exec("ALTER TABLE Fiches_Ligbl MODIFY fam_ligbl char(20)")
  Try Utils.db.Exec("ALTER TABLE Fiches_HistoLigfac MODIFY fam_ligfac char(20)")
  Try Utils.db.Exec("ALTER TABLE Fiches_FamDep MODIFY fam char(20)")
  Try Utils.db.Exec("ALTER TABLE Fiches_LigblM MODIFY fam_ligbl char(20)")
  Try Utils.db.Exec("ALTER TABLE Fiches_HistoLigfacM MODIFY fam_ligfac char(20)")
  Try Utils.db.Exec("ALTER TABLE Fiches_Materiels MODIFY mat_fam char(20)")
  Try Utils.db.Exec("ALTER TABLE Fiches_Mo MODIFY mo_fam char(20)")
  Try Utils.db.Exec("ALTER TABLE Fiches_HisLigTickets MODIFY fam char(20)")
  Try Utils.db.Exec("ALTER TABLE Fiches_LigTicketz MODIFY fam char(20)")
  Try Utils.db.Exec("ALTER TABLE Fiches_ImpArtDef MODIFY cfam char(20)")
  'initialise la longueure des familles et les s/totaux si ça n'a pas déjà été fait
  Try txt = Start.LocalSettings["/Soc" & Start.Societe & "/nbfam"]
  If txt = Null Then
    Try Start.LocalSettings["/Soc" & Start.Societe & "/nbfam"] = "5"
    Try $ipr.Add(5)
    Try Start.LocalSettings["/Soc" & Start.Societe & "/ipr"] = $ipr
    'mise des options à faux
    Try Start.LocalSettings["/Soc" & Start.Societe & "/pp"] = False
    Try Start.LocalSettings["/Soc" & Start.Societe & "/bois"] = False
    Start.LocalSettings.Save
  Endif
  'ajout fiche client
  Try Utils.db.Exec("ALTER TABLE Fiches_Cli ADD (cli_tour char(15))")
  Try Utils.db.Exec("ALTER TABLE Fiches_Cli ADD cli_gestion decimal(5,2) DEFAULT 0.00")
  Try Utils.db.Exec("ALTER TABLE Fiches_Cli ADD cli_regr char(1) DEFAULT 'S'")
  Try Utils.db.Exec("ALTER TABLE Fiches_Cli ADD cli_siret char(14)")

  'ajout fiche adresse de livraison
  Try Utils.db.Exec("ALTER TABLE Fiches_AdrlivC ADD (tourne char(15))")
  'fichier des bl
  Try Utils.db.Exec("ALTER TABLE Fiches_Ligbl ADD tour_ligbl char(15)")
  Try Utils.db.Exec("ALTER TABLE Fiches_Bl ADD gestbl decimal(5,2) DEFAULT 0.00")
  Try Utils.db.Exec("ALTER TABLE Fiches_LigblM ADD tour_ligbl char(15)")
  Try Utils.db.Exec("ALTER TABLE Fiches_BlM ADD gestbl decimal(5,2) DEFAULT 0.00")
  'ficher des factures
  Try Utils.db.Exec("ALTER TABLE Fiches_HistoLigfac ADD tour_ligfac char(15)")
  Try Utils.db.Exec("ALTER TABLE Fiches_HistoLigfacM ADD tour_ligfac char(15)")
  Try Utils.db.Exec("ALTER TABLE Fiches_HistoFac ADD gestfac decimal(5,2) DEFAULT 0.00")
  Try Utils.db.Exec("ALTER TABLE Fiches_HistoFacM ADD gestfac decimal(5,2) DEFAULT 0.00")
  'ajout fichier parametre
  Try Utils.db.Exec("ALTER TABLE Fiches_Parametres ADD frais decimal(6,2)")
  Try Utils.db.Exec("ALTER TABLE Fiches_Parametres ADD cptfrais char(8)")
  Try Utils.db.Exec("ALTER TABLE Fiches_Parametres ADD tvafrais char(2)")
  'fichier des tournées
  Try Utils.db.Exec("CREATE TABLE Fiches_tourne " &
    "(code char(15) ," &
    "tourne char(50) ," &
    "PRIMARY KEY (code))")
  'Mise à jour des caisses
  Tab1 = "Fiches_Caisses"
  rResult = Utils.db.Exec("SELECT * FROM " & Tab1 & " ")
  If rResult.Available Then
    Repeat
      Tab = "Fiches_EntTickets" & rResult!code
      Try Utils.db.Exec("ALTER TABLE " & Tab & " ADD (prev_numero Char(7))")
    Until rResult.MoveNext()
  Endif
  'Mise à jour des caisses
  Tab = "Fiches_Touches"
  Try Utils.db.Exec("ALTER TABLE " & Tab & " modify touche Char(6)")

  Tab1 = "Fiches_Caisses"
  rResult = Utils.db.Exec("SELECT * FROM " & Tab1 & " ")
  If rResult.Available Then
    Repeat
      Tab = "Fiches_EntTickets" & rResult!code
      Try Utils.db.Exec("ALTER TABLE " & Tab & " ADD (prev_numero Char(7))")
    Until rResult.MoveNext()
  Endif

  If Not Error Then bmaj = True

End

Public Sub Maj369()

  Dim PB As ProgBar
  
  'Changemement Date format en ticket (le moulinage est effectué avant MAJ)
  Tab1 = "Fiches_Caisses"
  rResult = Utils.db.Exec("SELECT * FROM " & Tab1 & " ")
  If rResult.Available Then
    Repeat
      Tab = "Fiches_EntTickets" & rResult!code
      Try Utils.db.Exec("ALTER TABLE " & Tab & " change date date datetime")  
      tab = "Fiches_LigTickets" & rResult!code
      Try Utils.db.Exec("ALTER TABLE " & tab & " MODIFY fam Char(20)")
      tab = "Fiches_Ticketx" & rResult!code
      Try Utils.db.Exec("ALTER TABLE " & tab & " MODIFY fam char(20)")
      tab = "Fiches_Ticketz" & rResult!code
      Try Utils.db.Exec("ALTER TABLE " & tab & " MODIFY fam char(20)")
    Until rResult.MoveNext()
  Endif
  Tab = "Fiches_EntTicketz"
  Try Utils.db.Exec("ALTER TABLE " & Tab & " change date date datetime")

  
  'Fichier facture rajout date de saisie et n° bl
  PB = New ProgBar("Conversion des dates facture", 4)
  PB.Show()
  PB.Avancement("Table Factures", 1)
  Try Utils.db.Exec("ALTER TABLE Fiches_HistoLigfac change dtligbl_ligfac dtligbl_ligfac datetime")
  Try Utils.db.Exec("ALTER TABLE Fiches_HistoLigfac ADD dtligbl_ligfac datetime")
  Try Utils.db.Exec("ALTER TABLE Fiches_HistoLigfac ADD numbl_ligfac char(6)")
  PB.Avancement("Table Factures Matériels", 1)
  Try Utils.db.Exec("ALTER TABLE Fiches_HistoLigfacM change dtligbl_ligfac dtligbl_ligfac datetime")
  Try Utils.db.Exec("ALTER TABLE Fiches_HistoLigfacM ADD dtligbl_ligfac datetime")
  Try Utils.db.Exec("ALTER TABLE Fiches_HistoLigfacM ADD numbl_ligfac char(6)")
  PB.Avancement("Lignes Factures", 1)
  Utils.db.Exec("UPDATE Fiches_HistoLigfac,Fiches_HistoFac SET dtligbl_ligfac=datefac WHERE numfac=num_ligfac AND dtligbl_ligfac IS NULL")
  PB.Avancement("Lignes Factures Materiels", 1)
  Utils.db.Exec("UPDATE Fiches_HistoLigfacM,Fiches_HistoFacM SET dtligbl_ligfac=datefac WHERE numfac=num_ligfac AND dtligbl_ligfac IS NULL")
  PB.Close()
  'Fichier BL rajout date de sasie
  PB = New ProgBar("Conversion des dates BL", 4)
  PB.Show()
  PB.Avancement("Table BL", 1)
  Try Utils.db.Exec("ALTER TABLE Fiches_Ligbl ADD dte_ligbl datetime")
  PB.Avancement("Table BL Matériels", 1)
  Try Utils.db.Exec("ALTER TABLE Fiches_LigblM ADD dte_ligbl datetime")
  PB.Avancement("Ligned BL", 1)
  Utils.db.Exec("UPDATE Fiches_Ligbl,Fiches_Bl SET dte_ligbl=datebl WHERE numbl=num_ligbl AND dte_ligbl IS NULL")
  PB.Avancement("Ligned BL Matériels", 1)
  Utils.db.Exec("UPDATE Fiches_LigblM,Fiches_BlM SET dte_ligbl=datebl WHERE numbl=num_ligbl AND dte_ligbl IS NULL")
  PB.Close()
  'maj des options
  If Start.LocalSettings["/Soc" & Start.Societe & "/pp"] = True Then
    Try Utils.db.Exec("ALTER TABLE Fiches_LigblM ADD tipp_ligbl char(2)")
    Try Utils.db.Exec("ALTER TABLE Fiches_HistoLigfacM ADD tipp_ligfac char(2)")
    Try Utils.db.Exec("ALTER TABLE Fiches_Societes ADD tipp char(2)")
  Endif
  If Start.LocalSettings["/Soc" & Start.Societe & "/bois"] = True Then
    Try Utils.db.Exec("ALTER TABLE Fiches_Societes ADD ident varchar(20)")
    Try Utils.db.Exec("ALTER TABLE Fiches_Societes ADD caution vatchar(25)")
    Try Utils.db.Exec("ALTER TABLE Fiches_Parametres ADD arrete char(7)")
    Try Utils.db.Exec("ALTER TABLE Fiches_ligregie ADD volumess decimal(7,2)")
  Endif

  'Changemement Date format en histo ticket
  Tab = "Fiches_HisEntTickets"
  Try Utils.db.Exec("ALTER TABLE " & Tab & " ADD (date2 datetime)")
  rResult = Utils.db.Exec("SELECT * FROM " & Tab & " order by numero")
  PB = New ProgBar("Conversion des dates des tickets caisse archivés", rResult.Count)
  PB.Show()
  If rResult.Available Then
    Repeat
      PB.Avancement("Tickets " & rResult!numero, 300)
      If TypeOf(rResult!date) = gb.String
        'Utilisation de la classe LDate pour les conversions de date
        Utils.db.Exec("UPdate   " & Tab & " SET date2 = &1 WHERE lInd = &2", LDate(rResult!date).DT, rResult!lInd)
      Endif
    Until rResult.MoveNext()
    PB.Close()
    Try Utils.db.Exec("ALTER TABLE " & Tab & " drop date")
    Try Utils.db.Exec("ALTER TABLE " & Tab & " change date2 date datetime")
  Endif
  
  'contrib asirbu2002
  Tab = "Fiches_Ligabon"
  Try Utils.db.Exec("ALTER TABLE " & Tab & " ADD (libelle VarChar(50))")
  Try Utils.db.Exec("ALTER TABLE " & Tab & " ADD (numDoc Char(10))")
  Try Utils.db.Exec("ALTER TABLE " & Tab & " ADD (numLot Char(10))")
  
  Sha1Calc.CalcSha1_all("Fiches_Mvt")
  'Sha1Calc.CalcSha1_all("Fiches_Mvt1") 'A REMETTRE AVANT COMMIT : DO NOT PUSH
  
  If Not Error Then bmaj = True
  
End
