' Gambas module file

Private hlb As Label
Private hpb As ProgressBar

Public Sub Verif_Maj()
  
  Dim version As String
  Dim txt As String
  Dim $hform As Form
  Dim hLabel As Label
  
  $hForm = New Form As "Form"
  $hform.Width = 600
  $hform.Height = 400
  $hForm.Border = Border.Etched
  $hform.Title = "Mise à jour de Laurux"
  hLabel = New Label($hForm)
  hLabel.Text = "La mise à jour prend un peu de temps.\n Veuillez patienter SVP."
  hLabel.Width = 600
  hLabel.Alignment = Align.center
  hLabel.Height = 40
  hLabel.Y = 12
  'hLabel.Border = Border.Plain
  hlb = New Label($hForm)
  hlb.Width = 600
  hlb.Height = 20
  hlb.Y = 70
  hlb.Alignment = Align.center
  hpb = New ProgressBar($hForm)
  hpb.Width = 400
  hpb.Height = 20
  hpb.X = 100
  hpb.Y = 100
  $hForm.Move($hForm.ScreenX, $hForm.ScreenY, 600, 200)
  $hform.Center
  Version = Settings["/dbase/Version"]
  If Not Exist(User.home & "/tmp") Then Mkdir User.home & "/tmp"
  If Exist(User.Home & "/tmp/pb1.txt") Then Kill User.Home & "/tmp/pb1.txt"
  If Exist(User.Home & "/tmp/ping.txt") Then Kill User.Home & "/tmp/ping.txt"
  If Exist(User.Home & "/version.txt") Then Kill User.Home & "/version.txt"
  If Exist(User.Home & "/Laurux3.tar.gz") Then Kill User.Home & "/Laurux3.tar.gz"
  Shell "ping -c 1 www.laurux.fr >" & User.home & "/tmp/ping.txt 2>&1" Wait
  If Exist(User.Home & "/tmp/ping.txt") Then
    txt = Trim$(File.Load(User.Home & "/tmp/ping.txt"))
  Endif  
  If InStr(txt, "cpanel1") <> 0 Then
    Shell "wget -q" & " " & "http://www.laurux.fr/file/version.txt" & " -P " & User.Home Wait
    If Exist(User.Home & "/version.txt") Then
      txt = Trim$(File.Load(User.Home & "/version.txt"))
      If IsNull(Version) And Not IsNull(txt) Or If Not IsNull(Right$(version, 4)) And Not IsNull(txt) Then
        If Replace$(Right$(txt, 4), ",", ".") >= Replace$(Right$(version, 4), ",", ".") Then
          If Message.Question("Attention ! Vous allez mettre à jour votre logiciel Laurux\n Vous devez être connecté au réseau internet. \n Etes-vous d'accord ?", "Oui", "Non") = "1" Then
            Try Move Application.Path & "/Laurux3.gambas" To Application.Path & "/Laurux3.old.gambas"
            Shell "cd " & User.Home
            $hForm.Show
            Wait 1
            $hform.Mouse = Mouse.Wait
            Shell "wget http://www.laurux.fr/file/Laurux3.tar.gz -P " & User.Home & " -o ~/tmp/pb1.txt"
            Avancement()
            Shell "cd " & User.Home & " " & "; tar xvfz " & User.Home & "/Laurux3.tar.gz" Wait
            Wait 2
            Kill User.Home & "/Laurux3.tar.gz"
            Kill User.Home & "/version.txt"
            $hform.Mouse = Mouse.Default
            $hform.Close
            Settings["/Affmaj"] = 1
            Settings["/dbase/Version"] = Txt
            Settings.Save
            Message.Warning("Mise à jour terminée ! Veuillez relancer Laurux3 SVP !")
            Quit
          Endif
        Else
          Message.Warning("Aucune mise à jour n'est a faire !")
        Endif
      Endif
    Else
      $hform.Mouse = Mouse.Default
      Message.Warning("Problème de mise à jour! Veuillez vérifier votre connexion SVP.")
    Endif
  Else
    $hform.Mouse = Mouse.Default
    Message.Warning("Problème de mise à jour! Veuillez vérifier votre connexion SVP.")
  Endif
Catch
  Music.Load(Start.Musique)
  Music.Play
  message.Error(Error.Text & " " & Error.where)
  
End

Public Sub Avancement()
  
  Dim hFile As File
  Dim chaine As String
  Dim v As Integer
  Dim numligne As Integer
  Dim L3 As String = "0"
  
  numligne = 0
  v = 0
  Do While Not Exist(User.home & "/tmp/pb1.txt")  'On test l'existence du fichier temporaire
  Loop
  Wait 0.1
  Do While L3 <> "100"      'On test la fin du téléchargement
    hFile = Open User.home & "/tmp/pb1.txt" For Input
    numligne = 0
    While Not Eof(hFile)
      Line Input #hFile, chaine
      If v = 100 Then L3 = "100"
      If Mid(chaine, 7, 2) = "K " And Len(chaine) <= 78 And Len(chaine) >= 75 Then
        L3 = Mid(chaine, 63, 3)
        If CInt(L3) > v Then  'On incrémente la barre de progression
          v = CInt(L3)
          Hpb.Value = CInt(L3) / 100
          hlb.Text = Chaine
        Endif
      Else
        Wait
      Endif
    Wend
    Close #hFile
  Loop
  'CLOSE #hFile
  Try Kill User.Home & "/tmp/pb1.txt"  '--- Suppression du fichier temporaire ---
  
End
