' Gambas module file

Private Cotable[7] As String

Public Sub Colco_Data(Colco As Gridview, Row As Integer, Column As Integer)
  
  Dim CoulB As Integer
  Dim CoulF As Integer
  Dim Fnt As String
  
  With Utils
    CoTable[0] = "compte_cc"
    CoTable[1] = "intitule_cc"
    CoTable[2] = "type_cc"
    CoTable[3] = "solde"
    CoTable[4] = "coll_cc"
    .rs3.MoveTo(Row)
    Try Colco.data.Text = Str(.rs3[CoTable[Column]])
    If Not Error Then
      If Settings["/Soc" & Start.Societe & "/Coul_fen"] Then
        CoulB = Val("&HFAFAFA&")
      Else
        CoulB = Val("&HF9F9BD&")
      Endif
      CoulF = Val("&H000000&")
      Fnt = "serif 10"
    Endif
    If column = 2 Then Colco.Data.Alignment = 3
    If column = 3 Then
      Colco.data.Text = Format$(Val(.cpoint(Colco.data.Text)), "0.00")
      Colco.Data.Alignment = 2
    Endif
    Colco.Data.Background = CoulB
    Colco.Data.Foreground = CoulF
    'Colco.Data.Font = Font[Fnt]
    
  End With
  
End

Public Sub Tris(Colco As Gridview, CO As TextBox, Intit As Textbox, Ty As Textbox, Sol As Textbox, Co2 As Textbox)
  
  With Colco
    .Columns.count = 5
    .Columns[0].Width = CO.Width
    .Columns[1].Width = Intit.Width
    Try .Columns[2].Width = Ty.Width
    Try .Columns[3].Width = Sol.Width
    Try .Columns[4].Width = Co2.Width
  End With
  
End

Public Sub Deb2(Colco As Gridview, Tab As String, Tri As String, Sel As String)
  
  Utils.Base3(Colco, "select * from " & Tab & " where " & Tri & " like  \"" & sel & "%\" order by " & Tri & "")
  Colco.Refresh
  
End

Public Sub Deb3(Colco As Gridview, Tab As String, Tri As String, Sel As String)
  
  Utils.Base3(Colco, "select * from " & Tab & " where " & Tri & " like  \"" & sel & "%\" order by " & Tri & " Desc")
  Colco.Refresh
  
End

Public Sub Deb4(Colco As Gridview, Tab As String, Tri As String, Sel As String, Type As String, NbEnreg As Integer, Nb As Integer)
  
  If Type <> "B" Then
    Utils.Base3(Colco, "SELECT * FROM " & Tab & " WHERE " & Tri & " like  \"" & sel & "%\" and type_cc like  \"" & Type & "%\"  and coll <> " & 1 & " order by " & Tri & "  limit " & NbEnreg & ", " & nb & "")
  Else
    Utils.Base3(Colco, "SELECT * FROM " & Tab & " WHERE " & Tri & " like  \"" & sel & "%\" and type_cc like  \"" & Type & "%\"  order by " & Tri & " limit " & NbEnreg & ", " & nb & "")
  Endif
  Colco.Refresh
  
End

Public Sub Deb5(Colco As Gridview, Tab As String, Tri As String, Sel As String, Type As String, NbEnreg As Integer, Nb As Integer)
  
  If Type <> "B" Then
    Utils.Base3(Colco, "SELECT * FROM " & Tab & " WHERE " & Tri & " like  \"" & sel & "%\" and type_cc like  \"" & Type & "%\" and coll <> " & 1 & " order by " & Tri & " Desc limit " & NbEnreg & ", " & nb & "")
  Else
    Utils.Base3(Colco, "SELECT * FROM " & Tab & " WHERE " & Tri & " like  \"" & sel & "%\" and type_cc like  \"" & Type & "%\" order by " & Tri & " Desc limit " & NbEnreg & ", " & nb & "")
  Endif
  Colco.Refresh
  
End

Public Sub Deb6(Colco As Gridview, Tab As String, Tri As String, Sel As String, Type As String, Type2 As String)
  
  If Type <> "B" Then
    Utils.Base3(Colco, "SELECT * FROM " & Tab & " WHERE " & Tri & " like  \"" & sel & "%\" and type_cc like  \"" & Type & "%\" and coll <> " & 1 & " or " & Tri & " like  \"" & sel & "%\" and type_cc like  \"" & Type2 & "%\" and coll <> " & 1 & " order by " & Tri & "")
  Else
    Utils.Base3(Colco, "SELECT * FROM " & Tab & " WHERE " & Tri & " like  \"" & sel & "%\" and type_cc like  \"" & Type & "%\" and coll <> " & 1 & " or " & Tri & " like  \"" & sel & "%\" and type_cc like  \"" & Type2 & "%\" order by " & Tri & "")
  Endif
  Colco.Refresh
  
End

Public Sub Deb7(Colco As Gridview, Tab As String, Tri As String, Sel As String, Type As String, Type2 As String)
  
  If Type <> "B" Then
    Utils.Base3(Colco, "SELECT * FROM " & Tab & " WHERE " & Tri & " like  \"" & sel & "%\" and type_cc like  \"" & Type & "%\" and coll <> " & 1 & " or " & Tri & " like  \"" & sel & "%\" and type_cc like  \"" & Type2 & "%\" and coll <> " & 1 & " order by " & Tri & " Desc")
  Else
    Utils.Base3(Colco, "SELECT * FROM " & Tab & " WHERE " & Tri & " like  \"" & sel & "%\" and type_cc like  \"" & Type & "%\" and coll <> " & 1 & " or " & Tri & " like  \"" & sel & "%\" and type_cc like  \"" & Type2 & "%\" order by " & Tri & " Desc")
  Endif
  Colco.Refresh
  
End

'Pour un journal de trésorerie on ne récupère pas les comptes banque

Public Sub Deb8(Colco As Gridview, Tab As String, Tri As String, Sel As String, Type As String, NbEnreg As Integer, Nb As Integer)
  
  If Type <> "B" Then
    Utils.Base3(Colco, "SELECT * FROM " & Tab & " WHERE " & Tri & " like  \"" & sel & "%\" and type_cc like  \"" & Type & "%\"  and coll <> " & 1 & " order by " & Tri & " limit " & NbEnreg & ", " & nb & "")
  Else
    Utils.Base3(Colco, "SELECT * FROM " & Tab & " WHERE " & Tri & " like  \"" & sel & "%\" and type_cc like  \"" & Type & "%\"  and comptr_cc = " & 0 & " order by " & Tri & " limit " & NbEnreg & ", " & nb & "")
  Endif
  Colco.Refresh
  
End

Public Sub Deb9(Colco As Gridview, Tab As String, Tri As String, Sel As String, Type As String, NbEnreg As Integer, Nb As Integer)
  
  If Type <> "B" Then
    Utils.Base3(Colco, "SELECT * FROM " & Tab & " WHERE " & Tri & " like  \"" & sel & "%\" and type_cc like  \"" & Type & "%\" and coll <> " & 1 & " order by " & Tri & " Desc limit " & NbEnreg & ", " & nb & "")
  Else
    Utils.Base3(Colco, "SELECT * FROM " & Tab & " WHERE " & Tri & " like  \"" & sel & "%\" and type_cc like  \"" & Type & "%\" and comptr_cc = " & 0 & " order by " & Tri & " Desc limit " & NbEnreg & ", " & nb & "")
  Endif
  Colco.Refresh
  
End
