' Gambas module file

Private Cotable[8] As String

Public Sub Ecrit_Data(Ecrit As Gridview, Row As Integer, Column As Integer)
  
  With Utils
    CoTable[0] = "jour"
    CoTable[1] = "compte"
    CoTable[2] = "dte"
    CoTable[3] = "numero"
    CoTable[4] = "numdoc"
    CoTable[5] = "montantd"
    CoTable[6] = "montantc"
    CoTable[7] = "libelle"
    Try .rs1.MoveTo(Row)
    Ecrit.data.Text = Str(.rs1[CoTable[Column]])
    If column = 2 Then
      Ecrit.data.Text = Replace$(Ecrit.data.Text, "/", ".")
      Ecrit.data.Text = Left$(Ecrit.data.Text, 6) & Mid$(Ecrit.data.Text, 7, 4)
    Endif
    If column = 3 Then
      Ecrit.Data.Alignment = 2
    Endif
    If column = 5 Or If column = 6 Then
      Try Ecrit.data.Text = Format$(Val(Ecrit.data.Text), "0.00")
      Ecrit.Data.Alignment = 2
    Endif
  End With
  
End

Public Sub Tris2(Ecrit As Gridview, JO As TextBox, COM As TextBox, DA2 As Textbox, NUMERO As Textbox, DOC2 As Textbox, DEB As Textbox, CRED As Textbox, INTITULE As Textbox)
  
  With Ecrit
    .Columns.count = 8
    .Columns[0].Width = JO.Width
    .Columns[1].Width = COM.Width
    .Columns[2].Width = DA2.Width
    .Columns[3].Width = NUMERO.Width
    .Columns[4].Width = DOC2.Width
    .Columns[5].Width = DEB.Width
    .Columns[6].Width = CRED.Width
    .Columns[7].Width = INTITULE.Width
  End With
  
End

Public Sub Debe1(ecrit As Gridview, Tab As String, Tri As String, Sel As String)
  
  Utils.Base(ecrit, "select * from " & Tab & " WHERE provisoire = " & "1" & " and tresorerie =  " & 1 & "   and cloturee = " & 0 & " and collectif is null and " & Tri & " like  \"%" & sel & "%\" order by " & Tri & "")
  ecrit.Refresh
  
End

Public Sub Debe2(ecrit As Gridview, Tab As String, Tri As String, Sel As String)
  
  Utils.Base(ecrit, "select * from " & Tab & " WHERE provisoire = " & "1" & " and tresorerie =  " & 1 & "  and cloturee = " & 0 & " order by " & Tri & " DESC")
  ecrit.Refresh
  
End

Public Sub Debe3(ecrit As Gridview, Tab As String, Tri As String, Sel As String)
  
  Utils.Base(ecrit, "select * from " & Tab & " WHERE validee = " & "1" & " and tresorerie =  " & 1 & " and cloturee = " & 0 & " and collectif is null and " & Tri & " like  \"%" & sel & "%\" order by " & Tri & "")
  ecrit.Refresh
  
End

Public Sub Debe4(ecrit As Gridview, Tab As String, Tri As String, Sel As String)
  
  Utils.Base(ecrit, "select * from " & Tab & " WHERE validee = " & "1" & " and tresorerie =  " & 1 & "  and cloturee = " & 0 & " order by " & Tri & " DESC")
  ecrit.Refresh
  
End

Public Sub Debn1(ecrit As Gridview, Tab As String, Tri As String, Sel As String)
  
  Utils.Base(ecrit, "select * from " & Tab & "  where validee = " & "0" & " and tresorerie =  " & 0 & "  and cloturee = " & 0 & " and " & Tri & " like  \"%" & sel & "%\" order by " & Tri & "")
  ecrit.Refresh
  
End

Public Sub Debn2(ecrit As Gridview, Tab As String, Tri As String, Sel As String)
  
  Utils.Base(ecrit, "select * from " & Tab & "  where validee = " & "0" & " and tresorerie =  " & 0 & "  and cloturee = " & 0 & " and " & Tri & " like  \"%" & sel & "%\" order by " & Tri & " DESC")
  ecrit.Refresh
  
End

Public Sub Debn3(ecrit As Gridview, Tab As String, Tri As String, Sel As String)
  
  Utils.Base(ecrit, "select * from " & Tab & " where validee = " & "1" & " and tresorerie =  " & 0 & "  and cloturee = " & 0 & " and " & Tri & " like  \"%" & sel & "%\" order by " & Tri & "")
  ecrit.Refresh
  
End

Public Sub Debn4(ecrit As Gridview, Tab As String, Tri As String, Sel As String)
  
  Utils.Base(ecrit, "select * from " & Tab & "  where validee = " & "1" & " and tresorerie =  " & 0 & "  and cloturee = " & 0 & " and " & Tri & " like  \"%" & sel & "%\" order by " & Tri & " DESC")
  ecrit.Refresh
  
End
