' Gambas module file

Private Cotable[7] As String

Public Sub Colco_Data(Colco As Gridview, Row As Integer, Column As Integer)
  
  Dim CoulB As Integer
  Dim CoulF As Integer
  Dim Fnt As String
  
  With Utils
    CoTable[0] = "numero"
    CoTable[1] = "intitule"
    .rs2.MoveTo(Row)
    Try Colco.data.Text = Str(.rs2[CoTable[Column]])
    If Not Error Then
      If Settings["/Soc" & Start.Societe & "/Coul_fen"] Then
        CoulB = Val("&HFAFAFA&")
      Else
        CoulB = Val("&HF9F9BD&")
      Endif
      CoulF = Val("&H000000&")
      Fnt = "serif 10"
    Endif
    Colco.Data.Background = CoulB
    Colco.Data.Foreground = CoulF
    Colco.Data.Font = Font[Fnt]
    
  End With
  
End

Public Sub Tris(Colco As Gridview, Num As TextBox, Intit As Textbox)
  
  With Colco
    .Columns.count = 2
    .Columns[0].Width = Num.Width
    .Columns[1].Width = Intit.Width
  End With
  
End

Public Sub Deb1(Colco As Gridview, Tab As String, Tri As String, Sel As String, typec As String, BT As Boolean)
  
  Dim sTresor As String = "0"
  
  If BT = False Then
    Utils.Base2(Colco, "select * from " & Tab & " where " & Tri & " like  \"" & sel & "%\" and type_cc like \"" & typec & "%\" order by " & Tri & "")
  Else
    Utils.Base2(Colco, "select * from " & Tab & " where " & Tri & " like  \"" & sel & "%\" and type_cc like \"" & typec & "%\" and comptr_cc like \"" & sTresor & "\" order by " & Tri & " ")
  Endif
  
End

Public Sub Deb2(Colco As Gridview, Tab As String, Tri As String, Sel As String, typec As String, BT As Boolean)
  
  Dim sTresor As String = "0"
  
  If BT = False Then
    Utils.Base2(Colco, "select * from " & Tab & " where " & Tri & " like  \"" & sel & "%\" and type_cc like \"" & typec & "%\" order by " & Tri & " Desc")
  Else
    Utils.Base2(Colco, "select * from " & Tab & " where " & Tri & " like  \"" & sel & "%\" and type_cc like \"" & typec & "%\" and comptr_cc like \"" & sTresor & "\" order by " & Tri & " Desc")
  Endif
  
End

Public Sub Deb3(Colco As Gridview, Tab As String, Tri As String, Sel As String, BT As Boolean)
  
  Utils.Base(Colco, "select * from " & Tab & " where " & Tri & " like  \"" & sel & "%\" order by " & Tri & "")
  
End
