' Gambas module file

Private hfile As File
Private Filename As String
Private Lig As String

Public Sub Pass(Origine As String, type As String, code As String) As String

  Dim rResult As Result
  Dim $Serveur As String

  If Origine = "Art" Then
    Filename = User.Home & "/Art_Serveur.txt"
    If Exist(filename) Then
      Try hFile = Open filename For Read Write
    Else
      Try hFile = Open filename For Write Create
    Endif
    While Not Eof(hFile)
      Line Input #hFile, Lig
    Wend
    rResult = Utils.db.Exec("SELECT * FROM Fiches_Art where art_code = &1", code)
    $Serveur = Type & ";" & code & ";" & rResult!art_design & ";" & rResult!art_design2 & ";" & rResult!art_four & ";" & rResult!art_fam & ";" & rResult!art_cequ & ";" & rResult!art_cbarre & ";" & rResult!art_cfour & ";" & rResult!art_nbd & ";" & rResult!art_dec & ";" & rResult!art_pbht & ";" & rResult!art_tr & ";" & rResult!art_remcas1 & ";" & rResult!art_remcas2 & ";" & rResult!art_remcas3 & ";" & rResult!art_pauaht & ";"
    $Serveur &= rResult!art_txconv & ";" & rResult!art_paht & ";" & rResult!art_frais & ";" & rResult!art_prvt & ";" & rResult!art_coef & ";" & rResult!art_pvht & ";" & rResult!art_poids & ";" & rResult!art_mincom & ";" & rResult!art_pvttc & ";" & rResult!art_pvcons & ";" & rResult!art_ect & ";" & rResult!art_ect2 & ";" & rResult!art_eco & ";" & rResult!art_eco2 & ";" & rResult!art_cn8 & ";" & rResult!art_mat & ";"
    $Serveur &= rResult!art_stocke & ";" & rResult!art_suspendu & ";" & rResult!art_qte & ";" & rResult!art_poids2 & ";" & rResult!art_vol & ";" & rResult!art_ua & ";" & rResult!art_uv & ";" & rResult!art_centrale & ";" & rResult!art_refcentrale & ";" & rResult!art_refliee & ";" & rResult!art_pmp & ";" & rResult!art_stkmin & ";" & rResult!art_stkmax & ";" & rResult!art_cpp & ";" & rResult!art_copp & ";" & rResult!art_etiq & ";" & rResult!art_impcar & ";" & rResult!art_casier
    $Serveur &= rResult!art_prdcomp & ";" & rResult!art_impdetail & ";" & rResult!art_depg & ";" & rResult!art_cnsg & ";" & rResult!art_marque & ";" & rResult!art_bonus & ";" & rResult!art_colvte & ";" & rResult!art_pvht2 & ";" & rResult!qte1 & ";" & rResult!qte2 & ";" & rResult!qte3 & ";" & rResult!qte4 & ";" & rResult!qte5 & ";"
    $Serveur &= rResult!qte6 & ";" & rResult!qte7 & ";" & rResult!qte8 & ";" & rResult!qte9 & ";" & rResult!qte10 & ";" & rResult!qte11 & ";" & rResult!qte12 & ";" & rResult!rem1 & ";" & rResult!rem2 & ";" & rResult!rem3 & ";" & rResult!rem4 & ";" & rResult!rem5 & ";" & rResult!rem6 & ";" & rResult!art_photo & ";" & rResult!art_crst
    Print #hFile, $Serveur
  Endif

  If Origine = "Fam" Then
    Filename = User.Home & "/Fam_Serveur.txt"
    If Exist(filename) Then
      Try hFile = Open filename For Read Write
    Else
      Try hFile = Open filename For Write Create
    Endif
    While Not Eof(hFile)
      Line Input #hFile, Lig
    Wend
    rResult = Utils.db.Exec("SELECT * FROM Fiches_Fam where code_fam = &1", code)
    $Serveur = Type & ";" & code & ";" & rResult!libell_fam & ";" & rResult!coef_fam & ";" & rResult!cdtva_fam & ";" & rResult!compt_fam & ";" & rResult!compt2_fam & ";" & rResult!compt3_fam & ";" & rResult!compt4_fam & ";" & rResult!compt5_fam & ";" & rResult!txtva_fam & ";" & rResult!cptrem_fam & ";"
    $Serveur &= rResult!ect_fam & ";" & rResult!rem_fam & ";" & rResult!qte1 & ";" & rResult!qte2 & ";" & rResult!qte3 & ";" & rResult!qte4 & ";" & rResult!qte5 & ";" & rResult!qte6 & ";" & rResult!qte7 & ";" & rResult!qte8 & ";" & rResult!qte9 & ";" & rResult!qte10 & ";"
    $Serveur &= rResult!qte11 & ";" & rResult!qte12 & ";" & rResult!rem1 & ";" & rResult!rem2 & ";" & rResult!rem3 & ";" & rResult!rem4 & ";" & rResult!rem5 & ";" & rResult!rem6
    Print #hFile, $Serveur
  Endif

  If Origine = "Stock" Then
    Filename = User.Home & "/Stock_Serveur.txt"
    If Exist(filename) Then
      Try hFile = Open filename For Read Write
    Else
      Try hFile = Open filename For Write Create
    Endif
    While Not Eof(hFile)
      Line Input #hFile, Lig
    Wend
    Print #hFile, code & ";"
  Endif
  Close #hFile

End

Public Function ReplaceFam(mtt As String) As String

  Dim i As Integer = 3

  mtt = LCase$(mtt)
  For i = 3 To 10
    If InStr("0123456789", Mid$(mtt, i, 1)) Then
      mtt = Left$(mtt, i - 1) & "0" & Mid$(mtt, i, 1) & Mid$(mtt, i + 1, Len(mtt))
      Inc i
    Endif
  Next
  If InStr(mtt, "a") Then mtt = Replace$(mtt, "a", "10")
  If InStr(mtt, "b") Then mtt = Replace$(mtt, "b", "11")
  If InStr(mtt, "c") Then mtt = Replace$(mtt, "c", "12")
  If InStr(mtt, "d") Then mtt = Replace$(mtt, "d", "13")
  If InStr(mtt, "e") Then mtt = Replace$(mtt, "e", "14")
  If InStr(mtt, "f") Then mtt = Replace$(mtt, "f", "15")
  If InStr(mtt, "g") Then mtt = Replace$(mtt, "g", "16")
  If InStr(mtt, "h") Then mtt = Replace$(mtt, "h", "17")
  If InStr(mtt, "i") Then mtt = Replace$(mtt, "i", "18")
  If InStr(mtt, "j") Then mtt = Replace$(mtt, "j", "19")
  If InStr(mtt, "k") Then mtt = Replace$(mtt, "k", "20")
  If InStr(mtt, "l") Then mtt = Replace$(mtt, "l", "21")
  If InStr(mtt, "m") Then mtt = Replace$(mtt, "m", "22")
  If InStr(mtt, "n") Then mtt = Replace$(mtt, "n", "23")
  If InStr(mtt, "o") Then mtt = Replace$(mtt, "o", "24")
  If InStr(mtt, "p") Then mtt = Replace$(mtt, "p", "25")
  If InStr(mtt, "q") Then mtt = Replace$(mtt, "q", "26")
  If InStr(mtt, "r") Then mtt = Replace$(mtt, "r", "27")
  If InStr(mtt, "s") Then mtt = Replace$(mtt, "s", "28")
  If InStr(mtt, "t") Then mtt = Replace$(mtt, "t", "29")
  If InStr(mtt, "u") Then mtt = Replace$(mtt, "u", "30")
  If InStr(mtt, "v") Then mtt = Replace$(mtt, "v", "31")
  If InStr(mtt, "w") Then mtt = Replace$(mtt, "w", "32")
  If InStr(mtt, "x") Then mtt = Replace$(mtt, "x", "33")
  If InStr(mtt, "y") Then mtt = Replace$(mtt, "y", "34")
  If InStr(mtt, "z") Then mtt = Replace$(mtt, "z", "35")
  Return mtt

End
