' Gambas module file

Private hfile As File
Private Filename As String
Private Lig As String

Public Sub Pass(Origine As String, type As String, code As String, code2 As String) As String

  Dim rResult As Result
  Dim $Serveur As String

  If Origine = "Art" Then
    Filename = Variables.Schmprix & "/Art_Serveur.txt"
    If Exist(filename) Then
      Try hFile = Open filename For Read Write
    Else
      Try hFile = Open filename For Write Create
    Endif
    While Not Eof(hFile)
      Line Input #hFile, Lig
    Wend
    rResult = Utils.db.Exec("SELECT * FROM Fiches_Art where art_code = &1", code)
    $Serveur = Type & ";" & code & ";" & rResult!art_design & ";" & rResult!art_fam & ";" & rResult!art_four & ";" & rResult!art_cequ & ";" & rResult!art_cbarre & ";" & rResult!art_cfour & ";" & rResult!art_pbht & ";" & rResult!art_tr & ";" & rResult!art_pauaht & ";" & rResult!art_coef & ";" & rResult!art_pvht & ";" & rResult!art_tva & ";" & rResult!art_pvttc & ";" & rResult!art_cdarr & ";" & rResult!art_dec & ";" & rResult!art_stocke & ";" & rResult!art_nbd & ";" & rResult!art_design2 & ";" & rResult!art_ect & ";" & rResult!art_eco & ";" & rResult!art_paht & ";" & rResult!art_txconv & ";" & rResult!art_pmp & ";" & rResult!art_stkmin & ";" & rResult!art_stkmax & ";" & rResult!art_suspendu & ";" & rResult!art_cpp & ";" & rResult!art_copp & ";" & rResult!art_frais & ";"
    $Serveur &= rResult!art_prvt & ";" & rResult!art_ect2 & ";" & rResult!art_eco2 & ";" & rResult!art_depg & ";" & rResult!art_cnsg & ";" & rResult!art_qte & ";" & rResult!art_refliee & ";" & rResult!art_etiq & ";" & rResult!art_poids & ";" & rResult!art_vol & ";" & rResult!art_mincom & ";"
    $Serveur &= rResult!art_poids2 & ";" & rResult!art_mat & ";" & rResult!art_marque & ";" & rResult!art_photo & ";" & rResult!art_crst & ";" & rResult!art_impcar & ";" & rResult!art_casier & ";" & rResult!art_pvcons & ";" & rResult!art_prdcomp & ";" & rResult!art_impdetail & ";" & rResult!art_remcas1 & ";" & rResult!art_remcas2 & ";" & rResult!art_remcas3 & ";" & rResult!art_bonus & ";" & rResult!art_pbfbt & ";" & rResult!art_datefbt & ";" & rResult!art_centrale & ";" & rResult!art_refcentrale & ";" & rResult!art_colvte & ";" & rResult!art_pvht2 & ";" & rResult!art_cn8 & ";" & rResult!art_crpl1 & ";" & rResult!art_ua & ";" & rResult!art_uv & ";" & rResult!art_ect & ";"
    Print #hFile, $Serveur
    Close #hFile
  Endif

  If origine = "EQ" Then
    Filename = Variables.Schmprix & "/EQ_Serveur.txt"
    If Exist(filename) Then
      Try hFile = Open filename For Read Write
    Else
      Try hFile = Open filename For Write Create
    Endif
    While Not Eof(hFile)
      Line Input #hFile, Lig
    Wend
    $Serveur = "EQ" & ";" & type & ";" & code & ";" & code2 & ";"
    Print #hFile, $Serveur
    Close #hFile
  Endif

  If origine = "CB" Then
    Filename = Variables.Schmprix & "/CB_Serveur.txt"
    If Exist(filename) Then
      Try hFile = Open filename For Read Write
    Else
      Try hFile = Open filename For Write Create
    Endif
    While Not Eof(hFile)
      Line Input #hFile, Lig
    Wend
    $Serveur = "CB" & ";" & type & ";" & code & ";" & code2 & ";"
    Print #hFile, $Serveur
    Close #hFile
  Endif

  If Origine = "Fam" Then
    Filename = Variables.Schmprix & "/Fam_Serveur.txt"
    If Exist(filename) Then
      Try hFile = Open filename For Read Write
    Else
      Try hFile = Open filename For Write Create
    Endif
    While Not Eof(hFile)
      Line Input #hFile, Lig
    Wend
    rResult = Utils.db.Exec("SELECT * FROM Fiches_Fam where code_fam = &1", code)
    $Serveur = Type & ";" & code & ";" & rResult!libell_fam & ";" & rResult!coef_fam & ";" & rResult!cdtva_fam & ";" & rResult!compt_fam & ";" & rResult!compt2_fam & ";" & rResult!compt3_fam & ";" & rResult!compt4_fam & ";" & rResult!compt5_fam & ";" & rResult!txtva_fam & ";" & rResult!cptrem_fam & ";"
    $Serveur &= rResult!ect_fam & ";" & rResult!rem_fam & ";" & rResult!qte1 & ";" & rResult!qte2 & ";" & rResult!qte3 & ";" & rResult!qte4 & ";" & rResult!qte5 & ";" & rResult!qte6 & ";" & rResult!qte7 & ";" & rResult!qte8 & ";" & rResult!qte9 & ";" & rResult!qte10 & ";"
    $Serveur &= rResult!qte11 & ";" & rResult!qte12 & ";" & rResult!rem1 & ";" & rResult!rem2 & ";" & rResult!rem3 & ";" & rResult!rem4 & ";" & rResult!rem5 & ";" & rResult!rem6
    Print #hFile, $Serveur
    Close #hFile
  Endif

  If Origine = "Four" Then
    Filename = Variables.Schmprix & "/Four_Serveur.txt"
    If Exist(filename) Then
      Try hFile = Open filename For Read Write
    Else
      Try hFile = Open filename For Write Create
    Endif
    While Not Eof(hFile)
      Line Input #hFile, Lig
    Wend
    rResult = Utils.db.Exec("select * from Fiches_Four Left join Fiches_Comptes on compte_cc = fo_code where fo_code = &1", code)
    $Serveur = Type & ";" & code & ";" & rResult!fo_col & ";" & rResult!fo_rs_soc & ";" & rResult!fo_nom & ";" & rResult!fo_pnm & ";" & rResult!fo_adr1 & ";" & rResult!fo_adr2 & ";" & rResult!fo_cd_ptl & ";" & rResult!fo_ville & ";" & rResult!fo_email & ";"
    $Serveur &= rResult!fo_tel_std & ";" & rResult!fo_tel_bur & ";" & rResult!fo_tel_post & ";" & rResult!fo_pble & ";" & rResult!fo_fx1 & ";" & rResult!fo_fx2 & ";" & rResult!fo_obs & ";" & rResult!fo_cd_bq & ";" & rResult!fo_cd_gch & ";" & rResult!fo_num_cpt & ";"
    $Serveur &= rResult!fo_cle_rib & ";" & rResult!fo_dom & ";" & rResult!fo_id_tva & ";" & rResult!fo_cd_cli & ";" & rResult!fo_collectif & ";" & rResult!fo_site & ";" & rResult!fo_cdech & ";" & rResult!fo_pays & ";" & rResult!fo_franco & ";" & rResult!fo_centrale & ";" & rResult!fo_ccentrale & ";" & rResult!fo_copie & ";" & rResult!fo_mincom & ";" & rResult!fo_iban & ";" & rResult!fo_bic & ";" & rResult!fo_exo & ";" & rResult!fo_fport & ";" & rResult!fo_cb & ";" & rResult!lettrable & ";"
    Print #hFile, $Serveur
    Close #hFile
  Endif

  If Origine = "ContactF" Then
    Filename = Variables.Schmprix & "/ContactF_Serveur.txt"
    If Exist(filename) Then
      Try hFile = Open filename For Read Write
    Else
      Try hFile = Open filename For Write Create
    Endif
    While Not Eof(hFile)
      Line Input #hFile, Lig
    Wend
    If Type <> "S" Then
      rResult = Utils.db.Exec("select * from Fiches_ContactF where code = &1 and num = &2", code, code2)
      $Serveur = Type & ";" & code & ";" & code2 & ";" & rResult!nom & ";" & rResult!pnm & ";" & rResult!fonction & ";" & rResult!tel & ";" & rResult!mail & ";" & rResult!portable & ";"
    Else
      $Serveur = Type & ";" & code & ";" & code2 & ";"
    Endif
    Print #hFile, $Serveur
    Close #hFile
  Endif

  If Origine = "Cli" Then
    Filename = Variables.Schmprix & "/Cli_Serveur.txt"
    If Exist(filename) Then
      Try hFile = Open filename For Read Write
    Else
      Try hFile = Open filename For Write Create
    Endif
    While Not Eof(hFile)
      Line Input #hFile, Lig
    Wend
    rResult = Utils.db.Exec("select * from Fiches_Cli Left join Fiches_Comptes on compte_cc = cli_code where cli_code = &1", code)
    $Serveur = Type & ";" & code & ";" & rResult!cli_rs_soc & ";" & rResult!cli_nom & ";" & rResult!cli_pnm & ";" & rResult!cli_adr1 & ";" & rResult!cli_adr2 & ";" & rResult!cli_cd_ptl & ";" & rResult!cli_ville & ";" & rResult!cli_email & ";" & rResult!cli_tel_dom & ";" & rResult!cli_tel_bur & ";" & rResult!cli_tel_poste & ";" & rResult!cli_pble & ";" & rResult!cli_fx1 & ";" & rResult!cli_fx2 & ";" & rResult!cli_plaf_ecrs & ";" & rResult!cli_cd_bq & ";" & rResult!cli_cd_gch & ";" & rResult!cli_dmln & ";" & rResult!cli_cle_rib & ";" & rResult!cli_num_cpt & ";" & rResult!cli_cd_ent & ";" & rResult!cli_cd_acc & ";" & rResult!cli_ref_tir & ";" & rResult!cli_id_tva & ";" & rResult!cli_rlvc & ";" & rResult!cli_rlvf & ";" & rResult!cli_obs & ";" & rResult!cli_collectif & ";" & rResult!cli_typec & ";"
    $Serveur &= rResult!cli_rmo & ";" & rResult!cli_rart & ";" & rResult!cli_exo & ";" & rResult!cli_cdech & ";" & rResult!cli_typec & ";" & rResult!cli_expl & ";" & rResult!cli_pays & ";" & rResult!cli_statut & ";" & rResult!cli_reg & ";" & rResult!cli_copie & ";" & rResult!cli_actif & ";" & rResult!cli_div & ";" & rResult!cli_iban & ";" & rResult!cli_bic & ";" & rResult!cli_rum & ";" & rResult!cli_datab & ";" & rResult!cli_aban & ";" & rResult!cli_sage & ";" & rResult!cli_livraison & ";" & rResult!cli_comm & ";" & rResult!cli_autoent & ";" & rResult!lettrable & ";"
    Print #hFile, $Serveur
    Close #hFile
  Endif

  If Origine = "ContactC" Then
    Filename = Variables.Schmprix & "/ContactC_Serveur.txt"
    If Exist(filename) Then
      Try hFile = Open filename For Read Write
    Else
      Try hFile = Open filename For Write Create
    Endif
    While Not Eof(hFile)
      Line Input #hFile, Lig
    Wend
    If Type <> "S" Then
      rResult = Utils.db.Exec("select * from Fiches_ContactC where code = &1 and num = &2", code, code2)
      $Serveur = Type & ";" & code & ";" & code2 & ";" & rResult!nom & ";" & rResult!pnm & ";" & rResult!fonction & ";" & rResult!tel & ";" & rResult!mail & ";" & rResult!portable & ";"
    Else
      $Serveur = Type & ";" & code & ";" & code2 & ";"
    Endif
    Print #hFile, $Serveur
    Close #hFile
  Endif

  If Origine = "Stock" Then
    Filename = Variables.Schmprix & "/Stock_Serveur.txt"
    If Exist(filename) Then
      Try hFile = Open filename For Read Write
    Else
      Try hFile = Open filename For Write Create
    Endif
    While Not Eof(hFile)
      Line Input #hFile, Lig
    Wend
    Print #hFile, code & ";"
    Close #hFile
  Endif

  If Origine = "Rpl1" Then
    Filename = Variables.Schmprix & "/Rpl1_Serveur.txt"
    If Exist(filename) Then
      Try hFile = Open filename For Read Write
    Else
      Try hFile = Open filename For Write Create
    Endif
    While Not Eof(hFile)
      Line Input #hFile, Lig
    Wend
    $Serveur = Type & ";" & code & ";" & code2 & ";"
    Print #hFile, $Serveur
    Close #hFile
  Endif

  If Origine = "Rpl2" Then
    Filename = Variables.Schmprix & "/Rpl2_Serveur.txt"
    If Exist(filename) Then
      Try hFile = Open filename For Read Write
    Else
      Try hFile = Open filename For Write Create
    Endif
    While Not Eof(hFile)
      Line Input #hFile, Lig
    Wend
    $Serveur = Type & ";" & code & ";" & code2 & ";"
    Print #hFile, $Serveur
    Close #hFile
  Endif

End

Public Sub Docs(Origine As String, type As String, compte As String, nomfichier As String, Etiq As String) As String

  Dim rResult As Result
  Dim $Serveur As String

  If Origine = "Art" Then
    Filename = Variables.Schmprix & "/DocA_Serveur.txt"
    If Exist(filename) Then
      Try hFile = Open filename For Read Write
    Else
      Try hFile = Open filename For Write Create
    Endif
    While Not Eof(hFile)
      Line Input #hFile, Lig
    Wend
    $Serveur = Type & ";" & compte & ";" & nomfichier & ";" & Etiq & ";"
    Print #hFile, $Serveur
  Endif

  If Origine = "Four" Then
    Filename = Variables.Schmprix & "/DocF_Serveur.txt"
    If Exist(filename) Then
      Try hFile = Open filename For Read Write
    Else
      Try hFile = Open filename For Write Create
    Endif
    While Not Eof(hFile)
      Line Input #hFile, Lig
    Wend
    $Serveur = Type & ";" & compte & ";" & nomfichier & ";" & Etiq & ";"
    Print #hFile, $Serveur
  Endif

  If Origine = "Cli" Then
    Filename = Variables.Schmprix & "/DocC_Serveur.txt"
    If Exist(filename) Then
      Try hFile = Open filename For Read Write
    Else
      Try hFile = Open filename For Write Create
    Endif
    While Not Eof(hFile)
      Line Input #hFile, Lig
    Wend
    $Serveur = Type & ";" & compte & ";" & nomfichier & ";" & Etiq & ";"
    Print #hFile, $Serveur
  Endif

End

Public Function ReplaceFam(mtt As String) As String

  Dim i As Integer = 3

  mtt = LCase$(mtt)
  For i = 3 To 10
    If InStr("0123456789", Mid$(mtt, i, 1)) Then
      mtt = Left$(mtt, i - 1) & "0" & Mid$(mtt, i, 1) & Mid$(mtt, i + 1, Len(mtt))
      Inc i
    Endif
  Next
  If InStr(mtt, "a") Then mtt = Replace$(mtt, "a", "10")
  If InStr(mtt, "b") Then mtt = Replace$(mtt, "b", "11")
  If InStr(mtt, "c") Then mtt = Replace$(mtt, "c", "12")
  If InStr(mtt, "d") Then mtt = Replace$(mtt, "d", "13")
  If InStr(mtt, "e") Then mtt = Replace$(mtt, "e", "14")
  If InStr(mtt, "f") Then mtt = Replace$(mtt, "f", "15")
  If InStr(mtt, "g") Then mtt = Replace$(mtt, "g", "16")
  If InStr(mtt, "h") Then mtt = Replace$(mtt, "h", "17")
  If InStr(mtt, "i") Then mtt = Replace$(mtt, "i", "18")
  If InStr(mtt, "j") Then mtt = Replace$(mtt, "j", "19")
  If InStr(mtt, "k") Then mtt = Replace$(mtt, "k", "20")
  If InStr(mtt, "l") Then mtt = Replace$(mtt, "l", "21")
  If InStr(mtt, "m") Then mtt = Replace$(mtt, "m", "22")
  If InStr(mtt, "n") Then mtt = Replace$(mtt, "n", "23")
  If InStr(mtt, "o") Then mtt = Replace$(mtt, "o", "24")
  If InStr(mtt, "p") Then mtt = Replace$(mtt, "p", "25")
  If InStr(mtt, "q") Then mtt = Replace$(mtt, "q", "26")
  If InStr(mtt, "r") Then mtt = Replace$(mtt, "r", "27")
  If InStr(mtt, "s") Then mtt = Replace$(mtt, "s", "28")
  If InStr(mtt, "t") Then mtt = Replace$(mtt, "t", "29")
  If InStr(mtt, "u") Then mtt = Replace$(mtt, "u", "30")
  If InStr(mtt, "v") Then mtt = Replace$(mtt, "v", "31")
  If InStr(mtt, "w") Then mtt = Replace$(mtt, "w", "32")
  If InStr(mtt, "x") Then mtt = Replace$(mtt, "x", "33")
  If InStr(mtt, "y") Then mtt = Replace$(mtt, "y", "34")
  If InStr(mtt, "z") Then mtt = Replace$(mtt, "z", "35")
  Return mtt

End

Public Function convBStr(bln As Boolean) As String

  Dim sRet As String

  If bln = False Then
    sRet = "0"
  Else
    sRet = "1"
  Endif
  Return sRet

End
