' Gambas module file

Public Societe As String
Public son As Integer
Public Musique As String = "son/warning.ogg"
Public Caisse As Boolean
Public Proform As String
Public Commande As String
Public Devis As String
Public Devis2 As String
Public Bon As String
Public Facture As String
Public Epuises As String
Public Stockes As String
Public Nstockes As String
Public Suspendus As String
Private Lig2 As String[]
Private Fontes As String
Private hpb As ProgressBar
Public R As Integer = 255
Public G As Integer = 255
Public B As Integer = 255
Public R2 As Integer
Public G2 As Integer
Public B2 As Integer
Public Motdepasse As String
Private hlb As Label

Public Sub Main()

  Dim $cle, $cle2, txt, sha As String
  Dim bcle As Boolean = False
  Dim Btunnel As Boolean = True
  Dim Pids As String
  Dim psExist As Process

  If Settings["/dbase/Con-ssh"] And If Settings["/Soc" & Start.Societe & "/Replique"] And If Settings["/Soc" & Start.Societe & "/Breplique"] Then
    Btunnel = Utils.ControlTunnel()
    If Not Btunnel Then
      Message.Error("La réplication est inactive ! Continuer le travail avec Laurux peut causer des soucis.")
      Return
    Endif
  Endif

  Try Societe = Settings["/Soc"]
  Try Son = Settings["/son"]
  Music.Load(Musique)
  Proform = Settings["/Coul/Prf"]
  Commande = Settings["/Coul/Cmde"]
  Devis = Settings["/Coul/Devis"]
  Devis2 = Settings["/Coul/Devis2"]
  Bon = Settings["/Coul/Bl"]
  Facture = Settings["/Coul/Facts"]
  Epuises = Settings["/Coul/Eps"]
  Stockes = Settings["/Coul/Stk"]
  Nstockes = Settings["/Coul/Nstk"]
  Suspendus = Settings["/Coul/Spd"]
  If Error Or If IsNull(Settings["/Coul" & "/Fnets"]) Then
    Settings["/Coul" & "/Fnets"] = "Background: &HDDDDDD&; "
    Settings["/Coul" & "/Btns"] = "Background: &HBDBDBD&; "
    Settings["/Coul" & "/Znss"] = "Background: &HFAFAFA&; "
    Settings["/Coul" & "/Znaff"] = "Background: &HEEEEEE&; "
    Settings["/Coul" & "/Focus"] = "Background: &HF9FFC7&; "
    Settings["/Coul" & "/Coulfonds"] = "Background: &FFEE81&; "
    Settings["/Coul" & "/Others"] = "Background: &FFE0B8&; "
    Settings["/Coul" & "/Fcs"] = "Background: &HF9FFC7&"
    Settings["/Coul" & "/Stk"] = "Background: &HCFF58E&; Font: serif,9; "
    Settings["/Coul" & "/Coulfonds"] = "255;252;216;"
    Settings["/Coul" & "/Others"] = "255;232;199;"
    Settings["/Coul" & "/Facts"] = "Background: &HFFFFFF&; Font: Serif,9; "
    Settings["/Coul" & "/Avs"] = "Background: &HFFFFFF&; Font: Serif,9; "
    Settings["/Coul" & "/Bl"] = "Background: &HFFFFFF&; Font: Serif,9; "
    Settings["/Coul" & "/Devis"] = "Background: &HFFFFFF&; Font: Serif,9; "
    Settings["/Coul" & "/Devis2"] = "Background: &HFFFFFF&; Font: Serif,9; "
    Settings["/Coul" & "/Cmde"] = "Background: &HFFFFFF&; Font: Serif,9; "
    Settings["/Coul" & "/Prf"] = "Background: &HFFFFFF&; Font: Serif,9; "
    Settings["/Coul" & "/Nstk"] = "Background: &HFFFFFF&; Font: Serif,9; "
    Settings["/Coul" & "/Eps"] = "Background: &HFFFFFF&; Font: Serif,9; "
    Settings["/Coul" & "/Spd"] = "Background: &HFFFFFF&; Font: Serif,9; "
    Settings["/Coul" & "/Motps"] = "Background: &HFFFFFF&; Font: Serif,9; "
    Settings["/Coul" & "/Momnt"] = "Background: &HFFFFFF&; Font: Serif,9; "
    Settings.save
    Settings.Reload
  Endif
  If Not Exist(User.home & "/tmp") Then Mkdir User.home & "/tmp"
  Application.Font = Font["Serif,11"]
  Try Fontes = Settings["/Soc" & Societe & "/Font"]
  If IsNull(fontes) Then
    Application.Font = Font["Serif,11"]
  Else
    Application.Font = Font[Fontes]
  Endif
  Coul()
  If Exist(User.home & "/" & Application.Name & ".lock") Then
    If son Then
      Music.Play
    Endif
    Pids = File.Load(User.home & "/" & Application.Name & ".lock")
    psExist = Shell "ps -p " & Pids Wait
    If psExist.Value = 0 Then
      If Message.Warning(("Il semblerait que " & Application.Name & "\nProcess : " & Pids & "\nsoit encore ouvert!\n\nOuvrir deux fois Laurux peut causer des dysfonctionnements (erreur de stock etc...)\net utiliser un programme qui n'a pas été fermé normalement \nsignifie que la base n'est peut-être pas à jour et que vous devriez faire une restauration."), ("Ne pas ouvrir"), ("Ouvrir")) = 2 Then
        Lancement()
      Endif
    Else
      'le process est inexistant
      Try Kill User.home & "/" & Application.Name & ".lock"
      Lancement()
    Endif
  Else
    Lancement()
  Endif

End

Public Sub Coul()

  Dim Fonds As String

  Try Fonds = Settings["/Coul/Others"]
  If Not Error Then
    If Not IsNull(Fonds) Then
      lig2 = Split(Fonds, ";")
      Try R = Lig2[0]
      Try G = Lig2[1]
      Try B = Lig2[2]
      If Error Then
        R2 = 229
        G2 = 233
        B2 = 255
      Endif
    Endif
  Endif
  Try Fonds = Settings["/Coul/Coulfonds"]
  If Not Error Then
    If Not IsNull(Fonds) Then
      lig2 = Split(Fonds, ";")
      Try R2 = Lig2[0]
      Try G2 = lig2[1]
      Try B2 = lig2[2]
      If Error Then
        R2 = 255
        G2 = 254
        B2 = 212
      Endif
    Endif
  Endif

End

            Try Kill User.home & "/Laurux.lock"
Public Sub Lancement()
  
  Dim Pids As String = ""
  
  Try Pids = File.Load(User.home & "/" & Application.Name & ".lock") & " "
  File.Save(User.home & "/" & Application.Name & ".lock", Pids & Application.Id)
  
  If IsNull(proform) Then Proform = "&HF9F9BD&"
  If IsNull(Commande) Then Commande = "&HF9F9BD&" ""
  If IsNull(Devis) Then Devis = "&HF9F9BD&"
  If IsNull(Bon) Then Bon = "&HF9F9BD&"
  If IsNull(Facture) Then Facture = "&HF9F9BD&"
  If IsNull(proform) Then Proform = "&HF9F9BD&"
  If IsNull(Commande) Then Commande = "&HF9F9BD&" ""
  If IsNull(Devis) Then Devis = "&HF9F9BD&"
  If IsNull(Bon) Then Bon = "&HF9F9BD&"
  If IsNull(Facture) Then Facture = "&HF9F9BD&"
  If IsNull(Epuises) Then Epuises = "&HF9F9BD&"
  If IsNull(Stockes) Then Stockes = "&HF9F9BD&"
  If IsNull(Nstockes) Then Nstockes = "&HF9F9BD&"
  If IsNull(Suspendus) Then Suspendus = "&HF9F9BD&"
  If Settings["/Soc" & Societe & "/Compta"] Then
    Fmenuc.Show
  Else
    If Settings["/Soc" & Societe & "/Gestion"] Then
      Fmenuf.Show
    Else
      Fmenu.Show
    Endif
  Endif
  If Settings["/Soc" & Societe & "/Caisse"] Then Caisse = True
  If Settings["/Tips"] Then
    Ftips.Run
  Endif

End
