' Gambas module file

Private hfile As File
Private Filename As String
Private Lig As String

Public Sub Pass(Origine As String, type As String, p1 As String, p2 As String, p3 As String, p4 As String, p5 As String, p6 As String, p7 As String, p8 As String, p9 As String, p10 As String, p11 As String, p12 As String, p13 As String, p14 As String, p15 As String) As String
  
  If Origine = "Art" Then
    Filename = "/tmp/Art_Thelia.txt"
    If Exist(filename) Then
      Try hFile = Open filename For Read Write
    Else 
      Try hFile = Open filename For Write Create
    Endif
    While Not Eof(hFile)
      Line Input #hFile, Lig
    Wend
    Print #hFile, CStr(Type) & ";" & CStr(p1) & ";" & CStr(p2) & ";" & CStr(ReplaceFam(p3)) & ";" & CStr(p4) & ";" & CStr(p5) & ";" & CStr(p6) & ";" & CStr(p7) & ";" & CStr(p8) & ";" & CStr(p9) & ";" & CStr(p10) & ";" & CStr(p11) & ";" & CStr(p12) & ";" & CStr(p13) & ";" & CStr(p14) & ";" & CStr(p15)
  Endif
  
  If Origine = "Fam" Then
    Filename = "/tmp/Fam_Thelia.txt"
    If Exist(filename) Then
      Try hFile = Open filename For Read Write
    Else 
      Try hFile = Open filename For Write Create
    Endif
    While Not Eof(hFile)
      Line Input #hFile, Lig
    Wend
    Print #hFile, CStr(Type) & ";" & CStr(p1) & ";" & CStr(ReplaceFam(p2)) & ";" & CStr(p3) & ";" & CStr(p4) & ";" & CStr(p5)
  Endif
  
  If Origine = "Stock" Then
    Filename = "/tmp/Stock_Thelia.txt"
    If Exist(filename) Then
      Try hFile = Open filename For Read Write
    Else 
      Try hFile = Open filename For Write Create
    Endif
    While Not Eof(hFile)
      Line Input #hFile, Lig
    Wend
    Print #hFile, CStr(p1) & ";" & CStr(p2)
  Endif
  Close #hFile
  
End 

Public Function ReplaceFam(mtt As String) As String
  
  Dim i As Integer = 3
  
  mtt = LCase$(mtt)
  For i = 3 To 10
    If InStr("0123456789", Mid$(mtt, i, 1)) Then 
      mtt = Left$(mtt, i - 1) & "0" & Mid$(mtt, i, 1) & Mid$(mtt, i + 1, Len(mtt))
      Inc i
    Endif
  Next
  If InStr(mtt, "a") Then mtt = Replace$(mtt, "a", "10") 
  If InStr(mtt, "b") Then mtt = Replace$(mtt, "b", "11")
  If InStr(mtt, "c") Then mtt = Replace$(mtt, "c", "12")
  If InStr(mtt, "d") Then mtt = Replace$(mtt, "d", "13")
  If InStr(mtt, "e") Then mtt = Replace$(mtt, "e", "14")
  If InStr(mtt, "f") Then mtt = Replace$(mtt, "f", "15")
  If InStr(mtt, "g") Then mtt = Replace$(mtt, "g", "16")
  If InStr(mtt, "h") Then mtt = Replace$(mtt, "h", "17")
  If InStr(mtt, "i") Then mtt = Replace$(mtt, "i", "18")
  If InStr(mtt, "j") Then mtt = Replace$(mtt, "j", "19")
  If InStr(mtt, "k") Then mtt = Replace$(mtt, "k", "20")
  If InStr(mtt, "l") Then mtt = Replace$(mtt, "l", "21")
  If InStr(mtt, "m") Then mtt = Replace$(mtt, "m", "22")
  If InStr(mtt, "n") Then mtt = Replace$(mtt, "n", "23")
  If InStr(mtt, "o") Then mtt = Replace$(mtt, "o", "24")
  If InStr(mtt, "p") Then mtt = Replace$(mtt, "p", "25")
  If InStr(mtt, "q") Then mtt = Replace$(mtt, "q", "26")
  If InStr(mtt, "r") Then mtt = Replace$(mtt, "r", "27")
  If InStr(mtt, "s") Then mtt = Replace$(mtt, "s", "28")
  If InStr(mtt, "t") Then mtt = Replace$(mtt, "t", "29")
  If InStr(mtt, "u") Then mtt = Replace$(mtt, "u", "30")
  If InStr(mtt, "v") Then mtt = Replace$(mtt, "v", "31")
  If InStr(mtt, "w") Then mtt = Replace$(mtt, "w", "32")
  If InStr(mtt, "x") Then mtt = Replace$(mtt, "x", "33")
  If InStr(mtt, "y") Then mtt = Replace$(mtt, "y", "34")
  If InStr(mtt, "z") Then mtt = Replace$(mtt, "z", "35")
  Return mtt
  
End
