' Gambas module file

' On regarde si le produit est dans la promo en cours

Public Sub art_Promo(Code_art As String, Code_Promo As String) As String
  
  Dim rprom As Result
  Dim Cprom As Boolean = False
  
  rprom = Utils.db.Exec("SELECT * FROM " & Cbase.Table("TabArtPromo") & " where code = &1 and code_promo = &2", Code_Art, Code_Promo)
  If rprom.Available Then Cprom = 1
  Return Cprom
  
End

' Si oui, on récupère le prix ht

Public Sub Prix_Promo(Code_art As String, Code_Promo As String) As String
  
  Dim rprom As Result
  
  rprom = Utils.db.Exec("SELECT * FROM " & Cbase.Table("TabArtPromo") & " where code = &1 and code_promo = &2", Code_Art, Code_Promo)
  If rprom.Available Then Return rprom!pht
  
End

' On récupère le prix ttc

Public Sub Prix_Promottc(Code_art As String, Code_Promo As String) As String
  
  Dim rprom As Result
  
  rprom = Utils.db.Exec("SELECT * FROM " & Cbase.Table("TabArtPromo") & " where code = &1 and code_promo = &2", Code_Art, Code_Promo)
  If rprom.Available Then Return rprom!pttc
  
End

' On met la qté vendue en moins (suppression de ligne par ex)

Public Sub Maj_qtemoins(Code_art As String, Code_Promo As String, qte As Float) As String
  
  Dim rprom As Result
  Dim Qstock As Float
  
  rprom = Utils.db.Exec("SELECT * FROM " & Cbase.Table("TabArtPromo") & " where code = &1 and code_promo = &2", Code_Art, Code_Promo)
  If rprom.Available Then
    Try Qstock = rprom!qte
    If Error Then Qstock = 0
    Qstock = Qstock - Qte
    Utils.db.Exec("UPDATE  " & Cbase.Table("TabArtPromo") & "  SET qte = &2 WHERE code = &1 and code_promo = &3", Code_art, Qstock, code_promo)
  Endif
  
End

' On met la qté vendue en plus

Public Sub Maj_qteplus(Code_art As String, Code_Promo As String, qte As Float) As String
  
  Dim rprom As Result
  Dim Qstock As Float
  
  rprom = Utils.db.Exec("SELECT * FROM " & Cbase.Table("TabArtPromo") & " where code = &1 and code_promo = &2", Code_Art, Code_Promo)
  If rprom.Available Then
    Try Qstock = rprom!qte
    If Error Then Qstock = 0
    Qstock = Qstock + Qte
    Utils.db.Exec("UPDATE  " & Cbase.Table("TabArtPromo") & "  SET qte = &2 WHERE code = &1 and code_promo = &3", Code_art, Qstock, code_promo)
  Endif
  
End
