' Gambas module file

'D'après une routine java par GALA OUSSE Brice

Public Function Calc_unite(nombre As Integer) As String

  Dim unite As String

  Select Case nombre
    Case 0
      unite = "zéro"
    Case 1
      unite = "un"
    Case 2
      unite = "deux"
    Case 3
      unite = "trois"
    Case 4
      unite = "quatre"
    Case 5
      unite = "cinq"
    Case 6
      unite = "six"
    Case 7
      unite = "sept"
    Case 8
      unite = "huit"
    Case 9
      unite = "neuf"
  End Select
  Return unite

End

Public Sub Calc_Dizaine(nombre As Integer) As String

  Dim dizaine As String

  Select Case nombre
    Case 10
      dizaine = "dix"
    Case 11
      dizaine = "onze"
    Case 12
      dizaine = "douze"
    Case 13
      dizaine = "treize"
    Case 14
      dizaine = "quatorze"
    Case 15
      dizaine = "quinze"
    Case 16
      dizaine = "seize"
    Case 17
      dizaine = "dix-sept"
    Case 18
      dizaine = "dix-huit"
    Case 19
      dizaine = "dix-neuf"
    Case 20
      dizaine = "vingt"
    Case 30
      dizaine = "trente"
    Case 40
      dizaine = "quarante"
    Case 50
      dizaine = "cinquante"
    Case 60
      dizaine = "soixante"
    Case 70
      dizaine = "soixante-dix"
    Case 80
      dizaine = "quatre-vingt"
    Case 90
      dizaine = "quatre-vingt-dix"
  End Select
  Return dizaine

End

Public Sub nbtostring(nombre As String) As String

  Dim nb2, nbtolet As String
  Dim quotient, reste As Float
  Dim nb, ipos As Integer

  If Len(nombre) > 9 Then Return
  If InStr("0123456789,.", nombre) = 1 Then Return
  nb2 = nombre
  nb = Val(nb2)
  Select Case Len(nb2)
    Case 1
      nbtolet = Calc_unite(nb)
    Case 2
      If nb > 19 Then
        quotient = nb2 / 10
        iPos = InStr(Str(quotient), ",")
        If ipos <> 0 Then quotient = Left$(nombre, iPos - 1)
        reste = Left$(Right(nb2, 1))
        If nb < 71 Or If nb > 79 And nb < 91 Then
          If reste = 0 Then
            nbtolet = Calc_Dizaine(quotient * 10)
          Endif
          If reste = 1 Then
            nbtolet = Calc_Dizaine(quotient * 10) & " " & Calc_Unite(reste)
          Endif
          If reste > 1 Then
            nbtolet = Calc_Dizaine(quotient * 10) & " " & Calc_Unite(reste)
          Endif
        Else
          nbtolet = Calc_Dizaine((quotient - 1) * 10) & " " & Calc_Dizaine(10 + reste)
        Endif
      Else
        If nb >= 10 And nb <= 19 Then
          nbtolet = Calc_Dizaine(nb)
        Else
          If nb > 0 And nb <= 9 Then
            nbtolet = Calc_Unite(nb)
          Endif
        Endif
      Endif

    Case 3
      quotient = nb2 / 100
      iPos = InStr(Str(quotient), ",")
      If ipos <> 0 Then quotient = Left$(nombre, iPos - 1)
      iPos = InStr(nombre, ",")
      If ipos <> 0 Then
        reste = Mid$(nombre, iPos, Len(nombre) - ipos)
      Else
        reste = Right$(nombre, 2)
      Endif
      If quotient = 1 And reste = 0 Then nbtolet = "cent"
      If quotient = 1 And reste > 0 Then nbtolet = "cent " & nbtostring(reste)
      If quotient > 1 And reste = 0 Then nbtolet = Calc_Unite(quotient) & " cents"
      If quotient > 1 And reste > 0 Then nbtolet = Calc_Unite(quotient) & " cent " & nbtostring(reste)

    Case 4
      quotient = nb2 / 1000
      iPos = InStr(Str(quotient), ",")
      If ipos <> 0 Then quotient = Left$(nombre, iPos - 1)
      iPos = InStr(nombre, ",")
      If ipos <> 0 Then
        reste = Mid$(nombre, iPos, Len(nombre) - ipos)
      Else
        reste = Right$(nombre, 3)
      Endif
      If quotient = 1 And reste = 0 Then nbtolet = "mille"
      If quotient = 1 And reste > 0 Then nbtolet = "mille " & nbtostring(reste)
      If quotient > 1 And reste = 0 Then nbtolet = nbtostring(quotient) & " mille"
      If quotient > 1 And reste > 0 Then nbtolet = nbtostring(quotient) & " mille " & nbtostring(reste)

    Case 5
      quotient = nb2 / 1000
      iPos = InStr(Str(quotient), ",")
      If ipos <> 0 Then quotient = Left$(nombre, iPos - 1)
      iPos = InStr(nombre, ",")
      If ipos <> 0 Then
        reste = Mid$(nombre, iPos, Len(nombre) - ipos)
      Else
        reste = Right$(nombre, 3)
      Endif
      If quotient = 1 And reste = 0 Then nbtolet = "mille"
      If quotient = 1 And reste > 0 Then nbtolet = "mille " & nbtostring(reste)
      If quotient > 1 And reste = 0 Then nbtolet = nbtostring(quotient) & " mille"
      If quotient > 1 And reste > 0 Then nbtolet = nbtostring(quotient) & " mille " & nbtostring(reste)

    Case 6
      quotient = nb2 / 1000
      iPos = InStr(Str(quotient), ",")
      If ipos <> 0 Then quotient = Left$(nombre, iPos - 1)
      iPos = InStr(nombre, ",")
      If ipos <> 0 Then
        reste = Mid$(nombre, iPos, Len(nombre) - ipos)
      Else
        reste = Right$(nombre, 3)
      Endif
      If quotient = 1 And reste = 0 Then nbtolet = "mille"
      If quotient = 1 And reste > 0 Then nbtolet = "mille " & nbtostring(reste)
      If quotient > 1 And reste = 0 Then nbtolet = nbtostring(quotient) & " mille"
      If quotient > 1 And reste > 0 Then nbtolet = nbtostring(quotient) & " mille " & nbtostring(reste)

  End Select
  Return nbtolet

End
