' Gambas module file

Public Function TestCai(Cai As String, Vdr As String) As String
  
  Dim Lig As String
  Dim $Vdr As String
  Dim C As Integer
  Dim b As Integer = 0
  Dim $Nc As String
  Dim Filetxt As String
  Dim hfile As File
  
  For C = 1 To 10
    $Nc = "Caisse" & C
    Filetxt = User.home & "/" & $Nc & ".lock"
    If Exist(Filetxt) Then
      ' [GB2:OPEN] OPEN filetxt FOR READ AS #hFile
      hFile = Open filetxt For Read
      Line Input #hFile, Lig
      $Vdr = Left$(lig, 1)
      If C <> Cai And $Vdr = Vdr Then
        Message.Warning("Cette caissière est déjà utilisée sur la caisse " & $Vdr)
        b = 1
        Break
      Endif
      Close #hFile
    Endif
  Next
  Return b
  
End
