' Gambas module file

Public Sub Envoi(Email As String, sujet As String, Txt As String, piece As Boolean, chemin As String, TypeM As String, FileN As String)

  Dim Hmail As New SmtpClient
  Dim spiece As String[]
  Dim spiece2 As String
  Dim piece2 As String = Start.LocalSettings["/Soc" & Start.Societe & "/Pdfchemin"]
  spiece = Split(piece2, "/")
 Try spiece2 = spiece[spiece.count - 1]
  With Hmail
    If Not IsNull(Email) Then
      .Debug = True
      .Host = Start.LocalSettings["/Smtp"]
      .Port = Start.LocalSettings["/Port"]
      .From = Start.LocalSettings["/Adrmail"]
      .User = Start.LocalSettings["/Utilisateur"]
      .Password = hexdblKey.crypt("de", Start.LocalSettings["/MdpStmp"], "Laurux")
      .Encrypt = Net.None
      .Subject = sujet
      .Alternative = False
      .To.Add(Email)
      .Bcc.Add(Settings["/Adrmail"])
      .Add(Txt, "text/plain")
      If piece = True And IsNull(piece2) Then
        .Add(File.Load(chemin & FileN), TypeM, FileN)
      Else
        If piece = True And Not IsNull(piece2) Then 
          .Add(File.Load(chemin & FileN), TypeM, FileN)
          .Add(File.Load(piece2), TypeM, spiece2)
        Endif
      Endif
      Try .Send()
      If Error Then Message.Error("Veuillez vérifier le courriel du client " & Email & " SVP car l'envoi n'a pas pu se faire !")
    Endif
  End With

End

Public Sub Envoi2b(Email As String, sujet As String, Corps As String, piece As String, Optional piece2 As String)

  If Not IsNull(Start.LocalSettings["/Soc" & Start.Societe & "/Prgmail"]) Then
    Select Case Start.LocalSettings["/Soc" & Start.Societe & "/Prgmail"]
      Case "Thunderbird"
        corps = Replace$(corps, ",", "%2C")
        corps = Replace$(corps, "\n", "%0A")
        corps = Replace$(corps, "(", "{")
        corps = Replace$(corps, ")", "}")
        corps = Replace$(corps, "'", " ")
        corps = Replace$(corps, ";", "%2C")
        If Not IsNull(Piece2) Then
          Shell "thunderbird -compose" & " \"" & "to=" & Email & ",subject=" & sujet & ",body=" & corps & ",attachment='" & piece & "," & Piece2 & "'\""
        Else
          Shell "thunderbird -compose" & " \"" & "to=" & Email & ",subject=" & sujet & ",body=" & corps & ",attachment=" & piece & "\""
        Endif

      Case "Icedove"
        corps = Replace$(corps, ",", "%2C")
        corps = Replace$(corps, "\n", "%0A")
        corps = Replace$(corps, "(", "{")
        corps = Replace$(corps, ")", "}")
        corps = Replace$(corps, "'", " ")
        corps = Replace$(corps, ";", "%2C")
        Shell "icedove -compose" & " to=" & Email & ",subject=" & sujet & " ,attachment=" & piece & ",body=" & corps

      Case "Evolution"
        Exec ["evolution", "mailto:" & Email & "?subject=" & sujet & "\\&body=" & corps & "\\&attach=" & piece]

      Case "Kmail"
        Exec ["kmail -s " & sujet & " --attach " & piece & " --msg " & corps & " " & Email]

    End Select
  Else
    Message.Warning("Le gestionnaire de messagerie n'est pas défini dans les préférences !")
  Endif

End

Public Sub Envoi3(Email As String, sujet As String, Corps As String, piece As String)

  Dim piece2 As String = Start.LocalSettings["/Soc" & Start.Societe & "/Pdfchemin"]

  If Not IsNull(Start.LocalSettings["/Soc" & Start.Societe & "/Prgmail"]) Then
    Select Case Start.LocalSettings["/Soc" & Start.Societe & "/Prgmail"]
      Case "Thunderbird"
        corps = Replace$(corps, ",", "%2C")
        corps = Replace$(corps, "\n", "%0A")
        corps = Replace$(corps, "(", "{")
        corps = Replace$(corps, ")", "}")
        corps = Replace$(corps, "'", " ")
        corps = Replace$(corps, ";", "%2C")
        Shell "thunderbird -compose" & " \"" & "to=" & Email & ",subject=" & sujet & ",body=" & corps & ",attachment=" & "'" & piece & "," & Piece2 & "'\""

      Case "Icedove"
        corps = Replace$(corps, ",", "%2C")
        corps = Replace$(corps, "\n", "%0A")
        corps = Replace$(corps, "(", "{")
        corps = Replace$(corps, ")", "}")
        corps = Replace$(corps, "'", " ")
        corps = Replace$(corps, ";", "%2C")
        Shell "icedove -compose" & " \"" & "to=" & Email & ",subject=" & sujet & ",body=" & corps & ",attachment=" & "'" & piece & "," & piece2 & "'" & "\""

      Case "Evolution"
        Exec ["evolution", "mailto:" & Email & "?subject=" & sujet & "\\&body=" & corps & "\\&attach=" & piece]

      Case "Kmail"
        Exec ["kmail -s " & sujet & "--attach " & piece & "--msg " & corps & " " & Email]

    End Select
  Else
    Message.Warning("Le gestionnaire de messagerie n'est pas défini dans les préférences !")
  Endif

End

Public Sub Envoi5(Email As String, sujet As String, Corps As String, piece As String, Optional piece2 As String[])
Dim Pjointe, piece3 As String
Dim i As Integer
  If Not IsNull(Start.LocalSettings["/Soc" & Start.Societe & "/Prgmail"]) Then
    Select Case Start.LocalSettings["/Soc" & Start.Societe & "/Prgmail"]
      Case "Thunderbird"
        corps = Replace$(corps, ",", "%2C")
        corps = Replace$(corps, "\n", "%0A")
        corps = Replace$(corps, "(", "{")
        corps = Replace$(corps, ")", "}")
        corps = Replace$(corps, "'", " ")
        corps = Replace$(corps, ";", "%2C")
          If piece2.Count > 0 Then
            piece3 = "thunderbird -compose" & " \"" & "to=" & Email & ",subject=" & sujet & ",body=" & corps & ",attachment='" & piece & ""
          Endif
          If piece2.count > 0 Then
For i = 1 To piece2.count - 1
  If Not IsNull(Piece2[i]) Then piece3 &= "," & Settings["/Soc" & Start.Societe & "/Bexpchemin"] & "/" & Piece2[i] 
Next
piece3 &= "'\""
         Shell piece3
        Else
          Shell "thunderbird -compose" & " \"" & "to=" & Email & ",subject=" & sujet & ",body=" & corps & ",attachment=" & piece & "\""
        Endif
    End Select
  Else
    Message.Warning("Le gestionnaire de messagerie n'est pas défini dans les préférences !")
  Endif

End

Public Sub Envoi2(Email As String, sujet As String, Corps As String, piece As String, Optional piece2 As String, Optional piece3 As String[])
Dim Pjointe, piece4 As String
Dim i As Integer
  If Not IsNull(Start.LocalSettings["/Soc" & Start.Societe & "/Prgmail"]) Then
    Select Case Start.LocalSettings["/Soc" & Start.Societe & "/Prgmail"]
      Case "Thunderbird"
        corps = Replace$(corps, ",", "%2C")
        corps = Replace$(corps, "\n", "%0A")
        corps = Replace$(corps, "(", "{")
        corps = Replace$(corps, ")", "}")
        corps = Replace$(corps, "'", " ")
        corps = Replace$(corps, ";", "%2C")
         If Not IsNull(piece3) Then
           If Not IsNull(Piece2) Then
            piece4 = "thunderbird -compose" & " \"" & "to=" & Email & ",subject=" & sujet & ",body=" & corps & ",attachment='" & piece & "," & Piece2 & "'\""
          Else
            piece4 = "thunderbird -compose" & " \"" & "to=" & Email & ",subject=" & sujet & ",body=" & corps & ",attachment='" & piece & ""
          Endif
          For i = 0 To piece3.count - 1
            If Not IsNull(Piece3[i]) Then piece4 &= "," & Settings["/Soc" & Start.Societe & "/Bexpcheminpj"] & "/" & Piece3[i] 
          Next
          piece4 &= "'\""
         Shell piece4
       Else
        If Not IsNull(Piece2) And If IsNull(piece3) Then
          Shell "thunderbird -compose" & " \"" & "to=" & Email & ",subject=" & sujet & ",body=" & corps & ",attachment='" & piece & "," & Piece2 & "'\""
        Else
          Shell "thunderbird -compose" & " \"" & "to=" & Email & ",subject=" & sujet & ",body=" & corps & ",attachment=" & piece & "\""
        Endif
        Endif
      Case "Icedove"
        corps = Replace$(corps, ",", "%2C")
        corps = Replace$(corps, "\n", "%0A")
        corps = Replace$(corps, "(", "{")
        corps = Replace$(corps, ")", "}")
        corps = Replace$(corps, "'", " ")
        corps = Replace$(corps, ";", "%2C")
        Shell "icedove -compose" & " to=" & Email & ",subject=" & sujet & " ,attachment=" & piece & ",body=" & corps

      Case "Evolution"
        Exec ["evolution", "mailto:" & Email & "?subject=" & sujet & "\\&body=" & corps & "\\&attach=" & piece]

      Case "Kmail"
        Exec ["kmail -s " & sujet & " --attach " & piece & " --msg " & corps & " " & Email]

    End Select
  Else
    Message.Warning("Le gestionnaire de messagerie n'est pas défini dans les préférences !")
  Endif

End

Public Function Extension(FileN As String) As String

  Dim Ext As New String[]
  Dim Type As String
  Dim i As Integer

  Ext = Split(FileN, ".")
  ' types text
  For i = 1 To 2
    If LCase$(Ext[i]) = "html" Or If LCase$(Ext[i]) = "css" Or If LCase$(Ext[i]) = "xml" Or If LCase$(Ext[i]) = "xsl"
      Type = "text/" & Ext[i]
    Endif
    If LCase$(Ext[i]) = "txt" Or If LCase$(Ext[i]) = "csv"
      Type = "text/plain"
    Endif
    ' types images
    If LCase$(Ext[i]) = "gif" Or If LCase$(Ext[i]) = "png" Or If LCase$(Ext[i]) = "tiff" Or If LCase$(Ext[i]) = "bmp"
      Type = "image/" & Ext[i]
    Endif
    If LCase$(Ext[i]) = "jpg" Or If LCase$(Ext[i]) = "jpeg"
      Type = "image/jpeg"
    Endif
    'types video
    If LCase$(Ext[i]) = "mpeg" Or If LCase$(Ext[i]) = "mpg" Or If LCase$(Ext[i]) = "avi" Or If LCase$(Ext[i]) = "wav"
      Type = "video/" & Ext[i]
    Endif
    'type audio
    If LCase$(Ext[i]) = "mp3"
      Type = "audio/mpeg"
    Endif
    If LCase$(Ext[i]) = "wma"
      Type = "audio/x-ms-wma"
    Endif
    'types application
    If LCase$(Ext[i]) = "ogg" Or If LCase$(Ext[i]) = "pdf" Or If LCase$(Ext[i]) = "rtf" Or If LCase$(Ext[i]) = "zip"
      Type = "application/" & Ext[i]
    Endif
    If LCase$(Ext[i]) = "ps"
      Type = "application/postscript"
    Endif
    If LCase$(Ext[i]) = "bz2"
      Type = "application/x-bzip"
    Endif
    If LCase$(Ext[i]) = "gz"
      Type = "application/x-gzip"
    Endif
    If LCase$(Ext[i]) = "tar"
      Type = "application/x-tar"
    Endif
    If LCase$(Ext[i]) = "doc" Or If LCase$(Ext[i]) = "rtf"
      Type = "application/msword"
    Endif
    If LCase$(Ext[i]) = "xls"
      Type = "application/excel"
    Endif
    If LCase$(Ext[i]) = "pps" Or If LCase$(Ext[i]) = "ppt"
      Type = "application/vnd.ms-powerpoint"
    Endif
    If LCase$(Ext[i]) = "swf"
      Type = "application/x-shockwave-flash"
    Endif
    If LCase$(Ext[i]) = "ods" Or If LCase$(Ext[i]) = "odp" Or If LCase$(Ext[i]) = "odt"
      Type = "application/x-zip"
    Endif
    If Not IsNull(type) Then Break
  Next
  Return Type

End
