' Gambas module file

Public ServeurB As New Connection

Public Sub connect_site()

  ServeurB.type = Settings["/dbase/type"]
  ServeurB.Name = Settings["/dbase/Prefixe"] & Settings["/dbase/Name"]
  ServeurB.Login = Settings["/dbase/Login"]
  ServeurB.Password = hexdblKey.crypt("de", Settings["/dbase/Password"], "Laurux")
  ServeurB.Host = Settings["/dbase/Host"]
  ServeurB.Port = Settings["/dbase/Port"]

End
