' Gambas module file

Public Serveur As New Connection

Public Sub connect_site()

  Serveur.type = Settings["/dbase/type"]
  Serveur.Name = Settings["/dbase/Prefixe"] & Settings["/dbase/Name"]
  Serveur.Login = Settings["/dbase/Login"]
  Serveur.Password = hexdblKey.crypt("de", Settings["/dbase/Password"], "Laurux")
  Serveur.Host = Settings["/dbase/Host"]
  Serveur.Port = Settings["/dbase/Port"]

End
