' Gambas module file

Public ServeurB As New Connection

Public Sub connect_site()

  ServeurB.type = Start.LocalSettings["/dbase/type"]
  ServeurB.Name = Start.LocalSettings["/dbase/Prefixe"] & Start.LocalSettings["/dbase/Name"]
  ServeurB.Login = Start.LocalSettings["/dbase/Login"]
  ServeurB.Password = hexdblKey.crypt("de", Start.LocalSettings["/dbase/Password"], "Laurux")
  ServeurB.Host = Start.LocalSettings["/dbase/Host"]
  ServeurB.Port = Start.LocalSettings["/dbase/Port"]

End
