' Gambas module file

Public Sub Aff_Rdv()
  
  Dim Action As Result
  Dim msg As String
  
  Action = Utils.db.Exec("SELECT * FROM " & Cbase.Table("TabAgenda") & " where haction = &1 and daction = &2 and nuser = &3", Format(Hour(Now), "00") & "h" & Format(Minute(Now), "00"), Format$(Now, "yyyy-mm-dd"), User.name)
  If Action.Count > 0 Then
    If Not IsNull(Action!iaction) Then
      msg = "Il est " & Hour(Now) & " heure " & Minute(Now) & " . " & Action!iaction
      Syntheses.message(msg)
      Message.Warning("Il est " & Action!haction & " !!!  " & Action!iaction)
    Endif
  Endif
Catch
  
End

Public Sub Calc_Timer(Timer1 As Timer)
  
  Timer1.Enabled = False
  Aff_Rdv()
  Timer1.Enabled = True
  
End
