' Gambas module file

Public Function Cascade(PaHT As String, Rem As String) As String
  
  Dim Pa As String
  
  Try Pa = Val(Utils.cpoint(Paht)) - (Val(Utils.cpoint(Paht)) * Val(Utils.cpoint(Rem)) / 100)
  If Error Then pa = "0"
  Return pa
  
End

Public Function CTva(Tva As String) As String
  
  Dim RTva As Result
  Dim Txtva As String
  
  RTva = Utils.db.Exec("SELECT * FROM " & Cbase.Table("TabTvav") & " WHERE code_tva = &1", Tva)
  If RTva.Available Then
    TxTva = RTva!taux_tva
  Endif
  Return txtva
  
End
