' Gambas module file

Public Sub Monip()
  
  Dim $hform As Form
  Dim hLabel As Label
  Dim Wanip As String
  Dim Lanip As String = System.Host
  
  $hForm = New Form As "Form"
  $hForm.Border = Border.Etched
  $hform.Title = "Mon IP"
  $hform.Resizable = False
  $hform.Height = 150
  $hform.Width = 500
  hLabel = New Label($hForm)
  hLabel.Background = &EBEBEB&
  hLabel.Width = 500
  hLabel.Height = 150
  hLabel.Alignment = 3
  $hForm.Move($hForm.ScreenX, $hForm.ScreenY, 500, 150)
  $hform.Center
  $hform.Mouse = Mouse.Default
  Shell "cd " & User.Home & ""
  Shell "curl ifconfig.me > monip" Wait
  Try Wanip = File.Load(User.Home & "/monip")
  If Not Error Then
    hLabel.Text = "Mon adresse WAN IP est : " & Wanip
    hLabel.Text = hLabel.Text & "\nMon nom d'hôte est : " & Lanip
    $hForm.Show
  Else
    Message.Warning("Problème de lecture du Wanip ! Vérifiez que curl soit bien installé...")
  Endif
  
End
