' Gambas module file

'***********************************
'*      On calcule la position     *
'***********************************
Public Function Pos(Qte As String) As String
  
  Select Case Qte
    Case 1
      qte = "premier"
      
    Case 2
      qte = "deuxième"
      
    Case 3
      qte = "troisième"
      
    Case 4
      qte = "quatrième"
      
    Case 5
      qte = "cinquième"
      
    Case 6
      qte = "sixième"
      
    Case 7
      qte = "septième"
      
    Case 8
      qte = "huitiéme"
      
    Case 9
      qte = "neuvième"
      
    Case 10
      qte = "dixiéme"
      
    Case 11
      qte = "onziéme"
      
    Case 12
      qte = "douzième"
      
    Case 13
      qte = "treizième"
      
    Case 14
      qte = "quatorzième"
      
    Case 15
      qte = "quinzième"
      
    Case 16
      qte = "seizième"
      
    Case 17
      qte = "dixseptième"
      
    Case 18
      qte = "dixhuitième"
      
    Case 12
      qte = "dixneuvième"
      
    Case 12
      qte = "vingtième"
      
  End Select
  
  Return qte 
  
End
