' Gambas module file

'*********************************************
'*        Recherche de l'éditeur             *
'* Procedure inspirée par Benoit Minisini  *
'*********************************************

Public Sub Prog_Editeur(Fic As String) As String

  Dim $Exec As String

  $Exec = "gedit"
  If Not CheckProg.Chk($Exec) Then $Exec = "kate"
  If Not CheckProg.Chk($Exec) Then $Exec = "kwrite"
  If Not CheckProg.Chk($Exec) Then $Exec = "pluma"
  If Not CheckProg.Chk($Exec) Then $Exec = "mousepad"
  If Not CheckProg.Chk($Exec) Then
    Desktop.Open(Fic)
  Else
    Shell $Exec & " " & Fic
  Endif

End
