' Gambas module file

'*********************************************
'*        Recherche de l'éditeur             *
'* Procedure inspirée par Benoit Minisini  *
'*********************************************

Public Sub Prog_Editeur(Fic As String) As String
  
  Dim $Exec As String
  
  $Exec = "gedit"
  If Not CheckProg.Chk($Exec) Then $Exec = "kate"
  If Not CheckProg.Chk($Exec) Then $Exec = "kwrite"
  If Not CheckProg.Chk($Exec) Then $Exec = "pluma"
  Shell $Exec & " " & Fic
  
End

Public Sub Prog_Email(Fic As String) As String
  
  Dim $Exec As String
  
  $Exec = "thunderbird"
  If Not CheckProg.Chk($Exec) Then $Exec = "kmail"
  If Not CheckProg.Chk($Exec) Then $Exec = "evolution"
  
End
