' Gambas module file

Public Function Table(Prog As String) As String

  Dim Tab As String

  Select Case Prog
    Case "TabParam"
      Tab = "Fiches_Parametres"

    Case "TabFam"
      Tab = "Fiches_Fam"

    Case "TabArt"
      Tab = "Fiches_Art"

    Case "TabCdBarre"
      Tab = "Fiches_CdBarre"

    Case "TabRpl1"
      Tab = "Fiches_Rpl1"

    Case "TabRpl2"
      Tab = "Fiches_Rpl2"

    Case "TabCequ"
      Tab = "Fiches_Cequ"

    Case "TabCdFour"
      Tab = "Fiches_CdFour"

    Case "TabTxmo"
      Tab = "Fiches_Txtmo"

    Case "TabMo"
      Tab = "Fiches_Mo"

    Case "TabComptes"
      Tab = "Fiches_Comptes"

    Case "TabTvav"
      Tab = "Fiches_Tvaav"

    Case "TabTvac"
      Tab = "Fiches_Tvaac"

    Case "TabParam"
      Tab = "Fiches_Parametres"

    Case "TabHisFac"
      Tab = "Fiches_HistoFac"

    Case "TabHisFacm"
      Tab = "Fiches_HistoFacM"

    Case "TabCom"
      Tab = "Fiches_Commentaires"

    Case "TabHisLigFac"
      Tab = "Fiches_HistoLigfac"

    Case "TabHisLigFacm"
      Tab = "Fiches_HistoLigfacM"

    Case "TabHisEntm"
      Tab = "Fiches_HisentMat"

    Case "TabSoc"
      Tab = "Fiches_Societes"

    Case "TabLibelFac"
      Tab = "Fiches_LibelFac"

    Case "Totalisation"
      Tab = "Totalisation"

    Case "TabMvtA"
      Tab = "Fiches_MvtA"

    Case "TabMvtA1"
      Tab = "Fiches_MvtA1"

    Case "TabMvtA2"
      Tab = "Fiches_MvtA2"

    Case "TabMvtA3"
      Tab = "Fiches_MvtA3"

    Case "TabMvtA4"
      Tab = "Fiches_MvtA4"

    Case "TabMvtA5"
      Tab = "Fiches_MvtA5"

    Case "TabMvt"
      Tab = "Fiches_Mvt"

    Case "TabMvt1"
      Tab = "Fiches_Mvt1"

    Case "TabMvt2"
      Tab = "Fiches_Mvt2"

    Case "TabMvt3"
      Tab = "Fiches_Mvt3"

    Case "TabMvt4"
      Tab = "Fiches_Mvt4"

    Case "TabMvt5"
      Tab = "Fiches_Mvt5"

    Case "TabArtSaisis"
      Tab = "Art_Saisis"

    Case "TabJour"
      Tab = "Fiches_Journaux"

    Case "TabCli"
      Tab = "Fiches_Cli"

    Case "TabClid"
      Tab = "Fiches_Clid"

    Case "TabAdrC"
      Tab = "Fiches_AdrlivC"

    Case "TabContact"
      Tab = "Fiches_ContactC"

    Case "TabCarte"
      Tab = "Fiches_Carte"

    Case "TabCliVtl"
      Tab = "Fiches_Cli_Vtl"

    Case "TabFour"
      Tab = "Fiches_Four"

    Case "TabFourVtl"
      Tab = "Fiches_Four_Vtl"

    Case "TabContactF"
      Tab = "Fiches_ContactF"

    Case "TabLibel"
      Tab = "Fiches_Libelles"

    Case "TabEntcom"
      Tab = "Fiches_Entcom"

    Case "TabLigcom"
      Tab = "Fiches_Ligcom"

    Case "TabMat"
      Tab = "Fiches_Materiels"

    Case "TabMarq"
      Tab = "Fiches_Marques"

    Case "TabBl"
      Tab = "Fiches_Bl"

    Case "TabLigbl"
      Tab = "Fiches_Ligbl"

    Case "TabBlM"
      Tab = "Fiches_BlM"

    Case "TabLigblM"
      Tab = "Fiches_LigblM"

    Case "TabEntrecpt"
      Tab = "Fiches_Entrecpt"

    Case "TabLigrecpt"
      Tab = "Fiches_Ligrecpt"

    Case "TabMvtexp"
      Tab = "Fiches_Mvtexp"

    Case "TabMvtexpdc"
      Tab = "Fiches_Mvtexpdc"

    Case "TabInv"
      Tab = "Fiches_Inv"

    Case "TabInvT"
      Tab = "Fiches_InvT"

    Case "TabStat"
      Tab = "Fiches_Stat"

    Case "Ecrs"
      Tab = "Ecrs"

    Case "TabNumabon"
      Tab = "Fiches_Numabon"

    Case "TabLigabon"
      Tab = "Fiches_Ligabon"

    Case "TabTleg"
      Tab = "Fiches_Tleg"

    Case "TabTmail"
      Tab = "Fiches_TxtMail"

    Case "TabTmailC"
      Tab = "Fiches_TxtMailC"

    Case "TabAgenda"
      Tab = "Fiches_Agenda"

    Case "TabTypec"
      Tab = "Fiches_Typec"

    Case "TabEch"
      Tab = "Fiches_Echeances"

    Case "TabTypec"
      Tab = "Fiches_Typec"

    Case "TabEntTck"
      Tab = "Fiches_EntTicketz"

    Case "TabLigTck"
      Tab = "Fiches_LigTicketz"

    Case "TabHEntTck"
      Tab = "Fiches_HisEntTickets"

    Case "TabHLigTck"
      Tab = "Fiches_HisLigTickets"

    Case "TabReglt"
      Tab = "Fiches_Regltz"

    Case "TabVendeurs"
      Tab = "Fiches_Vendeurs"

    Case "TabCommerciaux"
      Tab = "Fiches_Commerciaux"

    Case "TabCaisses"
      Tab = "Fiches_Caisses"

    Case "TabCliCaisse"
      Tab = "Fiches_ClientCaisse"

    Case "TabLibelTicket"
      Tab = "Fiches_LibelTicket"

    Case "TabLibelAvoirs"
      Tab = "Fiches_LibelAvoirs"

    Case "TabAvoirs"
      Tab = "Fiches_Avoirs"

    Case "TabHisEntTck"
      Tab = "Fiches_HisEntTickets"

    Case "TabHisLigTck"
      Tab = "Fiches_HisLigTickets"

    Case "TabRemTypec"
      Tab = "Fiches_RemTypec"

    Case "RemCliFam"
      Tab = "Fiches_RemCliFam"

    Case "TabStatut"
      Tab = "Fiches_Statut"

    Case "TabCpostaux"
      Tab = "Fiches_Cpostaux"

    Case "TabPromo"
      Tab = "Fiches_Promo"

    Case "TabArtPromo"
      Tab = "Fiches_ArtPromo"

    Case "TabEtiq"
      Tab = "Fiches_Etiquettes"

    Case "TabEtiqp"
      Tab = "Fiches_EtiProd"

    Case "TabEtiqg"
      Tab = "Fiches_EtiGond"

    Case "TabPrdComp"
      Tab = "Fiches_PrdComp"

    Case "TabIdentite"
      Tab = "Fiches_Identite"

    Case "TabCentrales"
      Tab = "Fiches_Centrales"

    Case "TabSuivis"
      Tab = "Fiches_Suivis"

    Case "TabCdocs"
      Tab = "Docs_Clients"

    Case "TabFdocs"
      Tab = "Docs_Fournisseurs"

    Case "TabPdocs"
      Tab = "Docs_Produits"

    Case "TabAdocs"
      Tab = "Docs_Autres"

    Case "TabCPTdocs"
      Tab = "Docs_Compta"

    Case "TabDepots"
      Tab = "Fiches_Depots"

    Case "TabStkDepots"
      Tab = "Fiches_StkDepots"

    Case "TabSdepots"
      Tab = "Fiches_Sdepots"

    Case "TabTarcli"
      Tab = "Fiches_Tarcli"

    Case "TabTcli"
      Tab = "Fiches_TarTypcli"

    Case "TabCtcli"
      Tab = "Fiches_CoeffTypec"

    Case "TabAna"
      Tab = "Fiches_Analytiques"

    Case "TabPostes"
      Tab = "Fiches_Postes"

    Case "TabMailFour"
      Tab = "Mails_Four"

    Case "TabMailCli"
      Tab = "Mails_Cli"

    Case "TabSms"
      Tab = "Fiches_Sms"

  End Select
  Return Tab

End
