' Gambas module file

Public spiece As String

Public Sub Dupli(Fichier As String, chemin As String, ty As String, Dtef As String)
  
  If Not Exist(User.home & chemin) Then Try Mkdir User.home & chemin
  If Error Then
    Message.Error("Problème lors de la création d'un répertoire\nMerci de créer manuellement un répertoire nommé 'Impressions'")
  Else
    Try spiece = ""
    Shell "cd " & User.Home & "" Wait
    Shell "cp " & User.Home & "/" & Fichier & " " & User.Home & chemin & "/" & ty & ".pdf" Wait
    spiece = User.Home & chemin & "/" & ty & ".pdf"
    Wait 0.5
  Endif
  
End

Public Sub Dupli1(Fichier As String, chemin As String, ty As String, Dtef As String)
  
  If Not Exist(User.home & chemin) Then Try Mkdir User.home & chemin
  If Error Then
    Message.Error("Problème lors de la création d'un répertoire !\n Copie du PDF impossible")
  Else
    Try spiece = ""
    Shell "cd " & User.Home & "" Wait
    Shell "cp " & Fichier & " " & User.Home & chemin & "/" & ty & ".pdf" Wait
    spiece = User.Home & chemin & "/" & ty & ".pdf"
  Endif
  
End

Public Sub Dupli2(Fichier As String, chemin As String, ty As String, Dtef As String, CodeC As String, Org As String)
  
  Try Chemin = Settings["/Soc" & Start.Societe & "/Factchemin"]
  If Not IsNull(Chemin) Then
    Try spiece = ""
    If Not Exist(chemin) Then Mkdir chemin
    Chemin = Settings["/Soc" & Start.Societe & "/Factchemin"] & "/Fac"
    If Not Exist(chemin) Then Try Mkdir chemin
    Chemin &= "/" & Codec
    If Not Exist(chemin) Then Try Mkdir chemin
    Chemin &= "/" & Right$(Dtef, 4)
    If Not Exist(chemin) Then Try Mkdir chemin
    Chemin &= "/" & Mid$(Dtef, 4, 2)
    If Not Exist(chemin) Then Try Mkdir chemin
    Shell "cp " & User.home & "/" & Fichier & " " & chemin Wait
    Shell "mv " & chemin & "/" & "Facture.pdf " & chemin & "/" & ty & ".pdf" Wait
    Try Utils.db.Exec("insert into " & Cbase.Table("TabCdocs") & " (code,doc, doc2, org) values ( &1,&2, &3, &4)", CodeC, chemin & "/" & ty & ".pdf", codec & "," & ty & ",", Org)
    spiece = chemin & "/" & ty & ".pdf"
    Wait 1
  Else
    Message.Warning("Le chemin des pdf n'est pas renseigné dans les préférences !")
  Endif
  
End

Public Sub Dupli2CPT(Piece As Integer, chemin As String, CodeC As String, ty As String)
  
  Try Utils.db.Exec("insert into " & Cbase.Table("TabCPTdocs") & " (code,doc, doc2) values ( &1,&2, &3)", piece, chemin, piece & "," & ty & "," & codec)
  'If Error Then Try Utils.db.Exec("insert into " & Cbase.Table("TabCPTdocs") & " (code,doc, doc2) values ( &1,&2, &3)", Piece, chemin & "|", codec & "," & ty & "," & Piece)
  
End

Public Sub Dupli3CPT(Piece As String, chemin As String, CodeC As String, ty As String)
  
  Try Utils.db.Exec("insert into " & Cbase.Table("TabCPTdocs") & " (code,doc, doc2) values ( &1,&2, &3)", Piece, chemin, codec & "," & ty & "," & Piece)
  If Error Then Try Utils.db.Exec("insert into " & Cbase.Table("TabCPTdocs") & " (code,doc, doc2) values ( &1,&2, &3)", Piece, chemin & "|", codec & "," & ty & "," & Piece)
  
End

Public Sub Dupli3(Fichier As String, dtef As String, codec As String, ty As String, tag As String, Org As String) As String
  
  Dim Chemin As String
  
  ty = Replace$(ty, " ", "")
  ty = Replace$(ty, "/", "")
  Try Chemin = Settings["/Soc" & Start.Societe & "/FactcheminF"]
  If Not IsNull(Chemin) Then
    Try spiece = ""
    If Not Exist(chemin) Then Mkdir chemin
    chemin &= "/Commandes"
    If Not Exist(chemin) Then Try Mkdir chemin
    chemin &= "/" & codec
    If Not Exist(chemin) Then Try Mkdir chemin
    Chemin &= "/" & Right$(Dtef, 4)
    If Not Exist(chemin) Then Try Mkdir chemin
    Chemin &= "/" & Mid$(Dtef, 4, 2)
    If Not Exist(chemin) Then Try Mkdir chemin
    Shell "cp " & User.home & "/" & Fichier & " " & chemin & "/" & ty & ".pdf" Wait
    Try Utils.db.Exec("insert into " & Cbase.Table("TabFdocs") & " (code,doc, doc2) values ( &1,&2, &3)", CodeC, chemin & "/" & ty & ".pdf", Tag)
  Else
    Message.Warning("Le chemin des pdf n'est pas renseigné dans les préférences !")
  Endif
  
End

Public Sub Dupli4(Fichier As String, chemin As String, ty As String, Dtef As String, CodeC As String) As String
  
  If IsNull(chemin) Then Try Chemin = Settings["/Soc" & Start.Societe & "/FactcheminF"] & "/BR"
  If Not IsNull(Chemin) Then
    Try spiece = ""
    If Not Exist(chemin) Then Mkdir chemin
    If Not Exist(chemin) Then Try Mkdir chemin
    chemin &= "/" & codec
    If Not Exist(chemin) Then Try Mkdir chemin
    Chemin = chemin & "/" & Right$(Dtef, 4)
    If Not Exist(chemin) Then Try Mkdir chemin
    Chemin = Chemin & "/" & Mid$(Dtef, 4, 2)
    If Not Exist(chemin) Then Try Mkdir chemin
    Shell "cp " & Fichier & " " & chemin Wait
    Shell "mv " & chemin & "/" & "BonReception.pdf " & chemin & "/" & ty & ".pdf" Wait
    Try Utils.db.Exec("insert into " & Cbase.Table("TabFdocs") & " (code,doc, doc2) values ( &1,&2, &3)", CodeC, chemin & "/" & ty & ".pdf", Codec & "," & ty)
    spiece = chemin & "/" & ty & ".pdf"
    Wait 1
  Else
    Message.Warning("Le chemin des pdf n'est pas renseigné dans les préférences !")
  Endif
  
End
