' Gambas module file


  
 Public Function ajoustat(TabStrip1 As TabStrip) As GridView     'dessin du gridview et des colonnes
  
  Dim res As Result
  Dim sdte As String[]
  Dim i, j, k As Integer
  Dim $grdv As GridView
  
  TabStrip1.Count += 1
  TabStrip1.Current.Text = "Statistiques"
  
  $grdv = New GridView(TabStrip1)
  $grdv.Height = TabStrip1.Height - 30
  $grdv.Width = TabStrip1.Width - 10
  $grdv.x = 0
  $grdv.y = 0
  
  $grdv.Header = GridView.Both
  $grdv.ScrollBar = Scroll.Both
  
  res = utils.db.Exec("SELECT * FROM Fiches_Parametres")
  If Not res.Available Then Return
  
  sdte = Split(res!dteclec, "/")
  $grdv.Columns.Count = 12
  $grdv.Rows.Count = 13
  
  k = 0
  For i = 0 To 3
    For j = 1 To 3
          $grdv.Columns[k].Alignment = Align.Center
      Select j
        Case 1 
          $grdv.Columns[k].Width = 110
          If sdte[0] <> "12" Then
            $grdv.Columns[k].Title = Str(Val(sdte[2]) - i) & "/" & Str(Val(sdte[2]) - (i + 1))
            $grdv.Columns[k].text &= " C.A"
          Else
            $grdv.Columns[k].text = Str(Val(sdte[2]) - i) 
            $grdv.Columns[k].text &= " C.A"
          Endif
        Case 2
           $grdv.Columns[k].text = "Quantité"
           $grdv.Columns[k].Width = 90
       Case 3
          $grdv.Columns[k].text = "Marge"
          $grdv.Columns[k].Width = 80
     End Select
    
      k += 1
    Next
  Next

  j = sdte[0]
  For i = 0 To 11
    j += 1
    If j = 13 Then j = 1
    $grdv.Rows[i].Text = utils.mois(j)
    $grdv.rows[i].Height = 18
    
  Next
  $grdv.Rows[12].Text = "TOTAL"
  $grdv.Rows[12].Height = 22
  TabStrip1.Index = 0

  Return $grdv
  
End

