' Gambas module file

Private Envr As String

Public Sub Init()

  If Application.Env["KDE_FULL_SESSION"] Then
    Envr = "kdesu "
  Else
    If Application.Env["GNOME_DESKTOP_SESSION_ID"] Then
      Envr = "gksu "
    Endif
  Endif
  If IsNull(Envr) Then Envr = "gksu "
  Shell Envr & "sudo -S /etc/init.d/mysql stop" Wait
  Shell Envr & "sudo -S /etc/init.d/mysql start" Wait

End

Public Function Process_List(lg As Integer) As Integer

  Dim sline As String
  Dim txterror As String

  Shell "gksu 'mysqladmin -h " & Settings["/dbase/Host"] & " -u " & Utils.db.Login & " -p" & Utils.db.Password & " processlist >" & User.Home & "/tmp/resultat 2>&1'" Wait
  If Exist(User.Home & "/tmp/resultat") Then txterror = File.Load(User.Home & "/tmp/resultat")
  For Each sline In Split(txterror, "\n")
    If Left$(sline, 7) <> "Warning" And If Not IsNull(sline) Then Inc lg
  Next
  Return lg

End
