' Gambas module file

' Gestion des impressions

'---------------------------- Entete de la societé ----------------------------------------
Coulfd As Integer
Coln As Boolean

Public Sub Entete1(rs As String, rs2 As String, adr11 As String, adr211 As String, adr22 As String, adr222 As String, ville As String, ville2 As String, cap As String, rcs As String, siret As String, ape As String, Tvaintra As String, tel As String, portable As String, fax As String, mail As String, site As String, Visudoc As Boolean, logo As Image, Pays As String, Iban As String, Colns As Boolean)
  
  Dim Posx As Integer
  Dim Posy As Integer
  
  Posx = 300
  Posy = 180
  Coln = Colns
  'IF Visudoc = FALSE THEN
  If Settings["/Soc" & Start.Societe & "/glogo"] Then Try Draw_Image(logo)
  'ENDIF
  Draw.FillColor = &FFFFFF&
  Draw.FillStyle = Fill.Solid
  Draw.Rect(200, 200, 2200, 1920)
  Draw.Rect(2600, 1260, 2200, 854)
  Draw.font = font["Bitstream Charter"]
  Draw.Font.Bold = True
  Draw.Font.Size = 14
  Draw.Text(rs, posX - 40, posY + 20)
  Draw.Font.Size = 12
  posY = posY + 200
  Draw.Text(adr11, posX, posY)
  posY = posY + 120
  Draw.Text(adr22, posX, posY)
  posY = posY + 120
  Draw.Text(ville, posX, posY)
  Draw.Font.Bold = False
  Draw.font = font["Century Schoolbook L"]
  Draw.Font.Size = 10
  posY = posY + 180
  If Not IsNull(cap) Then
    Draw.Text(cap, posX, posY)
    posY = posY + 120
  Endif
  If Not IsNull(rcs) Then
    Draw.Text(rcs, posX, posY)
    posY = posY + 120
  Endif
  If Not IsNull(siret) Then
    Draw.Text(siret, posX, posY)
    posY = posY + 120
  Endif
  If Not IsNull(ape) Then
    Draw.Text(ape, posX, posY)
    posY = posY + 120
  Endif
  Draw.Font.Bold = True
  Draw.Font.Size = 10
  Draw.Text(rs2, posX + 2380, 1360)
  Draw.Font.Size = 10
  Draw.Font.Bold = False
  If Not IsNull(Tvaintra) Then
    Draw.Text(Tvaintra, posX, posY)
    posY = posY + 120
  Endif
  If Not IsNull(tel) Then
    Draw.Text(tel, posX, posY)
    posY = posY + 120
  Endif
  If Not IsNull(portable) Then
    Draw.Text(portable, posX, posY)
    posY = posY + 120
  Endif
  Draw.Text(adr211, posX + 2400, 1540)
  If Not IsNull(fax) Then
    Draw.Text(fax, posX, posY)
    posY = posY + 120
  Endif
  Draw.Text(adr222, posX + 2400, 1640)
  If Not IsNull(site) Then
    Draw.Text(site, posX, posY)
    posY = posY + 120
  Endif
  Draw.Text(ville2, posX + 2400, 1800)
  If Not IsNull(mail) Then Draw.Text(mail, posX, posY)
  Draw.Text(Pays, posX + 2400, 1960)
  Draw.Font.Size = 8
  Draw.Font.Italic = True
  If Not IsNull(Iban) Then Draw.Text(Iban, posX, posY + 120)
  Draw.Font.Italic = False
  
End

'---------------------------- Entete du client ----------------------------------------
Public Sub Entete2(rs2 As String, adr211 As String, adr222 As String, ville2 As String, Pays As String, Colns As Boolean)
  
  Dim Posx As Integer
  Dim Posy As Integer
  
  Coln = Colns
  Posx = 300
  Posy = 480
  Draw.Rect(2600, 1260, 2200, 854)
  Draw.Font.Size = 10
  posY = posY + 800
  Draw.Font.Bold = True
  Draw.Text(rs2, posX + 2400, posY)
  Draw.Font.Bold = False
  posY = posY + 120
  posY = posY + 120
  Draw.Text(adr211, posX + 2400, posY)
  posY = posY + 120
  Draw.Text(adr222, posX + 2400, posY)
  posY = posY + 120
  Draw.Text(ville2, posX + 2400, posY)
  posY = posY + 120
  Draw.Text(Pays, posX + 2400, posY + 20)
  posY = posY + 120
  
End

'---------------------------- Logo ----------------------------------------
Private Sub Draw_Image(img As Image)
  
  Dim Postx As Integer
  Dim Posty As Integer
  
  Postx = 3700 - (img.Width / 2)
  Posty = 600 - (img.Height / 2)
  Draw.Image(img, Postx, Posty)
  
End

'---------------------------- Entete des impressions normales ----------------------------------------
Public Sub EnteteN(ent As String)
  
  Dim Posx As Integer
  Dim Posy As Integer
  
  Posx = 90
  Posy = 80
  Draw.FillStyle = Fill.Dense50
  Draw.Rect(120, 80, 4700, 200)
  Draw.font = font["Bitstream Charter"]
  Draw.Font.Bold = True
  Draw.Font.Size = 16
  Draw.Text(ent, posx, PosY, 4700, 200, 3)
  
End

'---------------------------- Bas de page ----------------------------------------
Public Sub Baspage(Nbpage As String)
  
  Dim Posx As Integer
  Dim Posy As Integer
  
  Posx = 90
  Posy = 6660
  Paint.font = font["Bitstream Charter"]
  Paint.Font.Bold = True
  Paint.Font.Size = 8
  Paint.Text("Impression du " & Format$(Now, "dd.mm.yyy"), posX, posY)
  Paint.Text("Page N° " & Nbpage, 4400, PosY)
  
End

'Lignes continues
Public Sub Lines(PosY As String)
  
  Draw.LineStyle = Line.Solid
  Draw.Line(0, PosY, 5000, PosY)
  
End

' Numero de facture, date d'impression et page
Public Sub Level1F(Jour As String, Cde As String, Page As String, IdTva As String)
  
  Draw.Font.Bold = True
  Draw.Font.Size = 10
  Draw.Text(Jour, 210, 2150)
  Draw.Font.Bold = False
  Draw.Text(Cde, 2700, 2150)
  Draw.Text(Page, 4340, 2150)
  Draw.Font.Size = 8
  Draw.Text(Idtva, 2700, 2250)
  Draw.Font.Size = 10
  
End

'Entete des lignes de detail
Public Sub Level2F(Coulfond As String[], Impttc As Boolean, PosY As Integer)
  
  Draw.FillColor = Val(Coulfond[0])
  Draw.Rect(200, PosY, 600, 140)
  Draw.Rect(800, PosY, 1780, 140)
  Draw.Rect(2580, PosY, 180, 140)
  Draw.Rect(2760, PosY, 460, 140)
  Draw.Rect(3220, PosY, 400, 140)
  Draw.Rect(3620, PosY, 460, 140)
  Draw.Rect(4080, PosY, 260, 140)
  Draw.Rect(4340, PosY, 460, 140)
  Draw.Font.Size = 10
  Draw.Text("Code", 200, PosY + 10, 600, 100, 3)
  Draw.Text("Intitulé", 800, PosY + 10, 1780, 100, 3)
  If Not Settings["/Soc" & Start.Societe & "/AutoEnt"] And Not Settings["/Soc" & Start.Societe & "/Franchise"] Then Draw.Text("Tx", 2580, PosY + 10, 180, 100, 3)
  Draw.Text("Qté", 3220, PosY + 10, 400, 100, 3)
  Draw.Text("Rem", 4080, PosY + 10, 260, 100, 3)
  If Impttc = True And Not Settings["/Soc" & Start.Societe & "/AutoEnt"] Or If Impttc = True And Not Settings["/Soc" & Start.Societe & "/Franchise"] Then
    Draw.Text("PU TTC", 2760, PosY + 10, 460, 100, 3)
    Draw.Text("Brut TTC", 3620, PosY + 10, 460, 100, 3)
    Draw.Text("Net TTC", 4340, PosY + 10, 460, 100, 3)
  Else
    If Impttc = False And Not Settings["/Soc" & Start.Societe & "/AutoEnt"] And Not Settings["/Soc" & Start.Societe & "/Franchise"] Then
      Draw.Text("PU HT", 2760, PosY + 10, 460, 100, 3)
      Draw.Text("Brut HT", 3620, PosY + 10, 460, 100, 3)
      Draw.Text("Net HT", 4340, PosY + 10, 460, 100, 3)
    Endif
  Endif
  If Settings["/Soc" & Start.Societe & "/AutoEnt"] Or If Settings["/Soc" & Start.Societe & "/Franchise"] Then
    Draw.Text("PU", 2760, PosY + 10, 460, 100, 3)
    Draw.Text("Brut", 3620, PosY + 10, 460, 100, 3)
    Draw.Text("Net", 4340, PosY + 10, 460, 100, 3)
  Endif
  
End

'Entete des lignes de detail
Public Sub Level2Fa(Coulfond As String[], PosY As Integer)
  
  Draw.FillColor = Val(Coulfond[0])
  Coulfd = Val(Coulfond[0])
  Draw.Rect(200, PosY, 600, 140)
  Draw.Rect(800, PosY, 1780, 140)
  Draw.Rect(2580, PosY, 180, 140)
  Draw.Rect(2760, PosY, 460, 140)
  Draw.Rect(3220, PosY, 400, 140)
  Draw.Rect(3620, PosY, 460, 140)
  Draw.Rect(4080, PosY, 260, 140)
  Draw.Rect(4340, PosY, 460, 140)
  Draw.Font.Size = 10
  Draw.Text("Code", 200, PosY + 10, 600, 100, 3)
  Draw.Text("Intitulé", 800, PosY + 10, 1780, 100, 3)
  Draw.Text("Qté", 3220, PosY + 10, 400, 100, 3)
  
End

'Lignes de detail pour les produits et la MO
Public Sub Level3F(code As String, intitule As String, Pu As String, qte As String, Brut As String, Rem As String, Total As String, Txtva As String, PosY As Integer)
  
  If Coln = True Then Colonnes(PosY)
  Draw.font = font["Bitstream Charter"]
  Draw.Font.Size = 8
  Draw.Text(Code, 210, PosY, 600, 100, 1)
  Draw.Text(Intitule, 810, PosY, 1780, 100, 1)
  Draw.Text(Txtva, 2640, PosY, 180, 100, 1)
  Draw.Text(Pu, 2770, PosY, 460, 100, 2)
  Draw.Text(Qte, 3210, PosY, 400, 100, 2)
  Draw.Text(Brut, 3630, PosY, 460, 100, 2)
  Draw.Text(Rem, 4090, PosY, 252, 100, 2)
  Draw.Text(Total, 4340, PosY, 460, 100, 2)
  
End

Public Sub Colonnes(PosY As Integer)
  
  Draw.FillStyle = Fill.Dense12
  Draw.Background = Coulfd
  Draw.LineStyle = Line.None
  Draw.Rect(200, PosY - 10, 600, 160)
  Draw.FillStyle = Fill.Dense37
  Draw.Rect(800, PosY - 10, 1780, 160)
  Draw.FillStyle = Fill.Dense63
  Draw.Rect(2580, PosY - 10, 180, 160)
  Draw.FillStyle = Fill.Dense37
  Draw.Rect(2760, PosY - 10, 460, 160)
  Draw.FillStyle = Fill.Dense12
  Draw.Rect(3220, PosY - 10, 400, 160)
  Draw.FillStyle = Fill.Dense37
  Draw.Rect(3620, PosY - 10, 460, 160)
  Draw.FillStyle = Fill.Dense63
  Draw.Rect(4080, PosY - 10, 260, 160)
  Draw.FillStyle = Fill.Dense37
  Draw.Rect(4340, PosY - 10, 460, 160)
  Draw.LineStyle = Line.Solid
  
End

'Lignes de detail pour les composants
Public Sub Level8F(code As String, intitule As String, qte As String, PosY As Integer)
  
  If Coln = True Then Colonnes(PosY)
  Draw.font = font["Bitstream Charter"]
  Draw.Font.Size = 8
  Draw.Font.Italic = True
  'Draw.Text(Code, 210, PosY, 600, 140, 1)
  Draw.Text(Intitule, 810, PosY, 1780, 140, 1)
  Draw.Text(Qte, 3230, PosY, 400, 140, 2)
  Draw.Font.Italic = False
  
End

'Caractéristiques du matériel
Public Sub LevelM(Marque As String, Serie As String, dsg1 As String, dsg2 As String, Type As String, Coulfond As String[], typeD As String)
  
  Dim PosY As Integer
  
  PosY = 2280
  Draw.font = font["Bitstream Charter"]
  Draw.Font.Size = 10
  'Draw.Line(200, PosY, 4800, PosY)
  If TypeD = "A" Then Draw.FillColor = Val(Coulfond[0])
  If TypeD = "A" Then Draw.Rect(200, PosY, 4600, 280)
  If TypeD = "A" Then PosY = PosY + 30
  Draw.Text("Marque : " & Marque, 210, PosY)
  Draw.Text("Numéro série : " & Serie, 1410, PosY)
  Draw.Text("Désignation : " & Dsg1, 2520, PosY)
  Draw.Text("Type : " & Type, 210, PosY + 100)
  Draw.Text(Dsg2, 3020, PosY + 100)
  
End

'Caractéristiques du matériel
Public Sub Level3M(PosY As Integer)
  
  Draw.Line(200, PosY, 4800, PosY)
  
End

'Détail de l'intervention pour le matériel
Public Sub Level2M(libelle As String, PosY As Integer)
  
  Draw.font = font["Bitstream Charter"]
  Draw.Font.Size = 8
  Draw.Text(libelle, 210, PosY)
  
End

'Secondes lignes de designation ou lignes des commentaires
Public Sub Level4aF(intitule As String, PosY As Integer)
  
  If Coln = True Then Colonnes(PosY)
  Draw.font = font["Bitstream Charter"]
  Draw.Font.Size = 8
  Draw.Text(Intitule, 810, PosY)
  
End

'Ligne de l 'intitulé du bon
Public Sub Level4bF(intituleb As String, PosY As Integer)
  
  Draw.font = font["Bitstream Charter"]
  Draw.Font.Size = 8
  Draw.Text(Intituleb, 200, PosY)
  
End

'lignes des commentaires pour factures fin de mois
Public Sub Level4cF(intitule As String, PosY As Integer)
  
  Draw.font = font["Bitstream Charter"]
  Draw.Font.Size = 8
  Draw.Text(Intitule, 810, PosY)
  
End

'Lignes de detail des ecots participation et des taxes privées
Public Sub Level4F(intitule As String, PosY As Integer)
  
  If Coln = True Then Colonnes(PosY)
  Draw.font = font["Bitstream Charter"]
  Draw.Font.Size = 8
  Draw.Font.Italic = True
  Draw.Text(Intitule, 810, PosY)
  Draw.Font.Italic = False
  
End

'Recap de l'ecot participation
Public Sub Level5F(TotEco As String, PosY As Integer)
  '  IF Coln = TRUE THEN Colonnes(PosY)
  
  Draw.font = font["Bitstream Charter"]
  Draw.FillColor = Color.White
  Draw.Font.Italic = True
  Draw.Font.Size = 8
  Draw.Rect(220, PosY, 1600, 120)
  Draw.Text(TotEco, 240, PosY + 20)
  Draw.Font.Italic = False
  
End

'Recap bas de facture
Public Sub Level6F(Tmo As String, Tart As String, Trem As String, Txtbf As String, PosY As Integer)
  
  Draw.font = font["Bitstream Charter"]
  Draw.Font.Bold = True
  Draw.Font.Size = 7
  Draw.Text(Txtbf, 1200, PosY + 20, 2600, 420, 3)
  Draw.Font.Bold = False
  PosY = PosY + 120
  Draw.Text(Tmo, 240, PosY + 20)
  PosY = PosY + 80
  Draw.Text(Tart, 240, PosY + 20)
  PosY = PosY + 80
  Draw.Text(Trem, 240, PosY + 20)
  PosY = PosY + 100
  
End

'Lignes total bas de facture
Public Sub Level7F(Coulfond As String[], PosY As Integer, ImpAuto As Boolean, Franchise As Boolean)
  
  Draw.FillColor = Val(Coulfond[0])
  Draw.Rect(200, PosY, 1100, 140)
  Draw.Rect(1300, PosY, 440, 140)
  Draw.Rect(1740, PosY, 1260, 140)
  Draw.Rect(3000, PosY, 660, 140)
  Draw.Rect(3660, PosY, 400, 140)
  Draw.Rect(4060, PosY, 740, 140)
  Draw.font = font["Century Schoolbook L"]
  Draw.Font.Size = 10
  If ImpAuto = False And If Franchise = False Then
    Draw.Text("Code Taxe", 200, PosY + 10, 1100, 100, 3)
    Draw.Text("Taux " & Settings["/Soc" & Start.Societe & "/Taxe"], 1300, PosY + 10, 440, 100, 3)
    Draw.Text("Montant " & Settings["/Soc" & Start.Societe & "/Taxe"], 1740, PosY + 10, 1260, 100, 3)
    Draw.Text("Total net HT", 3000, PosY + 10, 660, 100, 3)
    Draw.Text("Total " & Settings["/Soc" & Start.Societe & "/Taxe"], 3660, PosY + 10, 400, 100, 3)
    Draw.Font.Bold = True
    Draw.Text("Total TTC", 4060, PosY + 10, 740, 100, 3)
  Else
    If ImpAuto = False Or If Franchise = False Then
      Draw.Text("Net à payer", 4060, PosY + 10, 760, 100, 3)
    Endif
  Endif
  Draw.Font.Bold = False
  
End

'Lignes Tva bas de facture
Public Sub Level9F(Ctx As String, Mht As String, Ttx As String, Mtva As String, Mttc As String, Coulfond As String[], PosY As Integer)
  
  Draw.FillColor = Val(Coulfond[0])
  Draw.font = font["Bitstream Charter"]
  Draw.Font.Size = 8
  Draw.Text(Ctx, 1020, PosY)
  Draw.Text(Ttx, 1380, PosY)
  Draw.Text(Mtva, 2120, PosY)
  
End

'Lignes Total bas de facture
Public Sub Level10F(Totht As String, Mtva2 As String, Toteuros As String, Txtleg As String, PosY As Integer, ImpAuto As Boolean, Exo As Boolean, Franchise As Boolean)
  
  Dim TxtAuto As String = "Entreprise non assujettie à TVA, art. 293 B du Code général des impôts."
  Dim TxtAuto2 As String = "Dispensée d'immatriculation en application de l'article L.123-1-1 du Code du commerce."
  Dim Txtexo As String = " Exonération de TVA, article 262 ter I du Code général des impôts."
  
  Draw.font = font["Bitstream Charter"]
  If ImpAuto = False Then
    Draw.Rect(3000, PosY, 660, 140)
    Draw.Rect(3660, PosY, 400, 140)
  Endif
  Draw.Rect(4060, PosY, 740, 140)
  Draw.Font.Bold = True
  Draw.Font.Size = 8
  Draw.Text(Txtleg, 220, PosY)
  If Impauto Or If Franchise Then
    Draw.Text(TxtAuto, 2000, PosY - 320)
  Else
    If Exo = True Then Draw.Text(Txtexo, 3400, PosY - 160)
  Endif
  If Settings["/Soc" & Start.Societe & "/AutoEnt"] Then Draw.Text(TxtAuto2, 2000, PosY - 160)
  Draw.Font.Size = 9
  If Not Impauto And Not Franchise Then
    Draw.Text(Totht, 3020, PosY, 620, 140, 2)
    Draw.Text(Mtva2, 3680, PosY, 360, 140, 2)
  Endif
  Draw.Text(Toteuros, 4080, PosY, 700, 140, 2)
  Draw.Font.Bold = False
  
End

'Texte legal
Public Sub Level11F(Txtleg2 As String, PosY As Integer)
  
  Draw.Font.Size = 6
  Draw.Clip.Enabled = True
  Draw.Clip(220, posy, 3700, 300)
  Draw.Text(Txtleg2, 220, PosY)
  Draw.Clip.Enabled = False
  
End

'Report
Public Sub Level12F(Rprt As String, PosY As Integer, devises As String)
  
  Rprt = "Report : " & Rprt & " " & devises
  Draw.Font.Bold = True
  Draw.Font.Size = 10
  Draw.Text(rprt, 3000, PosY)
  Draw.Font.Bold = False
  
End

'Acompte
Public Sub Level13F(Mfact As String, Mrglt As String, Macpt As String, Mtdut As String, PosY As Integer, Devises As String)
  
  Draw.FillColor = &E3E3E3&
  Draw.FillStyle = Fill.Solid
  Draw.Rect(200, PosY, 4620, 140)
  Draw.font = font["Century Schoolbook L"]
  Draw.Font.Size = 8
  Draw.Text("Montant de la facture : " & Mfact & " " & devises, 240, PosY)
  Draw.Text(Mrglt & Macpt & " " & devises, 1700, PosY)
  Draw.Text("Montant restant à payer : " & Mtdut & " " & devises, 3400, PosY)
  
End

'Bas de fiche atelier
Public Sub Level14F(Coulfond As String[])
  
  Draw.FillColor = Val(Coulfond[0])
  Draw.FillStyle = Fill.Solid
  Draw.Rect(200, 6000, 2400, 300)
  Draw.font = font["Century Schoolbook L"]
  Draw.Font.Size = 8
  Draw.Text("Matériel récéptionné le " & Format$(Now, "dd.mm.yyyy"), 210, 5820)
  Draw.Text("Signature client              : ", 210, 6080)
  Draw_Signature()
  
End

'coupon détachable
Public Sub Level15F(Client As String, Nfact As String, Mfact As String, Posy As Integer, Devises As String)
  
  Draw.Font.Size = 2
  Draw.FillColor = Color.White
  Draw.LineStyle = Line.DashDotDot
  Draw.Rect(3960, PosY, 1000, 500)
  Draw.Font.Size = 7
  Draw.Text("A joindre au réglement SVP", 4020, posy + 20)
  Draw.Font.Size = 7
  Draw.Text("N° facture : " & Nfact, 4020, posy + 120)
  Draw.Text("Code client : " & Client, 4020, posy + 190)
  Draw.Text("Montant TTC : " & Mfact, 4020, posy + 260)
  
End

'---------------------------- Signature ----------------------------------------
Private Sub Draw_Signature()
  
  Dim Postx As Integer
  Dim Posty As Integer
  Dim Signature As Image
  Dim Imagewidth As Integer
  Dim Imageheight As Integer
  Dim imageToPrint As Image
  
  Try Signature = Image.Load("Icones/signature.png")
  Imagewidth = Signature.Width * 4
  Imageheight = Signature.Height * 4
  imageToPrint = Signature.Stretch(Imagewidth, Imageheight, True)
  Postx = 810
  Posty = 6060
  Draw.Image(imageToPrint, Postx, Posty)
  
End
