' Gambas module file

' Uso:
' ConvierteNumero_a_letras(value as float, devise as string, mCent as string)
' Moneda y mCent van en singular. El resultado es siempre en MAYUSCULAS!.

' By: Marcos D. Henning
' Basado en: http://jsbsan.wordpress.com/2009/04/26/redondeo-round/
' Gracias a: Julio
' Diego González Arango

'Ejemplos: PESOS
'ConvierteNumero_a_letras(0.01, "PESO", "CENTAVO") == > UN CENTAVO
'ConvierteNumero_a_letras(0.99, "PESO", "CENTAVO") == > NOVENTA Y NUEVE CENTAVOS
'ConvierteNumero_a_letras(1.10, "DOLAR", "CENTAVO") == > UN DOLAR CON DIEZ CENTAVOS
'ConvierteNumero_a_letras(110, "DOLAR", "CENTAVO") == > CIENTO DIEZ DOLARES
'‘ConvierteNumero_a_letras(121.55, "DOLAR", "CENTAVO") == > CIENTO VEINTIUN DOLARES CON CINCUENTA Y CINCO CENTAVOS

' Licencia:
'/**
'‘ * NumerosLetras IS free software; you can redistribute it AND / OR modify
'* it under the terms OF the GNU General PUBLIC License AS published by
'‘ * the Free Software Foundation; either version 2 OF the License, OR
'‘* (at your option)any later version.
'‘ *
'‘ * Alba IS distributed IN the hope that it will be useful,
'‘ * but WITHOUT ANY WARRANTY; without even the implied warranty OF
'‘ * MERCHANTABILITY OR FITNESS FOR A PARTICULAR PURPOSE.See the
'‘ * GNU General PUBLIC License FOR more details.
'‘ *
'‘ * You should have received a COPY OF the GNU General PUBLIC License
'‘ * along WITH Alba; IF NOT, WRITE TO the Free Software
'‘ * Foundation, Inc., 51 Franklin St, Fifth Floor, Boston, MA 02110 – 1301 USA
'‘ * /

Public Function Convertir(valor As Float, devise As String) As String
  
  Dim i As Float
  Dim r As Float
  Dim hastacoma As String
  Dim texto As String
  Dim monedaPlural As String
  Dim mCentPlural As String
  Dim mcent As String
  Dim signe As String
  
  If IsNull(devise) Then devise = "euro"
  mcent = "centime"
  monedaPlural = palabraPlural(devise)
  mCentPlural = palabraPlural(mCent)
  If valor < 0 Then
    valor = Abs(valor)
    signe = "Moins "
  Else
    signe = ""
  Endif
  i = Int(valor)
  r = (valor - i) * 100
  If i = 0 Then
    If r = 1 Then
      Return signe & Num2Text(r) & " " & mCent & " "
    Endif
    If r > 1 Then
      Return signe & Num2Text(r) & " " & mCentPlural & " "
    Endif
  Else
    If r = 0 Then
      If i = 1 Then
        Return signe & Num2Text(i) & " " & devise
      Endif
      If i > 1 Then
        Return signe & Num2Text(i) & " " & monedaPlural
      Endif
    Else
      r = Round(r, -1) 'para tener números exactos redondeo los decimales en caso que el valor venga con más de 2 decimales.
      r = Int(r)
      If i = 1 Then
        If r = 1 Then Return signe & Num2Text(i) & " " & devise & " et " & Num2Text(r) & " " & mCent
        If r > 1 Then Return signe & Num2Text(i) & " " & devise & " et " & Num2Text(r) & " " & mCentPlural
      Else
        If r = 1 Then Return signe & Num2Text(i) & " " & monedaPlural & " et " & Num2Text(r) & " " & mCent
        If r > 1 Then Return signe & Num2Text(i) & " " & monedaPlural & " et " & Num2Text(r) & " " & mCentPlural
      Endif
    Endif
  Endif
  
End

Public Function palabraPlural(texto As String) As String
  
  Dim vocal As String
  Dim ultimaLetra As String
  
  'vocal = "aeiou"
  'ultimaLetra = Right(texto, 1)
  'If (InStr(vocal, ultimaLetra)) Then
  Return texto & "s"
  'Endif
  
End

'--------------------------------
'escribir el numero
'--------------------------------

Public Function Num2Text(value As Long) As String
  
  Dim texto As String
  
  If value = 0 Then Return "zéro"
  If value = 1 Then Return "un"
  If value = 2 Then Return "deux"
  If value = 3 Then Return "trois"
  If value = 4 Then Return "quatre"
  If value = 5 Then Return "cinq"
  If value = 6 Then Return "six"
  If value = 7 Then Return "sept"
  If value = 8 Then Return "huit"
  If value = 9 Then Return "neuf"
  If value = 10 Then Return "dix"
  If value = 11 Then Return "onze"
  If value = 12 Then Return "douze"
  If value = 13 Then Return "treize"
  If value = 14 Then Return "quatorze"
  If value = 15 Then Return "quinze"
  If value = 16 Then Return "seize"
  If value = 17 Then Return "dix sept"
  If value = 18 Then Return "dix huit"
  If value = 19 Then Return "dix neuf"
  'If value >= 16 And value < 20 Then
  'texto = "dix" & Num2Text(value - 10)
  'Return texto
  'Endif
  
  If value = 20 Then Return "vingt"
  'If value >= 21 And value <= 29 Then
  'texto = "vingt " & Num2Text(value - 20)
  'Return texto
  'Endif
  If value = 30 Then Return "trente"
  If value = 40 Then Return "quarante"
  If value = 50 Then Return "cinquante"
  If value = 60 Then Return "soixante"
  If value = 70 Then Return "soixante dix"
  If value = 80 Then Return "quatre vingt"
  If value = 90 Then Return "quatre vingt dix"
  If value > 70 And value < 80 Then
    texto = "soixante" & " " & Num2Text(10 + value Mod 10)
    If value = 71 Then texto = "soixante et onze"
    Return texto
  Else
    If value > 90 And value < 100 Then
      texto = "quatre vingt" & " " & Num2Text(10 + value Mod 10)
      Return texto
    Else
      If value < 100 Then
        If value Mod 10 = 1 Then
          texto = Num2Text(Int(value / 10) * 10) & " et un"
        Else
          texto = Num2Text(Int(value / 10) * 10) & " " & Num2Text(value Mod 10)
        Endif
        Return texto
      Endif
    Endif
  Endif
  If value = 100 Then Return "cent"
  If value < 200 Then
    texto = "cent " & Num2Text(value - 100)
    Return texto
  Endif
  
  If value = 200 Or value = 300 Or value = 400 Or value = 600 Or value = 800 Then
    texto = Num2Text(Int(value / 100)) & " cent"
    Return texto
  Endif
  
  If value = 500 Then Return "cinq cent"
  If value = 700 Then Return "sept cent"
  If value = 800 Then Return "huit cent"
  If value = 900 Then Return "neuf cent"
  
  If value < 1000 Then
    texto = Num2Text(Int(value / 100) * 100) & " " & Num2Text(value Mod 100)
    Return texto
  Endif
  
  If value = 1000 Then
    Return "mille "
  Endif
  
  If value < 2000 Then
    Texto = "mille " & Num2Text(value Mod 1000)
    Return texto
  Endif
  
  If value < 1000000 Then
    texto = Num2Text(Int(value / 1000)) & " mille"
    If (value Mod 1000) Then texto = texto & " " & Num2Text(value Mod 1000)
    Return texto
  Endif
  
  If value = 1000000 Then texto = "un million"
  
  If value < 2000000 Then
    Texto = "un million " & Num2Text(value Mod 1000000)
    Return texto
  Endif
  
  If value < 1000000000000.0 Then
    texto = Num2Text(Int(value / 1000000)) & " millions "
    If (value - Int(value / 1000000) * 1000000) Then Texto = Texto & " " & Num2Text(value - Int(value / 1000000) * 1000000)
    Return texto
  Endif
  
  If value = 1000000000000.0 Then Return "un billion"
  If value >= 2000000000000 Then
    Texto = ""
    Return texto
  Endif
  
End Function
