' Gambas module file

'Fonction pour récuperer le groupe de l'utilisateur.
Public Function Group() As String

  Dim gid As String
  Dim Hfile As File
  Dim Lig As String
  Dim cle As String
  Dim iPos As Integer

  gid = User.Group
  Shell "getent group " & gid & " > " & User.Home & "/tmp/group 2>&1" Wait
  If Exist(User.Home & "/tmp/group") Then
    HFile = Open User.Home & "/tmp/group" For Read
    Lig = File.Load(User.Home & "/tmp/group")
  Endif
  Line Input #hFile, Lig
  iPos = InStr(Lig, ":")
  cle = Left$(Lig, iPos - 1)
  Return cle

End

Public Function Utilisateur() As String

  Return User.Name

End
