' Gambas module file

' Gambas class file

Public Function CalcSha1(numecr As String)

  Dim sresult As Result
  Dim $cle, $cle2 As String

  sResult = Utils.db.Exec("SELECT * FROM Fiches_Mvt WHERE numero = &1", numecr)
  If sResult.Available Then
    Repeat
      $cle = sResult!jour & sResult!numero & sResult!compte & sResult!intitule & sResult!dte & sResult!numdoc & sResult!numlot & sResult!libelle & sResult!montantd & sResult!montantc & sResult!validee & sResult!provisoire & sResult!tresorerie & sResult!lettree & sResult!cloturee
      $cle &= sResult!numerodef & sResult!collectif & sResult!datee & sResult!dateech & sResult!numcol & sResult!pointee & sResult!nrlv & sResult!dteval & sResult!relance & sResult!export
      $cle = Replace$($cle, ")", "")
      $cle = Replace$($cle, "(", "")
      $cle = Replace$($cle, "'", "")
      Shell "echo " & $cle & " | sha1sum 2>&1" To $cle2
      Utils.db.Exec("update Fiches_Mvt set  control = &2 where lind = &1", sResult!lind, Left$($cle2, 40))
    Until sResult.MoveNext()
  Endif

End

Public Function CalcSha12()

  Dim sresult As Result
  Dim $cle, $cle2 As String

  sResult = Utils.db.Exec("SELECT * FROM Fiches_Mvt")
  If sResult.Available Then
    Repeat
      $cle = sResult!jour & sResult!numero & sResult!compte & sResult!intitule & sResult!dte & sResult!numdoc & sResult!numlot & sResult!libelle & sResult!montantd & sResult!montantc & sResult!validee & sResult!provisoire & sResult!tresorerie & sResult!lettree & sResult!cloturee
      $cle &= sResult!numerodef & sResult!collectif & sResult!datee & sResult!dateech & sResult!numcol & sResult!pointee & sResult!nrlv & sResult!dteval & sResult!relance & sResult!export
      Shell "echo " & $cle & " | sha1sum 2>&1" To $cle2
      Utils.db.Exec("update Fiches_Mvt set  control = &2 where lind = &1", sResult!lind, Left$($cle2, 40))
    Until sResult.MoveNext()
  Endif

End
