' Gambas module file

Public Function CalcSha1(numecr As String)

  Dim sresult, s2Result As Result
  Dim $cle, $cle2 As String

  sResult = Utils.db.Exec("SELECT * FROM Fiches_Mvt WHERE numero = &1", numecr)
  If sResult.Available Then
    s2Result = Utils.db.Exec("SELECT * FROM Fiches_Mvt WHERE numero < &1 order by lind desc limit 1", numecr - 1)
    If s2Result.Available Then
      $cle2 = s2Result!control
    Endif
    Repeat
      $cle = $cle2
      $cle &= sResult!jour & sResult!numero & sResult!compte & sResult!intitule & sResult!dte & sResult!numdoc & sResult!numlot & sResult!libelle & sResult!montantd & sResult!montantc & sResult!validee & sResult!provisoire & sResult!tresorerie & sResult!lettree & sResult!cloturee
      $cle &= sResult!numerodef & sResult!collectif & sResult!datee & sResult!dateech & sResult!numcol & sResult!pointee & sResult!nrlv & sResult!dteval & sResult!relance & sResult!export
      $cle = Replace$($cle, ")", "")
      $cle = Replace$($cle, "(", "")
      $cle = Replace$($cle, "'", "")
      Shell "echo " & $cle & " | sha1sum 2>&1" To $cle2
      Utils.db.Exec("update Fiches_Mvt set  control = &2 where lind = &1", sResult!lind, Left$($cle2, 40))
    Until sResult.MoveNext()
  Endif

End

Public Function CalcSha12()

  Dim sresult, s2Result As Result
  Dim $cle, $cle2 As String

  sResult = Utils.db.Exec("SELECT * FROM Fiches_Mvt order by numero asc")
  If sResult.Available Then
    Repeat
      $cle2 = ""
      s2Result = Utils.db.Exec("SELECT * FROM Fiches_Mvt WHERE numero < &1 order by lind desc limit 1", sResult!numero - 1)
      If s2Result.Available Then
        $cle2 = s2Result!control
      Endif
      $cle = $cle2
      $cle &= sResult!jour & sResult!numero & sResult!compte & sResult!intitule & sResult!dte & sResult!numdoc & sResult!numlot & sResult!libelle & sResult!montantd & sResult!montantc & sResult!validee & sResult!provisoire & sResult!tresorerie & sResult!lettree & sResult!cloturee
      $cle &= sResult!numerodef & sResult!collectif & sResult!datee & sResult!dateech & sResult!numcol & sResult!pointee & sResult!nrlv & sResult!dteval & sResult!relance & sResult!export
      $cle = Replace$($cle, ")", "")
      $cle = Replace$($cle, "(", "")
      $cle = Replace$($cle, "'", "")
      Shell "echo " & $cle & " | sha1sum 2>&1" To $cle2
      Utils.db.Exec("update Fiches_Mvt set  control = &2 where lind = &1", sResult!lind, Left$($cle2, 40))
    Until sResult.MoveNext()
  Endif

End

Public Function CalcSha2(lind As String) As String

  Dim sresult, s2Result As Result
  Dim $cle, $cle2 As String

  sResult = Utils.db.Exec("SELECT * FROM Fiches_Mvt WHERE lind = &1", lind)
  If sResult.Available Then
    s2Result = Utils.db.Exec("SELECT * FROM Fiches_Mvt WHERE numero < &1 order by lind desc limit 1", sResult!numero - 1)
    If s2Result.Available Then
      $cle2 = s2Result!control
    Endif
    $cle = $cle2
    $cle &= sResult!jour & sResult!numero & sResult!compte & sResult!intitule & sResult!dte & sResult!numdoc & sResult!numlot & sResult!libelle & sResult!montantd & sResult!montantc & sResult!validee & sResult!provisoire & sResult!tresorerie & sResult!lettree & sResult!cloturee
    $cle &= sResult!numerodef & sResult!collectif & sResult!datee & sResult!dateech & sResult!numcol & sResult!pointee & sResult!nrlv & sResult!dteval & sResult!relance & sResult!export
    $cle = Replace$($cle, ")", "")
    $cle = Replace$($cle, "(", "")
    $cle = Replace$($cle, "'", "")
    Shell "echo " & $cle & " | sha1sum 2>&1" To $cle2
    Return Left$($cle2, 40)
  Endif

End

'Clé pour la caisse
Public Function CalcShaC($Ncaisse As String, $numero As String)

  Dim sresult, s2Result As Result
  Dim $cle, $cle2, $Tab As String

  $Tab = "Fiches_EntTicketz"
  sResult = Utils.db.Exec("SELECT * FROM  " & $Tab & " WHERE caisse = &1 and numero = &2", $Ncaisse, $numero)
  If sResult.Available Then
    Repeat
      $cle2 = "" '
      s2Result = Utils.db.Exec("SELECT * FROM Fiches_Mvt order by numero desc, lind desc limit 1")
      If s2Result.Available Then
        $cle2 = s2Result!control
      Endif
      $cle = $cle2
      $cle &= sResult!caisse & sResult!numero & sResult!date & sResult!client & sResult!scheque & sResult!mcheque & sResult!nmcheque & sResult!scarte & sResult!mcarte & sResult!nmcarte & sResult!sespeces & sResult!mespeces & sResult!scredit & sResult!mcredit & sResult!mht & sResult!mtva & sResult!mttc & sResult!statut & sResult!savoir
      $cle &= sResult!scavoir & sResult!mavoir & sResult!type & sResult!vendeur & sResult!carte & sResult!points & sResult!sbonus & sResult!mbonus & sResult!sresto & sResult!mresto & sResult!sbachat & sResult!mbachat & sResult!nom & sResult!suppr & sResult!retro
      $cle = Replace$($cle, ")", "")
      $cle = Replace$($cle, "(", "")
      $cle = Replace$($cle, "'", "")
      Shell "echo " & $cle & " | sha1sum 2>&1" To $cle2
      Utils.db.Exec("update  " & $Tab & " set  control = &2 where lInd = &1", sResult!lInd, Left$($cle2, 40))
    Until sResult.MoveNext()
  Endif

End

'md5sum
Public Function md5sum()

  Dim $cle As String

  Shell "md5sum  " & User.Home & "/Laurux3/Laurux3.gambas  2>&1 " To $cle
  $cle = Left$($cle, 32)

End
