' Gambas module file

Public son As String = Settings["/son"]
Public Musique As String = "son/warning.ogg"
Public OrgTarCli As String = ""
Public OrgTarTypeCli As String = ""
Public OrgCoefTypeCli As String = ""
Public ArtCode As String = ""
Public Artintitule As String = ""
Public ArtTva As String = ""
Public ArtHt As String = ""
Public bRemise As Boolean = False
Public Bselection As Boolean = False
Public Bsel As Boolean = False
Public Qte As Float
Public TypeL As String
Public Codearticle As String
Public Cfour As String
Public obs As String
Public $fic As String
Public $doc As String
Public inumr As Integer
Public numerobl As String[]
