' Gambas module file

' Gestion des impressions de la caisse

'---------------------------- Entete ticket ----------------------------------------

Public Sub Entete1(Ent As String, PosX As String, PosY As String)
  
  Draw.Font.Size = 6  
  Draw.Font.Bold = True
  Draw.Text(Ent, posX, posY)
  Draw.Text(Ent, posX + 2400, posY)
  Draw.Font.Bold = False
  
End
'---------------------------- Entete facture ----------------------------------------

Public Sub Entete2(Ent As String, PosX As String, PosY As String)
  
  Draw.Font.Size = 8  
  '  Draw.Font.Bold = TRUE
  Draw.Text(Ent, posX, posY)
  Draw.Font.Bold = False
  
End

'---------------------------- Entete facture ----------------------------------------
Public Sub Com(Ent As String, PosX As String, PosY As String)
  
  Draw.Font.Size = 6  
  Draw.Text(Ent, posX, posY)
  Draw.Font.Bold = False
  
End

'---------------------------- Logo ----------------------------------------
Public Sub Draw_Image(img As Image, postx As Integer, posty As Integer)
  
  Postx = Postx - (img.Width / 2)
  Posty = Posty - (img.Height / 2)
  Draw.Image(img, Postx, Posty)
  
End

'Lignes continues
Public Sub Lines(PosY As String)
  
  Draw.Font.Size = 6
  Draw.LineStyle = Line.Solid
  Draw.Line(0, PosY, 4950, PosY)  
  
End

'Lignes de detail
Public Sub Level1(Code As String, Intitule As String, prix As String, qte As String, PosY As Integer, Typel As String)
  
  Draw.Font.Size = 6
  Draw.Text(Code, 120, PosY + 10, 400, 100, 1) 
  Draw.Text(Code, 2520, PosY + 10, 400, 100, 1)
  If typel <> "K" Then intitule = Left$(intitule, 35)
  If typel = "K" Then 
    Draw.Text(intitule, 120, PosY + 10, 2000, 100, 3) 
    Draw.Text(intitule, 2520, PosY + 10, 2000, 100, 3)
  Else
    If typel = "TA" Then
      Draw.Text(intitule, 520, PosY + 10, 1140, 100, 3) 
      Draw.Text(intitule, 2920, PosY + 10, 1140, 100, 3)
    Else 
      Draw.Text(intitule, 520, PosY + 10, 1140, 100, 1) 
      Draw.Text(intitule, 2920, PosY + 10, 1140, 100, 1)
    Endif
    Draw.Text(prix, 1660, PosY + 10, 200, 100, 2) 
    Draw.Text(prix, 4060, PosY + 10, 200, 100, 2)
    Draw.Text(qte, 1860, PosY + 10, 300, 100, 2) 
    Draw.Text(qte, 4260, PosY + 10, 300, 100, 2) 
  Endif 
  
End

'Lignes des ticketx
Public Sub Level2(Intitule As String, prix As String, qte As String, PosY As Integer)
  
  Draw.Font.Size = 6
  Draw.Text(intitule, 120, PosY + 10, 1040, 100, 1) 
  '  Draw.Text(intitule, 2520, PosY + 10, 1040, 100, 1)
  Draw.Text(prix, 1160, PosY + 10, 200, 100, 2) 
  '  Draw.Text(prix, 3540, PosY + 10, 200, 100, 2)
  Draw.Text(qte, 1360, PosY + 10, 300, 100, 2) 
  '  Draw.Text(qte, 3760, PosY + 10, 300, 100, 2)  
  
End

'Entete ticketx
Public Sub Level3(Intitule As String, Posy As Integer)
  
  Draw.Font.Size = 6 
  Draw.Text(intitule, 120, PosY + 10, 640, 100, 1)
  '  Draw.Text(intitule, 2520, PosY + 10, 640, 100, 1)
  
End

'Lignes des factures
Public Sub Level4(Code As String, Intitule As String, prix As String, qte As String, PosY As Integer)
  
  Draw.Font.Size = 8
  Draw.Text(Code, 120, PosY + 10, 500, 100, 1)
  Draw.Text(intitule, 620, PosY + 10, 2080, 100, 1) 
  '  Draw.Text(intitule, 2520, PosY + 10, 1040, 100, 1)
  Draw.Text(prix, 2700, PosY + 10, 400, 100, 2) 
  '  Draw.Text(prix, 3540, PosY + 10, 200, 100, 2)
  Draw.Text(qte, 3300, PosY + 10, 300, 100, 2) 
  '  Draw.Text(qte, 3760, PosY + 10, 300, 100, 2)  
  
End

'entetes bordereaux
Public Sub EnteteB(TxtB As String, PosY As Integer)
  
  Draw.Font.Size = 10
  Draw.Text(TxtB, 120, PosY, 2000, 100, 1)  
  
End

'Titre bordereaux
Public Sub TitreB(TxtB As String, PosY As Integer)

  Draw.Font.Size = 10
  Draw.Text(TxtB, 120, PosY, 4800, 100, 3)  

End

'Lignes bordereaux
Public Sub Level5(Intitule As String, prix As String, PosY As Integer)

  Draw.Font.Size = 10
  Draw.Text(intitule, 600, PosY + 10, 2600, 100, 1) 
  Draw.Text(prix, 3200, PosY + 10, 700, 100, 2) 

End

'Lignes continues ticketx
Public Sub Lines2(PosY As String)

  Draw.Font.Size = 6
  Draw.LineStyle = Line.Solid
  Draw.Line(0, PosY, 2000, PosY)  
End
