' Gambas module file

Public Sub Prog_Editeur(Fic As String, nb As Integer, $Imp As String) As String

  Shell "cd " & User.Home & ""
  If Not IsNull($Imp) Then
    Shell "lp -d " & $Imp & " -o fitplot -o scaling=97 -o page-top=0 -o page-bottom=0 -n " & nb & " " & Fic Wait
  Else
    Shell "lp  -n" & nb & " " & Fic Wait
  Endif

End

Public Sub Prog_Editeur2(Fic As String, nb As Integer, Imp As Boolean, $Imp As String) As String

  Dim $Exec As String

  Shell "cd " & User.Home & ""
  If Not Imp Then
    $Exec = "lp"
    If Not CheckProg.Chk($Exec) Then $Exec = "evince"
    If Not CheckProg.Chk($Exec) Then $Exec = "okular"
    If Not CheckProg.Chk($Exec) Then $Exec = "caja"
    If $Exec = "okular" Or If $Exec = "evince" Or If $Exec = "caja" Then
      Shell $Exec & " " & Fic Wait
    Else
      If $Exec = "lp" Then
        Shell $Exec & " -o fitplot -o scaling=97 -o page-top=0 -o page-bottom=0 -n" & nb & " " & Fic Wait
      Endif
    Endif
  Else
    If Not IsNull($Imp) Then
      Shell "lp -d " & $Imp & " -o fitplot -o scaling=97 -o page-top=0 -o page-bottom=0 -n " & nb & " " & Fic Wait
    Else
      Shell $Exec & "  -n" & nb & " " & Fic Wait
    Endif
  Endif

End
