' Gambas module file

Public Sub Prog_Editeur(Fic As String, nb As Integer, Imp As Boolean) As String
  
  Dim $Exec As String
  
  Shell "cd " & User.Home & ""
  If Imp Then 
    $Exec = "gtklp"
  Else
    $Exec = "lp"
  Endif
  If Not CheckProg.Chk($Exec) Then $Exec = "gtklp"
  If Not CheckProg.Chk($Exec) Then $Exec = "evince"
  If Not CheckProg.Chk($Exec) Then $Exec = "okular"
  If Not CheckProg.Chk($Exec) Then $Exec = "caja"
  If $Exec = "okular" Or If $Exec = "evince" Or If $Exec = "caja" Then
    Shell $Exec & " " & Fic Wait
  Else
    If $Exec = "lp" Then
      Shell $Exec & " -o fitplot -o scaling=97 -o page-top=0 -o page-bottom=0 -n" & nb & " " & Fic Wait
    Else 
      If $Exec = "gtklp" Then
        Shell $Exec & " -l -n" & nb & " " & Fic Wait
      Endif 
    Endif
  Endif
  
End
