' Gambas module file

Public Sub Web(chemin As String)
  
  Dim sExec As String
  
  sExec = Application.Env["BROWSER"]
  If Not CheckProg.Chk(sExec) Then sExec = "firefox"
  If Not CheckProg.Chk(sExec) Then sExec = "konqueror"
  If Not CheckProg.Chk(sExec) Then sExec = "mozilla-firefox"
  If Not CheckProg.Chk(sExec) Then sExec = "mozilla"
  If Not CheckProg.Chk(sExec) Then sExec = "opera"
  If Not CheckProg.Chk(sExec) Then Return
  Exec [sExec, chemin]
Catch
  Message.Error(Error.Text)
  
End
