' Gambas module file

Public Sub Gondole1(Mysock As Socket, barcode As String, Pvttc As String, Intitule As String, Code As String, ttc As String, Casier As String, Kgl As String, Cfourn As String)
  
  Write #Mysock, "^XA~TA0~JSO^LT0^MMT^MNW^MTT^PON^PMN^LH0,0^JMA^PR2,2^MD0^JUS^LRN^CI0^XZ"
  Write #Mysock, "^XA^LL0256"
  Write #Mysock, "^PW384"
  Write #Mysock, "^BY2,3,63^FT52,141^BCN,,Y,N"
  Write #Mysock, "^FD>;" & barcode & ">63^FS"
  Write #Mysock, "^FO,52^FS"
  Write #Mysock, "^FT6,180^A0N,18,22^FH^FD" & Kgl & "^FS"
  Write #Mysock, "^FT250,180^A0N,18,22^FH^FD" & Cfourn & "^FS"
  Write #Mysock, "^FT10,255^A0N,70,40^FH^FD" & Pvttc & "^FS"
  Write #Mysock, "^FO,37^FS"
  Write #Mysock, "^FT306,28^A0N,18,33^FH^FD" & Casier & "^FS"
  Write #Mysock, "^FT306,255^A0N,30,38^FH^FD" & TTC & "^FS"
  Write #Mysock, "^FO,30^FS"
  Write #Mysock, "^FT6,62^A0N,24,19^FH^FD" & utils.Remplace(Intitule) & "^FS"
  Write #Mysock, "^FO,19^FS"
  Write #Mysock, "^FT4,28^A0N,16,33^FH^FD" & Code & "^FS"
  Write #Mysock, "^PQ1,0,1,Y^XZ"
  
End