' Gambas module file

Public Sub Maj(code As String, cequ As String)
  
  Dim requ, requ2 As Result
  
  Try Utils.db.Exec("INSERT INTO " & Cbase.Table("TabCequ") & " (codep, codequ) VALUES (&1, &2)", Cequ, code)
  Try Utils.db.Exec("INSERT INTO " & Cbase.Table("TabCequ") & " (codep, codequ) VALUES (&1, &2)", Code, code)
  Try Utils.db.Exec("INSERT INTO " & Cbase.Table("TabCequ") & " (codep, codequ) VALUES (&1, &2)", Cequ, Cequ)
  Try Utils.db.Exec("INSERT INTO " & Cbase.Table("TabCequ") & " (codequ, codep) VALUES (&1, &2)", Cequ, code)
  Try Utils.db.Exec("update " & Cbase.Table("TabArt") & " art_cequ = &1 where art_code = &2 ", Cequ, code)
  'Try Utils.db.Exec("update " & Cbase.Table("TabArt") & " art_cequ = &1 where art_code = &2 ", code, Cequ)
  Requ2 = Utils.db.Exec("SELECT * FROM " & Cbase.Table("TabCequ") & " where codep = &1", Code)
  Repeat
    Requ = Utils.db.Exec("SELECT * FROM " & Cbase.Table("TabCequ") & " where codep = &1", requ2!codequ)
    Repeat
      Try Utils.db.Exec("INSERT INTO " & Cbase.Table("TabCequ") & " (codequ, codep) VALUES (&1, &2)", Code, Requ!codequ)
      Try Utils.db.Exec("INSERT INTO " & Cbase.Table("TabCequ") & " (codep, codequ) VALUES (&1, &2)", requ!codep, code)
      Try Utils.db.Exec("INSERT INTO " & Cbase.Table("TabCequ") & " (codep, codequ) VALUES (&1, &2)", Requ!codequ, requ2!codep)
    Until Requ.MoveNext()
  Until Requ2.movenext()
  Requ2 = Utils.db.Exec("SELECT * FROM " & Cbase.Table("TabCequ") & " where codep = &1", Cequ)
  Repeat
    Requ = Utils.db.Exec("SELECT * FROM " & Cbase.Table("TabCequ") & " where codep = &1", requ2!codequ)
    Repeat
      Try Utils.db.Exec("INSERT INTO " & Cbase.Table("TabCequ") & " (codequ, codep) VALUES (&1, &2)", Code, Requ!codequ)
      Try Utils.db.Exec("INSERT INTO " & Cbase.Table("TabCequ") & " (codep, codequ) VALUES (&1, &2)", requ!codep, code)
      Try Utils.db.Exec("INSERT INTO " & Cbase.Table("TabCequ") & " (codep, codequ) VALUES (&1, &2)", Requ!codequ, requ2!codep)
    Until Requ.MoveNext()
  Until Requ2.movenext()
  'Requ2 = Utils.db.Exec("SELECT * FROM " & Cbase.Table("TabCequ") & " where codep = &1", Cequ)
  'Repeat
  'Requ = Utils.db.Exec("SELECT * FROM " & Cbase.Table("TabCequ") & " where codep = &1", requ2!codequ)
  'Repeat
  'Try Utils.db.Exec("INSERT INTO " & Cbase.Table("TabCequ") & " (codequ, codep) VALUES (&1, &2)", Code, Requ!codequ)
  'Try Utils.db.Exec("INSERT INTO " & Cbase.Table("TabCequ") & " (codep, codequ) VALUES (&1, &2)", requ2!codep, Requ!codequ)
  'Try Utils.db.Exec("INSERT INTO " & Cbase.Table("TabCequ") & " (codep, codequ) VALUES (&1, &2)", Requ!codequ, requ2!codep)
  'Until Requ.MoveNext()
  'Until Requ2.movenext()
  
  Requ2 = Utils.db.Exec("SELECT * FROM " & Cbase.Table("TabCequ") & " where codequ = &1", Cequ)
  Repeat
    Requ = Utils.db.Exec("SELECT * FROM " & Cbase.Table("TabCequ") & " where codep = &1", requ2!codequ)
    Repeat
      Try Utils.db.Exec("INSERT INTO " & Cbase.Table("TabCequ") & " (codequ, codep) VALUES (&1, &2)", requ2!codequ, code)
      Try Utils.db.Exec("INSERT INTO " & Cbase.Table("TabCequ") & " (codep, codequ) VALUES (&1, &2)", requ2!codep, Requ!codequ)
      Try Utils.db.Exec("INSERT INTO " & Cbase.Table("TabCequ") & " (codep, codequ) VALUES (&1, &2)", Requ!codequ, requ2!codep)
    Until Requ.MoveNext()
  Until Requ2.movenext()
  
End

Public Sub Maj2(code As String, cequ As String)
  
  Dim requ, requ2 As Result
  
  Try Utils.db.Exec("INSERT INTO " & Cbase.Table("TabCequ") & " (codep, codequ) VALUES (&1, &2)", Cequ, code)
  Try Utils.db.Exec("INSERT INTO " & Cbase.Table("TabCequ") & " (codequ, codep) VALUES (&1, &2)", Cequ, code)
  Try Utils.db.Exec("update " & Cbase.Table("TabArt") & " art_cequ = &1 where art_code = &2 ", Cequ, code)
  Requ2 = Utils.db.Exec("SELECT * FROM " & Cbase.Table("TabArt") & " where art_code = &1", Cequ)
  If Requ2.Available Then 
    Requ = Utils.db.Exec("SELECT * FROM " & Cbase.Table("TabCequ") & " where codep = &1 or codequ = &1 or codep = &2 or codequ = &2", Cequ, code)
    Repeat
      Requ2 = Utils.db.Exec("SELECT * FROM " & Cbase.Table("TabArt") & " where art_code = &1", requ!codequ)
      If Requ2.Available Then
        If requ!codequ <> Code Or If requ!codep <> Code Then
          Try Utils.db.Exec("INSERT INTO " & Cbase.Table("TabCequ") & " (codep, codequ) VALUES (&1, &2)", requ!codep, Cequ)
          Try Utils.db.Exec("INSERT INTO " & Cbase.Table("TabCequ") & " (codequ, codep) VALUES (&1, &2)", requ!codep, Cequ)
          Try Utils.db.Exec("INSERT INTO " & Cbase.Table("TabCequ") & " (codep, codequ) VALUES (&1, &2)", requ!codequ, Code)
          Try Utils.db.Exec("INSERT INTO " & Cbase.Table("TabCequ") & " (codequ, codep) VALUES (&1, &2)", requ!codequ, Code)
        Endif
      Endif
    Until Requ.movenext()
  Endif
  
End

Public Sub Recup()
  
  Dim requ, requ2 As Result
  
  Requ2 = Utils.db.Exec("SELECT * FROM " & Cbase.Table("TabCequ") & " order by codep")
  Repeat
    Requ = Utils.db.Exec("SELECT * FROM " & Cbase.Table("TabCequ") & " where codep = &1", requ2!codequ)
    Repeat
      Try Utils.db.Exec("INSERT INTO " & Cbase.Table("TabCequ") & " (codep, codequ) VALUES (&1, &2)", requ2!codep, Requ!codequ)
      Try Utils.db.Exec("INSERT INTO " & Cbase.Table("TabCequ") & " (codep, codequ) VALUES (&1, &2)", Requ!codequ, requ2!codep)
    Until Requ.MoveNext()
  Until Requ2.movenext()
  
End
