' Gambas module file

Private DebHP As Float
Private CredHP As Float
Private TotSldHP As Float
Private TotDeb As Float
Private TotCred As Float
Private TotSld As Float
Private Slddeb As Float
Private Sldcred As Float
Private Sldtot As Float
Private debit As Float
Private credit As Float
Private solde As Float
Private montantd As Float
Private montantc As Float
Private mnt As Float
Private mnt1 As Float
Private dte As String
Private Filename As String
Private Tab1 As String
Private jour As String
Private Centr As Boolean
Private Mois As String
Private Datj As String
Private libelle As String
Private Compt As String
Private IntituleCpt As String
Private cResult As Result
Private rResult As Result
Private rrResult As Result
Private Tab2 As String
Private PosY As Integer
Private son As Integer = Start.Son
Private dateedition As String
Private Ste As String
Private pdf As Ccompta

'******************
'*   On imprime   *
'******************
Public Sub Imprime(cpt As String, cpt2 As String, type As String, dten0 As String, dten1 As String, Bgen As Boolean, Tab0 As String)

  Dim p As Integer
  Dim Intit As String
  Dim deb As String
  Dim SteResult As Result
  Dim rSouscomptes As Result
  Dim Tab3 As String
  Dim Cred As String
  Dim Libel As String
  Dim Lib As String
  Dim Nbpage As Integer
  Dim None As Boolean = False
  Dim Ecr As Boolean = False
  Dim debssc As Float = 0
  Dim credssc As Float = 0
  Dim sldssc As Float = 0
  Dim $debssc As String
  Dim $credssc, $solde As String
  Dim Souscomptes As Boolean = False
  Dim Tabssc As String = "Fiches_SousComptes"
  Dim Dersouscomptes, Psouscomptes, IntituleSouscompte, IntituleT As String
  Dim Slddeb2, Sldcred2, Sldtot2 As Float = 0
  Dim typecompte As String = "B"

  Nbpage = 1
  Shell "cd " & User.Home & ""
  Filename = User.Home & "/tmp/Glivre.pdf"
  pdf = New Ccompta("Portrait", "mm", "A4")
  pdf.Open()
  pdf.AliasNbPages()
  dte = Format$(Now, "dd.mm.yyyy")
  totsldhp = 0.00
  Tab1 = "Ctrln"
  Tab2 = "Fiches_Comptes"
  Tab3 = "Fiches_Societes"
  p = 0
  SteResult = Utils.db.Exec("SELECT * FROM " & Tab3 & " Where cd_sc = &1", Start.Societe)
  Ste = "Societe " & " " & SteResult!int_sc
  dateedition = "du " & dteN0 & " au " & dteN1
  Select Case type
    Case "C"
      IntituleT = " client"
    Case "F"
      IntituleT = " fournisseur"
    Case "G"
      IntituleT = " gestion"
    Case "B"
      IntituleT = " bilan"
    Case "BG"
      IntituleT = " général"
  End Select
  pdf.Entete("Grand livre" & IntituleT)
  posy = 26
  pdf.level0C(dateedition, Ste)
  pdf.level1C()
  posy = posy + 5
  p = 6
  Editcompte.Mouse = Mouse.Wait
  With Utils
    If type <> "BG" Then
      rrResult = Utils.db.Exec("SELECT  compte_cc, intitule_cc, cent_cc, cprincipal, type_cc  FROM " & Tab2 & " WHERE cast(compte_cc AS char) >= &1  and cast(compte_cc AS char) <= &2  and type_cc = &4 order by cast(compte_cc AS char)", cpt, cpt2, 0, type)
    Else
      rrResult = Utils.db.Exec("SELECT  compte_cc, intitule_cc, cent_cc, cprincipal, type_cc  FROM " & Tab2 & " WHERE cast(compte_cc AS char) >= &1  and cast(compte_cc AS char) <= &2  and type_cc = &4 or cast(compte_cc AS char) >= &1  and cast(compte_cc AS char) <= &2  and type_cc = &5 order by type_cc, cast(compte_cc AS char)", cpt, cpt2, 0, "G", "B")
    Endif
    If rrResult.Available Then
      Repeat
        compt = rrResult!compte_cc
        Intit = rrResult!intitule_cc
        Centr = rrResult!cent_cc
        If rrResult!type_cc <> typecompte And If Bgen Then
          PosY += 5
          pdf.level4T(slddeb2, sldcred2, sldtot2, "Bilan", Posy)
          PosY += 5
          pdf.Lines(posy)
          PosY += 5
          slddeb2 = 0
          sldcred2 = 0
          sldtot2 = 0
        Endif
        rsouscomptes = Utils.db.Exec("SELECT * FROM " & Tabssc & " WHERE code = &1 order by code_vtl ", compt)
        If compt > Dersouscomptes And Souscomptes = True Then
          $debssc = Format$(debssc, ",0.00")
          If $debssc = "0,00" Then $debssc = ""
          $credssc = Format$(credssc, ",0.00")
          If $credssc = "0,00" Then $credssc = ""
          If Not IsNull($debssc) Or If Not IsNull($credssc) Then
            pdf.level2s("", "Total sous-comptes " & Psouscomptes & " " & Intitulesouscompte, $debssc, $credssc, PosY)
            posy = posy + 8
          Endif
          bas_page()
          souscomptes = False
          dersouscomptes = ""
          Psouscomptes = ""
          debssc = 0
          credssc = 0
        Endif
        If rsouscomptes.Available Then
          Intitulesouscompte = intit
          souscomptes = True
          rsouscomptes.MoveLast()
          dersouscomptes = rsouscomptes!code_vtl
          Psouscomptes = compt
        Endif
        rResult = Utils.db.Exec("SELECT * FROM " & Tab0 & " WHERE compte = &1  and validee = &2  and dte >= &3 and dte <= &4 order by dte ", compt, 1, Utils.Cdate_dbase(dten0), Utils.Cdate_dbase(dten1))
        If rResult.count <> 0 Then
          None = False
          Ecr = True
          Utils.db.Exec("drop Table IF exists " & Tab1 & "")
          Utils.db.Exec("CREATE TABLE IF NOT EXISTS " & Tab1 &
            "(compte Char(8) NOT NULL," &
            "intitule Char(30)," &
            "jour Char(2)," &
            "Mois Char(6) NOT NULL," &
            "libelle Char(30) ," &
            "dte Char(10) ," &
            "montantd Decimal(12,2)," &
            "montantc Decimal(12,2)," &
            "PRIMARY KEY (compte, Mois))" & "ENGINE = MYISAM")
          bas_page()
          pdf.level3C(Compt, Intit, Posy)
          posy = posy + 5
          p = p + 1
          Repeat
            'IF .Cdate_Comp(rResult!dte) >= .Cdate_dbase(dten0.Text) AND .Cdate_Comp(rResult!dte) <= .Cdate_dbase(dten1.Text) THEN
            If Centr = False Then
              debit = rResult!montantd
              credit = rResult!montantc
              solde = solde + debit - credit
              totdeb = totdeb + debit
              totcred = totcred + credit
              totsld = totdeb - totcred
              If souscomptes = True Then
                debssc = debssc + rResult!montantd
                credssc = credssc + rResult!montantc
                sldssc = debssc - credssc
              Endif
              dte = .Cdate_Aff(rResult!dte)
              dte = Left(dte, 6) & Right(dte, 2)
              $solde = Format$(solde, ",0.00")
              If $solde = "-0,00" Then $solde = "0,00"
              pdf.level2C(rResult!libelle, rResult!jour, dte, rResult!numero, rResult!numlot, Format$(debit, ",0.00"), Format$(credit, ",0.00"), $solde, posy)
              posy = posy + 5
              Lib = rResult!libelle
              bas_page()
            Else
              libelle = rResult!libelle
              jour = rResult!jour
              Datj = .Cdate_Aff(rResult!dte)
              montantd = rResult!montantd
              montantc = rResult!montantc
              centralisation()
            Endif
          Until rResult.MoveNext()
          ' On récupere le solde des comptes centralisés
          If Centr = True Then
            Libel = ""
            libelle = "Centralisation"
            CResult = Utils.db.Exec("SELECT * FROM " & Tab1 & " WHERE compte = &1 Order by Mois", Compt)
            If CResult.Available Then
              Repeat
                Deb = CResult!montantd
                Cred = CResult!montantc
                dte = Cresult!dte
                Mois = cresult!Mois
                dte = Right$(dte, 2) & "." & Mid$(dte, 5, 2) & "." & Left$(dte, 4)
                Totdeb = Totdeb + Deb
                Totcred = Totcred + cred
                Totsld = Totsld + deb - cred
                pdf.level2C(libelle, jour, dte, "", "", Deb, Cred, Format(Totsld, ",0.00"), posy)
                PosY += 5
                bas_page()
                Inc p
              Until CResult.MoveNext()
            Endif
          Endif

          totdeb = totdeb
          totcred = totcred
          totsld = totsld + totsldhp
          Slddeb = Slddeb + Totdeb
          Sldcred = Sldcred + Totcred
          Sldtot = Slddeb - Sldcred
          Slddeb2 += totdeb
          Sldcred2 += totcred
          Sldtot2 = Slddeb2 - Sldcred2
          PosY += 5
          $solde = Format$(totsld, ",0.00")
          If $solde = "-0,00" Then $solde = "0,00"
          pdf.level4C(totdeb, totcred, $solde, compt, Posy)
          PosY += 5
          pdf.Lines(posy)
          PosY += 5
          bas_page()
        Else
          None = True
        Endif
        raz()
        Typecompte = rrResult!type_cc
      Until rrResult.MoveNext()
      If Ecr = True Then
        If Bgen Then
          PosY += 5
          pdf.level4T(slddeb2, sldcred2, sldtot2, "Gestion", Posy)
          PosY += 5
          pdf.Lines(posy)
        Endif
        PosY += 14
        pdf.level5C(Slddeb, Sldcred, Sldtot, Posy)
        posy += 5
        pdf.Lines(posy)
        pdf.Baspage()
        pdf.Output(Filename, False)
        Impression.Prog_Editeur(Filename)
      Else
        If None = True And Ecr = False Then
          If son Then
            Music.Play
          Endif
          message(" Aucune ecriture pour cette demande", "OK")
        Endif
      Endif
    Else
      If son Then
        Music.Play
      Endif
      message(" Aucune ecriture pour cette demande", "OK")
    Endif
    Slddeb = 0
    Sldcred = 0
    Sldtot = 0
  End With
  Editcompte.Mouse = Mouse.Pointing

End

Public Sub bas_page()

  If PosY >= 273 Then
    pdf.Baspage()
    pdf.Entete("Grand livre")
    posy = 26
    pdf.level0C(dateedition, Ste)
    pdf.level1C()
    posy = posy + 5
  Endif

End

'**************************************************
'*     Gestion de la centralisation si besoin     *
'**************************************************
Public Sub Centralisation()

  Dim Libel As String
  Dim Jrs As Date
  Dim jrs1 As String

  Tab1 = "Ctrln"
  Libel = "Centralisation"
  jrs = Date(Right$(Datj, 4), Format$(Val(Mid$(Datj, 4, 2)), "00"), 01)
  Mois = Right$(Datj, 4) & Mid$(Datj, 4, 2)
  Jrs1 = finmois(jrs)
  Jrs1 = Right$(Datj, 4) & Format$(Val(Mid$(Datj, 4, 2)), "00") & Jrs1
  With utils
    CResult = Utils.db.Exec("SELECT * FROM " & Tab1 & " WHERE compte = &1 and Mois = &2", Compt, Mois)
    If CResult.Available Then
      Mnt = montantd + cResult!montantd
      Mnt1 = montantc + cResult!montantc
      Utils.db.Exec("Update " & Tab1 & " set montantd = &2, montantc = &3, dte = &5 Where compte = &1 and Mois = &4", Compt, Mnt, Mnt1, Mois, Jrs1)
    Else
      Utils.db.Exec("INSERT INTO " & Tab1 & "(compte,intitule,dte,libelle, montantd, montantc, jour, Mois) VALUES (&1, &2, &3, '" & Libel & "', &5, &6, &7, &8)", Compt, intituleCpt, Jrs1, Jrs1, montantd, montantc, jour, Mois)
    Endif
  End With

End

'****************************************
'*    Calcul du dernier jour du mois    *
'****************************************
Public Function finmois(Jrs As Date) As Integer

  Dim Jrs1 As Integer

  If Month(Jrs) < 12 Then
    Jrs1 = Day(Date(Year(Jrs), Month(Jrs) + 1, 1) - 1)
  Else
    Jrs1 = Day(Date(Year(Jrs) + 1, 1, 1) - 1)
  Endif
  Return Jrs1

End

'********************
'* On remet à blanc *
'********************
Public Sub Raz()

  debhp = 0
  credhp = 0
  totsldhp = 0
  totdeb = 0
  totcred = 0
  totsld = 0
  solde = 0
  debit = 0
  credit = 0
  solde = 0

End